### ISSUE TITLE
Missing character: Minus Sign (U+2212)

### ISSUE THREAD

**Issue by baskerville** [googlei18n/noto-fonts#1013]
I'm not sure if this is intentional or not:
- Version 1.3840 contains *U+2212*.
- Version 2.0 doesn't.

**Comment by Kanjilearner817** [comment]
Which font? Please specify.

**Comment by baskerville** [comment]
*NotoSans-Regular*

**Comment by dougfelt** [comment]
This is intentional.  It will be in the Math font.  See NotoSansMath in noto-fonts-alpha for a preview.  This font has not been finalized yet.
