### ISSUE TITLE
Phase 3: Why are there the TTC versions of Noto Sans?

### ISSUE THREAD

**Issue by ytx21cn** [googlei18n/noto-fonts#1015]
I wonder what is the reason for having TTC versions of Noto Sans under the "hinted" directory?
![screenshot from 2017-12-18 10-12-44](https://user-images.githubusercontent.com/5900105/34120908-1728d53c-e3dc-11e7-892a-53ff64c10eb6.png)

**Comment by dougfelt** [comment]
@jungshik, we don't need .ttc versions any more, do we?  I seem to remember asking you about them before.  If we do need them, these need to be rebuilt since what's there now appears to have been built from the older phase2 fonts.

**Comment by ytx21cn** [comment]
They do not appear in phase 2, though.

**Comment by dougfelt** [comment]
They are two years old and predate the phase 3 versions of NotoSans-- the fonts that comprise them are phase 2 versions.  They exist to workaround an old ChromeOS font fallback issue that has since been resolved.  So I plan to delete these.

**Comment by dougfelt** [comment]
Deleted the .ttc versions.
