### ISSUE TITLE
Feature Request: replace Source Han Sans by Noto Sans in Noto Sans CJK

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#102]
```
bug filed to track this feature request from customers. 


```

Original issue reported on code.google.com by `xian...@google.com` on 29 Jul 2014 at 10:55

**Comment by behdad** [comment]
cc @xiangyexiao

**Comment by fontguy** [comment]
Moved to https://github.com/googlei18n/noto-cjk/issues/8
