### ISSUE TITLE
NotoSansKannada: U+0CC6, U+0CC7, U+0CC8, U+0CCB, U+0CCB should become more traditional

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#1020]
NotoSansKannada (don't know about Serif): U+0CC6, U+0CC7, U+0CC8, U+0CCB, U+0CCB has an extra half loop that is used in some ligature combinations. Per standard body they'd like to see this as the more common default form without the extra stroke. 

This is an allegedly more standard stroke.

![kannada-cc6-cc7-cc8-cca-ccb-bis](https://user-images.githubusercontent.com/13322623/34393808-ff8f8d0a-eb09-11e7-9ea0-8f24ef7a00b4.jpeg)

This is for Phase III but might also come back as an urgent fix to Phase II fonts.

**Comment by marekjez86** [comment]
@JelleBosmaMT : if you have any images that I could use with the current form to argue with the standard body please help.

**Comment by sridatta1** [comment]
I assume you are talking about in combination with ಙಞಱೞ etc. (Please correct if not). They are special/contextual forms. Which I have explained in #977
For consonants which don't have headstroke and round head in top-right corner (ಙಞಱೞ and optionally ಣ) take special forms for signs ಾ ೆ ೇ ೈ ೊ ೋ ್ since these vowel signs replace the headstroke. These are seen in printed books and manuscripts.

**Comment by JelleBosmaMT** [comment]
![knda](https://user-images.githubusercontent.com/12729011/34411673-94553c0e-ebd8-11e7-819a-cf1eb35a3331.png)

This shows the forms of the signs as used with headline consonant, no-headline consonant and dotted circle. I admit not being very consistent what variant is used by the dotted circle. Simply using the glyph that has the shape needed for rendering logic for the consonants.
We can align the 'e' with 'aa' and the virama, if that is needed to match the standard.

**Comment by marekjez86** [comment]
@sridatta1 , @JelleBosmaMT : I'm going to investigate more. Maybe this is non-issue and thank you for pointing it out.

**Comment by JelleBosmaMT** [comment]
In the Kannada Sans (in progress) the sign is now above the dotted circle, as in the samples of the original comment. The downside is that I had to add an additional glyph, specifically for the dotted circle, which doesn't get used elsewhere, because it is always replaced when used in text :-(
