### ISSUE TITLE
r+ vocalic vowels in Indic scripts

### ISSUE THREAD

**Issue by sridatta1** [googlei18n/noto-fonts#1023]
It is customary to write rṛ as the independent_vocalic_r with a repha instead of ra with vowel sign vocalic r in Devanagari and most other Indic scripts.
In Noto Sans Devangari ( Ver. 1.05) रृ is
![image](https://user-images.githubusercontent.com/23263723/34469003-1f4bedca-ef3b-11e7-83d7-68072102b281.png)
 I'm a native user of Devanagari and Kannada , I have seen rṛ being written as independent_vocalic_r with a repha in the words like निरृत नैरृत्य निरृति only.
In Noto Serif Devanagari these occur correctly 
![image](https://user-images.githubusercontent.com/23263723/34469028-c726d5d2-ef3b-11e7-8601-d1f7819f6984.png)
This is also true for other scripts as well.
Similar forms should occur in Sans and Serif fonts for Kannada, Bengali, Odia, Gujarati scripts which is not the current case.
Modern Telugu and Malayalam texts don't use repha.
For Gujarati-
![image](https://user-images.githubusercontent.com/23263723/34469062-8ef392f8-ef3c-11e7-85a6-28b9df1d429f.png)
For other scripts see section 5 of https://unicode.org/L2/L2017/17423-core-spec-indic.pdf

**Comment by marekjez86** [comment]
@waksmonskiMT : this is about using repha forms instead of ra with vowel sign vocalic r in Sans and Serif fonts for Kannada, Bengali, Odia, Gujarati

**Comment by sridatta1** [comment]
@marekjez86 can you add Devanagari label too, as this issue pertains to Noto Sans Devanagari as well.

**Comment by marekjez86** [comment]
@sridatta1 : added Devanagari label

**Comment by JelleBosmaMT** [comment]
Added a context rule to Kannada Sans that replaces Ra + Rvocalic to Rvocalic +Reph

**Comment by vizzmay** [comment]
This is yet to be added in Noto Sans Devanagari (2.000), Noto Sans Gujarati (2.001) and Noto Serif Gujarati (2.001).
