### ISSUE TITLE
Noto Sans/Serif Malayalam: ASCII text becomes tofu with InDesign CC 2017

### ISSUE THREAD

**Issue by cibu** [googlei18n/noto-fonts#1045]
### Title 
  User reported issue: Noto Sans/Serif Malayalam: ASCII text becomes tofu with Adobe InDesign CC 2017

### Font 
  NotoSansMalayalam-Regular.ttf
  NotoSerifMalayalam-Regular.ttf

### Font Version
  Sans Version 1.04
  Serif Version 1.01

### OS name and version
  macOS High Sierra Version 10.13.3

### Application name and version
  Adobe InDesign CC 2017

### Issue
  Couple of issues:

1.   Latin text gets displayed as tofus.
2.   Vowel sign U overlapped by subsequent consonant YA or RA.

Same issues are observed in Noto Serif as well.

However, this issue is not observed by Baloo Chettan font from Google Fonts project.
  
### Screenshot
  Screenshots with annotations are attached.

![malayalam font test](https://user-images.githubusercontent.com/1966942/35865108-90e9b544-0b4b-11e8-9295-1c0fe1c2b860.jpg)
![font test-1](https://user-images.githubusercontent.com/1966942/35865127-9c862ac2-0b4b-11e8-907e-84152fe6e692.jpg)

**Comment by tianblr** [comment]
For the ASCII text absence, I think it is supposed to be a feature. 

Since the font is designed to be used with fallback to Noto Sans / Noto Serif, Latin characters are not included. Therefore, if you would like to display the Latin texts correctly, you may need to download fonts of Latin characters and assign them to your texts.

**Comment by marekjez86** [comment]
@cibu : user needs to have a latin font and assign this property to the characters. Baloo Chettan includes an English subset of latin characters (hence you can see them). It would encounter the same situation (tofu) if these were Chinese or Arabic text instead of Latin characters.
