### ISSUE TITLE
1000 upem outlines for NotoSans-Gujarati Fonts

### ISSUE THREAD

**Issue by abumoallim** [googlei18n/noto-fonts#1054]
Is there 1000 upem outline for NotoSans-Gujarati Fonts ??

in this link :  https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/sans there is not Gujarati fonts.

or any upcoming possiblility of NotoSansSouthAsian as dicsussed in : https://github.com/googlei18n/noto-fonts/issues/13

I want fonts for Gujarati to be combined with NotoSans Regular

**Comment by marekjez86** [comment]
1000 upem outline for NotoSans-Gujarati Fonts will arrive much later in 2018.
I have attached merged version of 2048 upem NotoSans Regular and NotoSans Gujarati Regular (older prior version) that I used for testing of Gujarati for your own testing. Note that this version comes with NO support, no BUG fixing, etc... 

We are working on merge strategy so there might be NotoSansSouthAsian font in the future (but no promises :-))

[SOW12-extendedNotoSansGujarati-Regular.ttf.zip](https://github.com/googlei18n/noto-fonts/files/1772896/SOW12-extendedNotoSansGujarati-Regular.ttf.zip)
