### ISSUE TITLE
Differences between Noto Sans & Noto Sans Display?

### ISSUE THREAD

**Issue by cssobral2013** [googlei18n/noto-fonts#1056]
Edit: other than Display is being for larger sizes?

**Comment by marekjez86** [comment]
I wasn't around for beginning of the project but running notodiff (from https://github.com/googlei18n/nototools/tree/master/nototools ) shows that Noto Sans is slightly wider than Noto Sans Display (regular width A in Noto Sans Display has width of 604, but it has 639 in Noto Sans).

See some sample differences generated using notodiff:

![a_](https://user-images.githubusercontent.com/13322623/36869651-5ce5ad94-1d51-11e8-83b2-a6fd5aab322f.png)



![uni215a_](https://user-images.githubusercontent.com/13322623/36869572-1a2cd054-1d51-11e8-9ab2-f85c70eabaa0.png)
![uni2189](https://user-images.githubusercontent.com/13322623/36869586-280aef8a-1d51-11e8-9667-5695b8307051.png)
![uni2120](https://user-images.githubusercontent.com/13322623/36869610-3ece04f0-1d51-11e8-8d09-4b840d5ad8db.png)
