### ISSUE TITLE
Missing U+20F0 in Noto Serif Devanagari

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1062]
### Font 
NotoSerifDevanagari-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifDevanagari-unhinted.zip
Date: 2018-03-02

### Font Version
Noto Serif Devanagari: Version 1.01 uh

### Issue
The font is missing U+20F0, a Vedic mark used in Devanagari.

### Character data
क⃰
U+0915 DEVANAGARI LETTER KA
U+20F0 COMBINING ASTERISK ABOVE

### Screenshot
![क⃰](https://user-images.githubusercontent.com/1124347/36912415-96400bf2-1e14-11e8-9893-4d335ef88b35.png)

**Comment by marekjez86** [comment]
It's already implemented in the forthcoming release that's undergoing testing. See https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/sans/NotoSansDevanagari
