### ISSUE TITLE
Bad word in language coverage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#107]
```
Noto Sans/Serif "Thai" has a bad word "Kuy" in language coverage section.
This word spell in Thai is "ควย" and it mean Dick use to insult other.

Sorry for bad english.
Regards.
```

Original issue reported on code.google.com by `keitoc...@gmail.com` on 1 Aug 2014 at 2:40

Attachments:
* [noto.PNG](https://storage.googleapis.com/google-code-attachments/noto/issue-107/comment-0/noto.PNG)

**Comment by marekjez86** [comment]
xiangyexiao, could you check the language coverage section (Thai) for ควย ? If still exists, we need to remove it and if it doesn't then we need to close it and add a label state-unreproducible.
