### ISSUE TITLE
NotoSansOsage-Regular.ttf

### ISSUE THREAD

**Issue by LornaSIL** [googlei18n/noto-fonts#1070]
### Title 
Missing Characters

### Font 
NotoSansOsage-Regular.ttf

### Where the font came from, and when
https://noto-website-2.storage.googleapis.com/pkgs/NotoSansOsage-hinted.zip
Date: 2018-03-05

### Font Version
v2.000

### OS name and version
Windows 10

### Application name and version
Word 2016

### Issue

The font does not have standard punctuation and digits which the Osage script requires. See the [Osage Unicode proposal](http://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/14-214). Page 9 shows a keyboard layout using even more characters than I am suggesting. Thus, Word and some other applications will do font switching when a character is not supported and we end up with Tofu.

It would be best to include all of Basic Latin in Non-Roman fonts. At a minimum, Osage at least requires:
U+0021..U+0040, U+005B..U+0060, U+007B..U+007E, U+00A9, U+2018..U+2019, U+201C..U+201D

If you do add the quote marks, please also set the Unicode range bit for "General Punctuation".

### Character data
some text with punctuation and digits added
“𐓏𐒻𐒷 ‘𐒻𐒷,’ 𐓂𐒰𐒼𐒻𐓄𐓇𐒷” 158

**Comment by dougfelt** [comment]
The Noto fonts are not designed for standalone use, but are expected to be used in an environment that provides fallback for unsupported characters (e.g. Android, ChromeOS, web).  The Noto LGC fonts provide these characters.

There are font merging tools that can be used if you require a version of the font to be used in other environments.

**Comment by marekjez86** [comment]
@LornaSIL : as dougfelt stated all of our fonts are only for the script. There might be few exceptions (e.g., we might add ',' [comma] or '.' [dot] or something else), but if one wants to have Osage and LatinGreekCyrillic font one needs to use one of the tools in https://github.com/googlei18n/nototools/tree/master/nototools

**Comment by davelab6** [comment]
>> It would be best to include all of Basic Latin in Non-Roman fonts. 
>
> all of our fonts are only for the script.

@moyogo said in https://twitter.com/moyogo/status/974524738855845888 that in fact some latin characters **are** part of other scripts, like digits and punctuation, and I agree. 

Maybe not _all_ of Basic Latin, but certainly more than what is included today.

**Comment by brawer** [comment]
Actually Cosimo is working on packaging Noto as one single file, which would contain every glyph (minus CJK) in every available weight as a variation font. As this bug report illustrates, most users are overwhelmed with the complexity of our current packaging, which means we’ve got a problem. But it can be fixed.

**Comment by anthrotype** [comment]
> some latin characters are part of other scripts, like digits and punctuation

I don't think Denis meant that common characters like digits or punctuation are "latin characters", quite the opposite:

> Digits, punctuation and Latin letters are _different things_. The first two are required and specific.

anyway, I got the point.

> most users are overwhelmed with the complexity of our current packaging

The complexity is only shifted (onto me ;)

**Comment by moyogo** [comment]
@davelab6 for the record, I meant digits and punctuation are required and fonts cannot be used independently without them.
