### ISSUE TITLE
Some letters are omitted while generating PDF with 'iText '

### ISSUE THREAD

**Issue by JaewonKimCJK** [googlei18n/noto-fonts#1079]
### Title 
  > Some letters are omitted while generating PDF with 'iText '

### Font 
  > Full file name, 'NotoSerifCJKjp-SemiBold.otf'

### Where the font came from, and when
  >   Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifCJKjp-hinted.zip
  >   Date: 2018-03-07

### Font Version
  > Noto Serif CJK JP SemiBold
  > 1.001;PS 1.001;hotconv 16.6.54;makeotf....

### OS name and version
  > CentOS 6.x

### Application name and version
  > iText 5.5.5

### Issue
1. Draft a HTML in which includes 鶴 Character, and generate PDF with iText library.
   &lt;div style="font-family:NotoSerifCJKjp-SemiBold;"&gt;Test Chracter (鶴)&lt;/div&gt;
2. Observed results : Some letters are omitted
3. Expected results : Some letters are not omitted
4. This character's unicode is '\xE9B6B4'

  1. Steps to reproduce
  2. Observed results
  3. Expected results

### Character data
  > 鶴 (\xE9B6B4)

### Screenshot
  > Error Image : 
![itext_font](https://user-images.githubusercontent.com/37133811/37076331-8a7867a2-2219-11e8-84ba-79f84026ba5d.PNG)
  > Expected Image :
![itext_font_ok](https://user-images.githubusercontent.com/37133811/37076394-bc5c9edc-2219-11e8-9c9f-5b942885aef9.PNG)

**Comment by kenlunde** [comment]
While I will check this particular glyph using Adobe's PDF producers tomorrow, my guess from years of experience is that this is likely to be a PDF producer (iText's PDF library) issue, not a font issue.

**Comment by kenlunde** [comment]
As suspected, Adobe's PDF producers have no issue with this particular character (see [this PDF](https://github.com/googlei18n/noto-fonts/files/1815355/uni9DB4-Serif-JP-SB.pdf) that references the same character and font). I recommend that you file a bug with iText.

**Comment by marekjez86** [comment]
@JaewonKimCJK : per @kenlunde please file a bug with iText or use Adobe PDF.

**Comment by JaewonKimCJK** [comment]
Thank you for your prompt response. This issue has been resolved with iText, appreciate for your suggestion. we are using iText 5.5.13, and that issue does not occur in this version anymore. 

Thanks again.
Regards,
