### ISSUE TITLE
Chakma Unicode adding 3 characters - add to Noto Sans Chakma

### ISSUE THREAD

**Issue by sven-oly** [googlei18n/noto-fonts#1087]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
Add 3 new Chakma Unicode characters to Noto Sans Chakma: U+11144 - U+11146

### Font 
Noto Sans Chakma

### Where the font came from, and when
https://github.com/googlei18n/noto-fonts/blob/master/hinted/NotoSansChakma-Regular.ttf

### Font Version
Version in Github, Sept 19, 2017.

### OS name and version
Any
### Application name and version
This can be seen in a test vesion here: http://languagetools-153419.appspot.com/ccp/
Select font Noto Sans Chakma.

### Issue
 1. Open http://languagetools-153419.appspot.com/ccp/
2. Select font "Noto Sans Chakma"
3. Type some characters using the virtual keyboard.
4. Type characters at "/", shift-Z and shift-";".
5. Touch "Code Points" to see the unicode values for each
6. Note that the last 3 are shown as "tofu".

Note that the font "RigengUni 2018-02-21" does include these 3 characters. Download this font at 
http://languagetools-153419.appspot.com/ccp/downloads/

The fact that these are missing in Noto Sans Chakma can be seen with any font viewing too such as FontForge.

### Character data
𑅆𑅄𑅅
U+011146 U+011144 U+011145 

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

![selection_075](https://user-images.githubusercontent.com/10751250/37315031-a2d0199a-2614-11e8-8b3a-c109fd5cbcc9.png)

**Comment by punchcutter** [comment]
These characters are not in Unicode yet. They have been accepted, but are not included in any release. They will be added to Noto Chakma when they appear in Unicode (11.0 probably).

**Comment by jungshik** [comment]
Luckily, it appears that we already have glyphs (not in the released version). So, we just have to add back them to the released version. 

@marekjez86  and @waksmonskiMT  :  It'd be great if you could sort this out. Thanks a lot !

**Comment by jungshik** [comment]
@sven-oly :  can you point us the list of new characters added to Unicode 11 with the above 3 Chakma characters?   

@punchcutter : according to @sven-oly , they will be IN Unicode 11 (due this summer). That being the case, they should be added to Noto Sans Chakma.

**Comment by jungshik** [comment]
@sven-oly   http://www.unicode.org/versions/Unicode11.0.0/ does not list Chakma characters.  Is it outdated? Again, please, give us a pointer to the definitive list of new characters in Unicode 11 that does include Chakma characters.

**Comment by jungshik** [comment]
I found.    http://www.unicode.org/charts/PDF/Unicode-11.0/  and http://www.unicode.org/charts/PDF/Unicode-11.0/U110-11100.pdf clearly show that they're in for Unicode 11.0 (due June 2018). 

So, they should be added.

**Comment by punchcutter** [comment]
As far as I know the current Noto spec is for Unicode 9.0 which is why these characters were not included in the original delivery. I don't even know about Unicode 10.0 much less 11.0. I would love to add these characters sooner rather than later, but that's something for @marekjez86 and others to decide.

**Comment by jungshik** [comment]
If you don't have glyphs for them and have to draw them, that'd be a different story. 
If you already have glyphs for them, there is absolutely no reason to hold them off from the release. 
(I already talked to @marekjez86 off-line).

**Comment by punchcutter** [comment]
Sounds great to me.

**Comment by punchcutter** [comment]
This is all addressed in the latest source delivery: https://github.com/googlei18n/noto-source/tree/master/src/NotoSansChakma
Once fonts have been generated in noto-fonts this can be confirmed and closed.

**Comment by punchcutter** [comment]
These characters have been in for quite a while now so this can be closed.

**Comment by sven-oly** [comment]
Is there a publicly available .ttf version of the updated font, including these 3 new characters?

**Comment by punchcutter** [comment]
The TTF on here has the latest: https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoSansChakma/NotoSansChakma-Regular.ttf
