### ISSUE TITLE
Release phase 3 fonts in OTF with CFF outlines as well.  

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#1091]
Phase 3 fonts have been released in TTF but not in OTF (CFF outlines). 

This is a bit ironic because  outlines from Monotype is actually cubic spline and is converted to quadratic splines to generate TTF. 

And the size difference is rather significant. For Deva Regular, OTF (CFF outlines) is about 50% smaller than TTF version.

**Comment by marekjez86** [comment]
see https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted 
I might re-organize the whole directory, but it require planning (tools make certain assumptions about the directory structure)
