### ISSUE TITLE
Add MARK and MKMK for Noto Serif, to support IPA

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#11]
```
The current Noto Serif lacks MARK and MKMK feature, and is not convinent to 
type IPA.
```

Original issue reported on code.google.com by `typeof....@gmail.com` on 15 Aug 2013 at 2:35

**Comment by behdad** [comment]
cc @roozbehp

**Comment by fontguy** [comment]
Please verify whether the Noto Serif fonts were updated to include the features required.

**Comment by jungshik** [comment]
Took a look at Noto Serif (Regular and Italic) and they do have mark and mmrk features for various diacritic marks + Latin base letters. 

I'll close this issue. Please, file a separate bug if there's any concrete bug/issue with IPA or other LGC.
