### ISSUE TITLE
'fi' and 'fl' ligatures in Noto Sans Mono

### ISSUE THREAD

**Issue by antonio-rojas** [googlei18n/noto-fonts#1129]
NotoSansMono-Regular.ttf
Version: 131072 from git b207fc3
Linux

Issue

Noto Sans Mono replaces the 'fi' and 'fl' characters by a ligature

Steps to reproduce
Choose Noto Sans Mono, type 'fi'
Observed results
'fi' ligature
Expected results
no ligature, as expected in a monospace font

**Comment by fitojb** [comment]
This is a duplicate of issue #1021. Please look for possible duplicates before reporting issues.
