### ISSUE TITLE
No support for Tibetan Uchen Font

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#114]
```
The page introducing the Noto fonts says that Tibetan is not yet supported. It 
has a page in the Unicode basic plane, so this absence is surprising.
```

Original issue reported on code.google.com by `bernie.s...@gmail.com` on 4 Aug 2014 at 12:54

**Comment by brawer** [comment]
Regarding the three groups of glyph combinations mentioned by Chris Fynn, is there a list somewhere? It might be interesting to check coverage of NotoSansTibetan.
http://www.google.com/get/noto/#sans-tibt
https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansTibetan-Regular.ttf?raw=true

**Comment by jungshik** [comment]
Our approach to Noto TIbetan is very similar to What Christ Fynn wrote.  Roughly, our font should support the first two groups ('roughly' because presumably, the boundaries between three groups are not cut and dried; the first group (everyday modern use) should be fully covered, though).

**Comment by brawer** [comment]
See also https://github.com/googlei18n/nototools/issues/38. It points to a page by Chris Fynn, where the Tibetan glyphs are split into usage groups.

**Comment by jungshik** [comment]
What's this bug about? Shouldn't we close this bug now that we do have Tibetan fonts?
