### ISSUE TITLE
Backwards two-story italic g

### ISSUE THREAD

**Issue by derektoplasm** [googlei18n/noto-fonts#1202]
### Title 
  > Backwards two-story lowercase italic g

### Font 
  > NotoSansJP, 400 (normal)
  > Italic is added with the in-app `_*_` markdown

### Where the font came from, and when
  >   Site: www.slack.com (within a workspace) 
  >   Date: 2017-05-30 

### OS name and version
  > MacOS High Sierra Version 10.13.4 (17E199)

### Application name and version
  > Saw it first in the slack app, went to the online channel and it was reproduced

### Issue
  > When adding the italic `_*_` markdown wrapper around text in Slack (app and online), the lowercase, two-story g is backwards. You know, like all those "can you believe no one knows what a two-story g looks like" stories that's been everywhere... 

Here's the HTML from the line: 
> `<i data-stringify-prefix="_" data-stringify-suffix="_" data-stringify-requires-siblings="true">being</i>`

Here's the screenshot: 
<img width="172" alt="screenshot 2018-05-30 18 36 38" src="https://user-images.githubusercontent.com/8525483/40751714-662330a4-643a-11e8-96b4-b088c806a79f.png">

**Comment by fitojb** [comment]
That is Lato, not Noto, and that style is intentional.

**Comment by derektoplasm** [comment]
huh. Never seen that before. Ok, I was wrong! 

CSS call:`body{font-family:NotoSansJP,Slack-Lato,appleLogo,sans-serif;}`, which made me think it was Noto, but I must be missing the part where it's applying Lato...
