### ISSUE TITLE
Some numbers displaying weird

### ISSUE THREAD

**Issue by softseal** [googlei18n/noto-fonts#1212]
I just installed the packages fonts-noto, fonts-noto-cjk and fonts-noto-color-emoji and have no idea which one caused it, so I am posting here.

Installed the fonts from command line yesterday ("sudo apt-get install fonts-noto" etc.) and saw the problem today. I am using Bodhi Linux.

The problem seems to only be appearing in Chrome, but I'm not sure, since it doesn't affect all numbers for some reason.

See screenshot - some numbers appear bold and with space around them when they shouldn't.
![shot-2018-06-07_13-40-12](https://user-images.githubusercontent.com/29129132/41095176-523fa0ac-6a59-11e8-9349-e7a590b3fa45.png)

EDIT: Just noticed that also any number I type in the address bar/edit bookmark appears weird, but not the ones I type, for example, here on Github.

**Comment by dougfelt** [comment]
Those look like emoji numbers to me.  Chrome should not be prioritizing emoji digits over non-emoji digits, but either it is or the font fallback order leads it to prioritize them?

**Comment by softseal** [comment]
How do I check the order/un-prioritize them?

**Comment by softseal** [comment]
Nevermind, found it out myself.

**Comment by KikeNet900** [comment]
I have the same issue, how have you solved it?

**Comment by softseal** [comment]
@KikeNet900 edited the file /home/user/.config/fontconfig/fonts.conf to this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>

<alias>
 	<family>sans-serif</family>
 	<prefer>
   		<family>Noto Sans</family>
   		<family>Noto Color Emoji</family>
   		<family>Noto Emoji</family>
 	</prefer> 
</alias>

<alias>
 <family>serif</family>
 <prefer>
   <family>Noto Serif</family>
   <family>Noto Color Emoji</family>
   <family>Noto Emoji</family>
 </prefer>
</alias>

<alias>
<family>monospace</family>
<prefer>
  <family>Noto Mono</family>
  <family>Noto Color Emoji</family>
  <family>Noto Emoji</family>
 </prefer>
</alias>

</fontconfig>
```
