### ISSUE TITLE
Various existing noto fonts missing characters

### ISSUE THREAD

**Issue by awsdert** [googlei18n/noto-fonts#1243]
## Defect Report
I was using BabelMapPortable composite font manager and it revealed that some of the noto fonts were in fact missing some characters so I had to use other fonts that had ALL the characters, I love the noto range and would like to set it where I can, these missing characters prevent me from doing so however.

### Title 
Various existing noto fonts missing characters

### Font 
Applies to multiple fonts, just look at them through a font manager to which ones are missing characters like I did

### Where the font came from, and when
 Site: https://noto-website-2.storage.googleapis.com/pkgs/Noto-hinted.zip
 Date: 2017-04-10 (I think, it didn't occur to me to report this until now)

### Font Version
I'm on windows but I don't think that matters since I was using BabelMapPortable

### OS name and version
I'm on windows but I don't think that matters since I was using BabelMapPortable

### Application name and version
Didn't try with other apps but given that it's missing characters I'm talking about I don't think I need to try on other apps

### Issue
I was using BabelMapPortable composite font manager and it revealed that some of the noto fonts were in fact missing some characters so I had to use other fonts that had ALL the characters, I love the noto range and would like to set it where I can, these missing characters prevent me from doing so however.

### Character data
Non-specific here, just look for the various fonts reporting less characters than the highest character count font in any composite font manager or just use BabelMap like I did

### Screenshot
Not needed

**Comment by marekjez86** [comment]
@awsdert : do you have an example of 1 or more character(s) missing and from which fonts? It is true that current Noto fonts are up to and including Unicode 9 and do not include 10 and 11. We plan to extend Noto in the future.

**Comment by awsdert** [comment]
I don't have specfic examples because there were so many report 1 or 2 characters less than the rest, just download the app I mentioned (BabelMap/Portable) and find the ones in the font manager that report less than the others and compare them to find the missing characters, more often than not the missing ones are gonna be common judging by what you just said so maybe skip by those and find the ones that aren't already on you're to do list
