### ISSUE TITLE
Missing Roman Numbers in Noto Sans Thai 

### ISSUE THREAD

**Issue by mathiasjespersen** [googlei18n/noto-fonts#1264]
**Font** 
Noto Sans Thai Regular (and all the other Thai weights)

**Issue**
The basic roman numbers are not included in the Noto Sans Thai. Fonts are quite useless in desktop environment without the roman numbers. 

**Proposed Solution**
Basic Latin glyphs should be added to all Thai fonts

<img width="872" alt="screen shot 2018-07-31 at 20 49 42" src="https://user-images.githubusercontent.com/5310965/43480410-7935f52e-9503-11e8-9a01-9b3a18266913.png">
.

**Comment by basxkong** [comment]
i have got the same problem so,
i decide to modify by my self as you can see attached file.
![capture](https://user-images.githubusercontent.com/42060889/43633511-a131990c-9733-11e8-8a9c-f23ddaf118b4.JPG)
then if i finish it i will let you know.

**Comment by mathiasjespersen** [comment]
@basxkong Thanks for "supporting" my issue. Does the licence/eula allow to modify and re-distribute the fonts? I couldn't figure that out.

**Comment by mathiasjespersen** [comment]
@basxkong Fantastic! Thanks for sharing and putting the work into it. 

And thanks for pointing to the SIL which clearly states what I was looking for:

> The OFL allows the licensed fonts to be used, studied, **modified and**
> **redistributed freely** as long as they are not sold by themselves. The
> fonts, including any derivative works, can be bundled, embedded,
> redistributed and/or sold with any software provided that any reserved
> names are not used by derivative works. 

It would still make sense to include the roman glyphs in the official release. And secondly hear way they where not included initially.

**Comment by marekjez86** [comment]
@mathiasjespersen : this was intentional. Each script contains just the Unicode block for that script (exception: some punctuation characters U+0021,U+0022,U+0027,U+0028,U+0029,U+002C,U+002D,U+002E,U+003A,U+003F,U+2018,U+2019,U+201C,U+201D,U+2026 are also included if relevant)
We also provide font merge utility at https://github.com/googlei18n/nototools/blob/master/nototools/merge_fonts.py

**Comment by vinshehe** [comment]
@basxkong Hi, would you mind to reshare your Noto Sans version that contains the numbers? The link you shared is not working anymore. 
Really appreciate your work. Thank you in advance!
