### ISSUE TITLE
Noto Sans Myanmar issues

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#127]
```
What steps will reproduce the problem?
1. If you type U+1081 then U+102F or U+1030, the result is not very readable.
2. I think stylistically U+1083 should have some kind of "tail" on the descend, 
and not just a straight line.

Attached are those combinations in Noto, Padauk, then Shan Mohne Unicode for 
your reference.

What version of the product are you using? On what operating system?
Windows.

Please provide any additional information below.

Thank you for the hard work!
```

Original issue reported on code.google.com by `ray...@gmail.com` on 9 Aug 2014 at 3:09

Attachments:
- [ScreenHunter_35 Aug. 09 23.08.jpg](https://storage.googleapis.com/google-code-attachments/noto/issue-127/comment-0/ScreenHunter_35 Aug. 09 23.08.jpg)

**Comment by behdad** [comment]
cc @behdad @jungshik @roozbehp

**Comment by jungshik** [comment]
@KatMomoi, could you verify that this issue was taken care of in the latest delivery (along with #467 and #563 ) ?  Ask @marchbox for the latest delivery.

**Comment by marekjez86** [comment]
fonts to be tested with; it's OK to pick just Regular and bold of each kind [NotoMyanmar.zip](https://github.com/googlei18n/noto-fonts/files/572893/NotoMyanmar.zip)

**Comment by marekjez86** [comment]
@roozbehp : is there a test case where we could use to verify the design changes or a  person who could look at the newest set of fonts?

I'm leaning toward closing this github bug.

**Comment by marekjez86** [comment]
results of the tests:

[NotoSansMyanmar3-Bold-MN.pdf](https://github.com/googlei18n/noto-fonts/files/581324/NotoSansMyanmar3-Bold-MN.pdf)
[NotoSansMyanmar3-Regular-MN.pdf](https://github.com/googlei18n/noto-fonts/files/581325/NotoSansMyanmar3-Regular-MN.pdf)

the tests are here


[Myanmar3.html.zip](https://github.com/googlei18n/noto-fonts/files/581328/Myanmar3.html.zip)
