### ISSUE TITLE
New Noto family is missing bullets/geometric characters

### ISSUE THREAD

**Issue by Eneen** [googlei18n/noto-fonts#1282]
### Font 
Noto 2.0 family

### Where the font came from, and when
https://www.google.com/get/noto/

### Font Version
2.0 and up

### Issue
New 2.0 fonts are missing extra bullets and geometric characters. They are very useful for bulleted lists, beginning/end of text marks and other graphical text additions. They were present in previous Noto family as shown on screenshot (from Scribus > Add glyph option):
![noto_missing_bullets](https://user-images.githubusercontent.com/25537418/45206699-f116d500-b285-11e8-8352-5ee929bfb850.jpg)
New Noto 2.0 contains only basic bullet 0x2022 character.

Seems like all unicode geometric elements are missing:
https://www.unicode.org/charts/nameslist/n_25A0.html

Hopefully they can be added again!

**Comment by dougfelt** [comment]
These characters are in the Symbols or Symbols 2 fonts.
