### ISSUE TITLE
Wrong glyph for U+2AAE EQUALS SIGN WITH BUMPY ABOVE

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1292]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06/phaseIII_only/unhinted/ttf/NotoSansMath/NotoSansMath-Regular.ttf
Date: 2018-09-12

### Font version
Version 1.900

### Issue
U+2AAE EQUALS SIGN WITH BUMPY ABOVE looks like U+224F DIFFERENCE BETWEEN, a minus sign with bumpy above.

### Character data
⪮
U+2AAE EQUALS SIGN WITH BUMPY ABOVE

### Screenshot
![⪮](https://user-images.githubusercontent.com/1124347/45557696-313d0100-b80c-11e8-93f1-f590c28053da.png)

**Comment by marekjez86** [comment]
Version 2 has

![math-1292](https://user-images.githubusercontent.com/13322623/52679471-0b667600-2eea-11e9-90fb-40d491c2e0d3.jpeg)

This one appears to be closed
