### ISSUE TITLE
Wrong glyph for U+2A6B TILDE OPERATOR WITH RISING DOTS

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1297]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06/phaseIII_only/unhinted/ttf/NotoSansMath/NotoSansMath-Regular.ttf
Date: 2018-09-12

### Font version
Version 1.900

### Issue
The dots of U+2A6B TILDE OPERATOR WITH RISING DOTS aren’t rising. Cf. U+2A2C MINUS SIGN WITH RISING DOTS.

### Character data
⩫
U+2A6B TILDE OPERATOR WITH RISING DOTS

### Screenshot
![⩫](https://user-images.githubusercontent.com/1124347/45642113-538d8380-ba85-11e8-9e41-e1211c1b95b9.png)

**Comment by marekjez86** [comment]
in 2.000

![math-1297](https://user-images.githubusercontent.com/13322623/52679844-3ef5d000-2eeb-11e9-824d-ddec2775b671.jpeg)

**Comment by marekjez86** [comment]
appears to be fixed.
