### ISSUE TITLE
Wrong glyph for U+2AB6 SUCCEEDS ABOVE NOT EQUAL TO

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1299]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06/phaseIII_only/unhinted/ttf/NotoSansMath/NotoSansMath-Regular.ttf
Date: 2018-09-12

### Font version
Version 1.900

### Issue
The glyph of U+2AB6 SUCCEEDS ABOVE NOT EQUAL TO looks like its opposite, U+2AB5 PRECEDES ABOVE NOT EQUAL TO.

### Character data
⪶
U+2AB6 SUCCEEDS ABOVE NOT EQUAL TO

### Screenshot
![⪶](https://user-images.githubusercontent.com/1124347/45757658-e9deb800-bbf1-11e8-86fc-2f06e346f9fc.png)

**Comment by marekjez86** [comment]
now it has

![math-1299](https://user-images.githubusercontent.com/13322623/52680634-01467680-2eee-11e9-8ca8-b9ba2c8ec21a.jpeg)

@dscorbett : what do you think?

**Comment by dscorbett** [comment]
I think it is done too.
