### ISSUE TITLE
Wrong glyph for U+2AD9 ELEMENT OF OPENING DOWNWARDS

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1301]
### Font
NotoSansMath-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/db5c897c3954ab8dd49bfc3de4f3ef00a7ef6d06/phaseIII_only/unhinted/ttf/NotoSansMath/NotoSansMath-Regular.ttf
Date: 2018-09-12

### Font version
Version 1.900

### Issue
The glyph of U+2AD9 ELEMENT OF OPENING DOWNWARDS looks similar to U+22D4 PITCHFORK, with the vertical stroke protruding past the top of the curve, instead of like an inverted U+27D2 ELEMENT OF OPENING UPWARDS. The ISOAMSR entity name of U+2AD9 is forkv, i.e. “fork, variant”, so it is meant to be distinguishable from U+22D4 PITCHFORK.

### Character data
⫙
U+2AD9 ELEMENT OF OPENING DOWNWARDS

### Screenshot
![⫙](https://user-images.githubusercontent.com/1124347/45885270-fabf3300-bd83-11e8-85c5-0f346f39e67d.png)

**Comment by marekjez86** [comment]
version 2.0 has

![math-1301](https://user-images.githubusercontent.com/13322623/52680806-b37e3e00-2eee-11e9-9fb6-9c004770a617.jpeg)

**Comment by dscorbett** [comment]
Yes, it is fixed.
