### ISSUE TITLE
wpf Italic issue

### ISSUE THREAD

**Issue by kyungsik8090** [googlei18n/noto-fonts#1314]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
  > Font Style is not working

### Font 
  > NotoSansCJKkr-Bold.otf,
  > NotoSansCJKkr-Regular.otf.
__
### Where the font came from, and when
  >   Site: https://www.google.co.kr/get/noto/#sans-kore
  >   Date: 2017-11-23 

### Font Version
  > NotoSansCJKkr-Bold.otf - 1.004;PS 1.004;hotconv 1.0.82; makeotf.lib2.5.63406
  > NotoSansCJKkr-Regular.otf - 1.004;PS 1.004;hotconv 1.0.82; makeotf.lib2.5.63406

### OS name and version
  > OS : Windows7, 10

### Application name and version
  > WPF

### Issue
  1. WPF Xaml Code 
  2. TextBlock control
  3. Set FontFamily : "Noto Sans CJK KR Regular" OR "Noto Sans CJK KR Bold"
  4. Set FontStyle : Italic
  5. Not Displayed FontStyle

### Screenshot
 
![default](https://user-images.githubusercontent.com/43743058/46283112-002a3380-c563-11e8-9057-00ed5a308fa4.JPG)

**Comment by marekjez86** [comment]
@kenlunde : I don't think we have italic so I'm not sure how it is supposed to work

**Comment by kenlunde** [comment]
There are no italic glyphs in the _Noto CJK_ fonts, and there are no plans to add such glyphs. Style-linking, from Regular to Bold, works in _Noto Serif CJK_ from Version 1.000, and will work in _Noto Sans CJK_ Version 2.000.
