### ISSUE TITLE
Request to add 'Vithkuqi' font for Albanian

### ISSUE THREAD

**Issue by boricensis** [googlei18n/noto-fonts#1357]
## New font request
Officially, the Albanian language is written using Latin characters. However, there is a native 19th century script known as the [Vithkuqi Alphabet](https://en.wikipedia.org/wiki/Vithkuqi_alphabet), which Unicode has incorporated and which would be an invaluable addition to the noto font families.

### Title 
  > Add a Vithkuqi Alphabet font for Albanian

### Font 
  > Full file name: N/A
  Due to copyright issues, I am unable to provide any fonts developed for illustration by, or on behalf of, Unicode (see comments below, but feel free to reach out to the Unicode font author directly and the author of this report: https://www.unicode.org/L2/L2017/17316-n4854-vithkuqi.pdf). 

### Issue
  > Unicode range: 10570 to 105BF

**Comment by Evertype** [comment]
You do not have permission to extract this font from that PDF and you do not have permission to release it to the Noto font families. 

Michael Everson

**Comment by boricensis** [comment]
I humbly apologize and I will remove everything right away! I had assumed
the fact they were not protected in the pdf had been implied open use and I
was wrong. Once again, my apologies!

**Comment by Evertype** [comment]
Embedded fonts mean they are embedded for the document, not for extraction and further dissemination. Google has never taken much interest in my work, though long ago I had a nice chat with Dave Crossland about them. It is certainly wrong though to take glyphs and distribute them without checking with evident rights holders. Thank you for agreeing to remove the file.

**Comment by boricensis** [comment]
One action you could take in the future is protect embedded fonts from extraction. It's what many artists I know do...

**Comment by Evertype** [comment]
How is that accomplished?

**Comment by boricensis** [comment]
I wouldn't be familiar with the how.

But as one who believes in collective creativity powers, I'd advocate a Creative Commons license to virtually any work.

**Comment by dscorbett** [comment]
The unlicensed font ZIP is still available, just hidden. You have to [delete that revision of the comment](https://help.github.com/articles/tracking-changes-in-a-comment/#deleting-sensitive-information-from-a-comments-history).

There won’t be a Noto font for Vithkuqi until it is added to Unicode. The PDF you’ve linked to is a preliminary proposal, not an official Unicode code chart.

**Comment by boricensis** [comment]
The revisions have been deleted

**Comment by Evertype** [comment]
Perhaps one can advocate for a Creative Commons licence for any work if one is independentely wealthy and secure, William.

**Comment by NorbertLindenberg** [comment]
The unlicensed font ZIP is still available to anyone who was notified by Github about the original issue report – the link contained in the email still works.

**Comment by Evertype** [comment]
Please fix this. 

Michael Everson
http://evertype.com

**Comment by boricensis** [comment]
> The unlicensed font ZIP is still available to anyone who was notified by Github about the original issue report – the link contained in the email still works.

Norbert, GitHub support is asking me for the ZIP URL. Could you please email that to me at wb@itheorist.com because I cannot find it anywhere. GitHub support will then permanently delete it. Many thanks.

**Comment by twardoch** [comment]
It's not possible to protect a font embedded into a PDF from extraction. If the PDF is supposed to be rendered on screen, then the app that renders the PDF must read the font in order to display the text, and if it reads the font, it can extract it. PDF is a public format and there are hundreds of software packages that parse it (many of them opensource), and each of them reads the font streams just as it does any other PDF stream. When WOFF was first proposed, one of the ideas was that it would "protect" the web fonts from being used in the desktops. Well, in order to display the font, a browser must decode the WOFF and pass its SFNT structure to the font renderer. Since the most popular broesers are opensource... you know the rest.

**Comment by twardoch** [comment]
I think that the Noto font project would achieve its goal of providing “at least one glyph for each Unicode codepoint) faster if, for the lesser-user and still not covered scripts, it acquired a license from Michael Everson (Evertype) to publish his fonts in the Noto project under OFL. 

Michael is a tireless script researcher, and a prolific writer of Unicode proposals — and for some scripts, he effectively is the source of the only digital fonts for a given script. 

As far as I’m aware, Michael does not do complex script font development (with OpenType Layout behavior), but for non-complex scripts, his fonts would certainly be a useful addition to the “long tail” of not-yet-covered Unicode.

**Comment by boricensis** [comment]
The attachment (which @NorbertLindenberg mentioned above) has been permanently removed by GitHub Support.

**Comment by Evertype** [comment]
Noto has always ignored me. 

Michael Everson
http://evertype.com

**Comment by EkiRahardian** [comment]
Can we reopen this issue since Vithkuqi script is finally on Unicode?
