### ISSUE TITLE
Overlapping U+1172B AHOM SIGN KILLER

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1358]
### Font
NotoSerifAhom-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/d7af81e614086435102cca95961b141b3530a027/hinted/NotoSerifAhom-Regular.ttf
Date: 2018-10-24

### Font version
Version 2.001;GOOG;noto-source:20181019:f8f3770

### Issue
Repeated Ahom viramas overlap each other. See [L2/12-309R figure 3](https://www.unicode.org/L2/L2012/12309r-n4321r.pdf#page=10).

### Character data
𑜃𑜫𑜫
U+11703 AHOM LETTER NA
U+1172B AHOM SIGN KILLER
U+1172B AHOM SIGN KILLER

### Screenshot
![𑜃𑜫𑜫](https://user-images.githubusercontent.com/1124347/47468053-4459ce00-d7c7-11e8-8a81-93574715a3c6.png)

**Comment by marekjez86** [comment]
![aho-1358-Serif](https://user-images.githubusercontent.com/13322623/54712069-9c8fc480-4b08-11e9-9996-4943fbfadc3a.jpg)
@dscorbett : per MTI - fixed. If you see any issues please reopen.
