### ISSUE TITLE
Non-ligating U+1171F AHOM CONSONANT SIGN MEDIAL LIGATING RA

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1359]
### Font
NotoSerifAhom-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/d7af81e614086435102cca95961b141b3530a027/hinted/NotoSerifAhom-Regular.ttf
Date: 2018-10-24

### Font version
Version 2.001;GOOG;noto-source:20181019:f8f3770

### Issue
According to [L2/12-0309R](https://www.unicode.org/L2/L2012/12309r-n4321r.pdf), U+1171F AHOM CONSONANT SIGN MEDIAL LIGATING RA represents the medial <i>ra</i> in two archaic ligatures of <i>khra</i> and <i>phra</i>. However, the font only forms those ligatures when 'dlig' is enabled. The ligatures should always be formed: that is why U+1171F is called “LIGATING”.

### Character data
𑜁𑜟𑜇𑜟
U+11701 AHOM LETTER KHA
U+1171F AHOM CONSONANT SIGN MEDIAL LIGATING RA
U+11707 AHOM LETTER PHA
U+1171F AHOM CONSONANT SIGN MEDIAL LIGATING RA

### Screenshot
![𑜁𑜟𑜇𑜟](https://user-images.githubusercontent.com/1124347/47525488-6311a080-d86b-11e8-87c6-8e79469efadf.png)

**Comment by marekjez86** [comment]
![aho-1359-Serif](https://user-images.githubusercontent.com/13322623/54712019-7d913280-4b08-11e9-84c6-4e13e1375acc.jpg)
@dscorbett : per MTI - fixed. If you see any issues please reopen.

**Comment by dougfelt** [comment]
Hey Marek, just a question about these.  It seems all of these sample strings (plus font/script/language) could be regression test cases.  Are they being collected anywhere?  There was a repo and diff tool that Sascha Brawer created, not sure if they're integrated into some kind of regression testing or not.

**Comment by dougfelt** [comment]
@marekjez86 oops should have tagged you in my previous comment.

**Comment by marekjez86** [comment]
@dougfelt : I created a directory https://github.com/googlei18n/noto-source/tree/master/test where I gather interesting html files. I use most of them via fontdiff (aka Sascha's diff tool), but there are some with more complex html which fontdiff cannot handle, but they are still useful to use as tests.

For example, to test this issue I created https://github.com/googlei18n/noto-source/blob/master/test/Ahom/aho-1359.html (my current pattern for the filename is <lang-code>-<issue-num>.html )

**Comment by dougfelt** [comment]
Excellent, thanks for the info!
