### ISSUE TITLE
Wrong code point for Ahom glyph u11714.alt

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1360]
### Font
NotoSerifAhom-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/d7af81e614086435102cca95961b141b3530a027/hinted/NotoSerifAhom-Regular.ttf
Date: 2018-10-24

### Font version
Version 2.001;GOOG;noto-source:20181019:f8f3770

### Issue
According to [L2/12-0309R](https://www.unicode.org/L2/L2012/12309r-n4321r.pdf#page=5), the glyph called u11714.alt in Noto Serif Ahom “is a font variant of `AHOM LETTER GA (U+11714)`”. However, U+11714 is AHOM LETTER DHA: the proposal got the code point wrong, and the glyph should be a stylistic alternative of u11715. I know this is a form of <i>ga</i> and not <i>dha</i> because [the earlier version of the proposal](https://www.unicode.org/L2/L2012/12222-ahom.pdf#page=3) calls it GA and writes the code point consistently.

### Character data
𑜔𑜕
U+11714 AHOM LETTER DHA
U+11715 AHOM LETTER GA

### Screenshot
With 'salt':
![𑜔𑜕](https://user-images.githubusercontent.com/1124347/47596307-86177f80-d953-11e8-946c-b690ae95124d.png)

**Comment by marekjez86** [comment]
![aho-1360-Serif](https://user-images.githubusercontent.com/13322623/54711927-44f15900-4b08-11e9-9c80-7cf727883553.jpg)
@dscorbett : per MTI - fixed. If you see any issues please reopen.
