### ISSUE TITLE
Wrong glyph for U+11734 AHOM DIGIT FOUR

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1361]
### Font
NotoSerifAhom-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/d7af81e614086435102cca95961b141b3530a027/hinted/NotoSerifAhom-Regular.ttf
Date: 2018-10-24

### Font version
Version 2.001;GOOG;noto-source:20181019:f8f3770

### Issue
U+11734 AHOM DIGIT FOUR should look like 𑜏𑜣 <i>sī</i> but looks like 𑜏 <i>sa</i>.

### Character data
𑜴
U+11734 AHOM DIGIT FOUR

### Screenshot
![𑜴](https://user-images.githubusercontent.com/1124347/47618383-db18da00-daa8-11e8-877f-c65c631975d4.png)

**Comment by marekjez86** [comment]
![aho-1361-Serif](https://user-images.githubusercontent.com/13322623/54711858-1a9f9b80-4b08-11e9-9496-966843214738.jpg)
@dscorbett : per MTI - fixed. If you see any issues please reopen.
