### ISSUE TITLE
Inconsistent kerning in Ahom

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1372]
### Font
NotoSerifAhom-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/d7af81e614086435102cca95961b141b3530a027/hinted/NotoSerifAhom-Regular.ttf
Date: 2018-10-24

### Font version
Version 2.001;GOOG;noto-source:20181019:f8f3770

### Issue
Ahom <i>na</i> and <i>-i</i> are kerned apart, except when the syllable also includes <i>-u</i>. The <i>-u</i> does not modify or appear between the other two glyphs, so I’d expect it to have no effect on their spacing.

### Character data
𑜃𑜢
U+11703 AHOM LETTER NA
U+11722 AHOM VOWEL SIGN I
𑜃𑜢𑜤
U+11703 AHOM LETTER NA
U+11722 AHOM VOWEL SIGN I
U+11724 AHOM VOWEL SIGN U

### Screenshot
![𑜃𑜢 𑜃𑜢𑜤](https://user-images.githubusercontent.com/1124347/48221939-5dcf4e00-e361-11e8-9dbe-7a8eafc1db66.png)

**Comment by marekjez86** [comment]
![aho-1372-Serif](https://user-images.githubusercontent.com/13322623/54711898-2c813e80-4b08-11e9-9688-0d37577c41bc.jpg)
@dscorbett : per MTI - fixed. If you see any issues please reopen.

**Comment by dscorbett** [comment]
This bug is fixed, but the second string looks quite different than how it did in the previous version. Was that intentional?

**Comment by punchcutter** [comment]
The second string was actually wrong in the first place. The special I+U vowel ligature should not come after nga, na, da, or nya. In places where it does occur the spacing matches for both situations.
