### ISSUE TITLE
U+111CA SHARADA SIGN NUKTA blocks ligatures

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1387]
### Font
NotoSansSharada-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansSharada-Regular.ttf
Date: 2018-11-09

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
U+111CA SHARADA SIGN NUKTA blocks consonant–vowel ligatures in Sharada.

### Character data
𑆘𑆳𑆘𑇊𑆳
U+11198 SHARADA LETTER JA
U+111B3 SHARADA VOWEL SIGN AA
U+11198 SHARADA LETTER JA
U+111CA SHARADA SIGN NUKTA
U+111B3 SHARADA VOWEL SIGN AA

### Screenshot
![𑆘𑆳𑆘𑇊𑆳](https://user-images.githubusercontent.com/1124347/48906901-f7076580-ee33-11e8-9ace-e4933a02cdac.png)

**Comment by marekjez86** [comment]
![shrd-1387-Sans](https://user-images.githubusercontent.com/13322623/54712199-f5f7f380-4b08-11e9-898d-02d1096dea81.jpg)
@dscorbett : per MTI - fixed. If you see any issues please reopen.
