### ISSUE TITLE
Overlapping marks in Sharada

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1389]
### Font
NotoSansSharada-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansSharada-Regular.ttf
Date: 2018-11-09

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
Sharada vowel signs overlap other marks above.

### Character data
𑆤𑆵𑆀𑆤𑆴𑆁𑇂𑆑𑆼𑇃𑆥𑆽
U+111A4 SHARADA LETTER NA
U+111B5 SHARADA VOWEL SIGN II
U+11180 SHARADA SIGN CANDRABINDU
U+111A4 SHARADA LETTER NA
U+111B4 SHARADA VOWEL SIGN I
U+11181 SHARADA SIGN ANUSVARA
U+111C2 SHARADA SIGN JIHVAMULIYA
U+11191 SHARADA LETTER KA
U+111BC SHARADA VOWEL SIGN E
U+111C3 SHARADA SIGN UPADHMANIYA
U+111A5 SHARADA LETTER PA
U+111BD SHARADA VOWEL SIGN AI

### Screenshot
![𑆤𑆵𑆀𑆤𑆴𑆁𑇂𑆑𑆼𑇃𑆥𑆽](https://user-images.githubusercontent.com/1124347/48969000-dbcc5f80-efc5-11e8-96f1-b0f36669ff72.png)

**Comment by marekjez86** [comment]
![shrd-1389-Sans](https://user-images.githubusercontent.com/13322623/54712157-e082c980-4b08-11e9-9cf2-18b4189b2ba8.jpg)
@dscorbett : per MTI - fixed. If you see any issues please reopen.

**Comment by marekjez86** [comment]
<img width="273" alt="Screen Shot 2022-02-02 at 09 20 56" src="https://user-images.githubusercontent.com/13322623/152204530-2fe20d90-b9a1-4b21-ae75-ecdf5071961b.png">

Possibly two issues with the conversion (using 2.004):
1. the dot is over the third character (I believe it should be over the second)
2. half a circle and a dot should be over the first character

**Comment by marekjez86** [comment]
BTW, it got broken early (I think in the first release). I just didn't notice then.

**Comment by simoncozens** [comment]
Yeah. That was actually one of the test strings. I made sure that the new version was exactly as broken as the previous one. :-)

**Comment by marekjez86** [comment]
@simoncozens : great work :-)
