### ISSUE TITLE
Misplaced U+111C9 SHARADA SANDHI MARK

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1390]
### Font
NotoSansSharada-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansSharada-Regular.ttf
Date: 2018-11-09

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
According to [L2/12-322](https://www.unicode.org/L2/L2012/12322-n4330-sharada-sandhi-mark.pdf#page=4), one or two U+111C9 SHARADA SANDHI MARKs should be centered below U+111B3 SHARADA VOWEL SIGN AA.

### Character data
𑆩𑆳𑇉𑆩𑆳𑇉𑇉
U+111A9 SHARADA LETTER MA
U+111B3 SHARADA VOWEL SIGN AA
U+111C9 SHARADA SANDHI MARK
U+111A9 SHARADA LETTER MA
U+111B3 SHARADA VOWEL SIGN AA
U+111C9 SHARADA SANDHI MARK
U+111C9 SHARADA SANDHI MARK

### Screenshot
![𑆩𑆳𑇉𑆩𑆳𑇉𑇉](https://user-images.githubusercontent.com/1124347/48982319-e9a9df80-f0ae-11e8-9a7a-d2898c40b886.png)

**Comment by marekjez86** [comment]
![shrd-1390-Sans](https://user-images.githubusercontent.com/13322623/54712129-cba63600-4b08-11e9-9c90-3cf8d59b5b92.jpg)
@dscorbett : per MTI - fixed. If you see any issues please reopen.
