### ISSUE TITLE
Overlapping U+1123E KHOJKI SIGN SUKUN

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1396]
### Font
NotoSansKhojki-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/85e78f831469323c85847e23f95026c894159135/unhinted/NotoSansKhojki-Regular.ttf
Date: 2018-11-30

### Font version
Version 2.000

### Issue
U+1123E KHOJKI SIGN SUKUN overlaps marks above.

### Character data
𑈈𑈶𑈾
U+11208 KHOJKI LETTER KA
U+11236 KHOJKI SIGN NUKTA
U+1123E KHOJKI SIGN SUKUN

### Screenshot
![𑈈𑈶𑈾](https://user-images.githubusercontent.com/1124347/49297988-3d8b3e80-f48a-11e8-9984-f6e5002ced6d.png)

**Comment by marekjez86** [comment]
Updated sources at https://github.com/googlei18n/noto-source/tree/master/src/NotoSansKhojki , rebuilt Khojki font and tested them. Then released new update to https://github.com/googlei18n/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansKhojki/NotoSansKhojki-Regular.otf?raw=true (and corresponding ttf) which fixes the above problem.
test file is at https://github.com/googlei18n/noto-source/blob/master/test/Khojki/Khojki-1396.html

**Comment by davelab6** [comment]
Thanks Marek!

**Comment by davelab6** [comment]
And thank you @dscorbett for reporting!!
