### ISSUE TITLE
Wrong glyphs for Sharada kl̥ and kl̥̄

### ISSUE THREAD

**Issue by dscorbett** [googlei18n/noto-fonts#1402]
### Font
NotoSansSharada-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansSharada-Regular.ttf
Date: 2018-11-09

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
<i>Kl̥</i> and <i>kl̥̄</i> use the forms of <i>-l̥</i> and <i>-l̥̄</i> that [L2/15-255](https://unicode.org/L2/L2015/15255-sharada-vocalic-vs.pdf) explains are inauthentic.

### Character data
𑆑𑆺𑆑𑆻
U+11191 SHARADA LETTER KA
U+111BA SHARADA VOWEL SIGN VOCALIC L
U+11191 SHARADA LETTER KA
U+111BB SHARADA VOWEL SIGN VOCALIC LL

### Screenshot
![𑆑𑆺𑆑𑆻](https://user-images.githubusercontent.com/1124347/49482382-e6c09480-f7fc-11e8-9042-74843819d57d.png)

**Comment by marekjez86** [comment]
![shrd-1402-Sans](https://user-images.githubusercontent.com/13322623/54712091-afa29480-4b08-11e9-88ec-99b1a9c0d398.jpg)
@dscorbett : per MTI - fixed. If you see any issues please reopen.
