### ISSUE TITLE
Push commit messeges to noto-font@googlegroups.com list

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#141]
```
What steps will reproduce the problem?
1. Do any commit in noto git repo.
2. No email getting on noto-font@googlegroups.com

What is the expected output? What do you see instead?
Notification of commits vai email to noto-font@googlegroups.com

What version of the product are you using? On what operating system?
Latest noto

Please provide any additional information below.


```

Original issue reported on code.google.com by `pravin....@gmail.com` on 4 Sep 2014 at 7:19

**Comment by xiangyexiao** [comment]
not valid issue any more since we move.

**Comment by behdad** [comment]
Still relevant.  I'll set it up soon.

**Comment by dougfelt** [comment]
I don't see a straightforward way to set this up.  Does anyone know how to do this?  Have I just missed something blindingly obvious?

Even as a user I can't get fine-grained control over what actions trigger notifications.  I can choose to get email or github messages, but I can't say just notify me for commits/pushes and nothing else.

Looking at the developer docs it appears I can use webhooks or the developer API to get notifications sent to a server, which I could then do anything with.  But I'd have to set up a server.

**Comment by behdad** [comment]
Here:
https://github.com/googlei18n/noto-fonts/settings/hooks/new?service=email

**Comment by dougfelt** [comment]
I do not have access to the setting pages of our repositories.  I never see
a UI to get to the settings, and get a 404 when I try the url.  This is not
the case for the repository clones I created, so I must not be ACL'd for
these operations on the googlei18n repos.

**Comment by behdad** [comment]
Fixed.

**Comment by hrhatada** [comment]
This issue has not been updated since 08/24/2015.  I got 404 error to open https://github.com/googlei18n/noto-fonts/settings/hooks/new?service=email. Is this issue still relevant?

**Comment by dougfelt** [comment]
@hrhatada I don't get a 404 error when I click on that link.  I do get prompted to login to github.  Did this formerly work for you?
