### ISSUE TITLE
Noto Sans Javanese Regular file is a duplicate of the Bold weight

### ISSUE THREAD

**Issue by adtbayuperdana** [googlei18n/noto-fonts#1411]
### Font 
NotoSansJavanese-Bold.otf
NotoSansJavanese-Regular.otf

### Where the font came from, and when
  >   Site: https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansJavanese
  >   Date: 2018-12-18

### Issue
  > The weight of Noto Sans Javanese Regular in the downloaded file is identical with the Noto Sans Javanese Bold, which means the regular weight file is missing and cannot be obtained.

**Comment by marekjez86** [comment]
My bad. I messed up Linux commands while copying the files from build to release directories. 
Please check again.

**Comment by marekjez86** [comment]
@adtbayuperdana : thank you!!!!
