### ISSUE TITLE
Design inconsistencies in Noto Sans Javanese

### ISSUE THREAD

**Issue by bennylin** [googlei18n/noto-fonts#1426]
### Title 
  > The design of several glyphs need some adjustment for readability (legibility) and consistency between Regular and Bold, especially glyphs U+A993, A9AD, A9D7, A9BA, A9BB

### Font 
  > 'NotoSansJavanese-Regular.ttf' and 'NotoSansJavanese-Bold.ttf'

### Where the font came from, and when
  >   Site: https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansJavanese
  >   Date: 2019-01-15 (preferred format)

### Font Version
  > * Win -- It's version 1.01 for regular, and 2.000 for Bold

### OS name and version
  > Win 10 ver 1703

### Application name and version
  > Tested in Firefox 61, Edge 40, and IE 11

### Issue

![image](https://user-images.githubusercontent.com/3002108/51406574-50d89300-1b38-11e9-8e10-787ecf2b4212.png)

  > U+A993 (Ga Murda): The shape of the Bold one is correct, while the Regular shape's left side should form an "m" like shape. That shape too much resemble A992 or A9AB, which would affect readability. The pasangan in Bold is correct, while the pasangan in Regular is wrong.

  > U+A9AD (La): Similar as above. The shape of the Bold one is correct, while the Regular shape's left side should form an "m" like shape. That shape too much resemble A992 or A9AB, which would affect readibility. The pasangan in Bold is correct, while the shape of the pasangan in Regular also has the defect as the base.

  > U+A9D7 (numeral 7): It has the same shape as U+A993 (La), minus the pasangan.

  > U+A9BA and U+A9BB: same comments as above. The left part of the glyphs should looks more like the letter "m".

### Character data
  > U+A993, U+A9AD, U+A9AD, U+A9D7, U+A9BA and U+A9BB

### Screenshot
  > Screenshot already included in the Issue. Taken in Microsoft Word Office 365

**Comment by punchcutter** [comment]
You are comparing the very old version 1.01 Regular with the new version 2.0 Bold. Version 2 is a complete redesign so version 1.01 Regular is irrelevant. You need to compare the new Regular and Bold.

**Comment by bennylin** [comment]
Please add tag Script-Javanese

**Comment by bennylin** [comment]
> 
> 
> You are comparing the very old version 1.01 Regular with the new version 2.0 Bold. Version 2 is a complete redesign so version 1.01 Regular is irrelevant. You need to compare the new Regular and Bold.

I'm downloading it (again) from the latest version here (dated 29 days ago) https://github.com/googlei18n/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoSansJavanese/NotoSansJavanese-Regular.ttf

If you're saying they're not the latest one, please do tell me where I can find the latest one.

**Comment by punchcutter** [comment]
Those should be the latest or https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansJavanese-Regular.ttf and https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansJavanese-Bold.ttf
You probably need to delete the old one on Windows first. I suspect when you install it's adding a new file to your C:\Windows\Fonts folder, but not using it. When I have that issue I use cmd as administrator and delete all the old files completely before installing.

**Comment by bennylin** [comment]
> 
> 
> Those should be the latest or https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansJavanese-Regular.ttf and https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansJavanese-Bold.ttf
> You probably need to delete the old one on Windows first. I suspect when you install it's adding a new file to your C:\Windows\Fonts folder, but not using it. When I have that issue I use cmd as administrator and delete all the old files completely before installing.

That seems to do the trick. Thanks. Now it appears correctly

![image](https://user-images.githubusercontent.com/3002108/51409731-669e8600-1b41-11e9-8cbe-10a75da11f73.png)
