### ISSUE TITLE
Old Hungarian non-UNICODE characters must be remove

### ISSUE THREAD

**Issue by Kixidevel** [googlei18n/noto-fonts#1440]
## Defect Report
There are non UNICODE chars in Old Hungarian font, 
### Title 
Ad-hoc letters in Old Hungarian Noto fonts
### Font
NotoSansOldHungarian-Regular.ttf
 ### Character data
 https://unicode.org/charts/PDF/U10C80.pdf
### Screenshot
  
![kepernyokep errol 2019-02-10 09-18-00](https://user-images.githubusercontent.com/32356899/52531389-f5538c80-2d14-11e9-9752-b0764261beae.png)

**Comment by Kixidevel** [comment]
Please, remove the additional characters, most of them (example signed .ltr) never will be appeared.
NoTofu doesn't mean pushing letters stuff. Must to keep the UNICODE standard.

**Comment by Kixidevel** [comment]
The true UNICODE table:
![kepernyokep errol 2019-02-10 09-38-17](https://user-images.githubusercontent.com/32356899/52531574-d6a2c500-2d17-11e9-9981-aaa07633dcd9.png)

**Comment by Kixidevel** [comment]
The archived, stuffed, non full UNICODE compatible font site:
Site: https://github.com/googlei18n/noto-fonts/blob/d7af81e614086435102cca95961b141b3530a027/hinted/NotoSansOldHungarian-Regular.ttf

**Comment by brawer** [comment]
Why do you believe that the font is not Unicode-compliant?

For quite many writing systems, well-made fonts have to contain more glyphs than you’ll see in the Unicode chart. This is because Unicode encodes abstract codepoints, whereas a font contains visual glyphs. For an introduction to codepoints versus glyphs, see [chapter 1 of the Unicode specification](http://www.unicode.org/versions/Unicode11.0.0/ch01.pdf).

Old Hungarian is typically written in right-to-left line direction. However, users may choose to override the default line direction so that characters are written from left to right. For this unusual line direction, the Noto font supplies alternate mirrored glyph shapes via an [OpenType ‘ltrm’ table](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko#a-nameltrm-idltrmatag-39ltrm39). This mechanism is completely compliant with Unicode and OpenType.

At a first sight, it’s not clear whether alternate shapes are actually needed for Old Hungarian. Many sources write that Old Hungarian is always written right-to-left. But a few places, such as [the Wikipedia article on Boustrophedon](https://en.wikipedia.org/wiki/Boustrophedon), claim that Old Hungarian can occasionally get written in left-to-right order. In any case, the right-to-left shapes are the font’s default.

**Comment by brawer** [comment]
Also, a font may contain ligatures to visually combine glyphs. For example, Noto Sans Old Hungarian contains two different ligatures for the codepoint sequence `U+10CD9 U+10CD0`; which one gets used depends on the line direction. Unicode encodes logical codepoints, not visual glyph shapes; so this is completely standards-compliant, even if you can’t find those ligatures in the Unicode charts. You’ll encounter such ligatures (and other alternate glyph shapes) with pretty much any high-quality font.

![image](https://user-images.githubusercontent.com/1527880/52622004-0f25d880-2ea9-11e9-979a-17f97688b26f.png)

**Comment by Kixidevel** [comment]
Please see the https://unicode.org/charts/PDF/U10C80.pdf
document. This is the legal UNICONE standard of the Old Hungarian font.
There are a lots of extensions everywhere. Different Hungarian "Rovás" communities disagree with each other about the extensions!
[U10C80.pdf](https://github.com/googlei18n/noto-fonts/files/2856375/U10C80.pdf)

**Comment by Kixidevel** [comment]
Sorry, I got a spelling mistake, I wrote UNICONE instead of UNICODE.

**Comment by Kixidevel** [comment]
@brawer 
Do You know, what does "blob" mean? The binary object is too large.
Do You know, how do work ttf fonts? The logical letters aren't appearing!
Do You know, what is the UNICODE consortium? 
Do You know, which is the official page of UNICODE consortium?  It is unicode.org, it isn't the wikipedia.
There are lot of "facts" on the sites of wikipedia that have never been controlled!

**Comment by Kixidevel** [comment]
@marekjez86 
Will be removed non standard and logical letters from the NotoSansOldHungarian-Regular fontfile?

**Comment by marekjez86** [comment]
@brawer : good to see you. Thank you for the feedback.

@Kixidevel : 

Noto NotoSansOldHungarian-Regular supports the Unicode table:

![notosansoldhungarian](https://user-images.githubusercontent.com/13322623/53086027-1ce6e980-34b9-11e9-879f-89a8978547de.jpeg)

Do you see in the table above that IS NOT part of Old Hungarian block in the Unicode?

Outside of a subset from U+10C80..U+10CFF only space U+0020, ZWJ U+200D and 'HYPHEN-MINUS' U+002D are the only other Unicode codpoints present in the font file Noto Sans Old Hungarian file. 

All other glyphs and data present in the file that you can see using various tools are used to improve the quality of rendering of fonts and they are NOT directly accessible to the users.

We will continue to develop Noto as a high quality font therefore you can expect that the font files in addition to the Unicode glyphs to contain other glyphs and data required to improve the readability and quality of renderings.

**Comment by Kixidevel** [comment]
@marekjez86 
This version is Unicode conform already.
I talked about:
https://github.com/googlei18n/noto-fonts/blob/d7af81e614086435102cca95961b141b3530a027/hinted/NotoSansOldHungarian-Regular.ttf
font, which wasn't Unicode conform before.
Thanks

**Comment by Kixidevel** [comment]
@marekjez86 
Old Hungarian capital letter "enc" (0x10c85) hasn't got a good form. See its small pair (0x10cc5), which is correct.

**Comment by Kixidevel** [comment]
@marekjez86 
@brawer 
@davelab6 
Will be resolved the form mistake of Old Hungarian capital letter "enc" (0x1c85)?
Will be removed non UNICODE conform hidden ligatures from the font inside?

**Comment by brawer** [comment]
Well, it is perfectly valid (and often necessary) for fonts to contain ligatures and other stylistic variations that are not depicted in the Unicode charts. @Kixidevel, please read the introduction chapter in the Unicode book, especially the section about encoding characters versus glyphs. See earlier in this bug for pointers.

**Comment by Kixidevel** [comment]
@brawer 
1st: Please concentrate my 1st question: Will be resolved the form mistake of Old Hungarian capital letter "enc" (0x10c85)? Sorry, previously I had missed a 0 from the letter's code entry number.
2nd: Could you any process, how these logically existed ligatures will be visible phisicly without any phisical code entry?

**Comment by Kixidevel** [comment]
@brawer 
@marekjez86 
I just opened Your fonts by FontForge, I opened a ligature glyph info. See the attached file. Do you already belive me, that the ligatures in these font file just a "stuff" area for opsystems? 
![kepernyokep errol 2019-02-24 16-32-54](https://user-images.githubusercontent.com/32356899/53301419-e57a9300-3852-11e9-8af7-afe72a5dfb21.png)

**Comment by Kixidevel** [comment]
@marekjez86 , Please resolve the form mistake in NotoSansOldHungarian-Regular font's Capital letter "enc" (U+10C85)

**Comment by marekjez86** [comment]
@Kixidevel 
** about "enc" (U+10C85): please check OTF https://github.com/googlei18n/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.otf?raw=true or TTF https://github.com/googlei18n/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf?raw=true ; both should have correct forms (at least I hope they do :-))
** about "stuff": almost every font will have additional glyphs embedded in them (open several fonts on your system using FontForge and look at them). They are used by the system during rendering phase. They do NOT have Unicode associated with them. Same is true for NotoSansOldHungarian.

**Comment by Kixidevel** [comment]
@marekjez86 
[Test_of_NoTo_Old_Hung.pdf](https://github.com/googlei18n/noto-fonts/files/2914319/Test_of_NoTo_Old_Hung.pdf)
Good job! I uploaded a test case.
