### ISSUE TITLE
Indirect reqs for Old Hungarian scripts

### ISSUE THREAD

**Issue by Kixidevel** [googlei18n/noto-fonts#1462]
For writing Old Hungarian script, require some punctuation and quotation marks as described in document:
http://www.unicode.org/wg2/docs/n4268.pdf
 The chars are the followings:
U+0021 EXCLAMATION MARK
U+002D HYPHEN-MINUS
U+002E FULL STOP
U+003A COLONU+201F 
DOUBLE HIGH-REVERSED-9 QUOTATIONMARK
U+204F REVERSED SEMICOLON
U+2E2E REVERSED QUESTION MARK
U+2E41 REVERSED COMMAU+2E42 
DOUBLE LOW-REVERSED-9 QUOTATIONMARK

**Comment by Kixidevel** [comment]
@marekjez86 
?

**Comment by Kixidevel** [comment]
The chars are the followings:
U+0021 EXCLAMATION MARK
U+002D HYPHEN-MINUS
U+002E FULL STOP
U+003A COLON
U+201F DOUBLE HIGH-REVERSED-9 QUOTATIONMARK
U+204F REVERSED SEMICOLON
U+2E2E REVERSED QUESTION MARK
U+2E41 REVERSED COMMA
U+2E42 DOUBLE LOW-REVERSED-9 QUOTATIONMARK

**Comment by marekjez86** [comment]
@Kixidevel : 
I believe all of the codepoints you listed should be already included in the font. Here's the complete list of ALL codepoints contained:

      <map code="0x0" name="NULL"/><!-- ???? -->
      <map code="0x10c80" name="uni10C80"/><!-- OLD HUNGARIAN CAPITAL LETTER A -->
      <map code="0x10c81" name="uni10C81"/><!-- OLD HUNGARIAN CAPITAL LETTER AA -->
      <map code="0x10c82" name="uni10C82"/><!-- OLD HUNGARIAN CAPITAL LETTER EB -->
      <map code="0x10c83" name="uni10C83"/><!-- OLD HUNGARIAN CAPITAL LETTER AMB -->
      <map code="0x10c84" name="uni10C84"/><!-- OLD HUNGARIAN CAPITAL LETTER EC -->
      <map code="0x10c85" name="uni10C85"/><!-- OLD HUNGARIAN CAPITAL LETTER ENC -->
      <map code="0x10c86" name="uni10C86"/><!-- OLD HUNGARIAN CAPITAL LETTER ECS -->
      <map code="0x10c87" name="uni10C87"/><!-- OLD HUNGARIAN CAPITAL LETTER ED -->
      <map code="0x10c88" name="uni10C88"/><!-- OLD HUNGARIAN CAPITAL LETTER AND -->
      <map code="0x10c89" name="uni10C89"/><!-- OLD HUNGARIAN CAPITAL LETTER E -->
      <map code="0x10c8a" name="uni10C8A"/><!-- OLD HUNGARIAN CAPITAL LETTER CLOSE E -->
      <map code="0x10c8b" name="uni10C8B"/><!-- OLD HUNGARIAN CAPITAL LETTER EE -->
      <map code="0x10c8c" name="uni10C8C"/><!-- OLD HUNGARIAN CAPITAL LETTER EF -->
      <map code="0x10c8d" name="uni10C8D"/><!-- OLD HUNGARIAN CAPITAL LETTER EG -->
      <map code="0x10c8e" name="uni10C8E"/><!-- OLD HUNGARIAN CAPITAL LETTER EGY -->
      <map code="0x10c8f" name="uni10C8F"/><!-- OLD HUNGARIAN CAPITAL LETTER EH -->
      <map code="0x10c90" name="uni10C90"/><!-- OLD HUNGARIAN CAPITAL LETTER I -->
      <map code="0x10c91" name="uni10C91"/><!-- OLD HUNGARIAN CAPITAL LETTER II -->
      <map code="0x10c92" name="uni10C92"/><!-- OLD HUNGARIAN CAPITAL LETTER EJ -->
      <map code="0x10c93" name="uni10C93"/><!-- OLD HUNGARIAN CAPITAL LETTER EK -->
      <map code="0x10c94" name="uni10C94"/><!-- OLD HUNGARIAN CAPITAL LETTER AK -->
      <map code="0x10c95" name="uni10C95"/><!-- OLD HUNGARIAN CAPITAL LETTER UNK -->
      <map code="0x10c96" name="uni10C96"/><!-- OLD HUNGARIAN CAPITAL LETTER EL -->
      <map code="0x10c97" name="uni10C97"/><!-- OLD HUNGARIAN CAPITAL LETTER ELY -->
      <map code="0x10c98" name="uni10C98"/><!-- OLD HUNGARIAN CAPITAL LETTER EM -->
      <map code="0x10c99" name="uni10C99"/><!-- OLD HUNGARIAN CAPITAL LETTER EN -->
      <map code="0x10c9a" name="uni10C9A"/><!-- OLD HUNGARIAN CAPITAL LETTER ENY -->
      <map code="0x10c9b" name="uni10C9B"/><!-- OLD HUNGARIAN CAPITAL LETTER O -->
      <map code="0x10c9c" name="uni10C9C"/><!-- OLD HUNGARIAN CAPITAL LETTER OO -->
      <map code="0x10c9d" name="uni10C9D"/><!-- OLD HUNGARIAN CAPITAL LETTER NIKOLSBURG OE -->
      <map code="0x10c9e" name="uni10C9E"/><!-- OLD HUNGARIAN CAPITAL LETTER RUDIMENTA OE -->
      <map code="0x10c9f" name="uni10C9F"/><!-- OLD HUNGARIAN CAPITAL LETTER OEE -->
      <map code="0x10ca0" name="uni10CA0"/><!-- OLD HUNGARIAN CAPITAL LETTER EP -->
      <map code="0x10ca1" name="uni10CA1"/><!-- OLD HUNGARIAN CAPITAL LETTER EMP -->
      <map code="0x10ca2" name="uni10CA2"/><!-- OLD HUNGARIAN CAPITAL LETTER ER -->
      <map code="0x10ca3" name="uni10CA3"/><!-- OLD HUNGARIAN CAPITAL LETTER SHORT ER -->
      <map code="0x10ca4" name="uni10CA4"/><!-- OLD HUNGARIAN CAPITAL LETTER ES -->
      <map code="0x10ca5" name="uni10CA5"/><!-- OLD HUNGARIAN CAPITAL LETTER ESZ -->
      <map code="0x10ca6" name="uni10CA6"/><!-- OLD HUNGARIAN CAPITAL LETTER ET -->
      <map code="0x10ca7" name="uni10CA7"/><!-- OLD HUNGARIAN CAPITAL LETTER ENT -->
      <map code="0x10ca8" name="uni10CA8"/><!-- OLD HUNGARIAN CAPITAL LETTER ETY -->
      <map code="0x10ca9" name="uni10CA9"/><!-- OLD HUNGARIAN CAPITAL LETTER ECH -->
      <map code="0x10caa" name="uni10CAA"/><!-- OLD HUNGARIAN CAPITAL LETTER U -->
      <map code="0x10cab" name="uni10CAB"/><!-- OLD HUNGARIAN CAPITAL LETTER UU -->
      <map code="0x10cac" name="uni10CAC"/><!-- OLD HUNGARIAN CAPITAL LETTER NIKOLSBURG UE -->
      <map code="0x10cad" name="uni10CAD"/><!-- OLD HUNGARIAN CAPITAL LETTER RUDIMENTA UE -->
      <map code="0x10cae" name="uni10CAE"/><!-- OLD HUNGARIAN CAPITAL LETTER EV -->
      <map code="0x10caf" name="uni10CAF"/><!-- OLD HUNGARIAN CAPITAL LETTER EZ -->
      <map code="0x10cb0" name="uni10CB0"/><!-- OLD HUNGARIAN CAPITAL LETTER EZS -->
      <map code="0x10cb1" name="uni10CB1"/><!-- OLD HUNGARIAN CAPITAL LETTER ENT-SHAPED SIGN -->
      <map code="0x10cb2" name="uni10CB2"/><!-- OLD HUNGARIAN CAPITAL LETTER US -->
      <map code="0x10cc0" name="uni10CC0"/><!-- OLD HUNGARIAN SMALL LETTER A -->
      <map code="0x10cc1" name="uni10CC1"/><!-- OLD HUNGARIAN SMALL LETTER AA -->
      <map code="0x10cc2" name="uni10CC2"/><!-- OLD HUNGARIAN SMALL LETTER EB -->
      <map code="0x10cc3" name="uni10CC3"/><!-- OLD HUNGARIAN SMALL LETTER AMB -->
      <map code="0x10cc4" name="uni10CC4"/><!-- OLD HUNGARIAN SMALL LETTER EC -->
      <map code="0x10cc5" name="uni10CC5"/><!-- OLD HUNGARIAN SMALL LETTER ENC -->
      <map code="0x10cc6" name="uni10CC6"/><!-- OLD HUNGARIAN SMALL LETTER ECS -->
      <map code="0x10cc7" name="uni10CC7"/><!-- OLD HUNGARIAN SMALL LETTER ED -->
      <map code="0x10cc8" name="uni10CC8"/><!-- OLD HUNGARIAN SMALL LETTER AND -->
      <map code="0x10cc9" name="uni10CC9"/><!-- OLD HUNGARIAN SMALL LETTER E -->
      <map code="0x10cca" name="uni10CCA"/><!-- OLD HUNGARIAN SMALL LETTER CLOSE E -->
      <map code="0x10ccb" name="uni10CCB"/><!-- OLD HUNGARIAN SMALL LETTER EE -->
      <map code="0x10ccc" name="uni10CCC"/><!-- OLD HUNGARIAN SMALL LETTER EF -->
      <map code="0x10ccd" name="uni10CCD"/><!-- OLD HUNGARIAN SMALL LETTER EG -->
      <map code="0x10cce" name="uni10CCE"/><!-- OLD HUNGARIAN SMALL LETTER EGY -->
      <map code="0x10ccf" name="uni10CCF"/><!-- OLD HUNGARIAN SMALL LETTER EH -->
      <map code="0x10cd0" name="uni10CD0"/><!-- OLD HUNGARIAN SMALL LETTER I -->
      <map code="0x10cd1" name="uni10CD1"/><!-- OLD HUNGARIAN SMALL LETTER II -->
      <map code="0x10cd2" name="uni10CD2"/><!-- OLD HUNGARIAN SMALL LETTER EJ -->
      <map code="0x10cd3" name="uni10CD3"/><!-- OLD HUNGARIAN SMALL LETTER EK -->
      <map code="0x10cd4" name="uni10CD4"/><!-- OLD HUNGARIAN SMALL LETTER AK -->
      <map code="0x10cd5" name="uni10CD5"/><!-- OLD HUNGARIAN SMALL LETTER UNK -->
      <map code="0x10cd6" name="uni10CD6"/><!-- OLD HUNGARIAN SMALL LETTER EL -->
      <map code="0x10cd7" name="uni10CD7"/><!-- OLD HUNGARIAN SMALL LETTER ELY -->
      <map code="0x10cd8" name="uni10CD8"/><!-- OLD HUNGARIAN SMALL LETTER EM -->
      <map code="0x10cd9" name="uni10CD9"/><!-- OLD HUNGARIAN SMALL LETTER EN -->
      <map code="0x10cda" name="uni10CDA"/><!-- OLD HUNGARIAN SMALL LETTER ENY -->
      <map code="0x10cdb" name="uni10CDB"/><!-- OLD HUNGARIAN SMALL LETTER O -->
      <map code="0x10cdc" name="uni10CDC"/><!-- OLD HUNGARIAN SMALL LETTER OO -->
      <map code="0x10cdd" name="uni10CDD"/><!-- OLD HUNGARIAN SMALL LETTER NIKOLSBURG OE -->
      <map code="0x10cde" name="uni10CDE"/><!-- OLD HUNGARIAN SMALL LETTER RUDIMENTA OE -->
      <map code="0x10cdf" name="uni10CDF"/><!-- OLD HUNGARIAN SMALL LETTER OEE -->
      <map code="0x10ce0" name="uni10CE0"/><!-- OLD HUNGARIAN SMALL LETTER EP -->
      <map code="0x10ce1" name="uni10CE1"/><!-- OLD HUNGARIAN SMALL LETTER EMP -->
      <map code="0x10ce2" name="uni10CE2"/><!-- OLD HUNGARIAN SMALL LETTER ER -->
      <map code="0x10ce3" name="uni10CE3"/><!-- OLD HUNGARIAN SMALL LETTER SHORT ER -->
      <map code="0x10ce4" name="uni10CE4"/><!-- OLD HUNGARIAN SMALL LETTER ES -->
      <map code="0x10ce5" name="uni10CE5"/><!-- OLD HUNGARIAN SMALL LETTER ESZ -->
      <map code="0x10ce6" name="uni10CE6"/><!-- OLD HUNGARIAN SMALL LETTER ET -->
      <map code="0x10ce7" name="uni10CE7"/><!-- OLD HUNGARIAN SMALL LETTER ENT -->
      <map code="0x10ce8" name="uni10CE8"/><!-- OLD HUNGARIAN SMALL LETTER ETY -->
      <map code="0x10ce9" name="uni10CE9"/><!-- OLD HUNGARIAN SMALL LETTER ECH -->
      <map code="0x10cea" name="uni10CEA"/><!-- OLD HUNGARIAN SMALL LETTER U -->
      <map code="0x10ceb" name="uni10CEB"/><!-- OLD HUNGARIAN SMALL LETTER UU -->
      <map code="0x10cec" name="uni10CEC"/><!-- OLD HUNGARIAN SMALL LETTER NIKOLSBURG UE -->
      <map code="0x10ced" name="uni10CED"/><!-- OLD HUNGARIAN SMALL LETTER RUDIMENTA UE -->
      <map code="0x10cee" name="uni10CEE"/><!-- OLD HUNGARIAN SMALL LETTER EV -->
      <map code="0x10cef" name="uni10CEF"/><!-- OLD HUNGARIAN SMALL LETTER EZ -->
      <map code="0x10cf0" name="uni10CF0"/><!-- OLD HUNGARIAN SMALL LETTER EZS -->
      <map code="0x10cf1" name="uni10CF1"/><!-- OLD HUNGARIAN SMALL LETTER ENT-SHAPED SIGN -->
      <map code="0x10cf2" name="uni10CF2"/><!-- OLD HUNGARIAN SMALL LETTER US -->
      <map code="0x10cfa" name="uni10CFA"/><!-- OLD HUNGARIAN NUMBER ONE -->
      <map code="0x10cfb" name="uni10CFB"/><!-- OLD HUNGARIAN NUMBER FIVE -->
      <map code="0x10cfc" name="uni10CFC"/><!-- OLD HUNGARIAN NUMBER TEN -->
      <map code="0x10cfd" name="uni10CFD"/><!-- OLD HUNGARIAN NUMBER FIFTY -->
      <map code="0x10cfe" name="uni10CFE"/><!-- OLD HUNGARIAN NUMBER ONE HUNDRED -->
      <map code="0x10cff" name="uni10CFF"/><!-- OLD HUNGARIAN NUMBER ONE THOUSAND -->
      <map code="0x20" name="space"/><!-- SPACE -->
      <map code="0x200d" name="ZWJ"/><!-- ZERO WIDTH JOINER -->
      <map code="0xa0" name="uni00A0"/><!-- NO-BREAK SPACE -->
      <map code="0xd" name="CR"/><!-- ???? -->

**Comment by marekjez86** [comment]
@Kixidevel 
Noto fonts are meant for the operating systems like ChromeOS or Android and as such they need to work together as a collection of fonts. The codepoints you listed
U+0021
U+002D
U+002E
U+003A
U+201F
U+204F
U+2E2E
U+2E41
U+2E42
are included in any Noto Latin-Greek-Cyrillic font. For example, they are in https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSans (https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSans ). At this point we do not have a strategy/plan to duplicate these into individual fonts.

**Comment by Kixidevel** [comment]
@marekjez86 
Thanks!
You did a perfect work
