### ISSUE TITLE
Javanese script error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#149]
```
What steps will reproduce the problem?
1. Type the script
2. Compare it with other script (printed or digital texts)
3. See the difference

What is the expected output? What do you see instead?

A: See comparison table image attached

What version of the product are you using? On what operating system?

A: NotoSansJavanese-unhinted.zip (v. 1.01) downloaded today from 
http://www.google.com/get/noto on Win 7 OS, Firefox 28.0

Please provide any additional information below.

A: See attachments

Attachments:
1. noto sans.png - shows basic 20 Javanese script glyphs in Noto and their 
Latin readings. Compare with link [1]
2. table.png - shows the full Javanese Unicode block in Noto. Via link [2]
3. table2.png - Javanese pasangans (see link [3])
4. comparison.png - Comparison of glyphs in image 1. between three Javanese 
Unicode font, the left being the one most closest to the Javanese manuscripts 
(see link [4]). In-image explanations are given
5. comparison2.png - Comparison of glyphs in image 3, it shows the same errors 
as above (red), and either missing glyphs or incorrect renderings (blue)

Links:
[1] https://jv.wikipedia.org/wiki/Hanacaraka#Aksara_nglegena
[2] https://jv.wikipedia.org/wiki/Cithakan:Tabel_Unicode_Aksara_Jawa
[3] https://en.wikipedia.org/wiki/Javanese_script#Pasangan
[4] https://sites.google.com/site/jawaunicode/download
[5] https://ftp.gnu.org/gnu/unifont/
```

Original issue reported on code.google.com by `bknl...@gmail.com` on 15 Sep 2014 at 5:30

Attachments:
* [noto sans.png](https://storage.googleapis.com/google-code-attachments/noto/issue-149/comment-0/noto sans.png)
* [table.png](https://storage.googleapis.com/google-code-attachments/noto/issue-149/comment-0/table.png)
* [table2.png](https://storage.googleapis.com/google-code-attachments/noto/issue-149/comment-0/table2.png)
* [comparison.png](https://storage.googleapis.com/google-code-attachments/noto/issue-149/comment-0/comparison.png)
* [comparison2.png](https://storage.googleapis.com/google-code-attachments/noto/issue-149/comment-0/comparison2.png)

**Comment by behdad** [comment]
cc @roozbehp @xiangyexiao

**Comment by bennylin** [comment]
related to https://github.com/googlei18n/noto-fonts/issues/314

**Comment by kmansourMT** [comment]
The comments offered here regarding stylistic differences would carry more weight if we were still discussing the style to be chosen. At this stage, we will focus on any characters whose design is inconsistent with the overall style. We did in fact find that u+A9A5 was ambiguous and have redesigned it as shown below.
![ua9a5-correction](https://cloud.githubusercontent.com/assets/12738181/9338029/75bf7352-4597-11e5-81b5-67acbf675006.png)
