### ISSUE TITLE
Balinese taling mark displayed on wrong side of base character

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#163]
```
What steps will reproduce the problem?
Use a browser with a good rendering engine to go to
http://lindenbergsoftware.com/google/noto/bali-taling.html
The table on this page shows the different Balinese taling marks combined with 
different base characters. In each cell of the table, the first line uses Noto 
Sans Balinese, the second line the Aksara Bali font.

What is the expected output?
The taling or taling repa component of each cluster should be shown on the left 
side of the base character, the way the Aksara Bali font does. See also the 
Unicode reference glyphs at
http://www.unicode.org/charts/PDF/U1B00.pdf

What do you see instead?
The taling or taling repa component is shown on the right side of the base in 
the following cases:
– By Firefox in all combinations that include the tedung component in a 
precomposed form, i.e., the U+1B40 and U+1B41 code points.
– By Safari in all combinations.
See the attached screen shots.

What version of the product are you using? On what operating system?
Noto Sans Balinese Regular 1.02
Mozilla Firefox Nightly 35.0a1 (2014-09-25) on Mac OS X 10.9.5.
Safari on iOS 8.0.2.

Please provide any additional information below.
According to the Mozilla commit log, Firefox has recently been updated to 
Harfbuzz 0.9.34. Firefox is clearly not using OS X rendering, as other 
applications on OS X 10.9.5 render Noto Sans Balinese quite differently.
```

Original issue reported on code.google.com by `googled...@lindenbergsoftware.com` on 26 Sep 2014 at 2:27

Attachments:
* [Taling Firefox.png](https://storage.googleapis.com/google-code-attachments/noto/issue-163/comment-0/Taling Firefox.png)
* [Taling Safari.png](https://storage.googleapis.com/google-code-attachments/noto/issue-163/comment-0/Taling Safari.png)

**Comment by behdad** [comment]
cc @roozbehp @behdad

**Comment by xiangyexiao** [comment]
I close this issue since it is not issues in the font.

**Comment by bennylin** [comment]
Please add Script-Balinese label for this bug. Thanks!

**Comment by jungshik** [comment]
I'm afraid this has been regressed in 1.03. 

http://lindenbergsoftware.com/google/noto/bali-taling.html : Everything looks fine with Noto Sans Javanese 1.02 and Chrome 46 on Mac. 

However, with 1.03, some 'left' vowel is misplaced as shown in bug 572. 

I'll make a test file comparing 1.02 and 1.03.

**Comment by jungshik** [comment]
Hmm... it's strange. Balinese 1.03 is just a license change from 1.02. Let me check what's served at
http://lindenbergsoftware.com/google/noto/bali-taling.html

**Comment by jungshik** [comment]
Ok. The test page in this bug does not have any conjuct (all the consonants in the test page are 'simple'). 
Syllables with 'misplaced left-vowel or left-vowel part') in lines 4 and 5 of #572 have a conjunct. 

So, we can keep this bug closed and file a new one about the misplacement of vowels like U+1B3E, U+1B40 when a conjuct comes before them.
