### ISSUE TITLE
Flag of the Netherlands & Frisian sample text

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#183]
```
I created the flag of the Netherlands based on SVG file of the flag of Germany.
I just swapped the three colors for the three official colors for the flag of 
the Netherlands.

I also uploaded the Frisian sample text from the official translation of the 
"The Universal Declaration of Human Rights".
Source: http://www.ohchr.org/EN/UDHR/Documents/UDHR_Translations/fri.pdf
```

Original issue reported on code.google.com by `i...@robinvandervliet.nl` on 26 Oct 2014 at 10:35

Attachments:
* [emoji_u1f1f3_1f1f1.svg](https://storage.googleapis.com/google-code-attachments/noto/issue-183/comment-0/emoji_u1f1f3_1f1f1.svg)
* [fy-Latn.txt](https://storage.googleapis.com/google-code-attachments/noto/issue-183/comment-0/fy-Latn.txt)

**Comment by dougfelt** [comment]
the fy text sample from the UDHR is already in our text samples.

added flag to noto-emoji in commit a664ab20a4fab3c32f203ad80573f780584d5ee6

**Comment by dougfelt** [comment]
Removed the flag since we do not have a signed contributor agreement.
