### ISSUE TITLE
Colliding dots of ye with preceding letter 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#194]
```
What steps will reproduce the problem?
1. Write قریب using NotoUrduNastaleeqDraft.tff


What is the expected output? What do you see instead?

The two dots (nuqtas) below ye (ی) are colliding with re (ر) preceding it. 

What version of the product are you using? On what operating system?

I observed this problem on Chrome for android and Chrome for windows. Same 
problem with Firefox as well.

Please provide any additional information below.
Less pronounced problem with word "ایڈیٹر"
See Attached Files.

```

Original issue reported on code.google.com by `sayedzee...@gmail.com` on 10 Nov 2014 at 6:38

Attachments:
* [2014-11-10 06.28.07.png](https://storage.googleapis.com/google-code-attachments/noto/issue-194/comment-0/2014-11-10 06.28.07.png)

**Comment by kmansourMT** [comment]
The reported collisions have been resolved in v 1.00 as demonstrated by the attached graphic.
![reh_dal_collisions_resolved](https://cloud.githubusercontent.com/assets/12738181/8258687/c35bc85a-166b-11e5-93d6-8f8b1e16398d.png)

**Comment by behdad** [comment]
Thanks Kamal.

**Comment by khaledhosny** [comment]
Wouldn’t be better if the dots were moved below instead kerning them out, ایڈیٹر looks like two words now!
