### ISSUE TITLE
noto old Turkish

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#223]
```

I got download yout old turkish font but that is new turkish font...can you 
change it
:( :( :(
```

Original issue reported on code.google.com by `cankay...@gmail.com` on 24 Dec 2014 at 9:12

**Comment by fontguy** [comment]
Are you sure that you downloaded the correct font? This is the one that the website (google.com/get/noto) will give you for Old Turkic and what is in the github repo. It is also what Unicode calls Old Turkic. Please verify.

https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansOldTurkic-Regular.ttf

**Comment by TidharC** [comment]
Here are the chars I get from Old Turkic Noto font. Is this not the expected result?


 10C00 𐰀 OLD TURKIC LETTER ORKHON A
 10C01 𐰁 OLD TURKIC LETTER YENISEI A
 10C02 𐰂 OLD TURKIC LETTER YENISEI AE
 10C03 𐰃 OLD TURKIC LETTER ORKHON I
 10C04 𐰄 OLD TURKIC LETTER YENISEI I
 10C05 𐰅 OLD TURKIC LETTER YENISEI E
 10C06 𐰆 OLD TURKIC LETTER ORKHON O
 10C07 𐰇 OLD TURKIC LETTER ORKHON OE
 10C08 𐰈 OLD TURKIC LETTER YENISEI OE
 10C09 𐰉 OLD TURKIC LETTER ORKHON AB
 10C0A 𐰊 OLD TURKIC LETTER YENISEI AB
 10C0B 𐰋 OLD TURKIC LETTER ORKHON AEB
 10C0C 𐰌 OLD TURKIC LETTER YENISEI AEB
 10C0D 𐰍 OLD TURKIC LETTER ORKHON AG
 10C0E 𐰎 OLD TURKIC LETTER YENISEI AG
 10C0F 𐰏 OLD TURKIC LETTER ORKHON AEG
 10C10 𐰐 OLD TURKIC LETTER YENISEI AEG
 10C11 𐰑 OLD TURKIC LETTER ORKHON AD
 10C12 𐰒 OLD TURKIC LETTER YENISEI AD
 10C13 𐰓 OLD TURKIC LETTER ORKHON AED
 10C14 𐰔 OLD TURKIC LETTER ORKHON EZ
 10C15 𐰕 OLD TURKIC LETTER YENISEI EZ
 10C16 𐰖 OLD TURKIC LETTER ORKHON AY
 10C17 𐰗 OLD TURKIC LETTER YENISEI AY
 10C18 𐰘 OLD TURKIC LETTER ORKHON AEY
 10C19 𐰙 OLD TURKIC LETTER YENISEI AEY
 10C1A 𐰚 OLD TURKIC LETTER ORKHON AEK
 10C1B 𐰛 OLD TURKIC LETTER YENISEI AEK
 10C1C 𐰜 OLD TURKIC LETTER ORKHON OEK
 10C1D 𐰝 OLD TURKIC LETTER YENISEI OEK
 10C1E 𐰞 OLD TURKIC LETTER ORKHON AL
 10C1F 𐰟 OLD TURKIC LETTER YENISEI AL
 10C20 𐰠 OLD TURKIC LETTER ORKHON AEL
 10C21 𐰡 OLD TURKIC LETTER ORKHON ELT
 10C22 𐰢 OLD TURKIC LETTER ORKHON EM
 10C23 𐰣 OLD TURKIC LETTER ORKHON AN
 10C24 𐰤 OLD TURKIC LETTER ORKHON AEN
 10C25 𐰥 OLD TURKIC LETTER YENISEI AEN
 10C26 𐰦 OLD TURKIC LETTER ORKHON ENT
 10C27 𐰧 OLD TURKIC LETTER YENISEI ENT
 10C28 𐰨 OLD TURKIC LETTER ORKHON ENC
 10C29 𐰩 OLD TURKIC LETTER YENISEI ENC
 10C2A 𐰪 OLD TURKIC LETTER ORKHON ENY
 10C2B 𐰫 OLD TURKIC LETTER YENISEI ENY
 10C2C 𐰬 OLD TURKIC LETTER YENISEI ANG
 10C2D 𐰭 OLD TURKIC LETTER ORKHON ENG
 10C2E 𐰮 OLD TURKIC LETTER YENISEI AENG
 10C2F 𐰯 OLD TURKIC LETTER ORKHON EP
 10C30 𐰰 OLD TURKIC LETTER ORKHON OP
 10C31 𐰱 OLD TURKIC LETTER ORKHON IC
 10C32 𐰲 OLD TURKIC LETTER ORKHON EC
 10C33 𐰳 OLD TURKIC LETTER YENISEI EC
 10C34 𐰴 OLD TURKIC LETTER ORKHON AQ
 10C35 𐰵 OLD TURKIC LETTER YENISEI AQ
 10C36 𐰶 OLD TURKIC LETTER ORKHON IQ
 10C37 𐰷 OLD TURKIC LETTER YENISEI IQ
 10C38 𐰸 OLD TURKIC LETTER ORKHON OQ
 10C39 𐰹 OLD TURKIC LETTER YENISEI OQ
 10C3A 𐰺 OLD TURKIC LETTER ORKHON AR
 10C3B 𐰻 OLD TURKIC LETTER YENISEI AR
 10C3C 𐰼 OLD TURKIC LETTER ORKHON AER
 10C3D 𐰽 OLD TURKIC LETTER ORKHON AS
 10C3E 𐰾 OLD TURKIC LETTER ORKHON AES
 10C3F 𐰿 OLD TURKIC LETTER ORKHON ASH
 10C40 𐱀 OLD TURKIC LETTER YENISEI ASH
 10C41 𐱁 OLD TURKIC LETTER ORKHON ESH
 10C42 𐱂 OLD TURKIC LETTER YENISEI ESH
 10C43 𐱃 OLD TURKIC LETTER ORKHON AT
 10C44 𐱄 OLD TURKIC LETTER YENISEI AT
 10C45 𐱅 OLD TURKIC LETTER ORKHON AET
 10C46 𐱆 OLD TURKIC LETTER YENISEI AET
 10C47 𐱇 OLD TURKIC LETTER ORKHON OT
 10C48 𐱈 OLD TURKIC LETTER ORKHON BASH

**Comment by KatMomoi** [comment]
We have not been able to reproduce this problem with the current Noto Sans Old Turkic font. The glyphs seem to be those described at the Unicode site:

http://unicode.org/charts/PDF/U10C00.pdf

I am going to close this issue as not reproducible. If you disagree, please re-open with fresh evidence. Thanks!

**Comment by marekjez86** [comment]
@KatMomoi : thank you
