### ISSUE TITLE
Google Noto Fonts for Chromebooks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#241]
```
Can you make Noto Fonts work for Chromebooks? thanks. 
```

Original issue reported on code.google.com by `sanjen...@gmail.com` on 25 Jan 2015 at 6:35

**Comment by jungshik** [comment]
Chrome OS has all the Noto fonts released to date. So, you don't have to do anything. Noto fonts are just present on every Chromebook.
