### ISSUE TITLE
Noto Font not working 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#267]
```
Hello,

I have download noto font but it's not working in MVC project, please guide me 
ASAP, I have embed font in web site but it's not giving any effect, please 
suggest me best solution for that and also please give me the example along 
with step.

Thanks
```

Original issue reported on code.google.com by `snehalsh...@gmail.com` on 25 Feb 2015 at 5:40

**Comment by marekjez86** [comment]
we need more information here. how could we requested from the the original bug reported?

**Comment by TidharC** [comment]
Is this issue still reproducible?  If so, additional details are needed.

**Comment by marekjez86** [comment]
closing the bug with the following justification:
- unknown user on 25 Feb 2015 wrote "please guide me ASAP" while not providing enough information
- still at this time we have no information
