### ISSUE TITLE
Noto Serif Italic: Hinting for 'X' is mangled

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#270]
```
What steps will reproduce the problem?
1. Check out revision 3bd8e46 or later of 
fonts/individual/hinted/NotoSerif-Italic.ttf.
2. Render the character 'X' in this font on a system with bytecode hinting 
enabled (e.g., Windows, recent versions of Freetype).

What is the expected output? What do you see instead?
Expected: The character looks like a normal X.
Actual: The character looks vaguely like an X, but is extremely misshapen.


What version of the product are you using? On what operating system?
Revision 3bd8e46 or aae16d0; Windows 7.


Please provide any additional information below.
Screenshot of Windows' font rendering is attached.
```

Original issue reported on code.google.com by `codeman38` on 26 Feb 2015 at 4:49

Attachments:
* [notoserif-italic-X.png](https://storage.googleapis.com/google-code-attachments/noto/issue-270/comment-0/notoserif-italic-X.png)

**Comment by marekjez86** [comment]
jungshik, could we try this somewhere. I wanted to learn more about hints in fonts/systems

**Comment by jungshik** [comment]
I confirmed this issue with FreeType. See the screenshots below (this has only Latin 'xX', but Cyrilic has the same problem). 

With BCI hint ON : 
![image](https://cloud.githubusercontent.com/assets/8578343/9912487/bc1d57de-5c5c-11e5-800d-61c162ac14eb.png)

With Hint OFF: 
![image](https://cloud.githubusercontent.com/assets/8578343/9912504/cb787632-5c5c-11e5-9872-5c81036276cd.png)

With FT's autohint

![image](https://cloud.githubusercontent.com/assets/8578343/9912532/fa35d38e-5c5c-11e5-8dfe-3f1ddb909210.png)

**Comment by jungshik** [comment]
@waksmonskiMT : can you talk to your team to fix this issue? Thanks

**Comment by jungshik** [comment]
@marekjez86 : The above screenshot is produced with Freetype's (Freetype demo's) ftview tools. You need to download both freetype2 and ft2demos tarballs and uncompress them side-by-side. Then, build freetype and ft2demos and go to ft2demos/bin. Run 
`./ftview -m 'xX' 24 <path to a font>`.  You can control hinting with 'h' and 'H' key in ftview. Press '?' to see the help.

**Comment by jungshik** [comment]
@BrianKraimerMT FYI. 

I confirmed what @davelab6 wrote. Noto Serif Italic 1.03 is fine, but 1.04 has this bug.

**Comment by jungshik** [comment]
ХхΧχXx

Greek (U+03A7; Χ) and  Cyrillic (U+0425; Х) have the same problem. Apparently, they're all mapped to the same glyph as Latin 'X'. 

![image](https://cloud.githubusercontent.com/assets/8578343/9915081/e488d5d8-5c69-11e5-9cf6-391b8a7b8ed0.png)

Besides, Noto Serif Bold Italic is fine.

**Comment by jungshik** [comment]
There's no difference between cvt, fpgm and gasp tables between 1.03 and 1.04. In the diff of glyf table between 1.03 and 1.04, I didn't find anything that would prevent us from hot-fixing BCI instruction for 'X', either.

**Comment by jungshik** [comment]
1.04 with BCI for 'X' transplanted from 1.03 (everything else unchanged). 

![image](https://cloud.githubusercontent.com/assets/8578343/9916254/59a358e2-5c70-11e5-9517-a4763c8346de.png)

**Comment by codeman38** [comment]
Looking at the TTX decompilation, it looks like somehow the hints from "W" (starting in `183 38 1 ...`) got accidentally copied to "X" in 1.04.

**Comment by jungshik** [comment]
@davelab6 Can you update Noto Serif in Google Font to the latest git version?
