### ISSUE TITLE
Noto Sans Balinese smashes above-base marks together

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#299]
```
Balinese has several different kinds of above-base marks:
– nukta: U+1B34
– dependent vowels: U+1B36, U+1B37, U+1B3C, U+1B3D
– vowel modifiers: U+1B00, U+1B01, U+1B02
– final consonant: U+1B03

These can and to some extent are combined in complete syllables. If they are, 
Noto Sans Balinese renders them smashed together.

What steps will reproduce the problem?
1. Use a browser with a reasonable up-to-date version of Harfbuzz, such as 
current Firefox.
2. Go to http://lindenbergsoftware.com/google/noto/bali-above-base.html
3. Check the rendering in the Noto Sans Balinese column, and compare it to the 
Aksara Bali column.

What is the expected output?
Valid combinations of above-base marks should be rendered such that they're all 
separate and clearly visible. The Aksara Bali column shows what that could look 
like.

What do you see instead?
The above-base marks rendered by Noto Sans Balinese are smashed together so 
that in many cases they're no longer clearly recognizable.

What version of the product are you using? On what operating system?
Noto Sans Balinese 1.02, OS X 10.10.2, Firefox 36.0.1.

```

Original issue reported on code.google.com by `googled...@lindenbergsoftware.com` on 16 Mar 2015 at 1:49

Attachments:
- [Screen Shot 1.png](https://storage.googleapis.com/google-code-attachments/noto/issue-299/comment-0/Screen Shot 1.png)
- [Screen Shot 2.png](https://storage.googleapis.com/google-code-attachments/noto/issue-299/comment-0/Screen Shot 2.png)

**Comment by behdad** [comment]
cc @roozbehp @xiangyexiao

**Comment by jungshik** [comment]
![screen shot 2015-11-19 at 3 09 23 pm](https://cloud.githubusercontent.com/assets/8578343/11287345/a45b822e-8ecf-11e5-948f-986d726234dd.png)

The above is what Edge on Windows 10 does. It seems that USE treats some of sequences as invalid. 

@NobertLindenberg : can you make sure that they're valid per USE spec?

**Comment by jungshik** [comment]
OTOH, harfbuzz does not. The issue here is still outstanding in either way. 

![screen shot 2015-11-19 at 3 24 29 pm](https://cloud.githubusercontent.com/assets/8578343/11287594/bb5c4754-8ed1-11e5-868b-51d899b82e91.png)

The above is Firefox/Chrome rendering http://jungshik.github.io/noto/balinese/bug299.html

**Comment by NorbertLindenberg** [comment]
FYI, this image includes the rendering by the current version 1.10 of the Ubud font, the enhanced version of Noto Sans Balinese that's included in the [Balinese Font and Keyboard](http://lindenbergsoftware.com/balinese) app:

![ubud above-base marks](https://cloud.githubusercontent.com/assets/216206/12901141/d0960358-ce6e-11e5-95d8-cbd00c33e8ba.png)

**Comment by kmansourMT** [comment]
In the forthcoming version of Noto Balinese, the listed combinations of above-base marks wlll display correctly as follows:
![299-multipletopmarks-good-pt1](https://cloud.githubusercontent.com/assets/12738181/13412307/32c07732-def7-11e5-9a59-a4987abdb3a9.png)

Likewise, they will combine properly when placed over base characters as follows:
![299-multipletopmarks-good-pt2](https://cloud.githubusercontent.com/assets/12738181/13412319/4f858ea2-def7-11e5-8a2b-dfff84c5f0e2.png)
