### ISSUE TITLE
Hawaiian language

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#308]
```
I can't seem to find noto for Hawaiian language.  Does it exists?


```

Original issue reported on code.google.com by `kaki...@hawaiidoe.k12.hi.us` on 24 Mar 2015 at 6:36

**Comment by moyogo** [comment]
Unless I’m mistaken, there is no “Hawaiian script” per se, only a Hawaiian orthography.
The Hawaiian language is written with the Latin alphabet. Both Noto Sans and Noto Serif support the Hawaiian language orthography: CLDR’s `haw` exemplar character set is [a ā e ē i ī o ō u ū h k l m n p w ʻ].

**Comment by dougfelt** [comment]
Go to https://www.google.com/get/noto/ and search for 'Hawaiian', it shows the Noto Sans and Serif fonts that support Latin script.
