### ISSUE TITLE
downloaded font archives should include license file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#331]
```
1) This is required by following good software practises.

2) This is required when writing a yocto recipe for noto fonts.
All yocto recipes require to set LIC_FILES_CHKSUM to point to a license file 
for a specific project, in this case noto project.

This allows to automate upstream license changes when building embedded linux 
image, see yocto manual for more info. 


```

Original issue reported on code.google.com by `gatis.pa...@gmail.com` on 13 Apr 2015 at 3:32

**Comment by marekjez86** [comment]
for my own education I looked up http://elinux.org/Yocto_Project_Introduction on Yocto: "The Yocto Project is a collection of tools and meta-data (defined in a bit) that allows a developer to build their own custom distribution of Linux for their embedded platform".

assigning to jungshik@ to evaluate how difficult it would be to include the license.

we may need to inquire with Google legal about this process. xiangyexiao@ did we ever inquire about it?

**Comment by dougfelt** [comment]
The Noto font zips include license files (there was a period when they
didn't, which perhaps this dates from), and there are files in the git
repos. I think this can be closed.

**Comment by marekjez86** [comment]
gatis.pa...@gmail.com please respond with more details of what's expected if what dougfelt described doesn't satisfy the requirement you described above. Closing the bug.

**Comment by gatispaeglis** [comment]
Yes, I see it has been fixed. Font archive files now include the license file.
