### ISSUE TITLE
Subscripts (inferiors) missing from Noto Sans and Noto Serif

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#335]
```
Currently there's a full set of superscript numerals (0–9) but the subscripts 
are all missing. Shouldn't be too much of a problem to create them; they just 
need to be moved down and kerned.

What version of the product are you using? On what operating system?
Noto Sans 1.04
```

Original issue reported on code.google.com by `eemail...@gmail.com` on 17 Apr 2015 at 6:55

**Comment by aaaxx** [comment]
Hi, I was the one who reported this originally at Google Code. Is there a chance of it being taken care of in the near future? Seems a shame that easy fixes such as this one (characters already exist) get put on the back burner.

**Comment by marekjez86** [comment]
jungshik, how should I deal with this kind of bug? let's talk (no need to write anything here).

**Comment by xiangyexiao** [comment]
Why is it a high priority for Android, considering Android doesn't use Noto Sans.  (I assume the problem is in Noto Sans as reported by the external contributor)

**Comment by xiangyexiao** [comment]
and confirmed that subscripts (inferiors) numerals are missing in Phase II Noto Sans and Serif fonts, while superscript numerals (0–9) are included in Phase II Noto Sans and Serif fonts.

**Comment by roozbehp** [comment]
@xiangyexiao, as you discovered yourself, this is high priority for Android because of Noto Serif. The missing characters are very high frequency (they have been in Unicode from the first versions too).

**Comment by ArchangeGabriel** [comment]
They are also missing in Noto Mono. When typesetting LaTeX document in my terminal, I’ve got small boxes when entering ₀₁₂₃₄₅₆₇₈₉ (interestingly, while typing that in my browser which uses Noto to display too, the glyphs for 2, 3 and 4 subscripts appear, but not the others).

**Comment by marekjez86** [comment]
tested with Noto Sans * from https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/sans
and with Noto Serif * from https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/serif

[en-335-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/1069768/en-335-Roboto-Black.pdf)
[en-335-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/1069769/en-335-Roboto-Italic.pdf)
[en-335-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/1069774/en-335-NotoSansMono-Black.pdf)
[en-335-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/1069770/en-335-NotoSerif-Black.pdf)
[en-335-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/1069773/en-335-NotoSerif-Italic.pdf)
[en-335-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/1069771/en-335-NotoSerif-Regular.pdf)
[en-335-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/1069772/en-335-NotoSerifDisplay-Black.pdf)
[en-335-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/1069775/en-335-NotoSerifDisplay-Italic.pdf)
[en-335-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/1069778/en-335-NotoSerifDisplay-Regular.pdf)
[en-335-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/1069779/en-335-NotoSans-Black.pdf)
[en-335-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/1069776/en-335-NotoSans-Italic.pdf)
[en-335-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/1069777/en-335-NotoSans-Regular.pdf)
[en-335-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/1069780/en-335-NotoSansDisplay-Black.pdf)
[en-335-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/1069781/en-335-NotoSansDisplay-Italic.pdf)
[en-335-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/1069783/en-335-NotoSansDisplay-Regular.pdf)
[en-335-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/1069782/en-335-Roboto-Regular.pdf)


I do not see any missing subscripts

**Comment by ArchangeGabriel** [comment]
Hum… Those are unreleased version, right? The Mono font on my system is this one: https://github.com/googlei18n/noto-fonts/blob/master/hinted/NotoMono-Regular.ttf

By which file should I replace it to test the -alpha one?

**Comment by marekjez86** [comment]
@ArchangeGabriel  : https://github.com/googlei18n/noto-fonts-alpha/blob/master/from-pipeline/unhinted/ttf/sans/NotoSansMono-Regular.ttf

**Comment by ArchangeGabriel** [comment]
OK, that’s what I thought. So I’ve tried this, and suddenly my web browser (Firefox) started spinning all cores of my laptop for some minutes, and now this web page for instance is rendered in Noto Sans Mono (subscripts works btw), which is ugly.

And I can’t select this font in my terminal, it does not appear in the font list.

**Comment by ArchangeGabriel** [comment]
Just to let you know, Noto fonts where updated today on my system and now it works properly. Thanks!
