### ISSUE TITLE
Non-Latin Noto fonts are not listed on Fonts.com SkyFonts platform

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#365]
```
What steps will reproduce the problem?
1. Open SkyFonts App
2. Search for "Noto" under Google provider
3. Only "Noto Sans" and "Noto Serif" (Latin) shown

What is the expected output? What do you see instead?
See non-Latin Noto fonts, such as CKJ ones

What version of the product are you using? On what operating system?
SkyFonts 4.8.2.0, Windows 8.1 x64.

Please provide any additional information below.
That's it really.

```

Original issue reported on code.google.com by `jonrstan...@gmail.com` on 11 May 2015 at 2:52

Attachments:
* [SkyFont-No-Noto-CKJ-etc.png](https://storage.googleapis.com/google-code-attachments/noto/issue-365/comment-0/SkyFont-No-Noto-CKJ-etc.png)

**Comment by fontguy** [comment]
From the SkyFonts page (http://www.fonts.com/web-fonts/google) it looks like they provide those fonts from the Google Web Fonts service. Unfortunately, they only provide Noto Sans and Serif LGC in their regular distribution. All of the other Noto fonts are in their "Early Access" and some for a number of years.

If you'd like to see more Noto fonts in Google Web Fonts for more script then please reach out to the Google Web Fonts team. 

https://www.google.com/fonts#AboutPlace:about
https://docs.google.com/a/google.com/forms/d/1xXMnSwvmbaN_HkN4wSO5CaldwZO0nHdDU7CIwtPd6LE/viewform
