### ISSUE TITLE
Noto Nastaliq Urdu Draft is not joining Saraiki letters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#372]
```
What steps will reproduce the problem?
1. Writing Saraiki , the letters are not joined. 
2.
3.

What is the expected output? What do you see instead?

Add Saraiki  support.
What version of the product are you using? On what operating system?
Noto Nastaliq on windows 7.

Please provide any additional information below.

Noto Nastaliq Urdu Draft is not joining Saraiki letters
```

Original issue reported on code.google.com by `mpqa...@gmail.com` on 15 May 2015 at 3:02

**Comment by behdad** [comment]
cc @kmansourMT

**Comment by kmansourMT** [comment]
Version 1.00 of Noto Nastaliq Urdu supports all 6 Saraiki characters (u0678, u0683, u0759, u068A, u0684, 067B) that were missing in previous versions as evidenced by the following text samples:

![068a](https://cloud.githubusercontent.com/assets/12738181/8048249/12dcdb1e-0e04-11e5-8f86-8d7ba91b50aa.png)
![067b](https://cloud.githubusercontent.com/assets/12738181/8048250/12eee8fe-0e04-11e5-942f-ba9128855b2b.png)
![0684](https://cloud.githubusercontent.com/assets/12738181/8048252/130c5e20-0e04-11e5-9532-3acc9125acc3.png)
![0759](https://cloud.githubusercontent.com/assets/12738181/8048251/1302c5a4-0e04-11e5-9646-7e1d6f867846.png)
![0683](https://cloud.githubusercontent.com/assets/12738181/8048254/131b34ae-0e04-11e5-8122-03ed7a7f2373.png)
![0678](https://cloud.githubusercontent.com/assets/12738181/8048253/131a8d6a-0e04-11e5-9950-d7bcedf3dac4.png)

**Comment by behdad** [comment]
Thank you Kamal.

**Comment by behdad** [comment]
Reopening and assigning to myself, till we get the new version of font out.
