### ISSUE TITLE
Noto Sans Symbols: symbols between U+2983 to U+298A are too thick

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#377]
```
customer report:

========

Symbols between U+2983 to U+298A are too thick

========

Please check if this is intentional or a real issue.
```

Original issue reported on code.google.com by `xian...@google.com` on 29 May 2015 at 10:22

**Comment by behdad** [comment]
cc @xiangyexiao

**Comment by xiangyexiao** [comment]
jungshik is working on making a platform specific font build to have consistent thickness of symbols on the platform

**Comment by xiangyexiao** [comment]
duplicated with https://github.com/googlei18n/noto-fonts/issues/417
