### ISSUE TITLE
Noto Sans Balinese Om ligature diacritic alignment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#380]
```
What steps will reproduce the problem?
Any letter (U+1B05 to U+1B33) followed by any above-based diacritic (U+1B00 to 
U+1B04, U+1B34, U+1B36, U+1B37, U+1B3C, U+1B3D, U+1B42, U+1B43). In particular, 
the "Om" ligature (U+1B12 + U+1B01).

What is the expected output? What do you see instead?
Rightfully the above-based diacritic should be smack in the middle of the 
glyph, but ends up aligned on the right side. While this doesn't look like a 
big deal for most glyphs, but for "Om" it doesn't look right at all having the 
ulu candra diacritic standing on the very right when it's supposed to be on the 
'heart' of the okara tedung. "Om" is a holy symbol and thus should be outputted 
beautifully, and having the ulu candra in the middle is key to achieving this, 
the sense of balance and harmony projected by the ligature.

What version of the product are you using? On what operating system?
Noto Sans Balinese Regular v1.02
Google Chrome 43.0
Windows 7 Professional SP1

Please provide any additional information below.

```

Original issue reported on code.google.com by `tcl111...@gmail.com` on 31 May 2015 at 10:37

**Comment by jungshik** [comment]
Confirming. 
```<U+1B12, U+1B01>```

![screen shot 2015-11-20 at 2 52 27 am](https://cloud.githubusercontent.com/assets/8578343/11298126/d362d83a-8f31-11e5-92b9-1d30f304328d.png)

**Comment by jungshik** [comment]
@kmansourMT : please, look into this issue. Note that ```<U+1B12, U+1B01>``` is the worst case, but the reporter also complained about the position of other 'above-mark' with respect to a base glyph.

**Comment by kmansourMT** [comment]
In the forthcoming version of Noto Balinese, top marks are centered over the bases (consonants & independent vowels) instead of being right-aligned. The following graphic demonstrates the changes, including to the Om sign.
![bases-topmark](https://cloud.githubusercontent.com/assets/12738181/12798327/a4232656-ca7d-11e5-82ba-a4bb48abb1eb.png)

**Comment by jungshik** [comment]
@kmansourMT's fix will be included in upcoming phase 3 delivery.
