### ISSUE TITLE
U+20F0 COMBINING ASTERISK ABOVE should be six-pointed in Noto Symbols and Noto Sans

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#382]
```
As a Latin and general purpose character, it's considered a math character, 
proposed in http://www.unicode.org/L2/L2007/07011-n3198-math.pdf.

It's not supposed to match the asterisk in the font, but should be always 
six-pointed.

(Side note: The character is unified with a Vedic star. In Indic fonts, the 
character could have different numbers of points, based on local Vedic 
traditions.)
```

Original issue reported on code.google.com by `roozbeh@google.com` on 3 Jun 2015 at 6:17

**Comment by behdad** [comment]
cc @roozbehp @kmansourMT

**Comment by fontguy** [comment]
Actually, in the PDF document that is linked in the original bug report the image of a 5 pointed asterisk is shown as representative of the character U+20F0. Also, as I look at the fonts on my computer outside of the Noto fonts there seems to be a fairly even split between 5 and 6 pointed asterisks. Finally, if we look at the Latex accentstar macro package documentation (http://cs.brown.edu/about/system/managed/latex/doc/accents.pdf) we can see that they too use the five pointed asterisk.

It seems as if there is no consensus on 5 versus 6 pointed asterisk for this use.
