### ISSUE TITLE
Wrong Allah glyph and ligature rules in the Naskh font

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-fonts#384]
FDF2 الله ARABIC LIGATURE ALLAH ISOLATED FORM
≈ <isolated> 0627   0644   0644   0647 

using HTML print the char "xFDF2"
Expected: see
![u-fdf2](https://cloud.githubusercontent.com/assets/12721521/8074002/697c965c-0ee1-11e5-8a99-8c93640eb833.png)
 the attachment.
Actual: it displayed as لله

Sue, this is a high priority bug. We want it to be fixed ASAP, better to be within a month.

**Comment by roozbehp** [comment]
It seems that the lookup for forming Allah-related ligatures is also wrong. Using my own names, it is currently something like this:

lookup 10 { # type=4 flag=0x8
  sub alef.isol lam.init lam.medi shadda_superscriptalef heh.fina by alef_lam_lam_heh;
  sub lam.init lam.medi heh.fina by lam_lam_heh;
}

The first rule is basically eating the shadda and the superscript alef, and the second rule is shortening a lam unnecessarily.

It should instead be something like this:
lookup 10 {
  sub lam.init lam.medi shadda_superscriptalef heh.fina by lam_lam_shadda_superscriptalef_heh;
}

**Comment by roozbehp** [comment]
The second rule, the current
```
sub lam.init lam.medi heh.fina by lam_lam_heh;
```
could probably be replaced by an alternative, that shortens in second lam only when a shadda is present on it, to get words like <lam, lam, shadda, fatha, heh> (pronounce "lellah" in Persian) right. If we do this, we may need an additional glyph, that has a shorter second lam and shadda on that lam, but no superscript alef.

(This specific comment is really just an idea. It's not high priority. But the original report and my first comment are high priority.)

/cc @behdad

**Comment by roozbehp** [comment]
The lookup flag on lookup 10 may also need to change. Currently, it's set to skip marks, and  shadda_superscriptalef is defined as a mark, so it seems to be skipping it.

**Comment by roozbehp** [comment]
Internal tracker b/21492433

**Comment by roozbehp** [comment]
Lowering the priority, since we could do a hotfix for the product. We still need a fix, but it's no as urgent anymore.

**Comment by khaledhosny** [comment]
Note that there are many ways that this ligature can be applied in wrong contexts, like the word خالله (the last part of it is *not* the name of God and should not use the ligature) and many more. I suggest to either not apply the ligature by default or (if you think it is worth the effort) use some complex contextual rules like the ones used in [Amiri](https://github.com/khaledhosny/amiri-font/blob/master/sources/lellah.fea) (which might still give false positives, only Arabic was considered).

**Comment by raphlinus** [comment]
khaledhosny: We're trying to be more careful than that. In our current "hotfix" version, we form the ligature for alif-lam-lam-shadda-daggeralif-ha, but not for alif-lam-lam-ha. The word you pasted does form the ligature on my Mac (Geeza Pro, see <http://www.org.uib.no/smi/ksv/ArabicFonts.html>), but does not on Android.

There's a good chance it'll make it into the next M developer preview. If you could test it then, it would be deeply appreciated.

**Comment by khaledhosny** [comment]
I think this should be fine. For completeness, you probably should added a فلله ligature (that is feh-alif-lam-lam-shadda-daggeralif-ha).

**Comment by roozbehp** [comment]
A related issue found by @behdad: Currently the ligature doesn't have correct MarkLig positioning.

**Comment by dougfelt** [comment]
OK, version 1.05 of Naskh is in the repo now.  MTI says this issue has been fixed by this drop.  @roozbehp can you confirm?

**Comment by xiangyexiao** [comment]
confirmed it is fixed.
