### ISSUE TITLE
Noto Sans Gurmukhi glyph overlapping occurring with U+0A71 ADDAK

### ISSUE THREAD

**Issue by kulpreetchilana** [googlei18n/noto-fonts#385]
Glyph overlapping is occurring with all independent and dependent vowels and U+0A71 ADDAK. This is seen in the following examples:

ਈੱਕ ਉੱਕ ਊੱਕ ਏੱਕ ਐੱਕ ਓੱਕ ਔੱਕ
ਕੇੱਕ ਕੈੱਕ ਕੋੱਕ ਕੌੱਕ ਕੀੱਕ

This makes words like

ਉੱਤੇ
 
which means above, look a bit crowded.

![addak](https://cloud.githubusercontent.com/assets/235441/8152923/bed13964-12d8-11e5-88b3-f1869997721f.png)

**Comment by behdad** [comment]
cc @roozbehp @cibu @JelleBosmaMT

**Comment by JelleBosmaMT** [comment]
In October 2013 we decided that having the addak close to a preceding top
mark is a better compromise than creating a gap between the base glyphs.

**Comment by kulpreetchilana** [comment]
Is it not possible to move the ADDAK a hairline to the right, only when it appears next to a vowel and avoid the gap? It looks kind of ridiculous right now.

**Comment by JelleBosmaMT** [comment]
Checking my data when I investigated the issue the word ਉੱਤੇ is the third most frequent word that makes use of the addak. In 2013 the reviewers did not like me to increase the distance between ਉ and ਤ. The addak is therefore positioned in between the bowl of the ਉ and the e mark to the right. Which is a crowded place indeed.

The sequences ਉੱ and ੀੱ seems to be the most problematic with regards to the addak not standing out enough. Much less of a problem in the case of the e and ai marks for exampe, which lean to the left.
It may be worth in the next version of the fonts to move the addak to the right after ਉ and ੀ. Then for some specific combinations such ( ਉੱਤੇ ਉੱਠਿ ਉੱਥੋਂ  ਉੱਠੇ ਉੱਗਿ ਈੱਥੋਂ ) fiddle with the top marks to make room for the addak. It does require the software to support interaction between syllables, which may not always be the case...
