### ISSUE TITLE
Noto Sans Gurmukhi dotted circles for U+0A41 U and U +0A42 UU are not centered

### ISSUE THREAD

**Issue by kulpreetchilana** [googlei18n/noto-fonts#386]
Noto Sans Gurmukhi dotted circles for U+0A41 U and U +0A42 UU are not centered with the vowel and looks awkward:
![circles](https://cloud.githubusercontent.com/assets/235441/8152941/42ee7fc2-12d9-11e5-8b06-28ae4e7b86a0.png)

**Comment by fontguy** [comment]
The problem here isn't the centred-ness or lack thereof but the fact that the Gurmukhi font seems to be showing the dotted circles from the Unicode code chart that indicates a combining character. These shouldn't be shown when using the font.

cc @waksmonskiMT

**Comment by fontguy** [comment]
It seems that we have these dotted circles in other cases (though they are not required). Since we have them they should look correct.

**Comment by JelleBosmaMT** [comment]
The main purpose of the dotted circle is to show invalid combinations (spelling mistakes) that need correction. Although currently the position of the low vowels is not visually pleasing, it is good enough for that. I admit it would be more attractive if the marks are centered for usage in something like a key map utility or on-screen keyboard. I put a reminder in my source folder to fix this for phase 3, by putting the dotted circle on a larger advance width, moving marks to the centre.

**Comment by roozbehp** [comment]
We show vowels on dotted circles on Android's keyboards, so it's actually important to us that it looks good.

**Comment by JelleBosmaMT** [comment]
In principle this can be be fixed for the existing fonts within an hour by adding an entry for u+25CC in the GDEF and an anchor for it in the second lookup of the GPOS, without changing anything else, except the version number. But I don't know what has been agreed between Monotype and Google about maintenance and what the expectations are about QA, changes to copyright and trademark and new Lint hurdles that have to be taken, which makes the update procedure so much more complicated.

**Comment by xiangyexiao** [comment]
@waksmonskiMT We want this issue to be fixed by end of April. It seems that it probably needs to be fixed in Phase II fonts. Please investigate.

**Comment by xiangyexiao** [comment]
@waksmonskiMT 
An update on timeline. We want this issue to be fixed by end of March for Phase II.

**Comment by marekjez86** [comment]
@kulpreetchilana https://github.com/googlei18n/noto-fonts/tree/828c6a6c257487c39bd53a7bbea90d6079340c33/hinted has fix for this bug (also unhinted). Could you verify that it was fixed and advise us? Thank you.

**Comment by xiangyexiao** [comment]
I have verified this bug is fixed.
