### ISSUE TITLE
Noto Sans Gurmukhi U+0A51 UDAAT is in the wrong position

### ISSUE THREAD

**Issue by kulpreetchilana** [googlei18n/noto-fonts#390]
U+0A51 UDAAT is in the wrong position. It should be centered as shown in the Lohit Gurmukhi to the right:
![screen shot 2015-06-14 at 9 11 17](https://cloud.githubusercontent.com/assets/235441/8152979/ec1e473a-12d9-11e5-9017-7bf13f639f46.png)

**Comment by fontguy** [comment]
I see the same behaviour as Noto in 3 other Gurmukhi fonts.

cc @waksmonskiMT

**Comment by kulpreetchilana** [comment]
I investigated this a bit more and it looks like it's mainly important that the UDAAT joins at the right side of the foot of ਨ, as in ਨੑ

This seems to be occurring correctly in Noto Sans Gurmukhi. Feel free to close.
