### ISSUE TITLE
Noto Sans Gurmukhi does not support combining U+0A51 UDAAT and U+0A75 YAKAASH with U+0A41 U and U+0A42 UU

### ISSUE THREAD

**Issue by kulpreetchilana** [googlei18n/noto-fonts#391]
Noto Sans Gurmukhi does not support combining U+0A51 UDAAT and U+0A75 YAKAASH with U+0A41 U and U+0A42 UU:

![screen shot 2015-06-14 at 9 12 11](https://cloud.githubusercontent.com/assets/235441/8152985/0e429dca-12da-11e5-9fcf-cfbb6a779bfd.png)

See http://www.unicode.org/L2/L2006/06037-yakash.pdf for more information about how this should work.

**Comment by fontguy** [comment]
If we have the character then the joining rules should work.

cc @waksmonskiMT

**Comment by JelleBosmaMT** [comment]
When there is a dotted circle, the software has decided there is an invalid character combination. This is not a font issue. When there is software that does properly support the characters, it looks like this:

![gu](https://user-images.githubusercontent.com/12729011/31168410-821776e0-a8f5-11e7-89c0-bfadbbbfe100.png)

**Comment by kulpreetchilana** [comment]
Makes sense. No longer seems to occur on my Mac, running High Sierra.
