### ISSUE TITLE
In m̥ of Noto Sans, ring touches “m”

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#394]
In m̥ of Noto Sans, the “Combining ring below” mark touches the “m”. Can it be moved slightly further down, so they do not touch? See the attached screenshot of gedit in Ubuntu 15.04, taken after “sudo apt-get install fonts-noto” and making Noto the default font for gedit.

![screenshot of gedit in Ubuntu 15.04](https://cloud.githubusercontent.com/assets/1527880/8164449/6aff135e-1389-11e5-899b-b141181279aa.png)

**Comment by fontguy** [comment]
It doesn't touch when I look at it on the Mac but it is close. It looks to be about the same space between the L and the ring as between the m and the ring. We could look at adding a bit of space.

**Comment by jungshik** [comment]
No change in this regard between P2 (ttf) and P3(otf ; generated from Glyph source) in Noto Sans. 

Outlines do not touch, but are pretty close to each other. As mentioned earlier, we can consider adding a bit more space.

**Comment by TrueTyper** [comment]
There isn't room vertically to add more space in any of the master weights without then clipping the ring and changing the shape. I think this bug should be closed.

**Comment by marekjez86** [comment]
I tested it on:
NotoSans
NotoSans Italic
NotoSansDisplay
NotoSansDisplay Italic
NotoSerif
NotoSerif Italic
NotoSerifDisplay
NotoSerifDisplay Italic

The results are in the following files (it touches in case of NotoSans Black, but closing the bug):

[pl-394-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/610491/pl-394-NotoSans-Black.pdf)
[pl-394-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/610495/pl-394-NotoSans-Italic.pdf)
[pl-394-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/610493/pl-394-NotoSansDisplay-Black.pdf)
[pl-394-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/610494/pl-394-NotoSansDisplay-Italic.pdf)
[pl-394-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/610492/pl-394-NotoSerif-Black.pdf)
[pl-394-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/610490/pl-394-NotoSerif-Italic.pdf)
[pl-394-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/610496/pl-394-NotoSerifDisplay-Black.pdf)
[pl-394-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/610498/pl-394-NotoSerifDisplay-Italic.pdf)
[pl-394-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/610497/pl-394-NotoSans-Regular.pdf)
[pl-394-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/610501/pl-394-NotoSerif-Regular.pdf)
[pl-394-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/610500/pl-394-NotoSerifDisplay-Regular.pdf)
[pl-394-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/610499/pl-394-NotoSansDisplay-Regular.pdf)
