### ISSUE TITLE
Cherokee lowercase

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#396]
Unicode 8.0 added lowercase forms for Cherokee:
http://www.unicode.org/charts/PDF/UAB70.pdf

**Comment by fontguy** [comment]
Not a part of phase II which only covers until Unicode 6.x-ish.

**Comment by roozbehp** [comment]
/cc @ccornelius

FWIW, at the UTC meeting last week, it was discussed that the design of the lowercase Cherokee glyphs used in the Unicode code chart was not acceptable to the contacts from the Cherokee nation: the glyphs should not use ascenders or descenders, but should be in small-caps style. In other words, the lower-case should not be Latin-like, but Cyrillic-like.

UTC is planning to change the lowercase Cherokee glyphs in the charts.

**Comment by jungshik** [comment]
From the unicode announcement list: 

The Unicode Consortium has recently updated the current code charts for the Cherokee script specifically to provide improved reference glyphs for the lowercase letters introduced in Version 8.0. The new font is Phoreus Cherokee, a modern digital design by Mark Jamra of TypeCulture® LLC.

The new charts can be viewed through the current Charts page.
http://www.unicode.org/charts/PDF/U13A0.pdf
http://www.unicode.org/charts/PDF/UAB70.pdf
http://blog.unicode.org/2015/11/unicode-cherokee-chart-font-updated.html

**Comment by jungshik** [comment]
FYI: http://www.pressherald.com/2015/11/29/portland-graphic-designer-helps-the-cherokee-nation-update-its-language-for-the-digital-age/

**Comment by xiangyexiao** [comment]
Sue,
Please prioritize Cherokee (including lowercase support) among all Tier-4 scripts. I moved it to the top of Tier-4 scripts and mark it as Tier-4(3+).  Best to have font delivery by end of 2016.

https://b.corp.google.com/u/0/issues/26604030

**Comment by xiangyexiao** [comment]
The new desired timeline is late April / early May. Is it feasible?

**Comment by Alhadis** [comment]
What's MNTF mean?

(I tried Googling it, but found nothing conclusive...)

**Comment by marekjez86** [comment]
this was an internal acronym that meant "M Needs To Fix" :-) not used any longer hence. I'm deleting it

**Comment by marekjez86** [comment]
we have published alpha of dualcase Noto Sans cherokee in https://github.com/googlei18n/noto-fonts/tree/master/alpha/OTF/from-pipeline
