### ISSUE TITLE
Issues with Thaana

### ISSUE THREAD

**Issue by Kanjilearner817** [googlei18n/noto-fonts#399]
This website shows a number of issues with Noto Sans Thaana.
http://kodefly.com/blog/articles/101

**Comment by dougfelt** [comment]
There's a new version of Thaana available on github and it appears to have addressed the combining mark positioning issue.

**Comment by dougfelt** [comment]
The handwriting issue appears to be unaddressed by this version.

**Comment by xiangyexiao** [comment]
I'll leave this issue open for discussion in Phase III.

**Comment by xiangyexiao** [comment]
still want to know whether the handwriting issue mentioned in the past is valid or not, and something we can do in Phase III.

**Comment by marekjez86** [comment]
@Kanjilearner817 : is there a copy of the article that existed on http://kodefly.com/blog/articles/101
I wanted to understand the issues and to check if we made progress on addressing them.

**Comment by Kanjilearner817** [comment]
Doesn't look like it. Didn't even know about the page's disappearance until today. Sorry.

**Comment by marekjez86** [comment]
@Kanjilearner817 : Thank you for checking.

**Comment by pathumego** [comment]
@inerds You wrote the post on  http://kodefly.com, right?

**Comment by inerds** [comment]
My colleague  @aliharis have re written the article with more insights 
https://medium.com/kodefly/is-noto-sans-thaana-relevant-29a8307fb6cb

**Comment by pathumego** [comment]
@marekjez86 here is what we discussed https://medium.com/kodefly/is-noto-sans-thaana-relevant-29a8307fb6cb
