### ISSUE TITLE
Noto Serif and Noto sans cjk Merged otf/ttf

### ISSUE THREAD

**Issue by ambikakhatri** [googlei18n/noto-fonts#401]
Is it possible to merge noto serif and noto sans cjk regular font in same file? I have been trying to merge with fontforge but it's not working. Is there a plan to release combined otf/ttf for these two.

-Ambika

**Comment by wong2** [comment]
+1  wish there's a doc on how to merge multiple Noto fonts into one ttf

**Comment by Superpencil** [comment]
+1

**Comment by fontguy** [comment]
It's not possible to directly merge two fonts with different glyph formats. A font can only contain TrueType OR CFF outlines.
