### ISSUE TITLE
Oriya → Odia

### ISSUE THREAD

**Issue by davelab6** [googlei18n/noto-fonts#404]
The formal anglicised name of the language changed from Oriya to Odia (and the state from Orissa to Odisha) [in 2011](https://en.wikipedia.org/wiki/Odisha#Etymology) so I suggest updating the fonts to reflect this:

- [ ] NotoSansOriya-Regular.ttf → NotoSansOdia-Regular.ttf	
- [ ] NotoSansOriya-Bold.ttf → NotoSansOdia-Bold.ttf	
- [ ] NotoSansOriyaUI-Regular.ttf → NotoSansOdiaUI-Regular.ttf
- [ ] NotoSansOriyaUI-Bold.ttf	→ NotoSansOdiaUI-Bold.ttf

**Comment by dougfelt** [comment]
Yes.  This is not a new issue.

In general, there's lots of issues around naming and it can get a bit politically fraught.  We don't really want to go there.  The decision that's been made is to keep the font/script names stable and not adjust them to match current usage as it changes.  This does mean that the font names might not be immediately recognizable to some users.

**Comment by davelab6** [comment]
OK :)

**Comment by roozbehp** [comment]
Closing and confirming what Doug said. We are using the Unicode names for the scripts.
