### ISSUE TITLE
Farsi version

### ISSUE THREAD

**Issue by hadifarnoud** [googlei18n/noto-fonts#406]
there are very limited number of fonts that support Farsi/Persian and they're represented by an 'Arabic' name at the end.

in order to get proper support behind these fonts, please release more versions and name them accordingly. Arabic and Farsi are two very different languages albeit similar typography. We're not used to search for 'Arabic fonts'.

Looking forward to see more Farsi fonts in Google Fonts service. It's truly a missing service for Farsi language as there are no competitor filling the gap

**Comment by roozbehp** [comment]
You can get to the fonts by searching for "Persian" at http://www.google.com/get/noto/.

The name at the end is typically the name of the script, not the language. For example, Hindi is also supported by Noto Devanagari fonts. In this case, it happens that Persian is written in the Arabic script, which is also the name of a language.

Noto Naskh Arabic support Persian completely. We have made sure all requirements of the language are met, including support for alternative decimal separator, etc.

**Comment by amir-abdi** [comment]
Although I am not an expert, the fonts "Noto Kufi Arabic" and "Noto Naskh Arabic" do not seem to follow their corresponding Arabic scripts. They are simply Persian/Farsi scripts falsely named as Arabic and needs further revisions.

Please also consider the origin of Persian and Arabic languages as well as their scripts and the fact that neither of them originated from the other one.
