### ISSUE TITLE
Light variant of Arabic font

### ISSUE THREAD

**Issue by ebraminio** [googlei18n/noto-fonts#407]
Android uses light/thin typeface on lockscreen and some other places, it would be nice if noto (or roboto?) had light Arabic-Indic and Persian digits or a complete light Arabic font support.
![screenshot_2015-06-26-12-52-45](https://cloud.githubusercontent.com/assets/833473/8685006/171a50c2-2a91-11e5-9760-e5a5d22e8d0e.png)
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/833473/8685008/1b07dcb8-2a91-11e5-9c66-27c88a90792f.png)
![screenshot_2015-06-26-13-04-17](https://cloud.githubusercontent.com/assets/833473/8685013/21aaebb4-2a91-11e5-8912-cc3ec8e79039.png)
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/833473/8685011/1f79c6bc-2a91-11e5-8a36-df735d492b89.png)

**Comment by fontguy** [comment]
Noto fonts currently have 2 weights - regular and bold.

**Comment by ebraminio** [comment]
That is not fact for noto-CJK fonts. I thought it could be possible to have Light version if it would reasonable.

**Comment by fontguy** [comment]
That is correct - the CJK fonts come in more than two weights. They were developed in a different process than the other scripts. Never say never though.
