### ISSUE TITLE
U+0EBD LAO SEMIVOWEL SIGN NYO should like more like letter J

### ISSUE THREAD

**Issue by MahaHas** [googlei18n/noto-fonts#413]
It doesn't look the same shape as defined in Unicode set

Attached is a comparison between MAC,Android & Unicode
![lao-semivowel-nyo](https://cloud.githubusercontent.com/assets/12836138/8791936/4b5a0b96-2f16-11e5-9193-4df62e5fbe95.png)

**Comment by roozbehp** [comment]
@xiangyexiao or @marekjez86, would you please ask a Lao linguist/expert if this bug is valid?

**Comment by jungshik** [comment]
I think this is invalid. According to the designer (Danh Hong), the shape in the code chart or Mac OS X is not what is liked by Laotian speakers.
