### ISSUE TITLE
Some Geometric shapes need to be bigger to match Unicode

### ISSUE THREAD

**Issue by MahaHas** [googlei18n/noto-fonts#415]
Compared to Unicode and the other glyphs in Noto fonts, the attached geometric shapes need to be bigger.

Attached is a comparison between IE11, MAC,Android & Unicode
![geoshapes1](https://cloud.githubusercontent.com/assets/12836138/8792176/0e850786-2f19-11e5-9ead-78a2fb33fcec.png)
![geoshapes2](https://cloud.githubusercontent.com/assets/12836138/8792181/12050866-2f19-11e5-932e-2f2ba008ac02.png)

**Comment by xiangyexiao** [comment]
Maha, could you put these geometric characters next to Latin letters (e.g., English alphabet) and compare their sizes. Whether they are pairing well next to each together decides the proper size of them.

**Comment by MahaHas** [comment]
Xiangye
See attachments for Android WebView & TextView.
SOmething wrong with my computer, so I could not get the equivalent mac. 
Let me know if you need it.
![geoshape-textview-and1](https://cloud.githubusercontent.com/assets/12836138/8887067/e0c6d324-3229-11e5-80fc-8f4197e37b1b.png)
![geoshape-textview-and2](https://cloud.githubusercontent.com/assets/12836138/8887064/e0c41ed6-3229-11e5-87aa-ee2f6083f55b.png)
![webview-and11](https://cloud.githubusercontent.com/assets/12836138/8887065/e0c4668e-3229-11e5-86c1-3432767144c7.png)
![webview-and12](https://cloud.githubusercontent.com/assets/12836138/8887066/e0c66b64-3229-11e5-8673-9b0fb8fbd2f2.png)

**Comment by MahaHas** [comment]
xiangyexiao,
I found out you cannot see the name of files I attached, so:
The black & White is TextView
The Blue is Web View

**Comment by fontguy** [comment]
These generally look fine next to the latin text. The Unicode form is not normative and the form can vary.
