### ISSUE TITLE
U+2694 Crossed sword need to be more bold or larger

### ISSUE THREAD

**Issue by MahaHas** [googlei18n/noto-fonts#416]
using HTML print the char U+2694

Need to look the same as defined in Unicode set
Attached is a comparison between MAC,Android & Unicode

Definition From Unicode:
2694 ⚔ CROSSED SWORDS
= military term, battleground (on maps), killed in
action
![crossedsword-android](https://cloud.githubusercontent.com/assets/12836138/8792245/99ea08e4-2f19-11e5-96f8-1377a66f420b.png)

**Comment by xiangyexiao** [comment]
2694 in Noto Symbols looks smaller and thinner than other symbols in the nearby range.
<img width="412" alt="screen shot 2015-12-18 at 1 33 58 pm" src="https://cloud.githubusercontent.com/assets/12721521/11907857/319e40c2-a58c-11e5-97b6-3b3a3b23c563.png">

**Comment by xiangyexiao** [comment]
confirm it is solved.
