### ISSUE TITLE
The math brackets at U+2983..U+298A appear too thick

### ISSUE THREAD

**Issue by MahaHas** [googlei18n/noto-fonts#417]
using HTML print the char U+27E6..27EB and 2985..2986

Expected: to be displayed as defined in Unicode Chart 
Actual: see attachments for comparison between Mac-Android-Unicode 

![bracketandroid](https://cloud.githubusercontent.com/assets/12836138/8792286/1c4e3670-2f1a-11e5-8e49-452308cb86b3.png)

From Roozbeh:
U+2985 and U+2986 come from Noto Sans Symbols. It's not only these two that's too thick in the font. The characters next to them, the whole range U+2983 to U+298A is too thick. Maha, please file a bug at the public Noto tracker for Noto Sans Symbols.

**Comment by xiangyexiao** [comment]
Could you also put numbers next to Android and Mac fonts to see whether they are too thick? I saw the pairing image for Android, but not for Mac.

**Comment by MahaHas** [comment]
![comparaison](https://cloud.githubusercontent.com/assets/12836138/8886512/7d6e01a2-3220-11e5-8608-7f1586fc288d.png)

**Comment by xiangyexiao** [comment]
Glyphs in Noto for these symbols do look thicker than other fonts. For example, glyphs for u+2984 and u+2989 in the attached images are the thickest among all fonts on Mac.

<img width="141" alt="screen shot 2015-11-11 at 3 15 49 pm" src="https://cloud.githubusercontent.com/assets/12721521/11105970/488648f6-8887-11e5-90e9-2e596f71f65e.png">
<img width="148" alt="screen shot 2015-11-11 at 3 16 18 pm" src="https://cloud.githubusercontent.com/assets/12721521/11105971/4887cbf4-8887-11e5-931f-983431622832.png">

**Comment by xiangyexiao** [comment]
3rd of the two images are Noto's glyphs

**Comment by SteveMatteson** [comment]
This is not a bug. The symbols are designed to go with Noto Sans regular. The comparison fonts are serif and therefor high contrast. Math symbols designed to go with serif fonts are close to the hairline weight and therefore much lighter than sans.

**Comment by xiangyexiao** [comment]
I checked the range of U+2983 to U+298A. Noto Symbols doesn't look thicker for these glyphs when next to Roboto or Noto Sans. I will close the bug.

<img width="524" alt="screen shot 2015-12-18 at 12 05 35 pm" src="https://cloud.githubusercontent.com/assets/12721521/11906222/d34aadaa-a57f-11e5-932f-4efbdb3a8e38.png">
