### ISSUE TITLE
DOTTED CIRCLE is inconsistent across Noto

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#426]
Moved from googlei18n/noto-alpha#267

Imported from [Google Code issue #267](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=267) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-11-04T20:02:52.000Z:

----
The U+25CC DOTTED CIRCLE character is inconsistent across the Noto fonts. In some fonts, such as Noto Naskh Arabic, it's a dashed circle, while in Noto Sans (LGC) it's a dotted one.

/cc @fontguy 
/cc @xiangyexiao 
/cc @kmansourMT

**Comment by xiangyexiao** [comment]
they rendered the same in Noto Sans, Noto Symbols and Noto Naskh.
<img width="197" alt="screen shot 2015-12-18 at 12 21 58 pm" src="https://cloud.githubusercontent.com/assets/12721521/11906564/51ad7716-a582-11e5-9b00-8b17ffe85b58.png">
