### ISSUE TITLE
combining cedilla is misplaced w.r.t. a lot of base characters in Noto

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#427]
Moved from googlei18n/noto-alpha#246

Imported from [Google Code issue #246](https://code.google.com/p/noto-alpha/issues/detail?id=246) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-07-01T23:32:06.000Z:

---

The sequences z̧ and Z̧ don't render properly in Noto Sans and Noto Serif.

It appears that cedilla anchor marks in the GPOS table are limited to a small subset of Latin characters.

Attaching renderings from Noto Sans and Noto Serif.

Sample usage on the web at http://www.geographic.org/geographic_names/name.php?uni=-4494882&amp;fid=3775&amp;c=libya

noto-sans.png
![noto-sans](https://cloud.githubusercontent.com/assets/9939212/8630999/48276d84-2722-11e5-8790-fc8e0da2a380.png)
noto-serif.png
![noto-serif](https://cloud.githubusercontent.com/assets/9939212/8630998/4826b9c0-2722-11e5-9011-cda9089f8a3a.png)

**Comment by jungshik** [comment]
Comment [#1](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=246#c1) originally posted by roozbeh@google.com on 2014-07-01T23:38:10.000Z:

-----
Compare with attached sample, rendered in Calibri.
![calibri](https://cloud.githubusercontent.com/assets/9939212/8631004/5b436774-2722-11e5-9ad3-6a1a79b28c09.png)

**Comment by jungshik** [comment]
Behdad wrote: 
Font bug as far as HarfBuzz is concerned, though we might come up with a heuristic in the future.

**Comment by jungshik** [comment]
9 days ago: @dougfelt wrote:

This is still an issue in Noto Sans v1.05 and Serif v1.04.

**Comment by moyogo** [comment]
This should be generalized to any base letter as many combination of base letter with cedilla can be found.
This is also broken in Arimo, Cousine and Tinos.

For example:
* the Marshallese orthography uses the cedilla with m and o, M̧m̧O̧o̧, and ĻļŅņ which exist precomposed ĻļŅņ but with the comma-below cedilla;
* the General Cameroon Languages Alphabet used for many orthographies uses the cedilla with vowels, A̧a̧Ɛ̧ɛ̧Ə̧ə̧I̧i̧Ɨ̧ɨ̧O̧o̧Ɔ̧ɔ̧U̧u̧ (probably others as well), and Ȩȩ which exist precomposed Ȩȩ;
* the Kinande orthography uses the cedilla with i and u, I̧i̧U̧u̧;
* the ISO 9 transliteration uses the cedilla (or the comma below, it’s unclear) with z, Z̧z̧ and ĻļŅņ which exist precomposed ĻļŅņ as mentioned above;
* KNAB transliterations use the cedilla with f, x, F̧f̧X̧x̧.

There are probably other cases.

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif with: A̧a̧Ɛ̧ɛ̧Ə̧ə̧F̧f̧I̧i̧Ɨ̧ɨ̧M̧m̧O̧o̧Ɔ̧ɔ̧U̧u̧X̧x̧Z̧z̧
![screen shot 2015-09-05 at 23 24 53](https://cloud.githubusercontent.com/assets/1923747/9701523/64e31dd0-5425-11e5-8198-a520b0b5c047.png)

**Comment by jungshik** [comment]
Phase 3  Noto Sans {Regular, Italic} built from Monotype's source have this issue now fixed. 

![bug427 notosans_reg_trunk ttf](https://cloud.githubusercontent.com/assets/8578343/11405991/26afe136-9360-11e5-9074-7a7bb00fab45.png)

![bug427 notosans_italic_trunk ttf](https://cloud.githubusercontent.com/assets/8578343/11406005/3414c8e6-9360-11e5-91f4-05d8f5ac48c6.png)

**Comment by jungshik** [comment]
Hmm... Cedilla in ```ĻļŅņ ĻļŅņ``` ( decomposed and precomposed) look like comma.  

@moyogo and @tiroj ,  what do you think of them?

**Comment by tiroj** [comment]
The comma form for these diacritics is expected. These are used (with Ķķ) in the Latvian alphabet. Unicode encoded them for that purpose, but under the name 'WITH CEDILLA' but the preferred form is the below comma accent. If decomposed sequences of these letters plus U+0327 (combining cedilla) are resulting in the glyph with comma below, that indicates that the layout engine is performing canonical precomposition mapping when accessing the font cmap table. This is pretty common.

Of course, this does mean that there is no easy way to display these particular letters with an actual cedilla below them, if that is what is desired. @moyogo may know of some orthographies that would use these letters with cedilla, which would require either separate fonts or robust 'locl' feature support.

**Comment by codeman38** [comment]
#505 mentions that Marshallese uses an actual cedilla, rather than a comma, for LlNn.

**Comment by tiroj** [comment]
Ah yes, good example.

**Comment by moyogo** [comment]
Indeed, ĻļŅņ ĻļŅņ with the comma-shape cedilla is expected for Latvian, and a uniform shape is expected for Marshallese and the systems mentioned earlier. 

Regarding F̧:
The cedilla should probably be aligned on the stem of F instead of centered on the glyph’s width.
It’s a bit difficult to say where exactly the cedilla should be positioned for some of these letters. Centering on the glyph’s width or aligning it on a stem both occur and it’s not clear if either is wrong. However it seems centering the cedilla works with glyphs with more than one stem on the baseline (A, X, n, etc.) but is odd with glyphs with only one stem on the baseline (F, P, etc).
@tiroj What do you think?

**Comment by tiroj** [comment]
My take on cedilla and ogonek both is that attachment to the letter is characteristic. [There are stylistic variants of the cedilla in some typefaces that do not have a connecting stroke, but these are the minority.]

So I always look for somewhere to attach the cedilla and ogonek, and agree with Denis that in the case of F it should be the bottom of the vertical stem. The tricky thing with letters with more than one baseline terminal is knowing to which to attach the cedilla (the ogonek seems pretty consistent on the right side of letters, so that is easier). With the cedilla, we have the example of Ḩḩ in which the cedilla attaches to the left stem, but would that apply to other letters?

If a cedilla were to be centred on the letter width in such a way that it doesn't visually attach to any part of the letter, then I would be inclined to make a contextual variant cedilla without the connecting stroke, or with just a stub of that stroke. There's no point in having a connecting stroke that's not connecting to anything, and a glyph that is designed to overlap part of a letter to which it is attached seldom looks good when it doesn't.

**Comment by jungshik** [comment]
Thanks a lot, @tiroj and @moyogo.  
@TrueTyper, I can now assign this issue to you. Please, take into account the previous few comments by @tiroj and @moyogo when working on Noto Serif (and revising Noto Sans). Thanks.

**Comment by marekjez86** [comment]
bug 427 (this bug) is from now on used ONLY for noto issues. For Arimo, Cousine, Tinos issues please see https://github.com/googlei18n/noto-fonts/issues/680

**Comment by marekjez86** [comment]
Latvian (lv) test
[lv-427.html.zip](https://github.com/googlei18n/noto-fonts/files/616186/lv-427.html.zip)

sample image (Noto Serif Black)
![lv-noto-serif-black](https://cloud.githubusercontent.com/assets/13322623/20667824/3d18b082-b520-11e6-8aa9-c985718db275.jpg)

Detailed test results
[lv-427-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616177/lv-427-NotoSans-Black.pdf)
[lv-427-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616176/lv-427-NotoSans-Italic.pdf)
[lv-427-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616179/lv-427-NotoSansDisplay-Black.pdf)
[lv-427-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616180/lv-427-NotoSansDisplay-Italic.pdf)
[lv-427-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616181/lv-427-NotoSerif-Black.pdf)
[lv-427-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616178/lv-427-NotoSerif-Italic.pdf)
[lv-427-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616182/lv-427-NotoSerifDisplay-Black.pdf)
[lv-427-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616183/lv-427-NotoSerifDisplay-Italic.pdf)

**Comment by marekjez86** [comment]
Marshallese (mh) test
[lgc-427.html.zip](https://github.com/googlei18n/noto-fonts/files/616191/lgc-427.html.zip)

sample image (Noto Sans Black)
![mh-noto-sans-black](https://cloud.githubusercontent.com/assets/13322623/20667880/738e49d8-b520-11e6-8d8f-6414bf580ee9.jpg)

Detailed test results
[lgc-427-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616195/lgc-427-NotoSans-Black.pdf)
[lgc-427-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616193/lgc-427-NotoSans-Italic.pdf)
[lgc-427-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616194/lgc-427-NotoSansDisplay-Black.pdf)
[lgc-427-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616192/lgc-427-NotoSansDisplay-Italic.pdf)
[lgc-427-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616197/lgc-427-NotoSerif-Black.pdf)
[lgc-427-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616196/lgc-427-NotoSerif-Italic.pdf)
[lgc-427-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616198/lgc-427-NotoSerifDisplay-Black.pdf)
[lgc-427-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616199/lgc-427-NotoSerifDisplay-Italic.pdf)

**Comment by marekjez86** [comment]
@moyogo : what do you think, are we done with this bug :-) ?

**Comment by moyogo** [comment]
@marekjez86 LGTM
