### ISSUE TITLE
 Navajo lowercase a-ogonek and u-ogonek needs connection, acute accents appear to be misplaced

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#428]
Reported by @roozbehp 
Moved from googlei18n/noto-alpha#196

We need centered ogonek forms for Navajo text. The Unicode characters are shared between Polish, Lithuanian, Navajo, and a few other languages, but the Navajo forms require the ogonek to be centered below the letter, as opposed to attached to the bottom right.

Please add GSUB and GPOS features for Navajo, to center the combining ogonek (U+0328) and have alternates for precomposed letters used in Navajo with ogonek, with the language tag "NAV ". We need this is both Sans and Serif LGC fonts.

Navajo uses the ogonek in combination with lowercase and uppercase A, E, I, and O, which may also carry the acute accent at the same time.

Some links for existing Navajo fonts: http://www.unicode.org/mail-arch/unicode-ml/y2013-m06/0065.html

**Comment by jungshik** [comment]
/cc @TrueTyper 

It looks like P3 Noto Sans works as expected when language=NAV is selected. 

* Noto Sans, non-Nav
![bug428 notosans_reg_trunk](https://cloud.githubusercontent.com/assets/8578343/11408721/db1517cc-936f-11e5-8a5f-e68be694742a.png)

* Noto Sans Italic, non-Nav
![bug428 notosans_italic_trunk]
(https://cloud.githubusercontent.com/assets/8578343/11408744/f2059574-936f-11e5-9d0a-8486b3546db3.png)

* Noto Sans, lang=NAV
![bug428 notosans_reg_trunk_nav](https://cloud.githubusercontent.com/assets/8578343/11408753/04783d7e-9370-11e5-8e25-c6cc31decf00.png)

* Noto Sans Italic, lang=NAV
![bug428 notosans_italic_trunk_nav](https://cloud.githubusercontent.com/assets/8578343/11408762/11cb6fbe-9370-11e5-89a6-aa153b9a15de.png)

With lang=NAV, softdotted 'i' is not handled properly. This should be addressed, I think.

**Comment by jungshik** [comment]
With lang=NAV, softdotted 'i' is not handled properly. This should be addressed, I think.  #418 took care of it for non-NAV cases, but with lang=NAV, this is not handled properly. @TrueTyper

**Comment by marekjez86** [comment]
all appears to be resolved.

nav testcase for fontdiff
[nav-428.html.zip](https://github.com/googlei18n/noto-fonts/files/616531/nav-428.html.zip)

Sample output for NotoSans Black
![nav-421-sans-black](https://cloud.githubusercontent.com/assets/13322623/20671645/fbe7268a-b532-11e6-965b-0be9e8367112.jpg)

Outputs for all fonts
[nav-428-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616541/nav-428-NotoSans-Black.pdf)
[nav-428-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616540/nav-428-NotoSans-Italic.pdf)
[nav-428-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616537/nav-428-NotoSansDisplay-Black.pdf)
[nav-428-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616539/nav-428-NotoSansDisplay-Italic.pdf)
[nav-428-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616538/nav-428-NotoSerif-Black.pdf)
[nav-428-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616542/nav-428-NotoSerif-Italic.pdf)
[nav-428-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616544/nav-428-NotoSerifDisplay-Black.pdf)
[nav-428-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616543/nav-428-NotoSerifDisplay-Italic.pdf)

**Comment by frankrolf** [comment]
I am curious if any native Navajo speakers have options on the shape of Aogonek, aogonek, uogonek? Perhaps the problem cannot be properly addressed in Aogonek, but from a design perspective, I think the gap between the bowl and accent should be fixed in the lowercase letters.
@andrewkeithstrauss?

Side note for @marekjez86 – it seems your acute accents have shifted to the left.

**Comment by roozbehp** [comment]
What @frankrolf said. The acute accents are misplaced, and the lowercase a-ogonek and u-ogonek appear problematic at the connection.

**Comment by marekjez86** [comment]
@roozbehp , @frankrolf : there's an inherent conflict between what you suggest and what was attributed to @roozbehp in the beginning of this issue: "We need centered ogonek forms for Navajo text. [...] Navajo forms require the ogonek to be centered below the letter, as opposed to attached to the bottom right." It's either where it is (at the center; and looks the way it is right now) or looks "more connected" but NOT at the center. Was the initial requirement stated incorrectly?

**Comment by roozbehp** [comment]
@marekjez86: centered doesn't mean complete centering. It means around the center. In the case of lowercase a-ogonek and u-ogonek, the ogonek should actually move a little more to the left and attach under the belly of the letter, so it doesn't appear disconnected. Compare with Roboto, for example.

The only case where it actually should actually *be* disconnected is uppercase A-ogonek (which looks correct now).

**Comment by frankrolf** [comment]
@marekjez86
> there's an inherent conflict between what you suggest and what was attributed to @roozbehp in the beginning of this issue: "We need centered ogonek forms for Navajo text.

I don’t agree with this assessment. You are working on a visual product, so in the end your result needs to look good, not just fulfill a technical requirement.

**Comment by marekjez86** [comment]
testing with 
```html
<html lang="nav">
	<p><span style="font-weight:700">Ą́Ę́Į́Ǫ́Ų́ą́ę́į́ǫ́ų́</span></p>
	<p><span style="font-weight:700">ĄĘĮǪŲąęįǫų</span></p>
	<p><span style="font-weight:700">Ą́Ę́Į́Ǫ́Ų́ą́ę́į́ǫ́ų́</span></p>
</html>
```

results:
0. centered ogonek forms needed for Navajo are implemented in Noto LGC fonts (but see 2. and 3. below)
1. Roboto Navajo ogonek under u and similar glyphs is not centered (needs to become a bug against Roboto @jamesgk @roozbehp )
2. @waksmonskiMT : in most of Noto LGC fonts, lowercase a-ogonek and u-ogonek appear problematic at the connection 
3. @waksmonskiMT : the acute accents appear to be misplaced (not certain if this is Navajo related or not)

[nav-428-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677369/nav-428-Roboto-Italic.pdf)
[nav-428-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677372/nav-428-NotoSans-Black.pdf)
[nav-428-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677370/nav-428-NotoSans-Italic.pdf)
[nav-428-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677373/nav-428-NotoSans-Regular.pdf)
[nav-428-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677371/nav-428-NotoSansDisplay-Black.pdf)
[nav-428-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677368/nav-428-NotoSansDisplay-Italic.pdf)
[nav-428-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677374/nav-428-NotoSansDisplay-Regular.pdf)
[nav-428-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677375/nav-428-NotoSansMono-Black.pdf)
[nav-428-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677377/nav-428-NotoSansMono-Regular.pdf)
[nav-428-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677378/nav-428-NotoSerif-Black.pdf)
[nav-428-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677376/nav-428-NotoSerif-Italic.pdf)
[nav-428-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677379/nav-428-NotoSerif-Regular.pdf)
[nav-428-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677381/nav-428-NotoSerifDisplay-Black.pdf)
[nav-428-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677382/nav-428-NotoSerifDisplay-Italic.pdf)
[nav-428-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677380/nav-428-NotoSerifDisplay-Regular.pdf)
[nav-428-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677383/nav-428-Roboto-Black.pdf)
[nav-428-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677384/nav-428-Roboto-Regular.pdf)

**Comment by nv-wiki** [comment]
You can close this. Looks awesome, exactly as it should. Thank you. (There is no "u" in Navajo. )

**Comment by marekjez86** [comment]
@nv-wiki : thank you for the comment. closing the issue.
@waksmonskiMT : Sue, please pass the comment " Looks awesome, exactly as it should. Thank you" to the designer that worked on this and "thank you!"

**Comment by nv-wiki** [comment]
that change is nice and appreciated but not really important. as long as it's in the middle it's ok.

It would be a lot more important to have this available as a web font so people won't have to download it.
This:
`@import url('https://fonts.googleapis.com/css?family=Noto+Sans|Noto+Serif&subset=latin-ext');`
gives only the old version w/o this feature. (or maybe I'm doing something wrong...)

I'm not sure how to request this, maybe someone could see to it, if possible.  ahéheeʼ/thanks
