### ISSUE TITLE
LGC: Sans and Serif several modifier letters are incorrectly defined zero-width

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#429]
Moved from googlei18n/noto-alpha#157. Reported by @roozbehp 
Several of the spacing modifier letters in NotoSans and NotoSerif have zero width, whereas they should be normally spaced. (See Unicode range with descriptions at http://www.unicode.org/charts/PDF/U02B0.pdf .)

For example, IPA [miːn] displays incorrectly, since the triangular colon sign ː (U+02D0) is crushed between the i and n.

They also seem to be incorrectly defined as class 3 (non-spacing) in the GDEF/GlyphClassDef tables in the fonts.

There are at least ten such glyphs.

**Comment by jungshik** [comment]
@tiroj has the following comment on this (moved from googlei18n/noto-alpha#256) and googlei18n/noto-alpha#157 (fixed in Noto Sans 1.05 and Noto Serif 1.04 according to @dougfelt ):


These appear to relate to the same bug. The complete list of affected characters to be respaced is 

02C8 02CA 02CB 02CC 02CD 02CE 02CF 02D0 02D1 02D2 02D3 02D4 02D5 02D6 02D7 02DE 02DF 02EC 
02ED 02EF 02F0 02F1 02F2 02F4 02F5 02F6 02F7 02F8 02F9 02FA 02FB 02FC 02FD 02FE 02FF

We have to check them all.

**Comment by jungshik** [comment]
@dougfelt, when you wrote that this is fixed in Sans 1.05 and Serif 1.04, did you go through all the characters listed by @tiroj (perhaps, by checking their advance widths programatically)?  
If so, please close this as fixed. If not, could you check them all? Thanks

**Comment by dougfelt** [comment]
Hmmm, no I apparently only did a spot check of the original characters.

I added a check to lint and it found that U+02DE maps to a glyph with zero width.  The rest listed above are ok.  This character is 'commonly ligated' according to Unicode so perhaps in normal use this is not an issue.  We'd want a comment from Monotype.

The unicode link in the original report unfortunately includes the final period of the sentence in the link, it should be [http://www.unicode.org/charts/PDF/U02B0.pdf](http://www.unicode.org/charts/PDF/U02B0.pdf) instead.

**Comment by dougfelt** [comment]
@jungshik, please look at dougfelt/nototools@ad7aabc7ce4410b5fc5692cbffe40f6dfb58059a

**Comment by moyogo** [comment]
Modifier rhotic hook U+02DE is odd, it should behave like a diacritic as it attaches onto the previous letter much like Combining horn U+031B. It should add advance width to the base letter to avoid collision with anything that follows, with its own advance width or an OT feature. Any letter followed by the Modifier rhotic hook U+02DE should behave like U+025A ɚ or U+025D ɝ when compared with U+0259 ə or U+025C ɜ.

**Comment by moyogo** [comment]
Sorry, I didn’t see #436 had the relevant info on U+02DE.

**Comment by dougfelt** [comment]
Reassigning to Sue so that Monotype can look at the U+02DE issue.

**Comment by moyogo** [comment]
I would add ˉˆˇ 02C9 02C6 02C7 to the set ; they should be grouped with ˊˋˍˏˎꞈˬ˴ 02CA 02CB 02CD 02CF 02CE A788 02EC 02F4 and similar glyphs should behave in a similar way (acutes should have the same advance width, etc.).

Here’s Noto Sans, Noto Serif: nˉnˍnˊnˏnˋnˎn˴nˆnꞈnˇnˬn 006E 02C9 006E 02CD 006E 02CA 006E 02CF 006E 02CB 006E 02CE 006E 02F4 006E 02C6 006E A788 006E 02C7 006E 02EC 006E
![screen shot 2015-09-07 at 07 21 03](https://cloud.githubusercontent.com/assets/1923747/9710386/c33b732a-5531-11e5-96e5-b0d77e28d0de.png)

* ˉ 02CD should be spaced like ˍ 02C9
* ˍ 02C9 should be recentered in Noto Sans Italic
* ˆ 02C6, ꞈ A788, ˇ 02C7, ˬ 02EC should have narrower advance width to behave more like the others mentioned in this comment.

**Comment by jungshik** [comment]
What's listed in https://github.com/googlei18n/noto-fonts/issues/429#issuecomment-128148031 were taken care of. 

NotoSans {Regular,Italic} in P3 build
![3 noto_sans_trunk_reg](https://cloud.githubusercontent.com/assets/8578343/11410502/d8ef5626-937c-11e5-8dbd-ce017d8285fe.png)

![3 noto_sans_trunk_italic](https://cloud.githubusercontent.com/assets/8578343/11410505/e47011ca-937c-11e5-9433-85aeb5a61aaa.png)

However, what's raised in https://github.com/googlei18n/noto-fonts/issues/429#issuecomment-138206470 seems still outstanding. 

![2 noto_sans_trunk_reg](https://cloud.githubusercontent.com/assets/8578343/11410547/35ace522-937d-11e5-9b0b-61b299180e8f.png)
![2 noto_sans_trunk_italic](https://cloud.githubusercontent.com/assets/8578343/11410551/3f9b93b2-937d-11e5-82e9-54f8fbf21b04.png)

**Comment by xiangyexiao** [comment]
@SteveMatteson Can you take a look at Jungshik's comment https://github.com/googlei18n/noto-fonts/issues/429#issuecomment-159741931

**Comment by xiangyexiao** [comment]
@waksmonskiMT We want it to be fixed in Phase II fonts by end of March. Let me know if it is infeasible.

**Comment by xiangyexiao** [comment]
@waksmonskiMT 

An update. You don't need to fix this for Phase 2. @TrueTyper @SteveMatteson Please check Jungshik's comment #429 (comment)

**Comment by marekjez86** [comment]
A test case for fontdiff
[en-429.html.zip](https://github.com/googlei18n/noto-fonts/files/616591/en-429.html.zip)

Sample output for NotoSans Black
![en-429-sans-black](https://cloud.githubusercontent.com/assets/13322623/20672212/42156bce-b535-11e6-9b17-8df1f4c6e10e.jpg)

Outputs for all delivered sources
[en-429-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616602/en-429-NotoSans-Black.pdf)
[en-429-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616603/en-429-NotoSans-Italic.pdf)
[en-429-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616601/en-429-NotoSansDisplay-Black.pdf)
[en-429-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616605/en-429-NotoSansDisplay-Italic.pdf)
[en-429-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616604/en-429-NotoSerif-Black.pdf)
[en-429-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616606/en-429-NotoSerif-Italic.pdf)
[en-429-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/616607/en-429-NotoSerifDisplay-Black.pdf)
[en-429-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/616608/en-429-NotoSerifDisplay-Italic.pdf)

Appears to be fixed. @jungshik : what do you think?

**Comment by marekjez86** [comment]
with the following test

```html
<html lang="en">
	<p><span style="font-weight:700">nˈ nˊ nˋ nˌ nˍ nˎ nˏ nː nˑ n˒ n˓ n˔ n˕ n˖ n˗ n˞ n˟ nˬ</span></p>
	<p><span style="font-weight:700">n˭ n˯ n˰ n˱ n˲ n˴ n˵ n˶ n˷ n˸ n˹ n˺ n˻ n˼ n˽ n˾ n</span></p>
	<p><span style="font-weight:700">nˉnˍnˊnˏnˋnˎn˴nˆnꞈnˇnˬn˜n˷n˚n˳n</span></p>
</html>
```

all Noto LGC fonts are fine
Roboto fonts are fine but for n˞ (but there's a separate bug for this)

[en-429-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677256/en-429-NotoSans-Black.pdf)
[en-429-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677255/en-429-NotoSans-Italic.pdf)
[en-429-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677257/en-429-NotoSans-Regular.pdf)
[en-429-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677258/en-429-NotoSansDisplay-Black.pdf)
[en-429-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677259/en-429-NotoSansDisplay-Italic.pdf)
[en-429-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677260/en-429-NotoSansDisplay-Regular.pdf)
[en-429-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677261/en-429-NotoSansMono-Black.pdf)
[en-429-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677262/en-429-NotoSansMono-Regular.pdf)
[en-429-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677263/en-429-NotoSerif-Black.pdf)
[en-429-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677264/en-429-NotoSerif-Italic.pdf)
[en-429-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677265/en-429-NotoSerif-Regular.pdf)
[en-429-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677266/en-429-NotoSerifDisplay-Black.pdf)
[en-429-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677268/en-429-NotoSerifDisplay-Italic.pdf)
[en-429-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677267/en-429-NotoSerifDisplay-Regular.pdf)
[en-429-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677270/en-429-Roboto-Black.pdf)
[en-429-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677269/en-429-Roboto-Italic.pdf)
[en-429-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677271/en-429-Roboto-Regular.pdf)
