### ISSUE TITLE
KAYAH LI SIGN CWI should be added to  Latin fonts

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#432]
Imported from [Google Code issue #233](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=233) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-05-17T15:55:57.000Z:

---

Apart from the Kayah Li script, U+A92E KAYAH LI SIGN CWI is used in both Latin and Myanmar, and we need it to be added to Noto Sans, Noto Serif, and Myanmar fonts.

For background information, see http://www.unicode.org/L2/L2013/13137-a92e-props.pdf

**Comment by jungshik** [comment]
Burmese/Myanmar 1.07 has this added, but Noto Sans and Noto Serif do not have this character.

**Comment by marekjez86** [comment]
tested with the following

```html
<html lang="en">
	<p><span style="font-weight:700">꤮</span></p>
</html>
```

all Noto+Roboto fonts have U+A92E KAYAH LI SIGN CW

[en-432-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677223/en-432-NotoSerif-Regular.pdf)
[en-432-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677224/en-432-NotoSerifDisplay-Black.pdf)
[en-432-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677225/en-432-NotoSerifDisplay-Italic.pdf)
[en-432-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677229/en-432-NotoSerifDisplay-Regular.pdf)
[en-432-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677228/en-432-Roboto-Black.pdf)
[en-432-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677227/en-432-Roboto-Italic.pdf)
[en-432-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677226/en-432-Roboto-Regular.pdf)
[en-432-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677230/en-432-NotoSans-Black.pdf)
[en-432-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677231/en-432-NotoSans-Italic.pdf)
[en-432-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677232/en-432-NotoSans-Regular.pdf)
[en-432-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677234/en-432-NotoSansDisplay-Black.pdf)
[en-432-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677233/en-432-NotoSansDisplay-Italic.pdf)
[en-432-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677235/en-432-NotoSansDisplay-Regular.pdf)
[en-432-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677236/en-432-NotoSansMono-Black.pdf)
[en-432-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677237/en-432-NotoSansMono-Regular.pdf)
[en-432-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677238/en-432-NotoSerif-Black.pdf)
[en-432-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677239/en-432-NotoSerif-Italic.pdf)
