### ISSUE TITLE
Three-character tone letter ligatures not working in Noto Sans and Noto Serif

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#433]
Moved from googlei18n/noto-alpha#255

Imported from [Google Code issue #255](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=255) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-10-26T00:29:59.000Z:

---

The sequence &lt;02E8, 02E9, 02E7&gt; rendered by HarfBuzz in Noto Sans and Noto Serif (LGC) results in two glyphs instead of one.

Our early testing implies that this is a bug in the fonts' ccmp tables, but we have not tested on Windows 8.1 or 10 yet.

**Comment by jungshik** [comment]
Noto Serif (latest) still has this issue. Still two glyphs instead of one : 

![bug433_serif](https://cloud.githubusercontent.com/assets/8578343/10531035/f358a5de-7361-11e5-939c-f44095ff5aa9.png)


Noto Sans (p3 delivery) got worse. No combining at all. 

![bug433_sansp3](https://cloud.githubusercontent.com/assets/8578343/10531038/fe68f596-7361-11e5-843f-6bd4bd9ed1f0.png)

**Comment by jungshik** [comment]
Dejavu Sans got it right : 
![bug433_dejavusans](https://cloud.githubusercontent.com/assets/8578343/10531054/4136a4ea-7362-11e5-8800-fd7f49358b15.png)

**Comment by jungshik** [comment]
Arimo and Tinos also behave the same way as Noto Serif. Two glyphs instead of one glyphs for the 3 character sequence.

**Comment by jungshik** [comment]
And, Cousine is even more broken like Noto Sans is. 
![bug433_cousine](https://cloud.githubusercontent.com/assets/8578343/10548129/89fa853a-73ed-11e5-9bf5-f913f7a4cc0a.png)

**Comment by TrueTyper** [comment]
The phase 3 of Noto Sans (NotoSansUI-RomanMM.glyphs) has this working correctly. The next release of the serif should include the same ccmp feature. I did fix this in source for the Arimo and Tinos family TTFs.

The specification for Cousine was to match the OpenType functionality of Courier New, which does not have Latin mark positioning. That issue should be a new feature, rather than a bug.

**Comment by xiangyexiao** [comment]
@waksmonskiMT, we want it to be fixed in Phase II fonts by end of March. Let me know if it is infeasible.

**Comment by xiangyexiao** [comment]
We don't need to fix this for Phase 2. It is not a frequently used character. @marekjez86 please verify it is fixed for Phase 3.

**Comment by marekjez86** [comment]
marekjez86 to verify that "phase 3 of Noto Sans (NotoSansUI-RomanMM.glyphs) has this working correctly"

**Comment by marekjez86** [comment]
per @moyogo this doesn't happen in any of Arimo nor Tinos (they are fixed). Note that Arial doesn't handle (support) this three character combination.

**Comment by marekjez86** [comment]
All fonts are fine with the following test
```html
<html lang="en">
	<p><span style="font-weight:700">˨˩˧</span></p>
</html>
```

[en-433-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677200/en-433-NotoSerif-Italic.pdf)
[en-433-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677198/en-433-NotoSerif-Regular.pdf)
[en-433-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677201/en-433-NotoSerifDisplay-Black.pdf)
[en-433-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677202/en-433-NotoSerifDisplay-Italic.pdf)
[en-433-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677203/en-433-NotoSerifDisplay-Regular.pdf)
[en-433-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677199/en-433-Roboto-Black.pdf)
[en-433-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677205/en-433-Roboto-Italic.pdf)
[en-433-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677207/en-433-Roboto-Regular.pdf)
[en-433-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677204/en-433-NotoSans-Black.pdf)
[en-433-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677209/en-433-NotoSans-Italic.pdf)
[en-433-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677206/en-433-NotoSans-Regular.pdf)
[en-433-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677208/en-433-NotoSansDisplay-Black.pdf)
[en-433-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/677210/en-433-NotoSansDisplay-Italic.pdf)
[en-433-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677212/en-433-NotoSansDisplay-Regular.pdf)
[en-433-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677214/en-433-NotoSansMono-Black.pdf)
[en-433-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/677211/en-433-NotoSansMono-Regular.pdf)
[en-433-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/677213/en-433-NotoSerif-Black.pdf)
