### ISSUE TITLE
Serif LGC: U+033A COMBINING INVERTED BRIDGE BELOW is thicker than U+032A COMBINING BRIDGE BELOW

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#434]
Moved from googlei18n/noto-alpha#257
Imported from [Google Code issue #257](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=257) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-10-26T02:13:27.000Z:

---

Compare the rendering of &quot;d̪&quot; and &quot;d̺&quot; in Noto Serif.

Also, the rounded design _may_ be wrong. The Serif fonts I have checked (Times New Roman and Cambria) both use sharp connections. The IPA book also uses sharp connections.

Attaching screenshots.

noto-serif.png
![noto-serif](https://cloud.githubusercontent.com/assets/9939212/8631051/1ae21b0c-2723-11e5-9eac-902cabd4925b.png)
cambria.png
![cambria](https://cloud.githubusercontent.com/assets/9939212/8631049/1adf7d34-2723-11e5-857b-1e19444e0b21.png)
times.png
![times](https://cloud.githubusercontent.com/assets/9939212/8631050/1ae0b564-2723-11e5-8178-d876523e7a04.png)

**Comment by jungshik** [comment]
@tiroj has the following comment : 

Agree with the suggestion that the inside corners should be sharp, not rounded. Weight and
vertical alignment should be better coordinated with other below marks. This also relates to some 
others in this set, which are a bit too high or too low relative to the common alignment (e.g. U+0318 
U+0319)

**Comment by marekjez86** [comment]
[en-434-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/676721/en-434-NotoSerifDisplay-Italic.pdf)
[en-434-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676723/en-434-NotoSerifDisplay-Regular.pdf)
[en-434-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676724/en-434-Roboto-Black.pdf)
[en-434-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/676725/en-434-Roboto-Italic.pdf)

tested usin
```html
<html lang="en">
	<p><span style="font-weight:700"> "d̪" and "d̺"</span></p>
</html>
```

[en-434-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676726/en-434-Roboto-Regular.pdf)
[en-434-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676722/en-434-NotoSans-Black.pdf)
[en-434-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/676727/en-434-NotoSans-Italic.pdf)
[en-434-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676732/en-434-NotoSans-Regular.pdf)
[en-434-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676729/en-434-NotoSansDisplay-Black.pdf)
[en-434-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/676731/en-434-NotoSansDisplay-Italic.pdf)
[en-434-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676730/en-434-NotoSansDisplay-Regular.pdf)
[en-434-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676728/en-434-NotoSansMono-Black.pdf)
[en-434-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676733/en-434-NotoSansMono-Regular.pdf)
[en-434-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676734/en-434-NotoSerif-Black.pdf)
[en-434-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/676735/en-434-NotoSerif-Italic.pdf)
[en-434-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/676736/en-434-NotoSerif-Regular.pdf)
[en-434-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/676737/en-434-NotoSerifDisplay-Black.pdf)
