### ISSUE TITLE
Latin: U+035C double breve below appears incorrectly positioned

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#437]
Moved from googlei18n/noto-alpha#262 (reported by @roozbehp )
Imported from [Google Code issue #262](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=262) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-10-26T03:03:41.000Z:

Latin: U+035C double breve below appears incorrectly positioned

Compare the phrases &quot;pətit͜ami&quot; and &quot;pət͜si&quot; in Noto Sans, Noto Serif, and Cambria (examples can be seen on pages ix and 23 of the IPA handbook). The breves are too low and too much to the left in Noto.

The order of the images are Cambri, Noto Sans and Noto Serif

![cambria](https://cloud.githubusercontent.com/assets/12721521/8660098/b5d20f40-2963-11e5-97c8-effce0c6966d.png)
![noto-sans](https://cloud.githubusercontent.com/assets/12721521/8660097/b5d11aae-2963-11e5-9ca0-5c9f31a25f1a.png)
![noto-serif](https://cloud.githubusercontent.com/assets/12721521/8660099/b5d402b4-2963-11e5-9b05-113bc07c49fd.png)

**Comment by jungshik** [comment]
![bug437 sans](https://cloud.githubusercontent.com/assets/8578343/9586718/4ad5bcf0-4fd3-11e5-92db-f1adf1c0a449.png)

The above is rendered by harfbuzz 1.0.1 with a new version of Noto Sans UI (LGC). The issue is still outstanding and it seems worse than before. 

@waksmonskiMT, can you ask your team to look at this again? Thanks

**Comment by marekjez86** [comment]
@roozbehp : roboto looks bad (see below)
![en-437-roboto-black](https://cloud.githubusercontent.com/assets/13322623/21557097/34778c44-cddc-11e6-9644-40c96cd44025.jpeg)

all Noto Fonts look font-tastic :-)

[en-437-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678009/en-437-NotoSans-Black.pdf)
[en-437-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678010/en-437-NotoSans-Italic.pdf)
[en-437-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678014/en-437-NotoSans-Regular.pdf)
[en-437-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678013/en-437-NotoSansDisplay-Black.pdf)
[en-437-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678011/en-437-NotoSansDisplay-Italic.pdf)
[en-437-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678017/en-437-NotoSansDisplay-Regular.pdf)
[en-437-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678012/en-437-NotoSansMono-Black.pdf)
[en-437-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678020/en-437-NotoSansMono-Regular.pdf)
[en-437-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678015/en-437-NotoSerif-Black.pdf)
[en-437-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678016/en-437-NotoSerif-Italic.pdf)
[en-437-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678019/en-437-NotoSerif-Regular.pdf)
[en-437-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678018/en-437-NotoSerifDisplay-Black.pdf)
[en-437-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678021/en-437-NotoSerifDisplay-Italic.pdf)
[en-437-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678022/en-437-NotoSerifDisplay-Regular.pdf)
[en-437-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678023/en-437-Roboto-Black.pdf)
[en-437-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678024/en-437-Roboto-Italic.pdf)
[en-437-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678025/en-437-Roboto-Regular.pdf)

**Comment by roozbehp** [comment]
@marekjez86, if Roboto looks bad, please file a bug! You know where the repo is :)
