### ISSUE TITLE
Latin: U+02B2 modifier j, U+02E0 modifier gamma, and U+02E1 modifier l are too low

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#438]
Moved from googlei18n/noto-alpha#263. Reported by @roozbehp 

Imported from [Google Code issue #263](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=263) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-10-26T03:14:49.000Z:

---

U+02B2 modifier j, U+02E0 modifier gamma, and U+02E1 modifier l are too low

Compare the rendering of the sequence &quot;tʲ dʲ tˠ dˠ dˡ&quot; in Noto Sans, Noto Serif, Calibri, Cambria, Segoe UI, and Times. The Noto Sans version is very low, while the Noto Serif version is still too low, although not as bad as Noto Sans.

A print example can be found on page ix of the IPA handbook.

Noto Sans and Noto Serif have the problem reported here. 
![noto-sans](https://cloud.githubusercontent.com/assets/12721521/8660148/059dd720-2964-11e5-9584-1b0df4b89a48.png)
![noto-serif](https://cloud.githubusercontent.com/assets/12721521/8660151/059ffdb6-2964-11e5-80ad-875659eb4f4c.png)

---

Calibri and Cambria (top two below)  do not have this issue. (  Segoe UI and Times New Roman (bottom two)  are not as good as Calibri/Cambria). 

![calibri](https://cloud.githubusercontent.com/assets/12721521/8660150/059f4f92-2964-11e5-82c3-6dc9364d6d6d.png)
![cambria](https://cloud.githubusercontent.com/assets/12721521/8660147/059dbb82-2964-11e5-9630-03bd934505c5.png)
![segoeui](https://cloud.githubusercontent.com/assets/12721521/8660149/059e4f8e-2964-11e5-8bf8-13eea4cea8bf.png)
![times](https://cloud.githubusercontent.com/assets/12721521/8660152/05a04e9c-2964-11e5-943b-355271ee989f.png)

**Comment by jungshik** [comment]
I bought the IPA handbook (ebook : which may not be the best way for font testing because the ebook uses characters as much as possible. fortunately, this case, the book uses images). In the ebook, the example is in p. 14 and attached is the image taken from the ebook (it's an image in the ebook). 

<img width="226" alt="screen shot 2015-07-30 at 9 50 32 am" src="https://cloud.githubusercontent.com/assets/8578343/8989372/a84c48e6-36a0-11e5-8c08-b609158ef135.png">

**Comment by jungshik** [comment]
I've just built a Phase3 delivery from Monotype (built an otf using Glyphs) and this issue is fixed for Sans LGC. 

![bug438](https://cloud.githubusercontent.com/assets/8578343/9584708/7b0cb60a-4fc7-11e5-8b99-c80af6b35396.png)

**Comment by jungshik** [comment]
Hmm.. the position of U+02E0 is a bit too low compared with what IPA handbook has, though.

**Comment by jungshik** [comment]
@roozbehp, what's your take?

**Comment by jungshik** [comment]
@tiroj , what do you think?  

The positions of U+02B2 modifier j, U+02E0 modifier gamma, and U+02E1 modifier l are still lower in a new version than in Calibri and Cambria (especially relative to 'd') even though their positions are higher than in the previous version.

**Comment by tiroj** [comment]
The revised size of the superscripts in the Phase3 build is a definite improvement, and I'd consider these acceptable. It is possible to raise the height of superscripts so that, as in the IPA Handbook examples, the ascending modifier superscripts stand noticeably taller than the regular ascender height, but this can look untidy in text, so it is preferable to make the superscripts smaller, as as been done.

For reference, here is what I did in the Brill types, allowing the ascending superscripts to stand just slightly taller than the ascenders, which enabled me to increase the size of the superscripts while keeping them at a decent height relative to the regular letters.
<img width="540" alt="screen shot 2015-08-31 at 11 58 52" src="https://cloud.githubusercontent.com/assets/5614500/9587510/c21ec8c0-4fd7-11e5-8a68-90d7ad0ab9c0.png">

**Comment by moyogo** [comment]
There seems to be many issues with superscript modifier letters across various Unicode blocks: different alignments, different or inadequate weights, different sizes and misplacement.

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif: d¹ⁱⁿʰʲᵃᶣꟹd 
![screen shot 2015-09-06 at 00 41 44](https://cloud.githubusercontent.com/assets/1923747/9701725/1aa4be62-5430-11e5-8a4e-f53b49b29d01.png)

**Comment by TrueTyper** [comment]
Here is a draft of the current Noto Serif Roman superior modifier letters, next to the Latin d and superior one. d¹ⁱⁿʰʲᵃᶣꟹd
tʲ dʲ tˠ dˠ dˡ
![notoserifromansupersample](https://cloud.githubusercontent.com/assets/8724881/11602957/dabcabf6-9aa3-11e5-8448-681509aabc88.png)

And here is a sample of the above marks over the lowercase 'o':    oᷛoᷟoͣoͨoᷙ
![notoserifromanmarks](https://cloud.githubusercontent.com/assets/8724881/11603061/a44a7570-9aa4-11e5-960f-cce04e15007b.png)

Assuming this is well received here, we will deliver the rest of the Serif fonts with the same sizing and alignment later this month.

**Comment by dougfelt** [comment]
@jungshik, can you provide feedback on this?  Also see Brian's email.

**Comment by tiroj** [comment]
These seem too small, and definitely too light, although perhaps the intent is only to show proposed size and not weight? I would prefer it if the baseline of the modifier superscripts and the superior numerals and stylistic superiors were all aligned: that looks tidier in complex text settings involving multiple superscripts (e.g. descriptive grammars).

**Comment by TrueTyper** [comment]
The proposal is about size and alignment first and foremost. @tiroj when you say "These seem too small" are you referring to everything, or just the superscripts and not the marks?

**Comment by tiroj** [comment]
The superscripts. The marks are a touch narrow, but presumably will gain sone weight horizontally.

**Comment by TrueTyper** [comment]
OK, so based on @tiroj 's comments, this is what we propose to deliver..
<img width="783" alt="screen shot 2015-12-08 at 11 50 06 am" src="https://cloud.githubusercontent.com/assets/8724881/11663468/04be16e6-9da2-11e5-8b60-d517f527b032.png">

**Comment by tiroj** [comment]
That looks good to me. If there are concerns about the depth of the superscript descenders, these could be shortened a touch.

**Comment by marekjez86** [comment]
Since I created bug https://github.com/googlei18n/noto-fonts/issues/681 to track Arimo, Cousine and Tinos issues, I'm removing the ArimoTinosCousine label here.

From now on this bug ONLY covers Noto Serif and Noto Sans.

**Comment by marekjez86** [comment]
all fonts including Roboto look consistent and fine

[en-438-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678030/en-438-NotoSerifDisplay-Italic.pdf)
[en-438-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678031/en-438-NotoSerifDisplay-Regular.pdf)
[en-438-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678033/en-438-Roboto-Black.pdf)
[en-438-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678032/en-438-Roboto-Italic.pdf)
[en-438-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678041/en-438-Roboto-Regular.pdf)
[en-438-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678040/en-438-NotoSans-Black.pdf)
[en-438-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678034/en-438-NotoSans-Italic.pdf)
[en-438-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678035/en-438-NotoSans-Regular.pdf)
[en-438-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678036/en-438-NotoSansDisplay-Black.pdf)
[en-438-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678044/en-438-NotoSansDisplay-Italic.pdf)
[en-438-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678037/en-438-NotoSansDisplay-Regular.pdf)
[en-438-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678038/en-438-NotoSansMono-Black.pdf)
[en-438-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678039/en-438-NotoSansMono-Regular.pdf)
[en-438-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678042/en-438-NotoSerif-Black.pdf)
[en-438-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678043/en-438-NotoSerif-Italic.pdf)
[en-438-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678045/en-438-NotoSerif-Regular.pdf)
[en-438-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678046/en-438-NotoSerifDisplay-Black.pdf)
