### ISSUE TITLE
No loca feature for Macedonian and Serbian Cyrilic in both Noto Serif and Sans 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#44]
```
What steps will reproduce the problem?
Noto Serif Italic does not contain the Serbian and Macedonian glyphs for the 
italic letters.

Please see the attached screenshot.
— column 1 regular
— column 2 italic russian
— column 3 italic macedonian and serbian

Additionally the ѓ italic is missing as well.


Please have a look at the following wikipedia articles for a more in-depth 
explanation on how to prepare a solution.

http://en.wikipedia.org/wiki/Macedonian_Cyrillic
http://en.wikipedia.org/wiki/Serbian_Cyrillic_alphabet

Amazing from this — keep up the great job!
Thanks guys (bow)
```

Original issue reported on code.google.com by `enna...@gmail.com` on 16 Jul 2014 at 9:32

Attachments:
- [Serbian_Cyrillic_Italic.svg.png](https://storage.googleapis.com/google-code-attachments/noto/issue-44/comment-0/Serbian_Cyrillic_Italic.svg.png)

**Comment by jungshik** [comment]
Tests taken from https://en.wikipedia.org/wiki/Serbian_Cyrillic_alphabet

<span lang="sr">бгдпт</span>
<span lang="ru">бгдпт</span>

<span lang="sr" style="font-style: italic">бгдпт</span>
<span lang="ru" style="font-style: italic">бгдпт</span>

In Chrome, specify `text-rendering: optimizeLegibility` to invoke loca feature if present. In firefox, it's not necessary.

**Comment by jungshik** [comment]
@tiroj :  does Sans-serif need the same treatment?

**Comment by jungshik** [comment]
DejaVu Serif Italic : Serbian (top), Russian (bottom) 

![bug44_dejavu_serif_sr](https://cloud.githubusercontent.com/assets/8578343/10530552/b6d2744a-735d-11e5-9787-a5392e5c0980.png)
![bug44_dejavu_serif_ru](https://cloud.githubusercontent.com/assets/8578343/10530557/bb004c4a-735d-11e5-9223-ea18e1f88e7c.png)

Noto Serif Italic : Serbian and Russian are identical
![bug44_serif_sr](https://cloud.githubusercontent.com/assets/8578343/10530561/c8d4bd1a-735d-11e5-892d-7418e1011cdb.png)

![bug44_serif_ru](https://cloud.githubusercontent.com/assets/8578343/10530559/c077660e-735d-11e5-93c1-274081ac7004.png)

**Comment by jungshik** [comment]
I used harfbuzz's hb-view to generate the above images:

```
hb-view <font> --language=sr --script-Cyrl --output-file=<file name> бгдпт
hb-view <font> --language=ru --script-Cyrl --output-file=<file name> бгдпт

```

**Comment by jungshik** [comment]
Dejavu Serif also has different glyphs in Serif (Roman) for б.  Serbian (top) and Russian (bottom) 

![bug44_dejavu_serif_sr](https://cloud.githubusercontent.com/assets/8578343/10530671/d307b408-735e-11e5-9671-c1a26e9a92a0.png)
![bug44_dejavu_serif_ru](https://cloud.githubusercontent.com/assets/8578343/10530676/d776f22e-735e-11e5-9174-739aae644137.png)

**Comment by jungshik** [comment]
Dejavu also makes a distinction between ru and sr for б in Dejavu Sans and Dejavu Sans Oblique. 

Noto Sans (phase 3) delivery does not (let alone the existing Noto Sans ttf).

**Comment by tiroj** [comment]
The roman (upright) б variant is optional for Serbian and Macedonian: a lot of fonts do not include it, but I think it is nice to have if the italic has the localised form for this letter.

The localised italic forms are expected in any font in which the italic is something other than a sloped version of the upright. They are derived from the normal Serbian cursive written forms.

**Comment by jungshik** [comment]
Thank you, @tiroj !  Is the following a good summary? 

1. Serif Italic : We must have Serbian/Macedonian forms  for characters listed here : бгдпт
2. Serif Roman : Nice to have a Serbian/Macedonian variant for б especially considering that we need to do #1 
3. Sans Serif Italic : If it's a true Italic (as opposed to Oblique), we must have Serbian/Macedonian variants for бгдпт
4. Sans Serif Roman : same as #2

**Comment by tiroj** [comment]
Yes.

**Comment by brawer** [comment]
Any updates?

**Comment by c933103** [comment]
A while ago I read that Macedonian Wikipedia were troubled by this because little open source font support their itallic character. They ultimately find one that is useable but Noto should fix that so Android users don't need to root their phone and replace font file to get a correct italic font for them..

**Comment by marekjez86** [comment]
https://damjan.softver.org.mk/italic/
text from the above page: 'б в г д ѓ п т з к ѐ ѝ'

**Comment by tiroj** [comment]
Note that the form of italic г shown at 
https://damjan.softver.org.mk/italic/
is unconventional. The usual form resembles a Latin (dotless) i+macron.

**Comment by moyogo** [comment]
It seems https://damjan.softver.org.mk/italic/ uses an old version of DejaVu Serif for its screenshot. The italic г was fixed in 2010 after https://bugs.freedesktop.org/show_bug.cgi?id=31979 to match the usual form (dotless i + macron).

**Comment by marekjez86** [comment]
Closing this as fixed for Serbian. There are issues in Macedonian which were enumarated in https://github.com/googlei18n/noto-fonts/issues/794

**Comment by marekjez86** [comment]
using

``<html lang="mt"\> 	<p><span style="font-weight:700">'б в г д ѓ п т з к ѐ ѝ'</span></p> </html>
``
... and many more samples from Wikipedia
as input to notodiff and running it with all of these fonts

NotoSans
NotoSans Italic
NotoSansDisplay
NotoSansDisplay Italic
NotoSerif
NotoSerif Italic
NotoSerifDisplay
NotoSerifDisplay Italic

I verified that the issue is fixed with the 16/Nov/2016 delivery of sources for Serbian (but not Macedonian - see separate bug https://github.com/googlei18n/noto-fonts/issues/794)

I also asked the Serbian population at Google to check  the notodiff results. Their feedback was positive.

[sr-44-Serif-201611201134.pdf](https://github.com/googlei18n/noto-fonts/files/611858/sr-44-Serif-201611201134.pdf)
[sr-44-Sans-201611201134.pdf](https://github.com/googlei18n/noto-fonts/files/611857/sr-44-Sans-201611201134.pdf)

**Comment by marekjez86** [comment]
The test case for the fontdiff
[sr-44.html.zip](https://github.com/googlei18n/noto-fonts/files/611865/sr-44.html.zip)
