### ISSUE TITLE
Greek/IPA: placement of IPA combining marks on Greek IPA characters is broken

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#440]
Moved from googlei18n/noto-alpha#260 Reported by @roozbehp 

Imported from [Google Code issue #260](https://code.google.com/a/google.comp/noto-alpha/issues/detail?id=260) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-10-26T02:42:03.000Z:

---

The IPA-related combining marks should work for the four Greek characters used in IPA (β, θ, λ, χ).

For example, Compare the sequence β̞  in Noto Sans, Noto Serif, Calibri, and DejaVu Serif. The correct rendering can be seen on page ix of the IPA handbook.

**Comment by jungshik** [comment]
From the top: Calibri (correct), Noto Sans and Noto Serif (incorrect)

![calibri](https://cloud.githubusercontent.com/assets/12721521/8659863/74f8a868-2962-11e5-8bc6-2ae6b15d1135.png)
![noto-sans](https://cloud.githubusercontent.com/assets/12721521/8659864/74fbfd7e-2962-11e5-8f5f-443626dbe9c6.png)
![noto-serif](https://cloud.githubusercontent.com/assets/12721521/8659865/750adff6-2962-11e5-8a19-e8551e4648b8.png)

**Comment by jungshik** [comment]
The rendering of 'β̞' with harfbuzz and a new version  is attached below;  It seems even worse than the previous version: 
![bug440 sans](https://cloud.githubusercontent.com/assets/8578343/9586642/d13e30a2-4fd2-11e5-8842-673dedef3bd6.png)

@waksmonskiMT,  can you ask your team to take a look?

**Comment by jungshik** [comment]
@tiroj's comment on this issue:

Confirmed: phonetic diacritic mark positioning should be applied to Greek letters used in IPA and
other transcription systems. 

More details on IPA Greek:

IPA Greek

As noted abov, four characters from the Unicode Greek block are unified with IPA letters. 
This unification has always seemed to me a bad idea: IPA is more conveniently handled uniformly 
as an extension of the Latin script, and the style of Greek glyphs in a typeface may not harmonise 
sufficiently with the Latin for this dual rôle. It would have been better to encode Latin beta, theta, 
lambda and chi letters, as was done with the Latin gamma ɣ and iota ɩ. In the case of Noto Serif, 
the design of the Greek β,θ and χ is such that they harmonise reasonably well among Latin letters; 
the λ is, as usual, the one that stands out most.

In the Brill types, there are variant glyphs for these Greek characters, designed to harmonise 
better with Latin forms. These are mapped in the <locl> feature for the <IPPH> language system 
tag. [Peter Constable at Microsoft registered this language system tag for IPA and <APPH> for 
Americanist phonetic notation, following discussions about the best level at which to address 
glyph variants for these writing systems. IPA functions like a script, in which it is possible to write 
any language, but from an OTL script itemisation perspective it is a subset of Latin; hence the 
distinction needs to be made at the language system level.] This could be considered for Noto Serif, 
to provide for more fully harmonised Latin forms of these letters.

![image](https://cloud.githubusercontent.com/assets/8578343/9587331/e89e5bf6-4fd6-11e5-8a9b-52db957ec051.png)

In Noto Sans the Greek letters work pretty well with the Latin, although the β is massively wide:

![image](https://cloud.githubusercontent.com/assets/8578343/9587347/fcf32938-4fd6-11e5-93f5-8278604cb1df.png)

**Comment by moyogo** [comment]
Note that ꞵ U+A7B5 and ꭓ U+AB53 are Latin small letter beta and Latin small
letter chi. Latin beta was added for orthographic support and Latin chi for
German dialect phonetic transcription but is also used in orthographies.
Both are glyphically appropriate for IPA, meaning the IPA IPPH forms of the
Greek letters can look the same (or the other way around).

**Comment by jungshik** [comment]
@moyogo : thank you for the comment. I opened #489 to further discuss 'Greek and IPA'. Can you comment on that bug?

**Comment by TrueTyper** [comment]
I have added mark positioning for beta, theta, lambda and chi in the sources of the Noto Sans, Arimo and Tinos families.

The Noto Serif anchor point work in Glyphs will proceed upon completion of the new character set and weight extensions.

**Comment by marekjez86** [comment]
using
```html
<html lang="en">
	<p style="font-weight:700">β̞  θ̞  λ̞  χ̞  </p>
</html>
```
as a test case

All Noto fonts handle everything correctly.

[en-440-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678062/en-440-NotoSans-Black.pdf)
[en-440-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678064/en-440-NotoSans-Italic.pdf)
[en-440-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678059/en-440-NotoSans-Regular.pdf)
[en-440-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678060/en-440-NotoSansDisplay-Black.pdf)
[en-440-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678063/en-440-NotoSansDisplay-Italic.pdf)
[en-440-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678061/en-440-NotoSansDisplay-Regular.pdf)
[en-440-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678065/en-440-NotoSansMono-Black.pdf)
[en-440-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678066/en-440-NotoSansMono-Regular.pdf)
[en-440-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678067/en-440-NotoSerif-Black.pdf)
[en-440-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678068/en-440-NotoSerif-Italic.pdf)
[en-440-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678069/en-440-NotoSerif-Regular.pdf)
[en-440-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678070/en-440-NotoSerifDisplay-Black.pdf)
[en-440-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678071/en-440-NotoSerifDisplay-Italic.pdf)
[en-440-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678074/en-440-NotoSerifDisplay-Regular.pdf)
[en-440-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678072/en-440-Roboto-Black.pdf)
[en-440-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678073/en-440-Roboto-Italic.pdf)
[en-440-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678075/en-440-Roboto-Regular.pdf)
