### ISSUE TITLE
Add U+00B7 and other marks to Shavian.

### ISSUE THREAD

**Issue by Kanjilearner817** [googlei18n/noto-fonts#441]
Noto Shavian could benefit the additions of the punctuation marks, mathematical and currency symbols in the Basic Latin, Latin-1 Extended blocks and 00B7.

**Comment by marekjez86** [comment]
We will be consistent with other fonts (whatever this means -- I'll have to understand)

**Comment by dougfelt** [comment]
The general approach in Noto is to assume a fallback chain where characters that don't interact typographically get pulled from other fonts.  Generally we assume characters in NotoSans/NotoSerif don't have to be replicated in all the individual fonts.  We make exceptions for cases where a character's positioning, kerning, or appearance has to be modified to work properly in a font.

If you know of such cases, please tell us.

**Comment by marekjez86** [comment]
closing as WorkingAsIntended per comment above
