### ISSUE TITLE
Cherokee: Add combining marks

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#444]
Moved from googlei18n/noto-alpha#230 

Imported from [Google Code issue #230](https://code.google.com/p/noto-alpha/issues/detail?id=230) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-05-15T00:12:15.000Z:

---

Apparently some combining marks are used with Cherokee. (For more infornation and some examples, you can see http://www.unicode.org/L2/L2014/14064r-n4537r-cherokee.pdf, section 8.)

We need the following combining characters to be added to Noto Sans Cherokee, together with GPOS data for placing them:

0300;COMBINING GRAVE ACCENT
0301;COMBINING ACUTE ACCENT
0302;COMBINING CIRCUMFLEX ACCENT
0304;COMBINING MACRON
030B;COMBINING DOUBLE ACUTE ACCENT
030C;COMBINING CARON
0323;COMBINING DOT BELOW
0324;COMBINING DIAERESIS BELOW
0330;COMBINING TILDE BELOW
0331;COMBINING MACRON BELOW

/cc @kmansourMT

**Comment by xiangyexiao** [comment]
The new desired timeline is late April / early May. Is it feasible?

**Comment by benk-cogapp** [comment]
We would also find the COMBINING GRAVE ACCENT useful in Noto Serif. Our specific use case is for ALA-LC transliteration of Hebrew - see page 6 of http://www.loc.gov/cds/desktop/documents/Hebraica_cataloging.pdf and an example record at http://www.yiddishbookcenter.org/collections/yiddish-books/spb-nybc200956. We generally do well with Noto Serif using precombined characters, but as there isn't a precombined character LATIN SMALL LETTER S WITH GRAVE this falls back to the system font.

**Comment by dougfelt** [comment]
Can you please file a new issue for this?  This issue is specifically about Cherokee.

**Comment by benk-cogapp** [comment]
No problem - I've opened #729 for this case.

**Comment by KatMomoi** [comment]
These new combining glyphs are available in the regular weight, NotoSansCherokee-Regular.ttf (Version 1.900)

https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-pipeline/unhinted

Tidhar, can you verify the same for other Sans weights? Thanks.

**Comment by marekjez86** [comment]
IMHO, DOT BELOW looks fine in both cases (see PDFs). The rest are questionable (but I don't know) especially for uppercase.

lowercase combining characters look better than uppercase ones:
[specimen-Cherokee-diacritic-lowercase.pdf](https://github.com/googlei18n/noto-fonts/files/743965/specimen-Cherokee-diacritic-lowercase.pdf)

uppercase
[specimen-Cherokee-diacritic-uppercase.pdf](https://github.com/googlei18n/noto-fonts/files/743966/specimen-Cherokee-diacritic-uppercase.pdf)

using the following inputs to notodiff (where before and after is the same font)

[specimen-Cherokee-diacritic.zip](https://github.com/googlei18n/noto-fonts/files/743971/specimen-Cherokee-diacritic.zip)

**Comment by kmansourMT** [comment]
Using the alpha font (as indicated by Kat Momoi above), I did some spot-checks and found no problems with the combining marks.As can be seen by the following, the combinations all work well. I also verified that the Gpos contained all the necessary rules for the combinations with both upper and lower case. In the following graphics, you can see samples (in color) from our test environment, while the monochrome one is rendered using the latest Harfbuzz (through Firefox).

![screen shot 2017-02-01 at 17 32 01](https://cloud.githubusercontent.com/assets/12738181/22561523/71e1d91a-e92d-11e6-9505-71cda39bc0c5.png)

![ff-hbz-cherokee](https://cloud.githubusercontent.com/assets/12738181/22561211/1d65c596-e92c-11e6-9b4d-065acbe6539a.png)
![Uploading Screen Shot 2017-02-01 at 17.32.42.png…]()
![screen shot 2017-02-01 at 17 32 01](https://cloud.githubusercontent.com/assets/12738181/22561212/1d67605e-e92c-11e6-962a-3ac7ba51a979.png)

**Comment by marekjez86** [comment]
thank you @kmansourMT 

Looks to me that my test results were wrong (a problem with the linked-in version of harfbuzz in fontdiff?) and the fonts have the required diacritics and they behave properly. 

case closed :-)
