### ISSUE TITLE
Mongolian script font bugs

### ISSUE THREAD

**Issue by almas** [googlei18n/noto-fonts#445]
Here is some bugs on Mongolian script.

![11825047_932342913493264_4767800394958831742_n](https://cloud.githubusercontent.com/assets/90593/9055014/48f7b3b8-3ab9-11e5-86d9-0af63b28e7e6.jpg)
![11779809_931852656875623_8608787386878910191_o](https://cloud.githubusercontent.com/assets/90593/9055015/49479d4c-3ab9-11e5-8585-92d7cef9870e.jpg)

**Comment by almas** [comment]
There are some good Mongolian fonts there. http://mongoltolbo.com and http://mongolfont.com/

**Comment by dougfelt** [comment]
So I guess the problem is the 'flag' is missing from the glyphs in the middle three cases in the first image.  The last case in the first image I'm not sure about, is the problem the hook on the glyph?  The first case, being all in green, there's no problem?

I do not understand what issues the second image is illustrating.

**Comment by marekjez86** [comment]
http://www.almas.co.jp/ and an owner of  http://mongoltolbo.com (and the provider of the comment: "There are some good Mongolian fonts there. http://mongoltolbo.com and http://mongolfont.com/en/index.html ") appears to be behind this posting.

**Comment by almas** [comment]
Hello. I'm not that Almas. We have same name. They are company and from Japan. I'm individual person from Mongolia Ulaanbaatar.

* Yes on first picture green is fixed correct form, red is wrong glyphs.
* On second picture problem number 2 is same as first picture word Flash. 
* On second picture problem number 1 is wrong. It showing "start u" it's wrong, it must show "ending u".
* On second picture number 3 Latin letters don't correctly arranged in 1 line.

Sorry for my English is poor.

**Comment by jungshik** [comment]
@almas,  can you attach a plain text file with strings you used to generate the first image and the second image?  

Can you also tell us which font you used to generate 'all green line (the rightmost line) in your first image? 

Moreover,  what application and library did you use to generate your test images? 


As for item 3 in the second image, Noto Sans Mongolian does not have any Latin coverage so that it can't be blamed for that issue.

**Comment by almas** [comment]
ᠤᠪᠯᠠᠰᠲ᠂ ᠹᠯᠠᠱ᠂ ᠫᠯᠠᠽᠮᠠ᠂ ᠻᠯᠦᠪ᠂ ᠡᠻᠤᠯᠤᠭᠢ

Font was Mongolian Baiti (MS Windows font)

It was Android message app.

**Comment by KrasnayaPloshchad** [comment]
Another good Mongolian fonts are available from here:
http://trans.mglip.com/css/css.css
The following Wikipedia article has illustration of Mongolian/Manchu/Sibe presentation forms can be used for test:
https://en.wikipedia.org/wiki/Mongolian_%28Unicode_block%29

**Comment by KrasnayaPloshchad** [comment]
> On second picture problem number 2 is same as first picture word Flash.

It seems to me that the medial _L_ in this word need kerning.  

> On second picture problem number 1 is wrong. It showing "start u" it's wrong, it must show "ending u".

To fix this problem, the "ending u" must be implemented after following characters: U+00A0, U+202F, U+200D, 	U+2060, U+FEFF

**Comment by KrasnayaPloshchad** [comment]
In Wikipedia article [Pentaglot Dictionary](https://en.wikipedia.org/wiki/Pentaglot_Dictionary) you can found the following text:

> ᠬᠠᠭᠠᠨ ᠤ ᠪᠢᠴᠢᠭᠰᠡᠨ ᠲᠠᠪᠤᠨ ᠵᠦᠢᠯ ᠦᠨ ᠦᠰᠦᠭ᠌ ᠢᠶᠡᠷ ᠬᠠᠪᠰᠤᠷᠤᠭᠰᠠᠨ ᠮᠠᠨᠵᠤ ᠦᠭᠡᠨ ᠦ ᠲᠣᠯᠢ ᠪᠢᠴᠢᠭ᠌᠈

_qaɣan-u bičigsen tabun ǰüil-ün üsüg-iyer qabsuruɣsan manǰu ügen-ü toli bičig_

In this case there is a bug in Noto Sans Mongolian can be seen when display with this font, in the word _iyer_ the letter _i_ and _y_ looks different. cf. http://archive.wul.waseda.ac.jp/kosho/ho05/ho05_01928/ho05_01928_0001/ho05_01928_0001.html

**Comment by KrasnayaPloshchad** [comment]
Here is a list for Mongolian suffixes must be connected by Narrow NBSP:
http://lists.w3.org/Archives/Public/public-i18n-mongolian/2015JulSep/att-0005/DS05_Mongolian_NNBSP_Connected_Suffixes.pdf

**Comment by KrasnayaPloshchad** [comment]
On BabelStone website I found a good guide for design a Traditional Mongolian typeface. You can see it here if you can read Chinese:

http://babelstone.co.uk/Mongolian/MGWBM.html

**Comment by marekjez86** [comment]
Unicode is re-working Mongolian. I expect some results toward end of this year. We will NOT make any changes in Mongolian until we hear from the Unicode Consortium.

**Comment by KrasnayaPloshchad** [comment]
@marekjez86 Is there anyway to track their actions for Mongolian?

**Comment by marekjez86** [comment]
@KrasnayaPloshchad : On 2nd of June, I took part (as an observer) in the initial meeting on Mongolian by a Unicode sub-group. While I didn't contribute anything I've learned how complex Mongolian is. I don't know how the Unicode sub-group works so I cannot comment or even speculate on what they'll do or their timing.

**Comment by marekjez86** [comment]
released https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansMongolian and https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansMongolian which should have the fixes
