### ISSUE TITLE
Thai: Four characters need to be added for Patani Malay

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#447]
Moved from googlei18n/noto-alpha#234

Imported from [Google Code issue #234](https://code.google.com/p/noto-alpha/issues/detail?id=234) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-05-21T00:17:50.000Z:

---

The following characters, needed for Patani Malay (see http://www.unicode.org/L2/L2010/10451-patani-proposal.pdf), should be added to the our Thai fonts:

U+02BC MODIFIER LETTER APOSTROPHE
U+02D7 MODIFIER LETTER MINUS
U+0303 COMBINING TILDE
U+0331 COMBINING MACRON

Note that the two combining characters mentioned above could happen over the same base character as combining Thai vowels, where they should precede them visually, even if they follow them logically. (CC-ing Behdad for potential changes to HarfBuzz, if necessary.)

**Comment by dougfelt** [comment]
These characters are in the phase 2 NotoSansThai fonts.  And they're in Unicode 8.  So... is there anything left to do here?

**Comment by marekjez86** [comment]
verified as present in alpha.../{sans,serif}/*Thai*.ttf
