### ISSUE TITLE
Noto Sans Batak: lowercase script tag 'dflt' is invalid

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#450]
MOved from googlei18n/noto-alpha#189
Imported from [Google Code issue #189](https://code.google.com/p/noto-alpha/issues/detail?id=189) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-03-29T05:58:58.000Z:

----
The Noto Sans Batak font has a script tag of 'dflt' in its second script record in both its GPOS and GSUB tables.

'dflt' is not valid a script tag. Perhaps 'DFLT' was meant.

/cc @kmansourMT

**Comment by xiangyexiao** [comment]
corrected.
