### ISSUE TITLE
Inscriptional Parthian: Taw doesn’t look right

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#453]
moved from https://github.com/googlei18n/noto-alpha/issues/13
Imported from Google Code issue #13 created by roozbeh@google.com on 2013-11-14T02:58:41.000Z:

The glyph for Taw doesn’t look right. In all the Inscriptional Parthian sources I checked, the top right part of the glyph is rounded, looking like a small latin "n". It shouldn’t be sharp.

**Comment by marekjez86** [comment]
behdad could you check if this is still an issue (I moved too early :-))

**Comment by dougfelt** [comment]
In version 1.03 I don't see a change in this glyph's shape, though the bounding box appears to be a bit taller.  I can't tell what the original issue was from the description.

**Comment by kmansourMT** [comment]
In the most recent deliverable, the advance width of Taw (u10B55) changed from 1296 to 1353, and the left sidebearing was increased from 31 to 80. This change improved the spacing of the character.
<img width="172" alt="taw_current" src="https://cloud.githubusercontent.com/assets/12738181/10323684/82a5e04c-6c39-11e5-9169-4acd250ad996.png">
<img width="173" alt="taw_previous" src="https://cloud.githubusercontent.com/assets/12738181/10323683/82a1b1ca-6c39-11e5-90c4-819edad976fe.png">

**Comment by xiangyexiao** [comment]
Roozbeh, could you check if this issue still exists

**Comment by roozbehp** [comment]
This is all very confusing. The glyphs @kmansourMT has posted above do not appear to be a Taw, but the number 1000. I'll double check the latest font with my books back home as soon as possible to make sure everything looks fine.

**Comment by kmansourMT** [comment]
And indeed I did show the wrong glyph. My apologies. Following are the shapes of the Taw: the previous one (sharp corner) is on the left, and the updated one (rounded corner) on the right.
![453_taw-before-after](https://cloud.githubusercontent.com/assets/12738181/10624506/d69ba136-774d-11e5-9226-b372897ac069.png)

**Comment by xiangyexiao** [comment]
looks like it has been fixed in my eyes, but I'll defer to Roozbeh's judgement.

**Comment by dougfelt** [comment]
@roozbehp is this ok?

**Comment by roozbehp** [comment]
The new glyph LGTM.
