### ISSUE TITLE
Inscriptional Parthian: Nun and Sadhe designed assuming followed by another letter

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#454]
moved from https://github.com/googlei18n/noto-alpha/issues/14
Imported from Google Code issue #14 created by roozbeh@google.com on 2013-11-14T03:01:03.000Z:

Nun and Sadhe are designed assuming they are always followed by another Parthian letter. That doesn’t work well at the end of lines, next to Parthian numbers or non-Parthian characters (like a parenthesis), or at the end of words (for example, try `<Nun, Yodh, Space, Nun>`, where the space almost disappears and the two words and the Nuns connect).

The large negative left-side bearing should be increased (to a number with a smaller absolute value) and the trailing under behavior should only happen if the letter is followed by another Parthian letter.

**Comment by dougfelt** [comment]
This is 'nun one space nun yodh space nun':
![parthian](https://cloud.githubusercontent.com/assets/9939212/10260136/3ba48e3e-6926-11e5-98d3-6609be95e59e.png)
It looks to my unschooled eye like the above is ok.

This is 'sadhe one space sadhe yodh space sadhe':
![parthian2](https://cloud.githubusercontent.com/assets/9939212/10260150/679246a8-6926-11e5-9edd-cf6374a6c33d.png)
It looks to me like in the above the second and last sadhe have no space between them.  I'm not sure if they are supposed to be this close together or not.

**Comment by kmansourMT** [comment]
In an earlier version of Inscriptional Parthian, there was an incorrect assumption that these two letters would be followed by another alphabetic letter. In such situations, the tails of the respective characters would protrude excessively to the left. In the current deliverable, they have been changed as follows:
Sadhe: advance width (AW) changed from 1221 to 2439, LSB from -1188 to 30.
Nun: AW changed from 612 to 1788, LSB from -1346 to 30.
Narrower versions of these characters are used when necessary.

<img width="207" alt="454_sadhe_current" src="https://cloud.githubusercontent.com/assets/12738181/10324448/7d6f9082-6c3e-11e5-8c5c-ec85ba0b92f6.png">
<img width="212" alt="454_sadhe_previous" src="https://cloud.githubusercontent.com/assets/12738181/10324447/7d6cc71c-6c3e-11e5-9e49-4ca14ebf335a.png">
<img width="189" alt="454_nun_current" src="https://cloud.githubusercontent.com/assets/12738181/10324454/88bd95ce-6c3e-11e5-87fb-2f595630556d.png">
<img width="171" alt="454_nun_previous" src="https://cloud.githubusercontent.com/assets/12738181/10324453/88bd6d92-6c3e-11e5-8368-5e3a3f259c8d.png">

**Comment by kmansourMT** [comment]
The following demonstrates the new spacing behavior of Sadhe and Nun when they are not followed by alphabetic letter. In this case, each character is followed by One (u10B58) without any intervening spaces.
<img width="989" alt="454_nunsadhe_nonalpha" src="https://cloud.githubusercontent.com/assets/12738181/10324508/ea477d82-6c3e-11e5-8073-941cb446eb52.png">

**Comment by xiangyexiao** [comment]
fixed.
