### ISSUE TITLE
Inscriptional Parthian: ligatures missing

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#455]
Imported from Google Code issue #15 created by roozbeh@google.com on 2013-11-14T03:01:51.000Z:

The Unicode standard’s section on Inscriptional Parthian calls for nine standard ligatures. Of those, only Nun-Daleth works in the font. The other eight should also be supported.

**Comment by dougfelt** [comment]
Current version is 1.03.

I'm not sure exactly what this refers to.  I see in 7 ligatures explicitly called out in section 3.1 of http://www.unicode.org/L2/L2007/07207-n3286-parthian-pahlavi.pdf

But search isn't revealing to me where in the standard these are mentioned.  Perhaps by '9 ligatures' the reporter (@roozbehp?) also means to include the final two renderings (not necessarily ligatures) in that section of the document.

All of these look ok to me, at least there are ligatures present and the behavior seems correct.

![parthian_liga](https://cloud.githubusercontent.com/assets/9939212/10260513/c74b52ba-692b-11e5-89e9-382e8018ee2e.png)
![parthian_liga_2](https://cloud.githubusercontent.com/assets/9939212/10260517/ddedce26-692b-11e5-8865-3af365a43f71.png)
![parthian_other](https://cloud.githubusercontent.com/assets/9939212/10260520/e7bcd334-692b-11e5-96f2-a67d6bc36462.png)

**Comment by kmansourMT** [comment]
Whether we count the number of ligatures indicated in the proposal as 7 or 9, the current font satisfies all of them, as indicated in the above graphics.

**Comment by dougfelt** [comment]
Obviously, how we count them wasn't the point.  It was whether this document is what the reporter (@roozbehp?) was referring to when he mentioned the '9 ligatures'.

**Comment by roozbehp** [comment]
The 9 refers to what is now in Table 10-9 of TUS 8.0, pp. 416 and 417 (http://www.unicode.org/versions/Unicode8.0.0/ch10.pdf). I'm not sure if the shapes are done correctly (I need to check my sources), but based on Doug's images, I agree that all 9 are now supported.
