### ISSUE TITLE
Inscriptional Parthian: undesired glyph intersections

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#456]
Imported from [Google Code issue #16](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=16) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2013-11-14T03:02:56.000Z:

The sequence `<Nun, Shin>` results in the tail of the Nun intersecting with the Shin.

The sequence `<Nun, Sadhe>` results in the tails of the two letters intersecting.

The sequence `<Sadhe, Sadhe>` results in the tails of the two letters intersecting.

The sequence `<Sadhe, Nun, Daleth>` results in the tails of Sadhe and Nun intersecting.

The sequence `<Sadhe, Nun, Sadhe>` results in the tails of all three letters intersecting.

**Comment by dougfelt** [comment]
This is what the above sequences currently look like:

![parthian_collisions](https://cloud.githubusercontent.com/assets/9939212/10260564/ce5efa88-692c-11e5-9015-884daf5dc926.png)

sadhe-sadhe seem to connect, still.  the others have space separating them (sometimes very little).

Perhaps @roozbehp can comment.

**Comment by kmansourMT** [comment]
It is important to see how the above patterns are now being rendered more legibly. It is not only the degree of overlap that matters, but also the recognizability of each element in a combination. Following are some before and after images (before on the right, after on the left):

<img width="900" alt="sadhenunsadhe_cmp" src="https://cloud.githubusercontent.com/assets/12738181/10325788/6c24e90c-6c49-11e5-8e21-a7cbb3983c83.png">
<img width="718" alt="sadhenundaleth_cmp" src="https://cloud.githubusercontent.com/assets/12738181/10325787/6c248bec-6c49-11e5-8f5f-438299181407.png">
<img width="555" alt="nunsadhe_cmp" src="https://cloud.githubusercontent.com/assets/12738181/10325789/6c254eec-6c49-11e5-9af8-269c9403ddcd.png">
<img width="479" alt="nunshin_cmp" src="https://cloud.githubusercontent.com/assets/12738181/10325786/6c248796-6c49-11e5-97ae-20320402c4c6.png">

**Comment by dougfelt** [comment]
They're clearly better.  Just wanted @roozbehp to comment since I believe he filed the original report.

**Comment by xiangyexiao** [comment]
looks nice to my untrained eyes. Close it. @roozbehp feel free to reopen if the issue still exist.
