### ISSUE TITLE
Kaithi font is mistakenly defining ASCII digits instead of Devanagari digits 

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#458]
Moved from googlei18n/noto-alpha#154 
Imported from [Google Code issue #154](https://code.google.com/p/noto-alpha/issues/detail?id=154) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2013-12-26T21:12:30.000Z:

----
According to Unicode 6.2, section 10.7, page 347,

&quot;The digits in Kaithi are considered to be stylistic variants of those used in Devanagari. Hence the Devanagari digits located at U+0966..096F should be employed.&quot;

But the font instead employs the codepoints of the ASCII digits, at U+0030 to U+0039.

The cmap in the font should be changed to point from the Devanagari digits (not from the ASCII digits) to the glyphs defined in the font.

/cc @roozbehp  @kmansourMT

**Comment by xiangyexiao** [comment]
verified. fixed in 1.03
