### ISSUE TITLE
Kannada and Brahmi jihvamuliya and upadhmaniya don't work correctly

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#459]
moved from https://github.com/googlei18n/noto-alpha/issues/279

Imported from Google Code issue #279 created by roozbeh@google.com on 2015-02-19T18:45:32.000Z:

According to Unicode, the Kannada and Brahmi jihvamuliya and upadhmaniya should form ligatures with the following consonant without using any virama, but they don't do that in Noto Kannada and Noto Brahmi.

For Kannada reference, see page 485-486 of http://www.unicode.org/versions/Unicode7.0.0/ch12.pdf

For Brahmi reference, see page 539 of http://www.unicode.org/versions/Unicode7.0.0/ch14.pdf

Attaching the rendering of the three sequences <0CF1, 0C95>, <0CF2, 0CAB>, and <0CF1, 0C95. 0CBF> in Noto Sans Kannada. Compare with images in first reference above.

I haven't tested with Uniscribe yet, but I believe it has the same behavior as HarfBuzz.
 @behdad
  = = = = = = = = = = = = = = = = = 
behdad commented on Jun 30
Comment #1 originally posted by jelle.bosma@monotypeimaging.com on 2015-02-19T20:04:10.000Z:

With regard to Kannada:

In theory the shaper software could be enabled to create the subscript consonant after 0CF1, without any change to the existing fonts. It would have to pretend there is a virama in between and apply the blwf feature. Failing that, we could have a contextual lookup added to one of the presentation features to do the work, because there is no feature defined for creating the below base forms without a virama in the sequence.

Support for displaying 0CF2 as a mark over a crestless consonant is something that would be added to the fonts. Not sure if the information given by Unicode is sufficient to know how that is supposed to work with other consonants and what these consonants are and how to handle the presence of other marks.

I see this as a new feature request, not as a bug.

**Comment by marekjez86** [comment]
![9280a178-2977-11e5-9126-54b7af560764](https://cloud.githubusercontent.com/assets/13322623/9076182/e0f34cee-3ad3-11e5-93ca-1c8e233cc490.png)

**Comment by kmansourMT** [comment]
In the upcoming version of Noto Brahmi, the following ligatures will be provided:
 
Jihvamuliya (11003) + Ka (11013) 
Upadhmaniya (11004) + Pa (11027)

<img width="132" alt="screen shot 2018-01-16 at 09 22 35" src="https://user-images.githubusercontent.com/12738181/35002765-87b31ce8-fa9f-11e7-8ad3-b06a30a81101.png">

**Comment by dscorbett** [comment]
What about the conjuncts with aspirated consonants (𑀃𑀔 and 𑀄𑀨)?

**Comment by sridatta1** [comment]
In Sanskrit the following ligatures can also occur 
ẖkra, ẖkla, ẖkva, ẖkhya, ḫpra, ḫpla 
similar to other clusters vowel signs can also occur ẖkri ẖkhi ẖko etc.
see https://www.unicode.org/L2/L2017/17369r-newa-jihvamuliya-upadhmaniya.pdf

**Comment by kmansourMT** [comment]
@dscorbett 
Regarding the conjuncts of Jihvamuliya & Upadhmaniya conjuncts with aspirated consonants, would you have any graphics to propose for them?

**Comment by dscorbett** [comment]
The aspirated conjuncts look just like the unaspirated conjuncts, but with aspirated consonant glyphs instead of unaspirated consonant glyphs. [L2/13-242](http://www.unicode.org/L2/L2013/13242-kannada-rep.pdf) has examples in Kannada.

**Comment by JelleBosmaMT** [comment]
![image](https://user-images.githubusercontent.com/12729011/41293878-cf0fb210-6e56-11e8-8919-4419d38d26be.png)


The Noto Sans Kannada now support this: at least for Harfbuzz and the Apple shaper. The Microsoft shaper seems to ignore 0CF1 and 0CF2 for shaping

**Comment by MayuraVerma** [comment]
Can we please give get alpha/beta version of the font?

**Comment by MayuraVerma** [comment]
I am testing this in mac OS and Pages with the previously posted test build in a different thread.

Noto Sans Kannada works for only the example shown in Unicode document. But it doesn't work for other consonants and diacritics.

Also, the diacritic should be smaller in size.

![image](https://user-images.githubusercontent.com/14062593/41324582-d8afaae0-6e7a-11e8-9c3e-52bd0bbf411c.png)

**Comment by JelleBosmaMT** [comment]
This works for 4 specific combinations. ẖka, ẖkh, ḫpa, ḫpha. As sridatta1 mentioned there are a few combinations with an second consonant. That works too. This is a image from Chrome, showing the vowels being re-ordered, which I thinks looks better.

![image](https://user-images.githubusercontent.com/12729011/41329490-56439946-6ece-11e8-9ca1-9da250b280aa.png)

**Comment by sridatta1** [comment]
The glyphs for upadhmaniya+pa/pha need to be corrected. They don't have
subscript forms. See www.unicode.org/L2/L2013/13242-kannada-rep.pdf and
upadhmaniya is of smaller size.

**Comment by JelleBosmaMT** [comment]
Of the samples given in www.unicode.org/L2/L2013/13242-kannada-rep.pdf, figure 6 shows the most attractive (and most modern) typeface, so that is the interpretation I used.

**Comment by sridatta1** [comment]
It was due to lack of proper glyphs in the typeface(as the character is not
required for Kannada language) and also the had glyph similar to x  for
jinvamuliya again due to he same reason. The book ha used ೦೦ two zeroes and
pa-ottu. The glyphs in the images in the rest of the books should be used.

**Comment by JelleBosmaMT** [comment]
I am sorry to hear I haven't got it right. In September I made a design proposal, which Google had reviewed. So I thought it to be OK. But I am releasing the fonts today anyway, because in the big picture this doesn't seem a showstopper. I probably get feedback to fix one or another thing, and then add a ligature, tweak render rules. And this project covers Unicode 9.0. Once this project is done, we have to update with a new character and what looks like three new Vedic script extension characters that Unicode added in the mean time.

**Comment by marekjez86** [comment]
additional comment from <JB> "Got this to work for Apple and Google shapers. I implemented this as in the approved design proposal. But I may have used the wrong example according to the bug reporters. In the context of the work this is not a showstopper. I can deal with this once we have feedback with more issues, or the Unicode 10-11 updates."

Will be dealt with in the future release
