### ISSUE TITLE
Thai UI: solution for deep SARA U and SARA UU combinations may be problematic

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#461]
moved from https://github.com/googlei18n/noto-alpha/issues/273

Imported from Google Code issue #273 created by roozbeh@google.com on 2014-11-12T23:17:02.000Z:

Presently, in the Noto Sans Thai UI fonts, deep usages of SARA U and SARA UU are handled by moving the vowel signs towards top left so it can fit inside the consonant. For example, see that attached rendering of the sequence <0E0E, 0E39> (ฎู) in Noto Sans Thai UI.

This solution appears to be too novel, based on public feedback we've received (see, for example, http://lists.freedesktop.org/archives/harfbuzz/2014-November/004590.html).

We have received a suggestion that a better solution could be shortening the consonant instead (see the second attached image).

Comment #1 originally posted by roozbeh@google.com on 2014-11-14T01:58:27.000Z:

Two more data points:

Jungshik thinks there may have been a decision made about this one or the other by our reviewers. Assigning to him to dig this up.

From James Clark:

"- The most authoritative book on Thai font design I know of (http://ftp.opentle.org/pub/national-fonts/FONTBOOK.PDF) addresses this issue on page 83. (The illustration shows their recommended solution, which won't be quite enough for this case, I suspect). (Also see page 76 for an illustration showing how to deal with PHINTHU below DO CHADA and TO PATAK.)

It's common in Thai newspapers headlines (which are set with little leading) to have a vertically compressed DO CHADA and TO PATAK that do not extend below the baseline (e.g. http://www.thairath.co.th/media/IKbPejy4R5wTSf48k65QNeuVpZN.jpg) So one reasonable solution would be to use such a glyph with a normal SARA U or UU (similar to what Ed suggested)."
No action needed from Monotype at the moment, until Jungshik digs the information up.

Comment #2 originally posted by jungshik@google.com on 2014-11-24T19:09:49.000Z:

MTI-Google meeting note on 2014-01-08 has the following: 
(

AI: Monotype to answer from Guy regarding Thai UI font vertical space
Sent new UI font
Cibu/Roozbeh to look at the new data

Cibu/Roozbeh, I believe that the UI font change relevant to this issue might have been discussed during the above review process. Could you check the record from that review (Jan 2014)?

Comment #3 originally posted by roozbeh@google.com on 2014-11-24T20:34:55.000Z:

Thanks a lot Jungshik. Assigning to myself to dig in the records.

Top image is Noto UI; bottom image is the suggested change. Align to Sue to investigate.

![97d628f0-2968-11e5-8b48-d26c9224de8d](https://cloud.githubusercontent.com/assets/13322623/9077024/33f8f66e-3ade-11e5-97cf-a6b1d233f5cc.png)

![97d6eb3c-2968-11e5-8df9-a4928b390292](https://cloud.githubusercontent.com/assets/13322623/9077027/39a4bdb4-3ade-11e5-92a3-e138113884d9.png)

**Comment by marekjez86** [comment]
Sans and Sans UI are now consistent (I have no idea if right).
these PDFs are produced by harfbuzz
[specimen-th-461-SansThai.pdf](https://github.com/googlei18n/noto-fonts/files/745616/specimen-th-461-SansThai.pdf)
[specimen-th-461-SansThaiUI.pdf](https://github.com/googlei18n/noto-fonts/files/745617/specimen-th-461-SansThaiUI.pdf)
[specimen-th-461-SerifThai.pdf](https://github.com/googlei18n/noto-fonts/files/745615/specimen-th-461-SerifThai.pdf)

this image below is from Mac OSX textedit.app with Thai UI font

![thaiui-bug461](https://cloud.githubusercontent.com/assets/13322623/22518521/bfdbc3f0-e861-11e6-9fdc-a0da45c9ee7a.jpeg)

**Comment by roozbehp** [comment]
This apparently also happens with the following sequences:
U+0E0E U+0E38: ฎุ 
U+0E0E U+0E39: ฎู 
U+0E0F U+0E38: ฏุ 
U+0E0F U+0E39: ฏู 

Internal Google bug number: b/37009432
