### ISSUE TITLE
Tifinagh: Tifinagh Consonant Joiner has lost its outlines

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#462]
Moved from googlei18n/noto-alpha#94

Imported from [Google Code issue #94](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=94) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2013-12-13T17:33:49.000Z:

----
The glyph for U+2D7F Tifinagh Consonant Joiner has lost its outlines in version 1.01 of the font. The previous version had an outline.

The previous version of the glyph had an outline for the glyph, similar to the Microsoft and SIL fonts. The outline is needed, as it helps users distinguish the cases where biconsonants are meant, but are not available in the font.

**Comment by jungshik** [comment]
Targetting at Phase II because this is apparently a regression. 

/cc @roozbehp

**Comment by dougfelt** [comment]
With the new version of Tifinagh, the outline is back.  However, hb-view does not display Tifinagh consonant joiner in isolation.  By itself it has zero advance and hb-view generates little or no space for it.  I'm not sure how we expect this character to behave in isolation, or with space or dotted circle (which is not in the font anyway). @behdad?

**Comment by roozbehp** [comment]
Doug, the character should not be tested by itself, but in two scenarios: <consonant+joiner> and <consonant+joiner+consonant>. The second is the common case, where you want to make sure it works fine with any combination of consonants, and the first is for when a user is in the middle of typing the second sequence (the character should be visible). Please test on both HarfBuzz and a Windows 10 machine.

**Comment by dougfelt** [comment]
Your comment omits text for the the scenarios you mention. Perhaps github dropped the text.

I said what I meant.  My question is whether the font should allow displaying this character in isolation.  currently it does not.

The character is always visible except when there is a ligature for the sequence.  It's a nonspacing character that underhangs the previous character.  Half of it is visible (it's clipped) if the text is clipped to the advance width and there is no following spacing character.

I personally do not have a windows 10 machine on which to test this.

**Comment by roozbehp** [comment]
I edited to comment and fixed it.

**Comment by roozbehp** [comment]
The character in isolation probably doesn't matter much, and I don't have a strong opinion on how it should be displayed if it appears just by itself.

**Comment by dougfelt** [comment]
I'm closing this since the original problem (lack of an outline, causing the character to be invisible and hence unusable when applied to characters that don't combine) has been fixed.
