### ISSUE TITLE
Inscriptional Pahlavi: Beth is designed with a wrong assumption

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#463]
Moved from googlei18n/noto-alpha#19
Imported from [Google Code issue #19](https://code.google.com/a/google.com/p/noto-alpha/issues/detail?id=19) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2013-11-14T03:07:07.000Z:

---

Beth is designed assuming it is always followed by another Pahlavi letter. It doesn’t work well at the end of lines, next to numbers or non-Pahlavi characters (like a parenthesis), or at the end of words.

The large negative left-side bearing should be increased (to a number with a smaller absolute value) and the trailing under behavior should only happen if the letter is followed by another Pahlavi letter.

**Comment by marekjez86** [comment]
fixed in the font file present currently in noto-fonts-alpha
