### ISSUE TITLE
Inscriptional Pahlavi: Space between numbers too small

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#464]
Moved from googlei18n/noto-alpha#21

Imported from [Google Code issue #21](https://code.google.com/a/goole.com/p/noto-alpha/issues/detail?id=21) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2013-11-14T03:22:09.000Z:

---

The space between numbers when the follow each other is too small, making e.g. &lt;One, Two&gt; almost indistinguishable from Three.

Please make the whitespace slightly wider, like the Inscriptional Parthian font.

**Comment by marekjez86** [comment]
fixed in the font file present currently in noto-fonts-alpha
