### ISSUE TITLE
Myanmar Bold: positioning -U, -UU, -HU, and -HUU under the RA consonant is not optimal

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#467]
moved from https://github.com/googlei18n/noto-alpha/issues/253

Imported from [Google Code issue #253](https://code.google.com/p/noto-alpha/issues/detail?id=253) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-08-27T17:30:24.000Z:
---

They extend too far to the left, and appear weird in the bold weight.

Here is the comments from our Myanmar expert:
&quot;The current Noto Sans Myanmar rendering is correct (standard behavior by existing Myanmar typography) for RU, RUU, RHU, and RHUU combination [going under the letter RA]. However, it can still be improved (for example, U in RU should appear more to the right [in the bold face]). [...]

My perception is that most Myanmar fonts use relatively thinner strokes for its bold variants (Padauk for example).&quot;

Note: this bug is based on issue 204 (comment 2) and issue 193 (comment 5).

**Comment by jungshik** [comment]
@KatMomoi could you verify that this issue was addressed in the latest delivery?

**Comment by TidharC** [comment]
Can someone please provide the code point sequences to reproduce this issue?  Based on:

http://www.unicode.org/charts/PDF/U1000.pdf

I am not quite sure what they are.

**Comment by marekjez86** [comment]
fonts to be tested with; it's OK to pick just Regular and bold of each kind [NotoMyanmar.zip](https://github.com/googlei18n/noto-fonts/files/572893/NotoMyanmar.zip)

@TidharC : I'll check about the test case

**Comment by marekjez86** [comment]
results of the tests:

[NotoSansMyanmar3-Bold-MN.pdf](https://github.com/googlei18n/noto-fonts/files/581324/NotoSansMyanmar3-Bold-MN.pdf)
[NotoSansMyanmar3-Regular-MN.pdf](https://github.com/googlei18n/noto-fonts/files/581325/NotoSansMyanmar3-Regular-MN.pdf)

the tests are here


[Myanmar3.html.zip](https://github.com/googlei18n/noto-fonts/files/581328/Myanmar3.html.zip)
