### ISSUE TITLE
Myanmar: Dotted circle (U+25CC) is too small

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#468]
Imported from [Google Code issue #239](https://code.google.com/p/noto-alpha/issues/detail?id=239) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-06-04T00:30:07.000Z:

----
The dotted circle in the Myanmar fonts is too small. We depend on it for displaying things like vowels on keyboards in our UI, and the combination doesn't look right.

Probably a good size would be the size of the dotted circle in the Noto Sans LGC font, which is similar to the size of the circle in the Myanmar letter WA.

**Comment by xiangyexiao** [comment]
@kmansourMT please provide comment on whether the size of dotted circle is intentional or not?

<img width="804" alt="screen shot 2016-02-28 at 1 05 19 pm" src="https://cloud.githubusercontent.com/assets/12721521/13381890/ee01a142-de1b-11e5-8cbb-df55575d2c70.png">

**Comment by kmansourMT** [comment]
Previously, the complaint was that the dotted circle in Myanmar was not consistent with the rest of the Noto family. To satisfy that request, we adopted the dotted circle used by Noto LGC. You can see related comments further up: quoting <<_Probably a good size would be the size of the dotted circle in the Noto Sans LGC font, which is similar to the size of the circle in the Myanmar letter WA_.>>

We made this change intentionally. The issue should be closed.

**Comment by xiangyexiao** [comment]
the dotted circle in Noto Sans Myanmar and Noto Sans LGC have the same size already. Does Android pick up the right glyph from the font fallback chain? @roozbehp 

I will close the bug since it is not an issue in the font.

**Comment by roozbehp** [comment]
The bug does not come from Android, but my own testing of the Noto fonts. Based on Kamal's comment and your screenshot, it seems to be fixed now.
