### ISSUE TITLE
Dot accents in noto serif not aligned with i dot

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#47]
```
While the dot accents for characters such as U+0121 and U+022F seem to be 
aligned with the dot of the 'i' character in sans, in serif they are not. Text 
where characters with a dot accent are next to an i, such as in the Maltese 
word "niġi", looks bad.
```

Original issue reported on code.google.com by `tspit...@gmail.com` on 16 Jul 2014 at 11:41

**Comment by jungshik** [comment]
The latest version of Noto Serif has the same 'issue'.

**Comment by TrueTyper** [comment]
Fixed NotoSansUI-RomanMM.glyphs in source.

**Comment by TrueTyper** [comment]
Fixed NotoSerifMM-Regular.glyphs in source.

**Comment by jungshik** [comment]
Thank you, @TrueTyper.  We haven't received yet a new delivery of NotoSansUI, yet. Once I receive it from @waksmonskiMT, I'll check that out.

**Comment by marekjez86** [comment]
using 
``<html lang="mt">
	<p><span style="font-weight:700">niġi</span></p>
</html>``
as input to notodiff and running it with all of these fonts

- NotoSans
- NotoSans Italic
- NotoSansDisplay
- NotoSansDisplay Italic
- NotoSerif
- NotoSerif Italic
- NotoSerifDisplay
- NotoSerifDisplay Italic

I verified that the issue if fixed.

[mt-47-NotoSans-Italic-201611230547.pdf](https://github.com/googlei18n/noto-fonts/files/610252/mt-47-NotoSans-Italic-201611230547.pdf)
[mt-47-NotoSans-Regular-201611230547.pdf](https://github.com/googlei18n/noto-fonts/files/610251/mt-47-NotoSans-Regular-201611230547.pdf)
[mt-47-NotoSansDisplay-Italic-201611230547.pdf](https://github.com/googlei18n/noto-fonts/files/610256/mt-47-NotoSansDisplay-Italic-201611230547.pdf)
[mt-47-NotoSansDisplay-Regular-201611230547.pdf](https://github.com/googlei18n/noto-fonts/files/610255/mt-47-NotoSansDisplay-Regular-201611230547.pdf)
[mt-47-NotoSerif-Italic-201611230547.pdf](https://github.com/googlei18n/noto-fonts/files/610254/mt-47-NotoSerif-Italic-201611230547.pdf)
[mt-47-NotoSerif-Regular-201611230547.pdf](https://github.com/googlei18n/noto-fonts/files/610253/mt-47-NotoSerif-Regular-201611230547.pdf)
[mt-47-NotoSerifDisplay-Italic-201611230547.pdf](https://github.com/googlei18n/noto-fonts/files/610257/mt-47-NotoSerifDisplay-Italic-201611230547.pdf)
[mt-47-NotoSerifDisplay-Regular-201611230547.pdf](https://github.com/googlei18n/noto-fonts/files/610258/mt-47-NotoSerifDisplay-Regular-201611230547.pdf)
