### ISSUE TITLE
PT secondary language on your site should be "mirandese" not "galician"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#49]
```
What steps will reproduce the problem?
1. click on Portugal language dot 
2. you'll see Portuguese/Galician

What is the expected output? What do you see instead?

It should be Portuguese/Mirandese


Please provide any additional information below.

http://en.wikipedia.org/wiki/Mirandese_language
```

Original issue reported on code.google.com by `gcatar...@gmail.com` on 16 Jul 2014 at 12:02

Attachments:
* [Screen Shot 2014-07-16 at 12.57.59.png](https://storage.googleapis.com/google-code-attachments/noto/issue-49/comment-0/Screen Shot 2014-07-16 at 12.57.59.png)

**Comment by behdad** [comment]
cc @jungshik @xiangyexiao

**Comment by TidharC** [comment]
Is this issue still valid?  I don't see any map in:

https://www.google.com/get/noto/

**Comment by waldyrious** [comment]
@TidharC the map still appears after you pick a specific font, e.g. https://www.google.com/get/noto/#sans-lgc -- but it seems they've decoupled the languages data from the territories data (I'm sure they got lots of complaints similar to this one), so yeah, this issue should probably be closed as not applicable anymore.
