### ISSUE TITLE
Kannada font chandrabindu U0C81 not supported

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#492]
Thank you very much for creating the Kannada noto sans font.

Please support sign chandrabindu, unicode code U0C81 . this is a valid sign in Unicode version 8.0.

I am not sure when this was added to the character set.

but the symbol is exactly the same in the devanagari script, chandrabindu U0901. So the glyph will be the same as in devanagari.

Please support this sign.

**Comment by dougfelt** [comment]
This was added in Unicode 7.  The current fonts were designed with charsets based on Unicode 6.

Noto phase 3 will be based on a more recent version of Unicode.  If and when a new Kannada Noto is released it will contain this character. There is as of yet no estimated date for this.
