### ISSUE TITLE
Latin letters small capital i design issues

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#495]
The ɪ U+026A LATIN LETTER SMALL CAPITAL I is designed properly but its derived characters are not.
The letter small capital i is not a small capital i but instead a small serifed capital i, meaning with top and bottom cross-bars.

See the following with Arimo, Cousine, Tinos, Noto Sans, Noto Serif (in that order) in roman and then in italic: ɪᵻᶦᶧ (U+026A U+1D7B U+1DA6 U+1DA7)
![screen shot 2015-09-04 at 08 34 06](https://cloud.githubusercontent.com/assets/1923747/9678682/bd49a8f0-52df-11e5-8d55-5ecbdb2cbb66.png)

In Arimo and Cousine, ᵻ U+1D7B, ᶦ  U+1DA6, ᶧ U+1DA7 should have top and bottom cross-bars.

Tinos is alright.

In Noto Sans, ᵻ U+1D7B should have top and bottom cross-bars.

in Noto Serif, ᵻ U+1D7B should be based on ɪ U+026A instead of dotless i with a stroke.

**Comment by marekjez86** [comment]
@waksmonskiMT @SteveMatteson : what do you think about this design issue? Any feedback? Comments?

**Comment by marekjez86** [comment]
This bug is from now on used ONLY for Noto issues. For Arimo, Cousine issues please see https://github.com/googlei18n/noto-fonts/issues/683

Since I created bug https://github.com/googlei18n/noto-fonts/issues/683 to track Arimo, Cousine and Tinos issues, I'm removing the ArimoTinosCousine label here.

**Comment by marekjez86** [comment]
based on the following test
```html
<html lang="en">
	<p style="font-weight:700"> ɪᵻᶦᶧ (U+026A U+1D7B U+1DA6 U+1DA7)</p>
</html>
```

this issue appears to be fixed

[en-495-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678244/en-495-NotoSans-Black.pdf)
[en-495-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678241/en-495-NotoSans-Italic.pdf)
[en-495-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678239/en-495-NotoSans-Regular.pdf)
[en-495-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678240/en-495-NotoSansDisplay-Black.pdf)
[en-495-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678242/en-495-NotoSansDisplay-Italic.pdf)
[en-495-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678243/en-495-NotoSansDisplay-Regular.pdf)
[en-495-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678249/en-495-NotoSansMono-Black.pdf)
[en-495-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678247/en-495-NotoSansMono-Regular.pdf)
[en-495-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678246/en-495-NotoSerif-Black.pdf)
[en-495-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678245/en-495-NotoSerif-Italic.pdf)
[en-495-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678248/en-495-NotoSerif-Regular.pdf)
[en-495-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678250/en-495-NotoSerifDisplay-Black.pdf)
[en-495-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678251/en-495-NotoSerifDisplay-Italic.pdf)
[en-495-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678252/en-495-NotoSerifDisplay-Regular.pdf)
[en-495-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/678253/en-495-Roboto-Black.pdf)
[en-495-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/678255/en-495-Roboto-Italic.pdf)
[en-495-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/678254/en-495-Roboto-Regular.pdf)
