### ISSUE TITLE
Latin ram’s horn should be distinct from Latin gamma

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#498]
The IPA used to have a ram’s horn that was just a “baby gamma”, a small Latin gamma. It was replaced by a glyph with ram’s horn, meaning terminals pointing down like the horns of a ram.
There are two glyph variants in use for the ram’s horn, one has a small loop and the other has a large loop.

See the following with Arimo, Cousine, Tinos, Noto Sans, Noto Serif (in that order) in roman and then in italic: Ɣɣˠɤ (U+0194 U+0263 U+02E0 U+0264)
![screen shot 2015-09-04 at 09 54 41](https://cloud.githubusercontent.com/assets/1923747/9679963/1acf2850-52eb-11e5-97bb-699a6dc23c42.png)

In Arimo and Cousine, ɤ  U+0264 is alright. Some might prefer a larger loop.

In Tinos, ɤ  U+0264 is too much like Latin gamma, it should have curved terminals pointing down and a curved loop instead of an angular loop. Some might prefer a larger loop as well.

In Noto Sans, ɤ  U+0264 has terminals that could be more pronounced, they should point downwards. Some might prefer a larger loop as well.

In Noto Serif, ɤ  U+0264 is alright. Some might prefer a larger loop as well.

**Comment by marekjez86** [comment]
@xiangyexiao do you agree? if you agree please assign it to SteveMatteson

**Comment by moyogo** [comment]
Here are a couple of references:
On page 73 of Francis Nolan (1988). 2.2 Vowels. Journal of the International Phonetic Association, 18, pp 69-74 doi:10.1017/S0025100300003650
![screen shot 2015-10-09 at 16 50 55](https://cloud.githubusercontent.com/assets/1923747/10398643/2c203712-6ea6-11e5-8874-7854a132df41.png)

On page 73 of the International Phonetic Association (1989). Report on the 1989 Kiel Convention. Journal of the International Phonetic Association, 19, pp 67-80 doi:10.1017/S0025100300003868

![screen shot 2015-10-09 at 16 47 07](https://cloud.githubusercontent.com/assets/1923747/10398522/6e11f288-6ea5-11e5-86fe-ea947372c613.png)

**Comment by marekjez86** [comment]
Any suggestions/feedback on this? @SteveMatteson @waksmonskiMT

**Comment by marekjez86** [comment]
This bug is from now on used ONLY for Noto issues. For Arimo, Cousine or Tinos issues please see https://github.com/googlei18n/noto-fonts/issues/685 .

Since I created bug https://github.com/googlei18n/noto-fonts/issues/685 to track Arimo, Cousine or Tinos issues, I'm removing the ArimoTinosCousine label here.

**Comment by marekjez86** [comment]
from MTI: 'Steve thinks design is good "as is" and does not want to change the rams horn glyph.'

**Comment by moyogo** [comment]
OK.
