### ISSUE TITLE
Latin epsilons (open e) design issues

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#501]
Besides the lack of Latin features in Latin epsilon mentioned in #499, there are additional issues with the Latin epsilons:
- Latin ɜ U+025C should be a horizontally mirrored Latin ɛ U+025B;
- Latin ᴈ U+1D08 should be a turned (180 degrees) Latin ɛ U+025B;
- Latin ɜ U+025C and Latin ᴈ U+1D08 should be distinct.

To be able to distinguish ᴈ U+1D08 from ɜ U+025C, ᴈ U+1D08 must have a larger top counter and a smaller bottom counter. The designs of Ɛɛɜɝɞʚ (U+0190 U+025B U+025C U+025D U+025E U+029A) can follow the same logic (smaller top counter and larger bottom counter) but don’t necessarily have to.

See the following with Arimo, Cousine, Tinos, Noto Sans, Noto Serif (in that order) in roman and then in italic: ɛɜɝᴈɞʚ (U+025B U+025C U+025D U+1D08 U+025E U+029A)
![screen shot 2015-09-05 at 09 44 44](https://cloud.githubusercontent.com/assets/1923747/9698537/c58334ea-53b2-11e5-886d-3bff1d7d12f7.png)

In Arimo, ᴈ U+1D08 should be turned ɛ U+025B and more distinct from ɜ U+025C.

In Cousine, ᴈ U+1D08 should be turned ɛ U+025B and more distinct from ɜ U+025C, ɛɜᴈ U+025B U+025C U+1D08 should have the same width.

In Tinos, ᴈ U+1D08 should be turned ɛ U+025B, ɞʚ U+025E U+029A should have Latin contrast (thick vertical and thin horizontal) and be based on ɛ U+025B (#499).

In Noto Sans, ᴈ U+1D08 should be turned ɛ U+025B and more distinct from ɜ U+025C.

In Noto Serif, ᴈ U+1D08 should be turned ɛ U+025B and more distinct from ɜ U+025C.

**Comment by marekjez86** [comment]
Any update on this issue? @waksmonskiMT @SteveMatteson

**Comment by marekjez86** [comment]
per @moyogo this doesn't happen in any of Arimo, Tinos not Cousine. Removing ArimoTinosCousine tag.

**Comment by hrhatada** [comment]
Fix verify is in progress.

**Comment by hrhatada** [comment]
With the latest font, Arimo, Tinos, Noto Sans, Noto Serif seems fine.  But Cousine, ɛɜᴈ U+025B U+025C U+1D08 the width seem to have still problem.  See below.

![image](https://cloud.githubusercontent.com/assets/16353449/20810780/fc406a6c-b7bf-11e6-8e49-da1ad9dbfcbb.png)

The above image's font were created by the Fontdiff with 

`` <html lang="en-phonipa"><p><span style="font-size:150.0px">ɛɜɝᴈɞʚ</span></p></html> ``

You can verify more this problem with following PDF files which were generated with the Fontdiff & above specimen HTMLfile

[epsilons_Arimo-Reguler.pdf](https://github.com/googlei18n/noto-fonts/files/625665/epsilons_Arimo-Reguler.pdf)
[epsilons_Cousine-Reguler.pdf](https://github.com/googlei18n/noto-fonts/files/625663/epsilons_Cousine-Reguler.pdf)
[epsilons_NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/625664/epsilons_NotoSans-Black.pdf)
[epsilons_NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/625660/epsilons_NotoSansDisplay-Black.pdf)
[epsilons_NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/625662/epsilons_NotoSansDisplay-Italic.pdf)
[epsilons_NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/625661/epsilons_NotoSans-Italic.pdf)
[epsilons_NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/625670/epsilons_NotoSerif-Black.pdf)
[epsilons_NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/625668/epsilons_NotoSerifDisplay-Black.pdf)
[epsilons_NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/625669/epsilons_NotoSerifDisplay-Italic.pdf)
[epsilons_NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/625671/epsilons_NotoSerif-Italic.pdf)
[epsilons_Tinos-Reguler.pdf](https://github.com/googlei18n/noto-fonts/files/625672/epsilons_Tinos-Reguler.pdf)

**Comment by moyogo** [comment]
I seem to have omitted the derived modifier letters 1D4B, 1D9F, 1D4C.

Please also test ɛᵋɜᶟᴈᵌ.

Please also test Display, UI and Mono.

**Comment by moyogo** [comment]
LGTM

**Comment by marekjez86** [comment]
from MTI: "Latin ɜ U+025C should be a horizontally mirrored Latin ɛ U+025B;Latin ᴈ U+1D08 should be a turned (180 degrees) Latin ɛ U+025B Latin ɜ U+025C and Latin ᴈ U+1D08 should be distinct. Fix U+1D08, uni1D93, afii10073, eopenreversed, eopenreversedhook"

**Comment by moyogo** [comment]
Fixed.
