### ISSUE TITLE
Kannada font issue with U0CB1+U0CCD followed consonants and some vowel signs

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#502]
Noto Kannada Sans not rendering few combination of letters. More explanation in the attached screenshot.
ನಿರ್ದೇಶಕ
ಕಾರ್ಪೊರೇಟರ್‌ಗಳನ್ನು

Below screenshot is on Mac OS X El Capitan with NUMBERS:->
![screen shot 2015-09-05 at 4 31 29 am](https://cloud.githubusercontent.com/assets/14062593/9698682/25fabcca-5387-11e5-9630-400f5b194b8d.png)

Below screenshot is on Windows 7 with Excel (2010):->
![capture](https://cloud.githubusercontent.com/assets/14062593/9701777/f3ea2178-5401-11e5-8fa1-6108213484cd.PNG)

Below screenshot is on Mac OS X El Capitan with PAGES:->
![screen shot 2015-09-05 at 4 32 15 am](https://cloud.githubusercontent.com/assets/14062593/9698683/25fcf79c-5387-11e5-914b-fc0456229b13.png)

**Comment by MayuraVerma** [comment]
More observations.
For the below link 
http://www.prajavani.net/article/ಬಿಬಿಎಂಪಿ-ಕಾಂಗ್ರೆಸ್‌-ಸದಸ್ಯರಿಗೆ-ಬಿಜೆಪಿ-ಗಾಳ 

"ಕಾರ್ಪೊರೇಟರ್‌ಗಳನ್ನು" renders correctly on Google Chrome in Mac but incorrectly on Safari in Mac. Attached screenshot demonstrate it. Noto Kannada Sans is the default font for Kannada font on this mac.


"ಕಾರ್ಪೊರೇಟರ್‌ಗಳನ್ನು" and all the other character combination shown in the previous comment renders incorrectly on Safari, Pages, Numbers and Keynote applications in Mac. 


![screen shot 2015-09-05 at 4 39 11 am](https://cloud.githubusercontent.com/assets/14062593/9698722/4893a214-5388-11e5-90f7-366ae99852df.png)

**Comment by lianghai** [comment]
Apparently an reording bug of Apple's text engine (Core Text): the reph glyph is not being reodered to the correct place.
This issue is on Apple's side. It has nothing to do with the fonts.
Please report this issue to Apple through http://bugreport.apple.com

**Comment by MayuraVerma** [comment]
thank you for the clarification. its a masterstoke.

**Comment by lianghai** [comment]
Btw, a reph is not formed by `<U+0CB1 RRA, U+0CCD VIRAMA>`. It's `<U+0CB0 RA, U+0CCD VIRAMA>`.
Also, it'll be better to use the conventional notation `U+XXXX` instead of `UXXXX` to refer to a Unicode character, and `<U+XXXX, U+XXXX, ...>` to refer to a character sequence.

**Comment by MayuraVerma** [comment]
Thanks. It was overlooked.

**Comment by MayuraVerma** [comment]
@JelleBosmaMT and @lianghai 

Please comment on this issue. 

Kannada MN and KannadaSangamMN has lot of bugs. So, I have changed to Noto Kannada as the system default font in Mac. But I am facing this issue in Mac. 

According to CDAC, Open Type Indic font for mac should be treated differently. It is not a bug in the Apple's text engine.

http://www.cdac.in/index.aspx?id=mlc_gist_font 
"Open type fonts for MAC OS X for Indian Languages" .

**Comment by JelleBosmaMT** [comment]
>
>According to CDAC, Open Type Indic font for mac should be treated
>differently. It is not a bug in the Apple's text engine.
>http://www.cdac.in/index.aspx?id=mlc_gist_font
>"Open type fonts for MAC OS X for Indian Languages" .

Mac OS has supported the OpenType rendering for some time. So they should
work without the Apple specific state tables. I have skipped a few version
of Mac OS, so I am not quite sure with version it started. First they
implemented rendering rendering with the original script tags (deva,
knda). With 10.10 the second generation is supported (dev2, knd2). I just
tried Kannada and my proofing document looks OK in Pages.app .

The support for Devanagari dev2 is rather buggy though. It does strange
things with the i-vowel reordering once there are more than 2 consonants
in the syllable, for example. So I cannot guarantee Kannada renders as it
does in Windows (as it is supposed to do).

I haven’t yet installed the newest version of Mac OS that has been
released last month. Hopefully Apple has done some debugging.

**Comment by JelleBosmaMT** [comment]
I replied by e-mail, not realizing this was a different issue.
It looks the Mac has trouble re-ordering once there are more than 2 character codes in-between: whether it is Kannada or Devanagari. When the renderer splits the multi-part vowels, it moves the reph after the first vowel mark, instead after the last.

**Comment by MayuraVerma** [comment]
According to wiki https://en.wikipedia.org/wiki/Apple_Advanced_Typography#AAT_and_OpenType_in_OS_X

open type fonts need additional AAT tables for indic fonts in MAC OS/iOS, until apple supports natively, open type fonts for indic scripts.

I have confirm the reordered issue exists in latest El CAPITAN 10.11.1 and latest pages version 5.6(5663); ios 9.1 and pages 2.6.

So, is it reasonable request to update Kannada font with AAT tables until APPLE updates their text engine to fully support all indic scripts. 

![screen shot 2015-10-31 at 7 31 10 am](https://cloud.githubusercontent.com/assets/14062593/10863624/6855b322-7fa1-11e5-8d6b-d3a088c960a9.png)

**Comment by JelleBosmaMT** [comment]
I don’t know how trustworthy this wikipedia page is.  Either Apple
supports OpenType Layout or it  doesn’t.  It seems a bad idea of epic
proportions to expect fonts that need both AAT and OTL to work properly.
For what I can tell Devanagari fonts with “deva” script tag seem to work
OK. The ITF Devanagari fonts work OK, with “deva” rendering for GSUB and
GPOS, without any AAT table in the fonts. It is the change made in the
“dev2” method of rendering that has re-ordering issues.

Jelle

**Comment by MayuraVerma** [comment]
I can speculate. During iOS 8 launch, APPLE announced support of INDIAN LANGUAGE. Ever since they are replacing Kohinoor family fonts (ITF) the previous Sangam family fonts. I think recently added Telugu in iOS 9. They have not added Kannada yet.

It could be that, when they are adding Kohinoor font for indic language, they are updating the Open Type Font table for that language.

Since devanagari was added earlier, they may have fixed the table for it. Kannada might be later.

**Comment by lianghai** [comment]
@MayuraVerma: You're making too many wrong assumptions.

Let me clarify again (cc @JelleBosmaMT):

The issue you reported here is a mistake of reordering in Core Text (OS X and iOS's text engine)'s Kannada OpenType Layout.

Kannada MN and Kannada Sangam MN are simply not OpenType fonts. They're AAT TrueType fonts.

Core Text already supports all Indic1 and Indic2 OpenType Layout behaviors of all 9 major Indic scripts, including Kannada. However, it has bugs.

> So, I have changed to Noto Kannada as the system default font in Mac. But I am facing this issue in Mac.

What were you even trying to say?! I said, according to your screenshots, OS X's OpenType Layout engine has a bug on reordering Kannada reph. Of course Noto Sans Kannada (it's not "Noto Kannada" — can you at least write its name correct?) doesn't work well in terms of reph-reordering — Noto Sans Kannada is an OpenType Indic font that relies on Core Text's Kannada OpenType Layout engine!

> According to CDAC, Open Type Indic font for mac should be treated differently. It is not a bug in the Apple's text engine. http://www.cdac.in/index.aspx?id=mlc_gist_font "Open type fonts for MAC OS X for Indian Languages" .

C-DAC's information is horribly inaccurate and out-of-date. What useful information can you expect from an organization that can't even spell "OpenType" and "(Mac) OS X" correctly? The information you found is still valuable to a very limited extent, however you don't have enough knowledge to understand it well without being misled.
I'm telling you again: Core Text now supports both Indic1 and Indic2 OpenType Layout behaviors of all 9 major Indic scripts, just like how Windows and Linux distributions do. Clear?

> open type fonts need additional AAT tables for indic fonts in MAC OS/iOS, until apple supports natively, open type fonts for indic scripts.

Forget about those out-of-date information you found on Wikipedia (not "wiki"). Read what I've written, again.

@MayuraVerma, simply, read what I've written, all of my comments under this issue report, again.

**Comment by lianghai** [comment]
Off topic:

@JelleBosmaMT:

May I know what you meant by —
> It does strange things with the i-vowel reordering once there are more than 2 consonants in the syllable, for example.
— and —
> It is the change made in the “dev2” method of rendering that has re-ordering issues.
— in your comments? I've noted down a couple of reordering issues in Core Text's "dev2" implementation, but what you mentioned doesn't seem to be one of mine.

**Comment by MayuraVerma** [comment]
> @MayuraVerma: You're making too many wrong assumptions.
> 
Assumptions can be wrong.
> Let me clarify again (cc @JelleBosmaMT):
> 
> The issue you reported here is a mistake of reordering in Core Text (OS X and iOS's text engine)'s Kannada OpenType Layout.
> 
Ok
> Kannada MN and Kannada Sangam MN are simply not OpenType fonts. They're AAT TrueType fonts.
> 
That is true. It's known fact.
> Core Text already supports all Indic1 and Indic2 OpenType Layout behaviors of all 9 major Indic scripts, including Kannada. However, it has bugs.
> 
Could you please provide any reference indicating the same. Either it is not supported or buggy, there is work around to it by adding AAT table to OpenType font.
> So, I have changed to Noto Kannada as the system default font in Mac. But I am facing this issue in Mac.
> 
> What were you even trying to say?! I said, according to your screenshots, OS X's OpenType Layout engine has a bug on reordering Kannada reph. Of course Noto Sans Kannada (it's not "Noto Kannada" — can you at least write its name correct?) doesn't work well in terms of reph-reordering — Noto Sans Kannada is an OpenType Indic font that relies on Core Text's Kannada OpenType Layout engine!
> 
 Need reference? Can u point any document on Apple developer reference? Or is it YOUR ASSUMPTION?

"Noto Sans Kannada" don't slice and dice every word that is uttered. There is only Noto Kannada, everybody understands what is said, expect people with OCD.
> According to CDAC, Open Type Indic font for mac should be treated differently. It is not a bug in the Apple's text engine. http://www.cdac.in/index.aspx?id=mlc_gist_font "Open type fonts for MAC OS X for Indian Languages" .
> 
> C-DAC's information is horribly inaccurate and out-of-date. What useful information can you expect from an organization that can't even spell "OpenType" and "(Mac) OS X" correctly? The information you found is still valuable to a very limited extent, however you don't have enough knowledge to understand it well without being misled.
> I'm telling you again: Core Text now supports both Indic1 and Indic2 OpenType Layout behaviors of all 9 major Indic scripts, just like how Windows and Linux distributions do. Clear?
> 
Again need reference to your claims. I may have limited knowledge in this subject and I may be doing this as hobby/interest for my language. In my primary profession, even though I have full knowledge I don't do finger pointing and demean on anybody, because I find it rude and repulsive.
> open type fonts need additional AAT tables for indic fonts in MAC OS/iOS, until apple supports natively, open type fonts for indic scripts.
> 
> Forget about those out-of-date information you found on Wikipedia (not "wiki"). Read what I've written, again.
> 
According to @Iianghai both CDAC and Wiki extremely sorry Wikipedia have limited and out-of-date information. Should not we request proper documentation for this claim.
> @MayuraVerma, simply, read what I've written, all of my comments under this issue report, again.
> 

I read all your comments, this is what I understand -> in your mind everybody else is "SHITY", "HORRIBLE", "can't spell names right" "lack of knowledge". Please take a fresh air and rethink on how you are seeing the world. Nobody appreciates this arrogance unless you are Steve Jobs, which you clearly are not.

Relax and respect everybody around you.

**Comment by JelleBosmaMT** [comment]
![untitled](https://cloud.githubusercontent.com/assets/12729011/10865647/97c000f6-8012-11e5-877a-b7b45e11ee52.png)

Kokila (Windows 7) and Noto Sans with dev2 rendering. ITF Devanagari with deva rendering. In deva rendering the i is always moved in front. In dev2 it is supposed to be moved either in front or after the right-most virama that is still present after the Basic Shaping features have been applied.  nga does not have a half-form. Apple assumes that if you have a character that does not have a half form, you do not move the i in front. But sometimes the virama is taken out by a vatu or cjct feature. Oops.

**Comment by MayuraVerma** [comment]
@JelleBosmaMT although I learnt Devanagari script in school both for Samskrita and Hindi. I have lost touch in them due to lac of practice.

Please tell me how to solve the re-ordering issue in Noto Sans Kannada in OS X and iOS. Do we have to keep fingers crossed for Apple to fix the text engine? or can we do something in the font until they wake up?

KannadaSangamMN and KannadaMN (system default TTF fonts of OS X and iOS) both have other bugs in them, which makes it difficult to read.

Disclaimer (to people with OCD): English is not my first language and font designing is not my profession. Please do not point out silly mistakes in my writing and make yourself look silly.

**Comment by lianghai** [comment]
@MayuraVerma:
Yes, I have OCD. Thank you for the diagnosis.
No, I don't respect you at all, and I don't feel like to help you now. Don't mention me anymore.

**Comment by lianghai** [comment]
@JelleBosmaMT:
Aha! Yes, this is one of the bugs I've noticed. Btw, this bug is not only in Core Text's "dev2" implementation, but also in, at least, "gjr2".
I'm planning to report a bunch of Indic2 bugs (including this one) in Core Text, after some systematic tests. It'd be great if you can also report — if haven't — what you've found out.

**Comment by MayuraVerma** [comment]
@lianghai
Take care :) 

The fragile line between confidence and arrogance is humility.
NORMAN E. BOWIE & MEG SCHNEIDER, Business Ethics for Dummies

**Comment by JelleBosmaMT** [comment]
In theory it might be possible to add a lookup table that swaps reph and vowel marks around if in incorrect order. But I haven't done a systematic review of what happens when Mac OS encounters a Kannada OT font. So I am not sure yet. And adding a work-around in 2 fonts does not solve the real problem. Mac users of Karnataka should complain loud enough for Apple to take notice and fix what needs to be fixed.

**Comment by MayuraVerma** [comment]
@JelleBosmaMT 
KannadaSangamMN and KannadaMN font issue was taken as high as I could take it and I know few other users who reported the issue. They may have some plans in the pipeline to fix the issue with Kohinoor font, (again speculation, since they are replacing other Indic fonts recently). While they replace the font, they might fix the Text Engine. (it could be their plan, being optimistic). 

But for the time being could we please work around the issue in Noto Sans Kannada font. Since, we have Tunga (OpenType) font to check if the Text Engine is corrected or not in the future. If and when the Apple Text Engine is bug free, we can drop this lookup table.

My humble request to support Noto Sans Kannada for OS X and iOS.

(For a profit oriented company, such as Apple. They care least to resolve a minority font issue but worry more to swap pins in standard PCI-E SSD slot and brand it as PROPRIETARY. In other words, make it impossible for aftermarket upgrades, rather pay huge upgrade to OEM!)

**Comment by jungshik** [comment]
Note that both Chrome (Blink) and Firefox do not use CoreText to support opentype (as opposed to AAT) fonts. They use harfbuzz. Therefore, Chrome and Firefox do not suffer from whatever bug is present in opentype handling of CoreText. 

Unfortunately, other applications that use CoreText for opentype handling would not be as lucky.

**Comment by jungshik** [comment]
Anyway, I'm closing this bug because it's not a font bug.
