### ISSUE TITLE
Latin yogh design issues

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#503]
Latin yogh is a letter derived from the insular g used in the Middle Ages which makes it hard to translate in modern typefaces. However some of its main features should remain. It was unified with Ezh ʒ for a while because its shape is relatively close to it until Ȝȝ U+021C U+021D were introduced in Unicode 3.0 because they have different origin (ʒ comes from z, ȝ comes from g) and should be distinct. See Everson’s _On the derivation of YOGH and EZH_ http://www.evertype.com/standards/wynnyogh/ezhyogh.html.

I’m not sure it’s adequate to have yogh look like the Cyrillic ze Зз U+0417 U+0437 (even with a descender for the lowercase).

See the following with Arimo, Cousine, Tinos, Noto Sans, Noto Serif (in that order) in roman and then in italic: ȜȝЗз3 (U+021C U+021D U+0417 U+0437 U+0033)
![screen shot 2015-09-05 at 10 30 19](https://cloud.githubusercontent.com/assets/1923747/9698684/7ddc94ea-53b9-11e5-8bbb-85ebf614e1b6.png)

In Arimo and Cousine, Ȝȝ U+021C U+021D should have a shorter middle stroke, it shouldn’t extend as far left as the bottom stroke.

In Tinos, Ȝȝ U+021C U+021D are alright.

In Noto Sans and Noto Serif, Ȝȝ U+021C U+021D should be different, the middle stroke and bottom stroke should point down, the top stroke can stay the same or can start curved up.

**Comment by marekjez86** [comment]
per @moyogo this doesn't happen in any of Arimo, Tinos not Cousine. Removing ArimoTinosCousine tag.

**Comment by TidharC** [comment]
fix verification in progress.

**Comment by TidharC** [comment]
Looks like U+021C and U+021D are fixed.  Sans and Serif renderings are attached.

[specimenNotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/623263/specimenNotoSans-Black.pdf)
[specimenNotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/623262/specimenNotoSansDisplay-Black.pdf)
[specimenNotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/623264/specimenNotoSansDisplay-Italic.pdf)
[specimenNotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/623265/specimenNotoSans-Italic.pdf)
[specimenNotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/623266/specimenNotoSerif-Black.pdf)
[specimenNotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/623269/specimenNotoSerifDisplay-Black.pdf)
[specimenNotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/623267/specimenNotoSerifDisplay-Italic.pdf)
[specimenNotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/623268/specimenNotoSerif-Italic.pdf)
