### ISSUE TITLE
Latin cedilla alternate for Marshallese or as stylistic alternate

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#505]
As mentioned in #427 Marshallese uses L, m, n, o with cedilla. Because of the Latvian expected shape of cedilla, the cedilla of ĢĶĻŅŖģķļņŗ are comma-below cedillas. So Marshallese ends up with classic and comma-below cedillas. There should be ways to have a single cedilla in Marshallese.

This can be done with a locl feature for Marshallese MAH which would change the comma-below cedillas to classic cedilla (as this seems to be the preferred shape, see http://www.trussel2.com/MOD/stamp-n2.gif).
Two stylistic set features can also let the user pick whether they want the classic cedilla or the comma-below cedilla under all letters. One might want to represent the Latvian letters with cedilla with classic cedilla as they were for a few years before the comma-below cedilla became the norm, one might want to do something similar for Romanian ḐŞŢḑşţ or one might want to go the other direction with Çç etc from classic cedilla to comma-below cedilla. This would also apply to the g-cedilla’s cedilla above.

See http://www.unicode.org/L2/L2013/13155r-cedilla-comma.pdf on the topic.

**Comment by roozbehp** [comment]
We are not that much into stylistic letters in Noto

Noto currently correctly shows comma forms for the letters listed, but we definitely need an 'locl' feature for Marshallese (MAH) that produces the cedilla forms for the letters listed (ĢĶĻŅŖģķļņŗ) and for combining cedilla (U+0327). Assigning to Monotype to add the required glyphs and features.

**Comment by marekjez86** [comment]
Assigning to @SteveMatteson but see @roozbehp comment "... but we definitely need an ..."

**Comment by kmansourMT** [comment]
@roozbehp Since Marshallese uses only M, O, L, N (with cedilla), there’s no reason to make changes to all comma-below characters used by Latvian. Marshallese shares only L-cedilla and N-cedilla with Latvian. I propose we add a locale-based feature for Marshallese that changes the comma-below forms of L-cedilla (u013B/C) and N-cedilla (u0145/6) to true cedillas (u0327). For the remaining Marshallese cedilla combinations of M & O, the user will need to enter the desired letter, followed by a cedilla. Likewise, if the input is either L or N followed by cedilla, the resulting combination will conform to the Marshallese convention.

**Comment by marekjez86** [comment]
Why not adding a locale-based feature for Marshallese that changes the comma-below forms of M, O, L, N (with cedilla) to true cedillas (u0327) as opposed to comma-below?

A user of the language should be able to consistently type characters. I'd want to type it either (i) all  desired letter, followed by a cedilla or (ii) just desired letter. This might be like asking Germans to type ö for o-umlaut, but requiring them to enter ae instead of ä, and ue instead of ü. Just doesn't feel right from the usability point of view.
IMHO providing only N-cedilla and L-cedilla would be too confusing and would feel like a "halfway" solution.

**Comment by moyogo** [comment]
@marekjez86 there is not precomposed characters for M-cedilla or O-cedilla. One can only produce those by using the sequences M + combining cedilla and O + combining cedilla.
The input methods should let the user enter M-cedilla, etc. like N-cedilla, etc., and produce the right character sequences.

**Comment by kmansourMT** [comment]
Marek, I'm not sure how you interpreted my message, but I am saying the same thing as you.
If they type M, O, L, or N followed by cedilla, they will get a true-cedilla combination as a result.
If, instead, they type the precomposed characters L-cedilla (u013B/C) and N-cedilla (u0145/6), they will obtain true-cedilla forms only if a Marshallese locale is flagged for the text.

**Comment by marekjez86** [comment]
Agree with @kmansourMT 

@moyogo thanks for educating me

**Comment by jungshik** [comment]
@kmansourMT proposed in https://github.com/googlei18n/noto-fonts/issues/505#issuecomment-162970102 : 

> I propose we add a locale-based feature for Marshallese that changes the comma-below forms of L-cedilla (u013B/C) and N-cedilla (u0145/6) to true cedillas (u0327).

Has this been done?

**Comment by kmansourMT** [comment]
This issue was corrected in the Arimo, Tinos and Cousine fonts that were reworked and re-delivered in March

**Comment by marekjez86** [comment]
Assigning to KatMomoi to verify the fixes in the Arimo, Tinos and Cousine fonts that were reworked and re-delivered in March

**Comment by TidharC** [comment]
All cedillas still look comma-shaped even with the Marshallese language tag.
![marshallese1](https://cloud.githubusercontent.com/assets/16353803/20198881/160b6984-a75c-11e6-920a-1df5fe2173a9.png)

I used the following HTML code in Chrome browser:

<html lang="mh" xml:lang="mh">
	<meta charset="utf-8"/>
		<div style="font-family:arimo;font-size:500%;">
			Ļ ļ  Ņ ņ          Arimo
		</div>
		<div style="font-family:cousine;font-size:500%;">
			Ļ ļ  Ņ ņ          Cousine
		</div>
		<div style="font-family:tinos;font-size:500%;">
			Ļ ļ  Ņ ņ          Tinos
		</div>
	</meta>
</html>

**Comment by TidharC** [comment]
[Marshallese.txt](https://github.com/googlei18n/noto-fonts/files/584697/Marshallese.txt)

**Comment by TidharC** [comment]
All cedillas still look comma-shaped even with the Marshallese language tag.

![marshallese1](https://cloud.githubusercontent.com/assets/16353803/20199072/0a25cc58-a75d-11e6-8bc9-592071cb4bf2.png)

**Comment by TidharC** [comment]
HTML test snippet

[Marshallese.txt](https://github.com/googlei18n/noto-fonts/files/584703/Marshallese.txt)

**Comment by SteveMatteson** [comment]
is what you’re looking for a detached cedilla?
Steve Matteson
Creative Type Director
_________________________
1048 Meadow Court
Louisville, CO 80027
_________________________
303 588 9755

On Nov 10, 2016, at 4:43 PM, TidharC <notifications@github.com<mailto:notifications@github.com>> wrote:


All cedillas still look comma-shaped even with the Marshallese language tag.
[marshallese1]<https://cloud.githubusercontent.com/assets/16353803/20198881/160b6984-a75c-11e6-920a-1df5fe2173a9.png>

I used the following HTML code in Chrome browser:



Ļ ļ Ņ ņ Arimo


Ļ ļ Ņ ņ Cousine


Ļ ļ Ņ ņ Tinos

**Comment by TidharC** [comment]
From the comments above, I understood that the cedilla for L and N should look like this:

http://www.trussel2.com/MOD/stamp-l2.gif
http://www.trussel2.com/MOD/stamp-n2.gif

**Comment by TidharC** [comment]
Retested with Arimo/Cousine/Tinos fonts with language code "mh".  The cedilla now looks correct (renderings are attached).  Note that, with language code "lv", the comma-shaped cedilla is preserved.

[specimenArimo-Bold.pdf](https://github.com/googlei18n/noto-fonts/files/623413/specimenArimo-Bold.pdf)
[specimenArimo-BoldItalic.pdf](https://github.com/googlei18n/noto-fonts/files/623414/specimenArimo-BoldItalic.pdf)
[specimenArimo-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/623415/specimenArimo-Italic.pdf)
[specimenArimo-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/623416/specimenArimo-Regular.pdf)
[specimenCousine-Bold.pdf](https://github.com/googlei18n/noto-fonts/files/623420/specimenCousine-Bold.pdf)
[specimenCousine-BoldItalic.pdf](https://github.com/googlei18n/noto-fonts/files/623417/specimenCousine-BoldItalic.pdf)
[specimenCousine-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/623418/specimenCousine-Italic.pdf)
[specimenCousine-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/623419/specimenCousine-Regular.pdf)
[specimenTinos-Bold.pdf](https://github.com/googlei18n/noto-fonts/files/623422/specimenTinos-Bold.pdf)
[specimenTinos-BoldItalic.pdf](https://github.com/googlei18n/noto-fonts/files/623423/specimenTinos-BoldItalic.pdf)
[specimenTinos-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/623421/specimenTinos-Italic.pdf)
[specimenTinos-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/623424/specimenTinos-Regular.pdf)

**Comment by davelab6** [comment]
I filed https://github.com/google/fonts/issues/657 to better track this

@lanimoomoo you can download them from https://github.com/googlei18n/noto-fonts/tree/master/hinted (click the filename, then 'view raw')

**Comment by TidharC** [comment]
Confirming the font location:
https://github.com/googlei18n/noto-fonts/tree/master/hinted


The font versions are as follows:

Arimo
Regular:  1.33
Bold: 1.33
Italic: 1.33
Bold Italic: 1.33

Cousine
Regular: 1.23
Bold: 1.23
Italic: 1.23
Bold Italic: 1.23

Tinos
Regular: 1.33
Bold: 1.33
Italic: 1.33
Bold Italic: 1.33

**Comment by marekjez86** [comment]
@TidharC : the problem is that https://github.com/googlei18n/noto-fonts/tree/master/hinted has prior versions of the fonts

**Comment by dougfelt** [comment]
@marekjez86 I don't understand this.  If we have new versions of the fonts, they should be pushed to noto-fonts and replace the ones that are there now.  Are they not hinted?  Who has these new versions?

**Comment by marekjez86** [comment]
They were delivered to us in March of last year. I didn't understand the process then and didn't know what's going on (I was dealing mainly with the pipeline then). As of yesterday, I didn't know the right location to push them.

**Comment by brawer** [comment]
Well, thanks in advance for getting it fixed. :-)
