### ISSUE TITLE
Latin phonetic small cap letters design issues in Noto Sans and Serif

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#506]
There are several design issues with x-height small cap letters that should be based on the capital letters. They are here instead of separate issues.
See related issues #495 regarding Latin letter small capital i (always with crossbars so not based on capital letter) and #494 regarding Greek letter small capital omega.
## Letter small cap B

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif: Bʙᴃᴮᴯ U+0042 U+0299 U+1D03 U+1D2E U+1D2F
![screen shot 2015-09-06 at 09 47 28](https://cloud.githubusercontent.com/assets/1923747/9703444/66b47846-547c-11e5-8a66-6863e1d34c03.png)

In Arimo:
- italic ʙᴃ U+0299 U+1D03 should be based on Latin B U+0042 instead of Cyrillic В U+0412.

In Noto Sans:
- ᴃ U+1D03 should be base on ʙ U+0299 instead of being narrower.
- italic ʙ U+0299 should be based on Latin B U+0042 instead of Cyrillic В U+0412.
## Letter small cap E

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif: EᴇᴱƎⱻᴲ U+0045 U+1D07 U+1D31 U+018E U+2C7B U+1D32
![screen shot 2015-09-06 at 09 54 29](https://cloud.githubusercontent.com/assets/1923747/9703488/6d68f418-547d-11e5-86f8-6c8de93bb5dd.png)

In Tinos:
- ⱻ U+2C7B should be based on Ǝ U+018E and have a shorter bar on top and a longer bar below for consistency and optical reasons.
## Letter small cap J

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif: Jᴊȷᴶ U+004A U+1D0A U+0237 U+1D36
![screen shot 2015-09-06 at 10 02 51](https://cloud.githubusercontent.com/assets/1923747/9703523/85837c5c-547e-11e5-9860-badf36d4f1c6.png)

In Tinos:
- italic ᴊ U+1D0A should be based on J U+004A instead of ȷ U+0237

In Noto Sans and Noto Serif:
- ᴊ U+1D0A could maybe not have a descender to help make it more distinct from ȷ U+0237.
## Letter small cap M and N

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif: MᴍᴹNɴᴺᴎᴻ U+004D U+1D0D U+1D39 U+004E U+0274 U+1D3A U+1D0E U+1D3B
![screen shot 2015-09-06 at 10 08 43](https://cloud.githubusercontent.com/assets/1923747/9703549/61aacdac-547f-11e5-8d8f-ec44e4584663.png)

In Tinos:
- italic ᴍ U+1D0D should be based on Latin M U+004D instead of м U+043C
- italic ɴ U+0274 should be based on Latin N U+004E
- roman ᴎ U+1D0E can be a composite of Cyrillic и U+0438 but it it better if it is a flipped Latin ɴ U+0274 (with or without adjusted stroke contrast, thick verticals and thin diagonal)
- italic ᴎ U+1D0E cannot be a composite of Cyrillic и U+0438

In Noto Sans and Noto Serif:
- ᴎᴻ U+1D0E U+1D3B are alright, one could prefer them with adjusted stroke contrast, thick verticals and thin diagonal) for optical reasons but it’s uncommon.
## Letter small cap O

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif: Ooᴏᵒᴼ U+004F U+006F U+1D0F U+1D52 U+1D3C
![screen shot 2015-09-06 at 10 30 00](https://cloud.githubusercontent.com/assets/1923747/9703653/5772c9e0-5482-11e5-9cdf-1466e684b193.png)

In Arimo, Cousine and Tinos:
- Letter small capital ᴏ U+1D0F should be noticeably wider than o U+006F
  In Noto Sans and Noto Serif:
- Letter small capital ᴏ U+1D0F is alright next to o U+006F, but it is a bit hard to distinguish in normal.
## Letter small cap Ȣ

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif: Ȣȣᴕᴽ U+0222 U+0223 U+1D15 U+1D3D
![screen shot 2015-09-06 at 10 39 01](https://cloud.githubusercontent.com/assets/1923747/9703707/8544c430-5483-11e5-8719-4f7dd5c00b93.png)

In Arimo and Cousine:
- ᴕᴽ U+1D15 U+1D3D should be based on Ȣ U+0222 instead of having a different top counter.
## Letter small cap R

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif: Rꭆ U+0052 U+AB46
![screen shot 2015-09-06 at 10 40 48](https://cloud.githubusercontent.com/assets/1923747/9703720/d532b74a-5483-11e5-90a5-335085da6120.png)

In Arimo and Tinos:
- ꭆ U+AB46 should be a letter small capital instead of a letter capital.
## Letter small cap U

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif: Uᴜᵁ U+0055 U+1D1C U+1D41
![screen shot 2015-09-06 at 10 43 18](https://cloud.githubusercontent.com/assets/1923747/9703729/2793f760-5484-11e5-9a64-7f110c8dc1c9.png)

In Arimo and Cousine:
- ᴜ U+1D1C should be based on U U+0055 instead of being a composite of ʋ U+028B.
## Letter small cap V and W

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif: VvᴠⱽWwᴡ U+0056 U+0076 U+1D20 U+2C7D U+0057 U+0077 U+1D21
![screen shot 2015-09-06 at 10 51 20](https://cloud.githubusercontent.com/assets/1923747/9703754/3ecdb366-5485-11e5-8a0e-97db688ee3a2.png)

In Arimo, Cousine, Notos Sans:
- Letter small capitals ᴠᴡ U+1D20 U+1D21 are not distinct from vw U+0076 U+0077. UPA uses them in italic, maybe have stylistic alternates for italic vw U+0076 U+0077 for UPA that are curved as in Noto Serif or that have both left and right diagonal stems curved.

In Tinos:
- Letter small capitals ᴠᴡ U+1D20 U+1D21 should be based on VW U+0056 U+0057 instead of being composites for vw U+0076 U+0077.
## Letter small cap Ʒ

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif: Ʒᴣ U+01B7 U+1D23
![screen shot 2015-09-06 at 10 55 11](https://cloud.githubusercontent.com/assets/1923747/9703775/d16355aa-5485-11e5-9359-91c1c4d55bd4.png)

In Tinos:
- ᴣ U+1D23 should have a bottom serif like Ʒ U+01B7.

**Comment by roozbehp** [comment]
Confirming the bug.

**Comment by jungshik** [comment]
Any take on this issue, @SteveMatteson @TrueTyper @waksmonskiMT 

This affects Noto Sans/Serif and Arimo/Cousine/Tinos.

**Comment by marekjez86** [comment]
per @moyogo 👍 

Since I created bug https://github.com/googlei18n/noto-fonts/issues/678 to track Tinos issues, I'm removing the ArimoTinosCousine label here.

From now on this bug ONLY covers Noto Serif and Noto Sans.

**Comment by marekjez86** [comment]
@moyogo : could you look at the above and offer an opinion?

**Comment by marekjez86** [comment]
created a bug for roboto https://github.com/google/roboto/issues/225
