### ISSUE TITLE
Latin turned letters g, insular g, r-tail, t, and delta design issues

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#507]
The Latin lowercase turned letters usually have what was at x-height turned at baseline (or what was at the baseline at the x-height depending on how you look at it). For example h and ɥ, f and ɟ (although sometimes designed as dotless j with stroke but the rule still applies), k and ʞ, y and ʎ. This should also apply to g and ᵷ, ɽ and ⱹ, t and ʇ. For uppercase the current trend is to have the cap-height turned to the baseline, but baseline to x-height was also used before (by the American Board of Ethnology for example).

Turned g ᵷ is used in some book for transliterating Georgian letter turned gan ჹ, turned t ʇ was used in IPA and in James Owen Dorsey’s transcription of American languages, turned insular g ꝿ was used in transcription of old welsh and old cornish, turned r-tail ⱹ is used in Nordic language transcription, turned delta ƍ was used in IPA.

See ᵷ in figure 8 of http://std.dkuug.dk/JTC1/sc2/wg2/docs/n2608r2.pdf taken from Magometov 1965, aligned with the baseline of къ.
![screen shot 2015-09-06 at 14 08 47](https://cloud.githubusercontent.com/assets/1923747/9704491/d9844120-54a0-11e5-8987-3549fad06eb1.png)

See ꝿ in figure 5 in http://std.dkuug.dk/jtc1/sc2/wg2/docs/n3122.pdf taken from Pryce 1790.
![screen shot 2015-09-06 at 14 18 56](https://cloud.githubusercontent.com/assets/1923747/9704522/41f504b4-54a2-11e5-9055-777d6eb8ec97.png)

See ⱹ in figure 3 in http://www.unicode.org/L2/L2006/06036-lma-proposal.pdf from Slotte et al. 2000.
![screen shot 2015-09-06 at 14 33 51](https://cloud.githubusercontent.com/assets/1923747/9704633/f816b9c0-54a4-11e5-9fc9-9cf2528a5b7e.png)

See t in figures 1 and 2 in http://www.unicode.org/L2/L2012/12270-n4297-beta-etc.pdf taken from publications of the American Board of Ethnology.
![screen shot 2015-09-06 at 14 16 33](https://cloud.githubusercontent.com/assets/1923747/9704517/ed9134ce-54a1-11e5-9e69-68e29aeaf721.png)

See ƍ in J. C. W. (1976), “The Association’s Alphabet”, _Journal of the International Phonetic Association_, 6, pp 2-3 doi:10.1017/S0025100300001420
![screen shot 2015-09-06 at 15 07 49](https://cloud.githubusercontent.com/assets/1923747/9704750/32994384-54a9-11e5-9a64-10d04308965e.png)

See Arimo, Cousine, Tinos, Noto Sans, Noto Serif in roman and italic: gᵷᵹꝿɽⱹtʇƍ U+0067 U+1D77 U+1D79 U+A77F U+027D U+2C79 U+0074 U+0287 U+018D
![screen shot 2015-09-06 at 14 57 46](https://cloud.githubusercontent.com/assets/1923747/9704727/a0172f9e-54a8-11e5-8f29-7d7856f825f1.png)

In Arimo, Tinos :
- ᵷꝿⱹ U+1D77 U+A77F U+2C79  should have their bottom aligned to the baseline
- ʇ U+0287 should have the bottom of its ~~vertical~~ [horizontal] bar on the baseline
- ƍ U+018D is alright

In Cousine:
- ᵷꝿ U+1D77 U+A77F U+2C79  should have their bottom aligned to the baseline
- ⱹ U+2C79 is missing
- ʇ U+0287 should have the bottom of its ~~vertical~~ [horizontal] bar on the baseline
- ƍ U+018D is alright

In Noto Sans:
- ᵷ U+1D77  should have its bottom aligned to the baseline
- ⱹ U+2C79 is missing
- ʇ U+0287 ~~is alright~~ [should have the bottom of its horizontal bar on the baseline]
- ꝿ U+A77F is missing
- ƍ U+018D should have its top aligned to the x-height

In Noto Serif:
- ᵷ U+1D77 should have its bottom aligned to the baseline and it should be double storey like g U+0067
- ⱹ U+2C79 is missing
- ʇ U+0287 is alright
- ꝿ U+A77F is missing
- ƍ U+018D should have its top aligned to the x-height

**Comment by roozbehp** [comment]
Confirming the bug.

**Comment by SteveMatteson** [comment]
keep in mind Tinos and Arimo are to match Times and Arial - the 1D77 in Times and Arial descends so do we change it here? Horizontal metrics don't need to change so we can remain compatible.

**Comment by jungshik** [comment]
As long as horizontal metrics do not change, we'd better do the right thing.

**Comment by moyogo** [comment]
I updated the orginal comment regardin Arimo and Tinos, and Cousine:
- ʇ U+0287 should have the bottom of its ~~vertical~~ [horizontal] bar on the baseline

**Comment by moyogo** [comment]
I updated the original comment regarding Noto Sans:
- ʇ U+0287 ~~is alright~~ [should have the bottom of its horizontal bar on the baseline]

**Comment by TrueTyper** [comment]
I fear with some of these bugs that our latest data is not being tested. Noto Sans phase 3 delivery on June 23rd had the following, which looks correct to me:
![screen shot 2015-11-09 at 12 26 24 pm](https://cloud.githubusercontent.com/assets/8724881/11042546/5c9d7c98-86dd-11e5-8809-f35d67e2a511.png)

**Comment by SteveMatteson** [comment]
I assigned Jim to double check and look at this this morning because I thought he was done with the other edits mentioned a minute ago.

He's probably not the best to be working on these bugs because he's not good at telling me his status :-/ - but I have to keep feeding him work so it's a dilemma.



On Nov 9, 2015, at 11:28 AM, Tom Rickner <notifications@github.com<mailto:notifications@github.com>> wrote:


I fear with some of these bugs that our latest data is not being tested. Noto Sans phase 3 delivery on June 23rd had the following, which looks correct to me:
[screen shot 2015-11-09 at 12 26 24 pm]<https://cloud.githubusercontent.com/assets/8724881/11042546/5c9d7c98-86dd-11e5-8809-f35d67e2a511.png>

-

**Comment by moyogo** [comment]
@TrueTyper 
Based on the samples provided, this is what gᵷᵹꝿɽⱹtʇδƍ should look like:
![screen shot 2015-11-09 at 20 37 01](https://cloud.githubusercontent.com/assets/1923747/11045828/bfadadd2-8721-11e5-8ac7-55fee4872662.png)
Notice: gᵷᵹꝿ.

When turned, ascenders become descenders, descenders become ascenders, baseline becomes x-height, x-height becomes baseline.
Additionally ᵹ and ꝿ should not differ in shape: if ᵹ has an angle so should ꝿ.

**Comment by TrueTyper** [comment]
NotoSansUI-RomanMM.glyphs and NotoSerif-RomanMM.glyphs fixed in source.

**Comment by jungshik** [comment]
@KatMomoi : Please verify that this issue is fixed in Noto Sans and Noto Serif. 

Also, check the latest delivery of Arimo, Tinos and Cousine as well. 

Thanks

**Comment by marekjez86** [comment]
per @moyogo this doesn't happen in any of Arimo, Tinos not Cousine. Removing ArimoTinosCousine tag.

**Comment by TidharC** [comment]
Rebuilt Noto Sans fonts from source.

Alignment to baseline and x-height seems correct for Noto Sans UI and Noto Serif, incorrect for Noto Sans Display.

All 3 fonts now have glyphs for turned insular g (U+A77F) and turned r with tail (U+2C79).

The glyph for turned insular g looks like the wrong shape in Noto Sans Display.

![issue507](https://cloud.githubusercontent.com/assets/16353803/20323992/c4a8434c-ab33-11e6-8b1d-acd3c23a4550.png)

**Comment by TidharC** [comment]
Everything looks correct with one exception: in Noto Sans Display Italic, turned delta (U+018D) needs to be lower; the top should be level with the x-height line.

[specimenNotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/638197/specimenNotoSansDisplay-Italic.pdf)

Here are the renderings for the other fonts:

[specimenNotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/638202/specimenNotoSans-Black.pdf)
[specimenNotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/638199/specimenNotoSansDisplay-Black.pdf)
[specimenNotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/638200/specimenNotoSans-Italic.pdf)
[specimenNotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/638201/specimenNotoSansMono-Regular.pdf)
[specimenNotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/638203/specimenNotoSerif-Black.pdf)
[specimenNotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/638204/specimenNotoSerifDisplay-Black.pdf)
[specimenNotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/638206/specimenNotoSerifDisplay-Italic.pdf)
[specimenNotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/638205/specimenNotoSerif-Italic.pdf)

**Comment by moyogo** [comment]
LGTM

**Comment by marekjez86** [comment]
MTI comment: "fix A77F to be like 1D79 and fix alignments"
