### ISSUE TITLE
IPA modifier letters half ring, tack, plus and minus sign design issues

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#508]
IPA has a few modifier letters as alternative to combining diacritics below, they are meant to be centered between the x-height and the baseline.

In the _Principles of the International Phonetic Association_ 1949, the combining diacritics below are pretty large and the modifier letters have the same size.
![screen shot 2015-09-06 at 20 57 30](https://cloud.githubusercontent.com/assets/1923747/9706341/f1b23fac-54d9-11e5-9cb9-b2b59be461da.png)
![screen shot 2015-09-06 at 20 55 31](https://cloud.githubusercontent.com/assets/1923747/9706335/c424c028-54d9-11e5-98f2-4a7bd0071ab1.png)
![screen shot 2015-09-06 at 20 55 51](https://cloud.githubusercontent.com/assets/1923747/9706337/c742548c-54d9-11e5-9d3e-a6ea62c14f00.png)
![screen shot 2015-09-06 at 20 56 05](https://cloud.githubusercontent.com/assets/1923747/9706338/c9fde4fc-54d9-11e5-88dd-ea241acf3dcc.png)
![screen shot 2015-09-06 at 20 56 19](https://cloud.githubusercontent.com/assets/1923747/9706339/ccfd742e-54d9-11e5-8542-b9cbc7b8a0be.png)

In the _Hanbook of the International Phonetic Association_, 1999 the combining diacritics are not as large and the modifier letters are larger than the diacritics.
![screen shot 2015-09-06 at 20 52 47](https://cloud.githubusercontent.com/assets/1923747/9706343/01b767f6-54da-11e5-8ca9-cf9d823beae6.png)

Here’s Arimo, Cousine, Tinos, Noto Sans, Noto Serif: ˒˓˔˕˖˗ U+02D2 U+02D3 U+02D4 U+02D5 U+02D6 U+02D7 with ‘ho’ for context.
![screen shot 2015-09-06 at 20 37 43](https://cloud.githubusercontent.com/assets/1923747/9706244/f232eca8-54d7-11e5-8150-4c9cbf43141d.png)

Noto Sans and Noto Serif ˔˕˖˗ U+02D4 U+02D5 U+02D6 U+02D7 being below the baseline is particularly problematic.
In pretty much all 5 typefaces ˒˓˔˕˖˗ should be slightly bigger, ˔˕˖˗ should have more similar proportions. 

Modifier letter minus U+02D7 is also use in orthography of Côte d’Ivoire languages along with so it should never be too close to hyphen-minus U+002D. U+02D7 can have vertical crossbars in IPA, the form without crossbars seems to be the preferred shape in Côte d’Ivoire languages.

**Comment by roozbehp** [comment]
Confirming the bug.

**Comment by jungshik** [comment]
@marekjez86 will create a separate bug for Arimo/Tinos/Cousine.

**Comment by marekjez86** [comment]
per @moyogo this doesn't happen in any of Arimo, Tinos not Cousine. Removing ArimoTinosCousine tag.

**Comment by marekjez86** [comment]
MTI comment: "Add side bearings to overly tight forms. Make these consistently aligned. Remove vertical crossbars on minus sign in Sans designs."

**Comment by marekjez86** [comment]
test case
```html
<html lang="en-phonipa">
<p><span style="font-size:36.0px">ho˒ho˓ho˔ho˕ho˖ho˗ho</span></p>
</html>
```

en-508-Roboto-Regular
![en-508-roboto-regular](https://cloud.githubusercontent.com/assets/13322623/21594164/30e10f24-d0d4-11e6-8755-3e9c77888eb6.jpeg)
en-508-NotoSans-Italic
![en-508-notosans-italic](https://cloud.githubusercontent.com/assets/13322623/21594187/780b4298-d0d4-11e6-819e-c1f4a4d9f43b.jpeg)
en-508-NotoSans-Regular
![en-508-notosans-regular](https://cloud.githubusercontent.com/assets/13322623/21594227/f2e282c4-d0d4-11e6-8f6a-326425e10b17.jpeg)
en-508-NotoSansMono-Regular
![en-508-notosansmono-regular](https://cloud.githubusercontent.com/assets/13322623/21594244/29a3aed2-d0d5-11e6-969a-e454513b21ff.jpeg)
en-508-NotoSerif-Regular
![en-508-notoserif-regular](https://cloud.githubusercontent.com/assets/13322623/21594258/5f159df0-d0d5-11e6-8761-2d41759b7ce8.jpeg)


complete test results
[en-508-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/681220/en-508-Roboto-Regular.pdf)
[en-508-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/681223/en-508-NotoSans-Black.pdf)
[en-508-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/681224/en-508-NotoSans-Italic.pdf)
[en-508-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/681221/en-508-NotoSans-Regular.pdf)
[en-508-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/681225/en-508-NotoSansDisplay-Black.pdf)
[en-508-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/681222/en-508-NotoSansDisplay-Italic.pdf)
[en-508-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/681231/en-508-NotoSansDisplay-Regular.pdf)
[en-508-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/681226/en-508-NotoSansMono-Black.pdf)
[en-508-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/681227/en-508-NotoSansMono-Regular.pdf)
[en-508-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/681229/en-508-NotoSerif-Black.pdf)
[en-508-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/681228/en-508-NotoSerif-Italic.pdf)
[en-508-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/681230/en-508-NotoSerif-Regular.pdf)
[en-508-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/681233/en-508-NotoSerifDisplay-Black.pdf)
[en-508-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/681232/en-508-NotoSerifDisplay-Italic.pdf)
[en-508-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/681234/en-508-NotoSerifDisplay-Regular.pdf)
[en-508-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/681236/en-508-Roboto-Black.pdf)
[en-508-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/681235/en-508-Roboto-Italic.pdf)

**Comment by marekjez86** [comment]
@moyogo : please check the images and offer your opinion. thank you

**Comment by moyogo** [comment]
@marekjez86 LGTM
