### ISSUE TITLE
Latin modifier letter l with palatal hook 1DAA wrong in Noto Sans

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#511]
ᶪ 1DAA is wrong in Noto Sans, it should be a superscript ᶅ 1D85 with the palatal hook attached to the bottom-right of the stem, not to its center.

See with Noto Sans, Noto Serif: ᶅᶪ 1D85 1DAA
![screen shot 2015-09-09 at 00 08 16](https://cloud.githubusercontent.com/assets/1923747/9749687/5446a708-5687-11e5-8a14-87b7b4e67e9d.png)

**Comment by TidharC** [comment]
@moyogo, 
Here are the current Noto Sans renderings.  Please advise if these look correct.

[specimenNotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/626170/specimenNotoSans-Black.pdf)
[specimenNotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/626171/specimenNotoSansDisplay-Black.pdf)
[specimenNotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/626169/specimenNotoSansDisplay-Italic.pdf)
[specimenNotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/626168/specimenNotoSans-Italic.pdf)
[specimenNotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/626167/specimenNotoSansMono-Regular.pdf)

**Comment by moyogo** [comment]
LGTM
