### ISSUE TITLE
Which font editor are you guys using to edit Urdu NotoNastaliq font?

### ISSUE THREAD

**Issue by baig** [googlei18n/noto-fonts#514]

**Comment by dougfelt** [comment]
To create the design?  That's probably a question for @kmansourMT .

**Comment by kmansourMT** [comment]
Doug, the outlines were originally designed in FontLab Studio then converted to TrueType format. Afterwards, the outlines were passed through an outline-cleanup process. Additional work was done in FontDame, a Monotype in-house application.
