### ISSUE TITLE
Noto Sans Myanmar glyph adjustment for Sgaw Karen

### ISSUE THREAD

**Issue by HaDavids** [googlei18n/noto-fonts#516]
In the Noto Sans Myanmar font (latest version) the DOT below U+1037 is positioned behind the CHA U+1061 character. The correct position is on the left so that the DOT does not collide with the base character. This is for the Sgaw Karen language. Our translators in Myanmar would like to request this change. If approved and changed please let us know so that we can use the updated font.
![cha and dot below](https://cloud.githubusercontent.com/assets/14258071/9877267/b88b8806-5bb3-11e5-991c-3fbf0adc4c2c.jpg)

**Comment by tiroj** [comment]
Yes, this is a clear bug.

**Comment by jungshik** [comment]
@kmansourMT  : would you take it?

**Comment by kmansourMT** [comment]
Yes, I will.

**Comment by kmansourMT** [comment]
I've tested the text string (u1061+u1037) in Windows 8 and got the following result under MS Word for both NotoSansMyanmar and MyanmarText:
![screen shot 2015-10-07 at 14 46 46](https://cloud.githubusercontent.com/assets/12738181/10352158/46e61b5c-6d02-11e5-9124-87b5b344a262.png)

In addition, I ran the string through HarfBuzz and got the same result. HB indicates that the selected glyphs are "sha_skn & dot_below_spacing", which the image corrobates.

I suspect that the test was run in an environment that doesn't fully support Myanmar script. Does this environment enable the user to select a Karen-language locale?

**Comment by tiroj** [comment]
As I recall, we (Tiro/Microsoft) also got a bug report about this combination on the Myanmar Text font, which I passed on to Andrew Glass, who did the VOLT programming on that font. I believe the intention is to revise the mark positioning so that ring sits to the left of the descending stems, but have not confirmed this with Andrew.

So there are two issues here: the colliding positioning shown in the original post, which is clearly an error, but may be due to other software limitation rather than to a bug in the font; and the correct position of the ring relative to the descending stems, left or right.

**Comment by HaDavids** [comment]
Thank you for looking into this. To answer the question above we have used Windows 10 for this test and the Burmese locale since there is no Karen Windows locale as far as we know. We used Word 2010 on Windows 10. We get the colliding problem both with Myanmar Text and Noto Sans Myanmar fonts and not on the left side. Hope that helps. If there is something else we can do please let us know. This character is used by both Pwo and Sgaw Karen.

**Comment by HaDavids** [comment]
Sorry I closed by mistake.

**Comment by tiroj** [comment]
> We used Word 2010 on Windows 10.

Note that Office apps may use a different version of the Uniscribe shaping engine than the one in the operating system, so to test the Windows 10 shaping you should try NotePad or Wordpad. NotePad gives you the most direct representation of what the font lookups are doing, without potential interference from other text handling resources such as RichEdit, but Wordpad is pretty reliable and more flexible.

**Comment by HaDavids** [comment]
I tested the combination with Notepad on Windows 10 platform and both Myanmar Text and Noto Sans Myanmar display the combination without colliding to the right. That shows that as you said that the font lookups are ok but on the wrong side. If you agree though if you could position the dot on the left side would be great, on both fonts please. Then both Sgaw and Pwo Karen will be using this combination correctly. Let us know if there is anything else we can help with. If corrected our translators in Myanmar can then use both these fonts. Our goal is that all the six Myanmar based languages that we work with so far have some solid good looking fonts. Then we can also use the Noto Sans Myanmar font in our electronic publications.

**Comment by kmansourMT** [comment]
In a Karen setting, would we apply the same rules to Ra (u+101B) as for Sha (u+1061)?
/cc @HaDavids @tiroj

**Comment by HaDavids** [comment]
Hi.
Thanks for asking. If we understand your question correctly then yes the same rule will apply to SHA U+1061 also.
The following information does not apply to U+1061 but might be helpful.
As a general rule for the Karen languages the Dot Below U+1037 is a vowel sign, not a tonal mark. As such, it will always position to the left of the consonants. This means that for the Myanmar language RA U+101B and Dot Below U+1037 positions the Dot Below to the right side of the RA. However, for the Karen languages it will be positioned to the left e.g. underneath the round part of the RA.
Another example, for the Myanmar language the consonant (any consonant) and Medial HA (U+103E) or WA (U+103D) combined with the Dot Below (U+1037) will position the Dot Below to the right of the conjunct. However, for the Karen languages the Dot Below will be positioned to the left of the conjuncts.
Yet another example for the Myanmar language the RA (U+101B) and AA (U+102C) combined with the Asat (U+103A) forms a ligature shape where the AA now is attached to the RA. However, for the S’gaw Karen language the AA combined with the Asat is a tonal mark and as such should not form a ligature shape, e.g. it should be separate from the RA.
Possibly it might be better to make a separate font for the Karen languages such as the “Karen Text” since a different language ID is needed.
In a couple of weeks we plan to have all syllable combinations generated that Myanmar script languages (Myanmar, Pwo Karen, S’gaw Karen, Shan) are using. We can post them for you to check the Myanmar Noto font.
Thank you,
Håkan Davidsson

**Comment by HaDavids** [comment]
Hi. Thanks for asking. If we understand your question correctly then yes the same rule will apply to SHA U+1061 also.
The following information does not apply to U+1061 but might be helpful.
As a general rule for the Karen languages the Dot Below U+1037 is a vowel sign, not a tonal mark. As such, it will always position to the left of the consonants. This means that for the Myanmar language RA U+101B and Dot Below U+1037 positions the Dot Below to the right side of the RA. However, for the Karen languages it will be positioned to the left e.g. underneath the round part of the RA. 
Another example, for the Myanmar language the consonant (any consonant) and Medial HA (U+103E) or WA (U+103D) combined with the Dot Below (U+1037) will position the Dot Below to the right of the conjunct. However, for the Karen languages the Dot Below will be positioned to the left of the conjuncts.
Yet another example for the Myanmar language the RA (U+101B) and AA (U+102C) combined with the Asat (U+103A) forms a ligature shape where the AA now is attached to the RA. However, for the S’gaw Karen language the AA combined with the Asat is a tonal mark and as such should not form a ligature shape, e.g. it should be separate from the RA.
Possibly it might be better to make a separate font for the Karen languages such as the “Karen Text” since a different language ID is needed.
In a couple of weeks we plan to have all syllable combinations generated that Myanmar script languages (Myanmar, Pwo Karen, S’gaw Karen, Shan) are using. We can post them for you to check the Myanmar Noto font.

**Comment by kmansourMT** [comment]
@HaDavids Thank you for the details.
Since you've mentioned that Dot Below acts as a vowel in Karen languages, would it be correct to assume that it cannot occur in combination with the U vowels (102F, 1030) as in:
![screen shot 2015-12-14 at 11 19 21](https://cloud.githubusercontent.com/assets/12738181/11791481/1f3a710a-a256-11e5-86f6-2202e8408473.png)
In a hypothetical combination as below, please confirm whether Dot Below needs to move to the left of the Wa-Ha:
![screen shot 2015-12-14 at 11 20 05](https://cloud.githubusercontent.com/assets/12738181/11791753/596a0920-a257-11e5-93fc-1073d3dd677e.png)

**Comment by HaDavids** [comment]
Hi. Thanks for asking. Here is our reply.
See the comments in red below as well.
In addition to the points when Dot Below (U+1037) combines with RA and AA (Unicode order U+101B, U+1037 and U+102C) the Dot Below positions under the RA, not the AA part, like this:
[cid:image005.png@01D13711.7B7FCD80]
When the Dot Below combines with the HA Medial (U+103E) or WA Medial (103D) it positions to the left of the conjuncts, like this:
[cid:image006.png@01D13711.8124A850]
Another important consideration to mention is different from the Myanmar language is that Visarga (U+1038) and the AA with Asat (U+102C with U+103A) are Tonal Marks for the Karen languages. This will means that these will follow vowel signs too, where in the Myanmar language the combinations would be invalid. This is an example:
[cid:image002.png@01D13713.10BEEFB0][cid:image001.png@01D13710.F5EBC9D0]
Also, for the Karen languages when AA with Asat (U+102C with U+103A) combines with the RA (U+101B) it will separate from the RA, e.g. it will not form a ligature:
[cid:image004.png@01D13710.F5EBC9D0]

**Comment by HaDavids** [comment]
Hi. Thanks for asking. Here is our reply. See the comments in below as well.
In addition to the points when Dot Below (U+1037) combines with RA and AA (Unicode order U+101B, U+1037 and U+102C) the Dot Below positions under the RA, not the AA part, like this:
 ![image1](https://cloud.githubusercontent.com/assets/14258071/11805935/8cb6a5e4-a307-11e5-8cdf-027a548c2a1e.jpg)

When the Dot Below combines with the HA Medial (U+103E) or WA Medial (103D) it positions to the left of the conjuncts, like this:
 ![image2](https://cloud.githubusercontent.com/assets/14258071/11805945/9934c0d0-a307-11e5-9214-94f6ee097c01.jpg)

Another important consideration to mention is different from the Myanmar language is that Visarga (U+1038) and the AA with Asat (U+102C with U+103A) are Tonal Marks for the Karen languages. This will means that these will follow vowel signs too, where in the Myanmar language the combinations would be invalid. This is an example:
![image3](https://cloud.githubusercontent.com/assets/14258071/11805954/a9d6afe8-a307-11e5-958e-b17f5a954840.jpg)
![image4](https://cloud.githubusercontent.com/assets/14258071/11805958/ad75a99c-a307-11e5-8ac9-649a3071a3b7.jpg)
  
Also, for the Karen languages when AA with Asat (U+102C with U+103A) combines with the RA (U+101B) it will separate from the RA, e.g. it will not form a ligature:
 ![image5](https://cloud.githubusercontent.com/assets/14258071/11805970/bc1b514a-a307-11e5-907c-7882200a3758.jpg)

**Comment by kmansourMT** [comment]
In the upcoming release, the dot-below will appear as follows in the default locale:
![screen shot 2015-12-22 at 15 00 44](https://cloud.githubusercontent.com/assets/12738181/11968049/157aa712-a8bd-11e5-9623-a288f708a268.png)

...and as follows in Karen locale
![screen shot 2015-12-22 at 15 00 54](https://cloud.githubusercontent.com/assets/12738181/11968056/24d17dc6-a8bd-11e5-9abc-ec5aa9a030b4.png)

**Comment by HaDavids** [comment]
Thanks for confirming. Yes, that is correct.

**Comment by taylorcanning** [comment]
Hi, I hope this is still open- I have had some issues with my S'Gaw Karen characters displaying properly on Windows 10 (pc & mobile), with 'ha thee'/ high tone, I don't know how to tell you what the unicode name of the characters are, but they look like this ၣ် ၣ  they aren't joining properly. Know how I can rectify this? Thanks so much

**Comment by kmansourMT** [comment]
@taylorcanning Please provide the text string of S'Gaw Karen characters that you're finding troublesome.

**Comment by marekjez86** [comment]
@taylorcanning: would you be able to add here the text that caused the issues that you describe?

**Comment by marekjez86** [comment]
[NotoSansMyanmar-Regular-ksw.pdf](https://github.com/googlei18n/noto-fonts/files/421120/NotoSansMyanmar-Regular-ksw.pdf)

the original issue is fixed
