### ISSUE TITLE
Awkward letter spacing

### ISSUE THREAD

**Issue by mycroftxxx** [googlei18n/noto-fonts#518]
This is on Ubuntu 15.04, demoed in Libre Office.  If you zoom in on either image, you will clearly see there is subpixel antialiasing in effect.

In the first sample, notice the spacing of the letters in “awkward” appears different in different copies, and in all cases there is too much space between some pair of letters.  In the second sample, notice that the “k” and “w” are actually connected, but visually there is more space between the “w” and “k”.

In the third sample, you can see that the spacing around the “ffl” ligature is weird.  The same problem happens with “ffi”.  Also notice that “flu” and “re” in the first line don't look great, either.

![noto-10](https://cloud.githubusercontent.com/assets/1772872/10035716/99abf2fa-616b-11e5-9f72-05207d6957a7.png)
![noto-16](https://cloud.githubusercontent.com/assets/1772872/10035811/48168896-616c-11e5-9355-72703c669303.png)
![noto-16-ffl](https://cloud.githubusercontent.com/assets/1772872/10035940/fd45ff84-616d-11e5-9be3-9e235c334566.png)

**Comment by khaledhosny** [comment]
This is most likely a LibreOffice bug as it uses integer-based coordinate system and also tends to accumulate rounding errors, which would cause issues like this. Try to reproduce this in other applications (browsers would be a good choice) to rule out application issues.

**Comment by marekjez86** [comment]
@mycroftxxx please look at the text file and see if this reflects what you were testing.
If it does, copy the contents to test.html local file in your system and open it using 
1. a browser
2. libreoffice

I think @khaledhosny is right that this is a libreoffice problem and you will not see this problem under browser.

Thanks. Please let me know what you experience.

[test-noto-serif.txt](https://github.com/googlei18n/noto-fonts/files/8909/test-noto-serif.txt)

**Comment by marekjez86** [comment]
@mycroftxxx , I realized that my suggestion was too complex. You can just save your libreoffice file that you presented above as an html file and open it in the browser to see the results.

**Comment by marekjez86** [comment]
MTI comment: "Thi bug is not a font problem but it pointed out that the To, Wa and Aw kern pairs were missing as well as a f_f ligature. Add the kern pairs in Thin and add f_f liga."

**Comment by marekjez86** [comment]
test case
```html
html lang="en">
<p><span style="font-size:48.0px">Tom Waits Awkwardly.</span></p>
<p><span style="font-size:48.0px">Isn't that awkward? Awkward, awkward,</span></p>
<p><span style="font-size:48.0px">so awkward, and yet awkward too.</span></p>
<p><span style="font-size:48.0px">Tom Waits Awkwardly for five fluffy fireflies.</span></p>
<p><span style="font-size:48.0px">I'm baffled, baffled, baffled, baffled, baffled.</span></p>
</html>
```
used by https://github.com/googlei18n/fontdiff with the following fonts (against itself) show no problems.

[en-518-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683543/en-518-NotoSerifDisplay-Regular.pdf)
[en-518-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683544/en-518-Roboto-Black.pdf)
[en-518-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683547/en-518-Roboto-Italic.pdf)
[en-518-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683548/en-518-Roboto-Regular.pdf)
[en-518-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683546/en-518-NotoSans-Regular.pdf)
[en-518-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683545/en-518-NotoSansDisplay-Black.pdf)
[en-518-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683550/en-518-NotoSansDisplay-Italic.pdf)
[en-518-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683549/en-518-NotoSansDisplay-Regular.pdf)
[en-518-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683552/en-518-NotoSansMono-Black.pdf)
[en-518-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683551/en-518-NotoSansMono-Regular.pdf)
[en-518-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683554/en-518-NotoSerif-Black.pdf)
[en-518-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683553/en-518-NotoSerif-Italic.pdf)
[en-518-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683555/en-518-NotoSerif-Regular.pdf)
[en-518-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683559/en-518-NotoSerifDisplay-Black.pdf)
[en-518-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683557/en-518-NotoSerifDisplay-Italic.pdf)
[en-518-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683558/en-518-NotoSans-Black.pdf)
[en-518-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683556/en-518-NotoSans-Italic.pdf)
