### ISSUE TITLE
Lao and Khmer : remove spurious script (Latn) and features/langsys  ('zzdd's from VOLT) 

### ISSUE THREAD

**Issue by lemzwerg** [googlei18n/noto-fonts#520]
[commit abed4e560220062e1a0a1dd5623cf1922acbc639]

The fonts `unhinted/NotoSansLao*-Bold.ttf` contain identical GSUB features for both the `lao` and the `latn` script.  The latter is incorrect and should be completely removed – in particular, it prevents correct auto-hinting with `ttfautohint`.

**Comment by marekjez86** [comment]
@dougfelt , I don't know who owns the delivery of GSUB. If we do, then please help me by re-assigning it to the right person. If we do not, please reassign it to @waksmonskiMT 

thanks

**Comment by jungshik** [comment]
@marekjez86 Lao and Khmer fonts (in phase 2) were not made by MTI. They're made by Danh Hong. 

We have to fix these issues ourselves.

**Comment by jungshik** [comment]
hinted/NotoSansLaoUI-Bold.ttf is also interesting. Its GSUB table is different from that of unhinted version:

1. It only has 3 FeatureRecords instead of 14 as found in the unhinted version
2. Under both 'lao ' and 'latn' scripts, it does not have 'langsys record for 'zz01' that invokes 11 features missing in hinted version. 

What is 'zz01' langsys, btw?

**Comment by lemzwerg** [comment]
I've written directly to Danh in another mail.  Hopefully, he can comment.  For obvious reasons, *I* only look at the unhinted fonts :-)

**Comment by jungshik** [comment]
@tiroj : Do you know what 'zz01' (langsys) is for? I've found quite a lot of fonts with 'zz01' langsys (e.g. virtually all the Uighur fonts listed at http://www.wazu.jp/gallery/Fonts_Uighur2.html have that in addition to DFLT).  Is it kinda 'private' langsys?

**Comment by jungshik** [comment]
Hmm... NotoSansKhmer has a similar difference between hinted and unhinted versions. Unhinted has 20 extra feature records that are referred to only in 'langsys zz01' . Hinted does not have those feature records nor 'langsys zz01'.

**Comment by jungshik** [comment]
And, all those feature records (referred to only for langsys 'zz01') have a featuretag starting with 'zz'. 

@behdad, could you enlighten me on this? What does harfbuzz do with those features and langsys?

**Comment by jungshik** [comment]
As expected, zzdd is certainly not in the feature tag registry ( https://www.microsoft.com/typography/otspec/featurelist.htm ). And, according to https://www.microsoft.com/typography/otspec/featuretags.htm, a private feature tag should be made of 4 capital letters (A-Z) with no space (e.g.  'PRKN'. )

**Comment by tiroj** [comment]
Tags that begin 'zz-' indicate the presence of a VOLT source project table in the font. When the font is 'shipped' from VOLT, this table and these features are stripped and only the compiled GSUB, GPOS and GDEF tables remain.

**Comment by moyogo** [comment]
The zzdd tags are used by the VOLT proofing tool: each langsys is assigned a zzdd tag, each lookup is assigned a zzdd tag and can be enabled, in order, to test what each lookup does given a sequence of glyphs.

**Comment by jungshik** [comment]
Thank you, @tiroj and @moyogo !! 

It also occurred to me that zzdd's are from VOLT. To make absolutely sure, (*before* I saw your replies), I shaped 1,000 messages in Lao (extracted from Google's translation db)  with hinted and unhinted fonts (font with zz* and without zz*) with hb-view and there's absolutely no difference as expected. I'll get rid of zz* as well.

**Comment by jungshik** [comment]
Removing zzdd features and langsys worked fine in the sense that there's no shaping change when applied to 5000+ strings I extracted from translation DB. 

However, when I took out 'latn', there's a change in shaping in Lao when the input text has a Latin that is not covered by the font in question. In practice, this font (NotoSansLaoUI-Bold) will not be used for Latin (it does NOT cover Latin). So, this is kinda a non-issue.  

Nonetheless, it's interesting to see what's going on.  The minimum test string to trigger is "U ຕ້". 

With "latn" present, I got this:

![lao strings 45 min 2u_v1](https://cloud.githubusercontent.com/assets/8578343/10738794/54bda816-7bd6-11e5-9692-b25e69a7f2c8.png)

With "latn" removed, I got this (note the misplacement of U+0EC9).

![lao strings 45 min 2u_v2](https://cloud.githubusercontent.com/assets/8578343/10738809/5f420f2a-7bd6-11e5-814f-087d013b8b18.png)


NotoSansLaoUI-Bold with 'latn' present and without 'latn' are available (both of them do not have zzdd features and langsys any more) at 

http://jungshik.github.io/noto/NotoSansLaoUI-Bold.v1fix.ttf 
http://jungshik.github.io/noto/NotoSansLaoUI-Bold.no_latn.ttf

**Comment by jungshik** [comment]
BTW, the above images were generated with hb-view in harfbuzz 1.0.6. I also tried 5c8174eda (ToT as of now) and there's no difference from 1.0.6

**Comment by jungshik** [comment]
Talked to @behdad : the above issue is just an artifact of passing a font without Latin coverage to hb-view (that can take only one font).  I'll just go ahead with removing 'latn' from Lao.

**Comment by jungshik** [comment]
For the record, subset options I used to drop zzdd features/langsys are:

```--glyphs=* --name-IDs=* --notdef-outline --drop-tables= --no-subset-tables+=morx --glyph-names```

and ```--layout-features-=zz01,zz02,zz03,zz04....zz25```
