### ISSUE TITLE
IPA: under tie U+203F is missing

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#526]
UNDERTIE U+203F ‿ is used in IPA but is missing from Noto Sans and Noto Serif which intend to cover IPA.

In the 1999 IPA Handbook, page 23, the example has U+203F erroneously printed as COMBINING DOUBLE BREVE BELOW U+035C: [pətit͜ami].

> ‿ Fr. _petit ami_ [pətit‿ami] ‘boyfriend’

U+035C is an alternate of COMBINING DOUBLE INVERTED BREVE U+0361, used to indicate affricate and double articulation. See 1999 IPA Handbook, page 22:

> k͡p, t͡ʃ etc. Eng. _chief_ [t͡ʃif]; Yoruba _apa_ [ak͡pá] ‘arm’; Tswana _tsetse_ [t͜sét͜sé] ‘tsetse fly’
> Note: the tie bar can be placed above the symbols to be linked.

On page 174, the UCS code 203F is given for Linking (absence of a break), symbol 509:

> ‿   Bottom tie bar  Linking (absence of a break)    ˌfɑːɹ‿əˈweɪ    509 203F    230F

See U+203F in various IPA references:
- https://linguistlist.org/unicode/ipa.html
- ~~http://www.phon.ucl.ac.uk/home/wells/ipa-unicode.htm~~
- http://www.linguiste.org/chart.html
- https://westonruter.github.io/ipa-chart/keyboard/

**Comment by roozbehp** [comment]
Confirming that the character is needed in the LGC fonts.

**Comment by jungshik** [comment]
Giving to @SteveMatteson

**Comment by SteveMatteson** [comment]
I've confirmed an outline for 203F is in all 8 masters of LGC Noto Sans and is encoded correctly

**Comment by jungshik** [comment]
Sans serif (p3) has it, but serif (the latest ttf) still does not have U+203F, yet.

**Comment by marekjez86** [comment]
NotoSerif-Roman_20151222 glyphs file, delivered to us by MTI on 2015.12.22

Here's the dump by ttx from NotoSerif-Regular.otf created by the pipeline.

![from-notoserif-regular-ttx](https://cloud.githubusercontent.com/assets/13322623/13341979/1a45d466-dbf2-11e5-8613-ded26b5dff0f.jpg)

**Comment by marekjez86** [comment]
closing the bug

**Comment by moyogo** [comment]
:+1:

**Comment by marekjez86** [comment]
I closed it too early: while the current sources have undertie, I need to wait with bug closing until we deliver the fonts. Sorry.

**Comment by marekjez86** [comment]
@xiangyexiao : another bug fixed in PIII but not in PII

**Comment by TrueTyper** [comment]
@marekjez86 u+203F was never in the character set list for phase 2. So this is not a bug, rather it is a feature request, delivered in phase 3. This should be closed.

**Comment by marekjez86** [comment]
203F is in the following sources

NotoSans-ItalicMM.glyphs:unicode = 203F;
NotoSans-MM.glyphs:unicode = 203F;
NotoSansDisplay-ItalicMM.glyphs:unicode = 203F;
NotoSansDisplay-MM.glyphs:unicode = 203F;
NotoSansMono-MM.glyphs:unicode = 203F;
NotoSerif-ItalicMM.glyphs:unicode = 203F;
NotoSerif-MM.glyphs:unicode = 203F;
NotoSerifDisplay-ItalicMM.glyphs:unicode = 203F;
NotoSerifDisplay-MM.glyphs:unicode = 203F;

**Comment by moyogo** [comment]
@marekjez86 it’s non-spacing in Noto Serif * when it should be spacing like in the other fonts. I guess that’s a new bug.

**Comment by marekjez86** [comment]
Oh OK. @moyogo : Will you create a new bug or should I?

**Comment by moyogo** [comment]
@marekjez86 go ahead.
