### ISSUE TITLE
Musical symbol OpenType issue with Harfbuzz

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-fonts#530]
Kamal mentioned Harfbuzz and musical symbol doesn't work together on certain OpenType things, which I don't know detail. So, file this general/placeholder bug to track the issue.

@behdad, @jungshik, @dougfelt, @kmansourMT

**Comment by behdad** [comment]
I talked to Kamal about this today; looks like there's nothing actionable on our side for this right now.
