### ISSUE TITLE
U+03C6 (phi) appears with a loop in Noto Sans but with a stroke in Noto Serif

### ISSUE THREAD

**Issue by roozbehp** [googlei18n/noto-fonts#533]
I don't think this is an intentional design decision, but an accident. @SteveMatteson can correct us if it is, and explain why (see also https://github.com/googlei18n/noto-fonts/issues/512).

See Noto Sans and Noto Serif with φϕ φ 03C6 03D5
![screen shot 2015-09-09 at 08 38 33](https://cloud.githubusercontent.com/assets/1923747/9756034/cce7c29a-56ce-11e5-8dd7-7cd8fdda4652.png)

/cc @moyogo

**Comment by TrueTyper** [comment]
This has been fixed in source for NotoSerif-RomanMM.glyphs.

**Comment by xiangyexiao** [comment]
@dougfelt @jungshik @marekjez86 

This is similar to  #548. The wanted timeline by Android is April/May. We need to either get Phase III LGC fonts usable by Android, or update Phase II fonts with the new glyphs (available in Phase III fonts) by April/May.

**Comment by xiangyexiao** [comment]
@waksmonskiMT, we want it to be fixed in Phase II fonts by end of March. Let me know if it is infeasible.

**Comment by xiangyexiao** [comment]
@marekjez86 please pass TTF file converted from Phase 3 glyph to Jungshik, and Jungshik will add U+03C6 to Noto Serif for Phase II. 

@waksmonskiMT, you don't need to do anything for Phase 2.

**Comment by marekjez86** [comment]
passed the font file to @jungshik
