### ISSUE TITLE
Tamil: Character சூ wrongly rendered

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-fonts#538]
<img width="265" alt="screen shot 2015-10-27 at 10 56 04 am" src="https://cloud.githubusercontent.com/assets/12721521/10767443/60c23802-7c99-11e5-9888-edcec7c2cfc7.png">

**Comment by JelleBosmaMT** [comment]
I have a substantial collection of Tamil fonts. Few of them have the "correct" form. Almost all of them have the "wrong" form. Foundries that offer Tamil fonts on the Web have the "wrong" form. My Tamil Language guide has the "wrong" form. The World's Writing Systems book shows the "wrong" form and other literature shows the "wrong" form too. Old Monotype and old Linotype fonts use the "wrong" form. Even table 12-26 of the Unicode book shows the "wrong" form. 
It therefore seems reasonable to inquire by which criterion the most widely used form of the c-uu ligature is wrong and the rarely used alternative, is "correct".

**Comment by xiangyexiao** [comment]
this is a customer reported issue copied from Google's internal bug tracking system. Based on Jelle's reply, Noto glyph is just a style variance, if it is not the correct glyph. I will close the bug correspondingly.
