### ISSUE TITLE
Tifinagh font should not use script tag 'tfng'

### ISSUE THREAD

**Issue by dougfelt** [googlei18n/noto-fonts#539]
As with Lepcha, this script tag causes Harfbuzz to perform script-specific reorderings, but the font was designed assuming such reorderings don't take place.  The script tags should be 'DFLT' so that the text remains untransformed and the ligatures defined in the font apply as intended.

**Comment by kmansourMT** [comment]
The initial specs for the various fonts did not specify which script tags to include, nor what features each should offer. Monotype took the initiative to provide different composition paths through the default and the native scripts. Now that Harfbuzz has entered the picture, we need to define a general policy to guide the choice of script tags beyond the original specifications. For any script where such a policy should not be applied, there should be a clear description of which script tag(s) to include, as well as the specific behavior desired under each path.

**Comment by jungshik** [comment]
/cc @behdad 

> Monotype took the initiative to provide different composition paths through the default and 
> the native scripts.

@kmansourMT : Can you list all the scripts for which there are 'two composition paths' (default and native) in Noto?  

Then, we can compare the above list against the list of scripts that harfbuzz does script-specific renderings to come up with a list of scripts for which 'script tag' should be dropped with only 'DFLT' kept. 

How does it sound? Would it work?

**Comment by marekjez86** [comment]
adding Priority-Critical to make it consistent with https://github.com/googlei18n/noto-fonts/issues/543

**Comment by jungshik** [comment]
Afaict, Tifinagh shaping does not require any reordering. Combining mark support (GPOS; mark and mkmk) and ligature (ccmp in GSUB) are necessary. Just changing the script tag in GSUB/GPOS to DFLT is likely to work. (just leaving the font alone might work, too :-)).  Let me try to test.

**Comment by jungshik** [comment]
'DFLT' definitely works better with harfbuzz than 'tfng' for GSUB ccmp entries. All the ligature glyphs are picked up with 'DFLT'.  (there are 56 of them in GSUB). 

Let me check GPOS, too.

**Comment by jungshik** [comment]
With a limited test, GPOS works identically, DFLT or tfng.  So, we're good to switch to DFLT for Tfng. 

BTW, I filed #550 and #551 for separate issues.

**Comment by jungshik** [comment]
@dougfelt : FYI, 

The test file used to generate the screenshots in https://github.com/googlei18n/noto-fonts/issues/539#issuecomment-153925006

[test.gsub.nocomment.txt](https://github.com/googlei18n/noto-fonts/files/32453/test.gsub.nocomment.txt)

The same list of character sequences as the above but with Unicode codepoints listed :+1: 
[test.gsub.nocomment.txt](https://github.com/googlei18n/noto-fonts/files/32454/test.gsub.nocomment.txt)
