### ISSUE TITLE
Clean up opentype tables with multiple composition paths (DFLT and script-specific) leading to a conflict with harfbuzz

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#543]
I'm filing this bug as an umbrella bug for #539 (Tifnagh) , #451 (Lepcha) and potentially others. 

/cc @behdad 
/cc @dougfelt , @roozbehp @marekjez86 

@kmansourMT wrote in #539 

> Monotype took the initiative to provide different composition paths through the default and 
> the native scripts.

@kmansourMT : Can you list all the scripts for which there are 'two composition paths' (default and native) in Noto?  

Then, we can compare the above list against the list of scripts that harfbuzz does script-specific renderings to come up with a list of scripts for which 'script tag' should be dropped with only 'DFLT' kept. 

How does it sound? Would it work?

**Comment by jungshik** [comment]
This issue is blocking our internal bug ( b/25021494 ) and needs an immediate attention. 
@waksmonskiMT

**Comment by behdad** [comment]
I just looked through the fonts using my tools and I find these oddities:

in hinted/, Tibetan needs inspection:
```
NotoSansTibetan-Bold.ttf
    Script  0 of  3: DFLT
    Script  1 of  3: latn
    Script  2 of  3: tibt
    Script  0 of  1: tibt
NotoSansTibetan-Regular.ttf
    Script  0 of  3: DFLT
    Script  1 of  3: latn
    Script  2 of  3: tibt
    Script  0 of  1: tibt
```

Not sure why it has latn and DFLT.  For Adobe software?  Even then, the latn seems bogus.

For "unhinted/", report coming.

**Comment by behdad** [comment]
In unhinted/:

Tibetan fonts in unhinted/ have the same issue as the ones in hinted/.

TaiTham has only DFLT (good).

Lepcha has only DFLT in GSUB, bug DFLT and lepc in GPOS.  NEEDS FIX: remove lepc.

Tifinagh has DFLT in GSUB and tfng in GPOS.  NEEDS FIX: change tfng to DFLT and TEST.

The following have DFLT as well as some other thing:
NotoSansAvestan-Regular.ttf
NotoSansBalinese-Regular.ttf
NotoSansBamum-Regular.ttf
NotoSansBatak-Regular.ttf
NotoSansBrahmi-Regular.ttf
NotoSansBuginese-Regular.ttf
NotoSansBuhid-Regular.ttf
NotoSansCanadianAboriginal-Regular.ttf
NotoSansCherokee-Regular.ttf
NotoSansCoptic-Regular.ttf
NotoSansGothic-Regular.ttf
NotoSansHanunoo-Regular.ttf
NotoSansInscriptionalPahlavi-Regular.ttf
NotoSansInscriptionalParthian-Regular.ttf
NotoSansJavanese-Regular.ttf
NotoSansKaithi-Regular.ttf
NotoSansKayahLi-Regular.ttf
NotoSansKharoshthi-Regular.ttf
NotoSansLepcha-Regular.ttf
NotoSansLimbu-Regular.ttf
NotoSansMeeteiMayek-Regular.ttf
NotoSansMongolian-Regular.ttf
NotoSansNewTaiLue-Regular.ttf
NotoSansNKo-Regular.ttf
NotoSansPhagsPa-Regular.ttf
NotoSansRejang-Regular.ttf
NotoSansSamaritan-Regular.ttf
NotoSansSaurashtra-Regular.ttf
NotoSansSundanese-Regular.ttf
NotoSansSylotiNagri-Regular.ttf
NotoSansSyriacEastern-Regular.ttf
NotoSansSyriacEstrangela-Regular.ttf
NotoSansSyriacWestern-Regular.ttf
NotoSansTagalog-Regular.ttf
NotoSansTagbanwa-Regular.ttf
NotoSansTaiLe-Regular.ttf
NotoSansTaiViet-Regular.ttf

There are two groups of them, those that go through USE:
```
Balinese
Batak
Brahmi
Buginese
Buhid
Hanunoo
Kaithi
Kharoshthi
Lepcha
Limbu
MeeteiMayek
Rejang
Saurashtra
Sundanese
SylotiNagri
Tagalog
Tagbanwa
TaiLe
TaiViet
```

Javanese doesn't go through USE, but Indic shaper.  Needs manual inspection.  I really doubt that both DFLT and non-DFLT tables are tested and work.  I think DFLT needs to be removed.

For N'Ko, Mongolian, Phags Pa, and the three Syriac's:  I believe the DFLT should be removed.

New Tai Lue changed encoding model.  Need to remove non-DFLT and test / update for new encoding model.

For the rest, only DFLT should remain.  If DFLT and non-DFLT were equivalent, no retesting is required.

I believe this was a mistake on Monotype's side, and needs to be sent back for rework, even if we hotpatch them ourselves for scheduling reasons.

**Comment by jungshik** [comment]
Summarized below are open type tables in NotoSans{Script} fonts  harfbuzz routes to USE. 

1. Balinese
  - GPOS: Have both DFLT and bali. Their feature lists are different. 
  - GSUB:  DFLT uses two more look-ups (3, 4) than bali. Extra looksup in DFLT are likely to be for re-ordering and other 'pre-processing'. 
  - 'bali' is not likely to be USE-compatible so that we'd better remove bali.
  - Needs testing
2. Batak: 
  - GPOS : Have DFLT and batk. They refer to different features, but the look-up lists are identical in the corresponding pairs of features. So, DFLT and batk are identical. 
 - GSUB : Have DFLT and batk. Same as GPOS. they refer to different features and the look-up lists are identical. 
  - Assuming batk in the current font is not USE-compatible, shaping is likely to be improved. At least, it'd not be regressed by removing batk. I think we can just go ahead unless we hear from @kmansourMT or we verify that 'batk' is USE-compatible. 
3. Brahmi:
  - GPOS : DFLT and brah refer to different feature lists, but lookup lists are identical in the corresponding pair of features
  - GSUB: ditto 
  - Same conclusion as Batak
4. Buginese
  - GPOS/GSUB : same as Batak
  - Same conclusion as Batak
5. Buhid
  - Same as Batak
6. Hanunoo
  - Same as Batak
7. Kaithi
  - GPOS : same as Batak
  - GSUB: one feature (0 vs 1) out of 4  is different between two scripts. 
  - Needs testing
8. Kharoshthi
  - same as Batak
9. Lepcha
  - already fixed up in our repos
10. Limbu
  - same as Batak
11. MeeteiMayek
  - GPOS : DFLT and GPOS (two lang systems; default and MNI ) refer to different feature sets, but the corresponding triplets of features refer to the same set of lookups. 
  - GSUB: same as GPOS
  - What to do with "MNI" lang sys in 'mtei'
12. Rejang
  - GPOS: same as Batak
  - GSUB: 0 features in both scripts
13. Saurashtra
  - same as Batak
14. Sunanese
  - same as Batak
15. SylotiNagri
  - same as Batak
16. Tagalog
  - same as Batak (and GSUB with no feature)
17. Tagbanwa
  - same as Batak (and GSUB with no feature)
18. TaiLe
  - same as Batak
19. TaiViet
  -  same as Batak (and GSUB with no feature)

**Comment by jungshik** [comment]
Out of 16 scripts harfbuzz routes to USE, 16 of them have identical GSUB and GPOS tables (feature lists for two scripts are different, but the corresponding pair of features in the two scripts refer to the same set of lookups). 

The exceptions are MeeteiMayek, Kaithi and Balinese.

**Comment by jungshik** [comment]
@behdad wrote earlier, "For the rest, only DFLT should remain. If DFLT and non-DFLT were equivalent, no retesting is required.".   So, I guess we can go ahead with 16 of them listed above  **unless** we hear from @kmansourMT that some of them **are USE-compatible.**.

**Comment by kmansourMT** [comment]
When the specifications for these scripts were put together, USE was not in the picture. For future implementation, it would be good to set down clearly what is required for compatibility with USE.

**Comment by jungshik** [comment]
[test.txt](https://github.com/googlei18n/noto-fonts/files/33440/test.txt)

**Comment by jungshik** [comment]
> Javanese doesn't go through USE, but Indic shaper. Needs manual inspection. I really doubt that both > DFLT and non-DFLT tables are tested and work. I think DFLT needs to be removed.

#149, #161, #162, #178, #236, #297, #313 were addressed in the latest delivery for Javanese and tests done by @dougfelt must have used non-DFLT tables. That means that non-DFLT tables work for those issues. Obviously, it does not say anything about DFLT tables. As long as non-DFLT path (harfbuzz routes Javanese to) works,  I guess that having DFLT (that may not work and is NOT used by harfbuzz) should not have a user-visible difference (other than the font being unnecessarily larger). 

@behdad, am I right about this? 

> For N'Ko, Mongolian, Phags Pa, and the three Syriac's: I believe the DFLT should be removed.

The same be said of the above scripts.  

So, I'll prioritize what we need to do for 3 scripts whose non-DFLT tables are believed to be incompatible with USE and DFLT and non-DFLT tables are different :  MeeteiMayek, Kaithi and Balinese.

**Comment by behdad** [comment]
> Javanese doesn't go through USE, but Indic shaper. Needs manual inspection. I really doubt that both > DFLT and non-DFLT tables are tested and work. I think DFLT needs to be removed.
> 
> #149, #161, #162, #178, #236, #297, #313 were addressed in the latest delivery for Javanese and tests done by @dougfelt must have used non-DFLT tables. That means that non-DFLT tables work for those issues. Obviously, it does not say anything about DFLT tables. As long as non-DFLT path (harfbuzz routes Javanese to) works, I guess that having DFLT (that may not work and is NOT used by harfbuzz) should not have a user-visible difference (other than the font being unnecessarily larger).
> 
> @behdad, am I right about this?

Correct.

>     For N'Ko, Mongolian, Phags Pa, and the three Syriac's: I believe the DFLT should be removed.
> 
> The same be said of the above scripts.
> 
> So, I'll prioritize what we need to do for 3 scripts whose non-DFLT tables are believed to be incompatible with USE and DFLT and non-DFLT tables are different : MeeteiMayek, Kaithi and Balinese.

**Comment by jungshik** [comment]
Thanks, @behdad. 

It turned out that MeeteiMayek's DFLT and non-DFLT (default lang and "MNI ") are equivalent, too. So, I'll drop non-DFLT from MeeteiMayek, too.

**Comment by jungshik** [comment]
@kmansourMT gave me Kaithi strings (that involves rather complex conjuncts and vowel reordering). As far as I can tell, DFLT works much better with the latest harfbuzz (that routes Kaithi to USE if non-DFLT/kaithi-specific tables are present)  than with non-DFLT tables. 

Test file: 
[kaithi.mti.txt](https://github.com/googlei18n/noto-fonts/files/37297/kaithi.mti.txt)

* Harfbuzz + the current version with both DFLT and non-DFLT : harfbuzz sends this to USE
![kaithi mti old cond](https://cloud.githubusercontent.com/assets/8578343/11227325/2b359ca4-8d3a-11e5-9769-9b39bda63b67.png)

* Harfbuzz + a patched font (non-DFLT dropped) : harfbuzz uses DFLT shaper. 

![kaithi mti new cond](https://cloud.githubusercontent.com/assets/8578343/11227342/43424e6e-8d3a-11e5-8a0f-317325e23ce0.png)

@kmansourMT : can you confirm that the latter (DFLT only) is correct or at least much better than the former (DFLT + Kaithi)?  Thanks

**Comment by kmansourMT** [comment]
The second rendering (DFLT) is much better.

**Comment by jungshik** [comment]
Thanks, @kmansourMT for your response regarding Kaithi. 

Now, it's down to Balinese. I've just filed #572 because Balinese has rather complex issues to deal with.

**Comment by jungshik** [comment]
For Balinese, having 'bali' works a lot better (although there are still issues as shown in #572) so that I'll keep 'bali'. 

This bug can be closed because we took care of all the fonts that need this treatment.
