### ISSUE TITLE
inconsistency in GDEF class in Tifinagh

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#550]
In GDEF of Noto Sans Tifinagh, I found an seemingly inconsistent glyph class assignment that I don't understand. 

For instance, I wonder why the first one is class 1 (base) while the second one is class 3 (mark). [1] 

```
<ClassDef glyph="uni2D592D5C" class="1"/>
<ClassDef glyph="uni2D622D5C" class="3"/>
```

![image](https://cloud.githubusercontent.com/assets/8578343/10977864/af8c015a-83a8-11e5-974e-529d567c2c04.png)

If I understand GDEF glyph classes correctly, both seem to have to be assigned class 2 (ligature). 

[1] https://www.microsoft.com/typography/otspec/gdef.htm

Unicode Tifinagh block chart: http://www.unicode.org/charts/PDF/U2D30.pdf

/cc @dougfelt @roozbehp @behdad

**Comment by jungshik** [comment]
In addition, both uni2D592D5C and uni2D622D5C are included in the base character list for lookup 0 to be combined with U+030[12467], U+0323, U+0331.  So, I don't understand different glyph classes assigned to them in GDEF.

**Comment by behdad** [comment]
There's no requirement that ligatures be marked as ligatures in GDEF.  They have to, only if they need mark positioning on individual components, which might not be feasible if the ligature is inherently vertical...

**Comment by jungshik** [comment]
I gather that this inconsistency does not cause any user-visible/practical change. It's just a bit strange that there's an inconsistency (class 1 vs class 3). So, this issue is kinda just for book-keeping.

**Comment by marekjez86** [comment]
[NotoSansTifinagh-Regular.ttx.zip](https://github.com/googlei18n/noto-fonts/files/1039491/NotoSansTifinagh-Regular.ttx.zip)

all of the above are class 1

**Comment by marekjez86** [comment]
the font is in noto-fonts-alpha
