### ISSUE TITLE
U+0309 is missing in Noto Sans Tifinagh

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#551]
Unicode 9 19.3 Tifinagh (p. 710 http://www.unicode.org/versions/Unicode8.0.0/ch19.pdf )  has the following, but U+0309 is missing from Noto Sans Tifinagh. 

> represent vowels and foreign consonants. In this notation, "U+2D35, U+0307" represents
> “a”, "U+2D49, U+0309 "represents a long “i” /i:/, and "U+2D31, U+0302" represents a
> “p”. Some long vowels are represented using two diacritical marks above. A long “e” /e:/ is
> thus written "U+2D49, U+0307, U+0304". These marks are displayed side by side ab

/cc @dougfelt (do we check for this character ? ) @roozbehp

**Comment by dougfelt** [comment]
Right now noto_lint ignores characters after Unicode 6.1 by default, so
unless we add explicit requests for characters to the lint code it won't
pick it up and flag it.

**Comment by kmansourMT** [comment]
Please keep in mind that Tifinagh, and a whole bunch of other scripts, were implemented for Unicode 6.1.

**Comment by jungshik** [comment]
That's for Phase II. We have to address this issue for Phase 3.

**Comment by jungshik** [comment]
Pinging @kmansourMT to make sure that this issue is addressed in Phase 3 version of Noto Tifinagh.

**Comment by marekjez86** [comment]
[NotoSansTifinagh-Regular.ttf.zip](https://github.com/googlei18n/noto-fonts/files/1039505/NotoSansTifinagh-Regular.ttf.zip)

U+0309 is in the font file located in noto-fonts-aplha
