### ISSUE TITLE
Android settings tofu

### ISSUE THREAD

**Issue by drinkypoo** [googlei18n/noto-fonts#552]
Whatever character Android is using for the hyphen in Wi-Fi in the settings menu is a rectangle with noto sans. I was hoping this font would solve this problem, which occurs with many fonts.

**Comment by jungshik** [comment]
What's the UI language you use? And, could you tell us about Android OS version and a device you found this issue on (e.g. Nexus 5, Samsung Galaxy ..., etc) as well?  
And, a screenshot would be helpful, too.

**Comment by marekjez86** [comment]
@drinkypoo : would you be able to provide info on UI language used? Android OS version? device you found this issue on? screenshot?

Thanks

**Comment by drinkypoo** [comment]
Language used: English
Android OS version: 4.x, 5.x
Device found issue on: Multiple. TF201 and Pine64 so far. Both running quite vanilla settings.
Screenshot: are you kidding? It's the dash in Wi-Fi.

**Comment by marekjez86** [comment]
if not screenshot then could you attach a photo of the screen fragment with the Wi-Fi in the settings menu where you can see this rectangle?

**Comment by drinkypoo** [comment]
OK, I can manage that. I have not yet soldered the power button to my pine and I do not currently have xposed on my tf201... so here is a photo of my pine display from my tf201.

![img_20160505_170425](https://cloud.githubusercontent.com/assets/323265/15050564/1b67ce98-12e4-11e6-9f9c-fbc48709443b.jpg)

I got the same thing on my tf201, also running 5.1.1.

**Comment by jungshik** [comment]
Thank you for the reply, but I don't think your issue is relevant to Noto. 
(to begin with, the default UI font for Latin script on Android is not Noto but Roboto). 

See https://code.google.com/p/android/issues/entry?template=User%20bug%20report and file a bug if you believe your issue meets the criteria written there.

**Comment by drinkypoo** [comment]
I really don't care even slightly what the default font on Android is. That doesn't seem relevant. The purpose of the noto fonts is supposed to be to eliminate tofu. Obviously you are giving up, and blaming me. And in the process, you have wasted my time with this screenshot nonsense, when you were just going to give up anyway. It was obvious what character I was talking about, so you have wasted my time on purpose.

I don't think Noto is relevant. But thanks for playing.

**Comment by fitojb** [comment]
> Screenshot: are you kidding?

LOL, with that attitude how d’you expect people to help you?

When maintainers ask you for a screenshot, just post one. Read [“How to report bugs effectively”](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html), the section titled “Show me” is relevant. More often than not, things you thing that are obvious in fact are not! (Let’s see, what you called a dash is in reality called a hyphen…)

**Comment by drinkypoo** [comment]
fitojb, did you read my initial bug report, son? Guess not. Also, you have it ass-backwards. With the attitude of this project towards bug reports, why does it expect help? There was no need for a screenshot because only a defective could have failed to understand what I meant from the description. And when I finally provided the unnecessary screen shot, I was told my bug was irrelevant. Someone with two brain cells to rub together could have done that without a screenshot.
