### ISSUE TITLE
Some collisions in Javanese rendering

### ISSUE THREAD

**Issue by dougfelt** [googlei18n/noto-fonts#554]
There are a few cases in NotoSansJavanese 1.03 where characters collide.  See below:

![jv-java_ex1_anno](https://cloud.githubusercontent.com/assets/9939212/11049549/ee09df08-86f3-11e5-9b41-fa8e6ad7739d.png)

This is \ua9c5\ua9c9\ua99f\ua9c0\ua9a2\ua9bf\ua9c9\ua9c5

![jv-java_ex2_anno](https://cloud.githubusercontent.com/assets/9939212/11049585/26dccf2a-86f4-11e5-9888-4177278bef30.png)

This is \ua9a9\ua9b8\ua99a\ua9c0\ua995\ua982\ua98f\ua9bc\ua9a4\ua9c0\ua9a5\ua9bf\ua9a7\ua9ba\ua981\ua9b2\ua9ba\ua982\u200b\ua9a7\ua9b8\ua9a9\ua9b6\ua9c8

![jv-java_ex3_anno](https://cloud.githubusercontent.com/assets/9939212/11049595/3b42e2d8-86f4-11e5-86eb-175230d627ce.png)

This is \ua9a9\ua9ba\ua9b4\ua981\ua98f\u200b\ua9b1\ua9ab\ua9ae\ua9ba\ua9a2\ua9b6\ua9a4\ua9b6\ua981\ua9ab\ua9a0\ua9c0\u200b\ua9a2\ua9ba\ua9ab\ua9a4\ua9bf\ua9b8\ua9b1\ua9c0\ua98f\ua9bc\ua9a4\ua9c0\ua9b2\ua9b8\ua997\ua9c0\ua9ae\ua9ad\ua9a4\ua9c0\ua9a4\ua9b6\ua981\ua9c8

**Comment by kmansourMT** [comment]
Corrected in upcoming version of Noto Javanese as evidenced by 

<img width="458" alt="screen shot 2015-11-19 at 18 37 43" src="https://cloud.githubusercontent.com/assets/12738181/11290574/df67ea52-8eec-11e5-8700-7b21c0e46ada.png">
<img width="317" alt="screen shot 2015-11-19 at 18 37 32" src="https://cloud.githubusercontent.com/assets/12738181/11290576/df6add48-8eec-11e5-930f-99f673c80655.png">
<img width="383" alt="screen shot 2015-11-19 at 18 37 24" src="https://cloud.githubusercontent.com/assets/12738181/11290575/df6977d2-8eec-11e5-89d1-f088846bc269.png">

**Comment by dougfelt** [comment]
Great!

**Comment by dougfelt** [comment]
Fixed in version 1.04
