### ISSUE TITLE
Please provide a public notice on Droid fonts being superseded by Noto

### ISSUE THREAD

**Issue by copyninja** [googlei18n/noto-fonts#555]
Hi,

I'm the maintainer of Droid fonts in Debian, and during my latest update I noticed that upstream no longer ships Droid fonts other than Fallback variants. So I mailed @davelab6 on the status and he said Droid is being superseded by Noto fonts and there should be a public notice about it. I could not find any public notice on this so as per @davelab6 suggestion here [1] I'm filing this bug.

Please provide a public notice on this or if its already present can some one please point it to me?.

Thanks
[1] http://lists.alioth.debian.org/pipermail/pkg-fonts-devel/attachments/20151031/011f4334/attachment.mht

**Comment by marekjez86** [comment]
@copyninja : if you look at https://www.google.com/design/spec/material-design/introduction.html which is the official guidline for Google you can see a page https://www.google.com/design/spec/resources/roboto-noto-fonts.html

It specifies when (on Android Roboto is used and when Noto is used). This is not an explicit Droid message, but that's the best you can get at this point.

**Comment by xiangyexiao** [comment]
good suggestion. I don't remember we post publicly that we have renamed Droid to Noto and expand Noto to cover many more languages not covered by old Droid.

ReadMe seems to be a good place to host such info. I will add something very soon.

**Comment by xiangyexiao** [comment]
https://github.com/googlei18n/noto-fonts/blob/master/README.md

**Comment by copyninja** [comment]
Thanks for the update Xiangye.
