### ISSUE TITLE
19 Japanese TV symbols to be added to Noto Symbols

### ISSUE THREAD

**Issue by roozbehp** [googlei18n/noto-fonts#557]
Unicode just accepted the proposal at http://www.unicode.org/L2/L2015/15238-n4671.pdf and fast-tracked them for Unicode 9. These are symbols that would be required for all Japanese TVs in a short while.

The codepoints and glyphs are at page 73-80 of http://www.unicode.org/L2/L2015/15303-n4702-cd2-5th10646.pdf. There are 18 characters at U+1F19B..U+1F1AC and one at U+1F23B.

Please add them to Noto Symbols.

/cc @marekjez86

**Comment by marekjez86** [comment]
@BrianKraimerMT , this is FYI - see comment "Please add them to Noto Symbols."

**Comment by dougfelt** [comment]
TV symbols added in v1.08 of NotoSansSymbols-Regular.ttf.
