### ISSUE TITLE
Is there a mapping of "Unicodes supported" to "Noto font file"?

### ISSUE THREAD

**Issue by graphicore** [googlei18n/noto-fonts#559]
Or the other way around.

It could be useful to combine this information with [CSS/@font-face/unicode-range](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range)

**Comment by davelab6** [comment]
To generate such data, I would run

    cd ~/src/github.com/googlei18n/noto-fonts ;
    for font in `find . -iname *ttf`; do
    ~/src/github.com/google/fonts/tools/encodings/namelist.py $font | cut -d\  -f1 > $font-unicodes.txt;
    done;

and then use the \*-unicodes.txt files.

**Comment by dougfelt** [comment]
you can also use nototools.coverage.py in googlei18n/nototools:

```
./coverage.py -h
usage: coverage.py [-h] [--ranges] [--text] [--sep SEP] [--info] [--chars_per_line N]
                   [--limit ranges]
                   file [file ...]

positional arguments:
  file                Files to dump

optional arguments:
  -h, --help          show this help message and exit
  --ranges            Dump cmap as hex ranges
  --text              Dump cmap as sample text
  --sep SEP           Separator between chars in text, default space
  --info              Dump cmap as cp and unicode name, one per line
  --chars_per_line N  Format text in lines of at most this many codepoints, 0 to format as a single
                      line
  --limit ranges      string of hex codepoint ranges limiting cmap to output```

**Comment by marekjez86** [comment]
@graphicore : I believe both @davelab6 and @dougfelt provided solutions. Closing.

**Comment by graphicore** [comment]
I agree, thanks for closing. My attention shifted, I just forgot this issue.
I'll use one of the approaches when I come back to the task.
