### ISSUE TITLE
Variant zero should be added to Noto Sans and Noto Serif

### ISSUE THREAD

**Issue by roozbehp** [googlei18n/noto-fonts#561]
Unicode partially accepted the proposal at http://www.unicode.org/L2/L2015/15268-slashed-zero.pdf and added a variation sequence for a slashed form of the digit 0 with the slash not going outside the oval (with a glyph as seen on page 10 of the proposal). This was fast-tracked for Unicode 9.

The form should be drawn for Noto Sans and Noto Symbols (LGC), triggered by the sequence "U+0030, U+FE00".

**Comment by nizarsq** [comment]
Verification in process.

**Comment by nizarsq** [comment]
Tested new fonts and noticed triggering the sequence of "U+0030, U+FE00"  will not print digital zero with nonempty counter (slashed form of the digit 0). Attached test cases:
``<html lang="sr"> <p><span style="font-weight:700">&#48;&#65024;</span></p> </html>.``

[NotoSans-Black-561.pdf](https://github.com/googlei18n/noto-fonts/files/647024/NotoSans-Black-561.pdf)
[NotoSansDisplay-Black-561.pdf](https://github.com/googlei18n/noto-fonts/files/647029/NotoSansDisplay-Black-561.pdf)
[NotoSansDisplay-Italic-561.pdf](https://github.com/googlei18n/noto-fonts/files/647026/NotoSansDisplay-Italic-561.pdf)
[NotoSans-Italic-561.pdf](https://github.com/googlei18n/noto-fonts/files/647025/NotoSans-Italic-561.pdf)
[NotoSerif-Black-561.pdf](https://github.com/googlei18n/noto-fonts/files/647027/NotoSerif-Black-561.pdf)
[NotoSerifDisplay-Black561.pdf](https://github.com/googlei18n/noto-fonts/files/647028/NotoSerifDisplay-Black561.pdf)
[NotoSerifDisplay-Italic561.pdf](https://github.com/googlei18n/noto-fonts/files/647030/NotoSerifDisplay-Italic561.pdf)
[NotoSerif-Italic561.pdf](https://github.com/googlei18n/noto-fonts/files/647032/NotoSerif-Italic561.pdf)
[OldNotoSerif-Regular561.pdf](https://github.com/googlei18n/noto-fonts/files/647031/OldNotoSerif-Regular561.pdf)

**Comment by marekjez86** [comment]
sample
```html
<html lang="en">
<p><span style="font-size:48.0px">"0︀"</span></p>
</html>
```
"0︀" is "U+0030, U+FE00"
demonstrates that noto fonts are fine.

@roozbehp : should we expect this from Roboto? It's not implemented there.

[en-561-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683657/en-561-NotoSansMono-Regular.pdf)
[en-561-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683658/en-561-NotoSerif-Black.pdf)
[en-561-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683656/en-561-NotoSerif-Italic.pdf)
[en-561-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683659/en-561-NotoSerif-Regular.pdf)
[en-561-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683660/en-561-NotoSerifDisplay-Black.pdf)
[en-561-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683661/en-561-NotoSerifDisplay-Italic.pdf)
[en-561-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683662/en-561-NotoSerifDisplay-Regular.pdf)
[en-561-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683663/en-561-Roboto-Black.pdf)
[en-561-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683664/en-561-Roboto-Italic.pdf)
[en-561-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683665/en-561-Roboto-Regular.pdf)
[en-561-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683666/en-561-NotoSans-Black.pdf)
[en-561-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683667/en-561-NotoSans-Italic.pdf)
[en-561-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683668/en-561-NotoSans-Regular.pdf)
[en-561-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683669/en-561-NotoSansDisplay-Black.pdf)
[en-561-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683670/en-561-NotoSansDisplay-Italic.pdf)
[en-561-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683671/en-561-NotoSansDisplay-Regular.pdf)
[en-561-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683672/en-561-NotoSansMono-Black.pdf)
