### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by dougfelt** [googlei18n/noto-fonts#562]
this is a test

**Comment by df-test** [comment]
left a comment

**Comment by dougfelt** [comment]
[lzh-Hant_text.txt](https://github.com/googlei18n/noto-fonts/files/32489/lzh-Hant_text.txt)

**Comment by marekjez86** [comment]
is this real bug that needs to remain open ? just checking

**Comment by dougfelt** [comment]
No, I was experimenting with accounts of different permissions to see what you could do on github.
