### ISSUE TITLE
Khmer: some glyph names are missing

### ISSUE THREAD

**Issue by lemzwerg** [googlei18n/noto-fonts#564]
In all Noto Khmer fonts, the glyphs of the 'Khmer Symbols' block (U+19E0 - U+19FF) and the 'numeric symbols for divination lore' (U+17F0 - U+17F9) in the 'Khmer' block lack glyph names.

Basically, since TTFs are accessed via cmap tables, this isn't a real bug. However, all other glyphs *are* named, so it is at least an inconsistency.  Additionally, since the glyph names are of the form 'uniXXXX', they can be easily added, and I think it is more convenient to have them correctly set.

**Comment by jungshik** [comment]
hinted/* has the same issue. The above commit took care of unhinted.

**Comment by dougfelt** [comment]
Ugh, of course.

**Comment by dougfelt** [comment]
All Khmer post tables should be fixed now.
