### ISSUE TITLE
Noto Nastaliq does not have a glyph for ARABIC LETTER HIGH HAMZA (U+0674)

### ISSUE THREAD

**Issue by deepakjois** [googlei18n/noto-fonts#568]
Geeza Pro on OS X has it, and so does Jameel Noori Nastaleeq.

**Comment by roozbehp** [comment]
Why is it needed for Noto Nastaliq? It's only used in Kazakh etc which are not written in Nastaliq, as far as I know.

**Comment by deepakjois** [comment]
Here are some notes about _izāfat_ in Urdu (which is written in Nastaliq):
http://rishida.net/scripts/urdu/#izafat

> Izāfat is represented by a combining hamzā when the preceding word ends in either choṭī he ہ or ye ی

Here is the word used in the example above typeset in three different fonts:

<img width="395" alt="screenshot 2015-11-18 08 45 21" src="https://cloud.githubusercontent.com/assets/5342/11231683/3034f262-8dd1-11e5-8586-ba6887736133.png">

@khaledhosny, it seems that Amiri handles this correctly. Do you know more about this specific case?

**Comment by deepakjois** [comment]
Ok. I was mistaken, ARABIC LETTER HIGH HAMZA (U+0674) is different from ARABIC HAMZA ABOVE (U+0654).

I did not realise that my OS X Urdu Keyboard does support the character ARABIC LETTER HEH GOAL WITH HAMZA ABOVE (U+06C2) which I could have used in this situation. Moreover, the only available key for a standalone Hamza on the OS X Urdu Keyboard (Shift-7) outputs ARABIC LETTER HIGH HAMZA (U+0674) instead of ARABIC HAMZA ABOVE (U+0654).

However as can be seen in screenshot above, it appears that fonts support it. I suspect it is because people tend to commonly make the same mistake that I made.

**Comment by deepakjois** [comment]
I did some more investigation. I am sorry about the confusion above. Please ignore all my comments about ARABIC LETTER HIGH HAMZA (U+0674). I am new to Urdu and Arabic typing in general, and all this Hamza stuff can be confusing.

The real problem is that Noto Nastaliq seems to render this text incorrectly: قترۂاب

Please feel free to change the text of this bug report, or file a separate bug for this.

**Comment by deepakjois** [comment]
This is a much better illustration of the problem. It seems Amiri handles it nicely and most consistently (although it isn’t strictly a Nastaliq font). Maybe @khaledhosny can comment on this.

<img width="705" alt="screenshot 2015-11-18 13 03 03" src="https://cloud.githubusercontent.com/assets/5342/11235137/c54b33b6-8df4-11e5-9d47-5e19c15ee508.png">

**Comment by khaledhosny** [comment]
I’m afraid I don’t really get what you want here and what is the expected output. the Amiri output you are citing as correct certainly does not look right.

**Comment by deepakjois** [comment]
Ok. For some reason I thought the output by Amiri and by Jameel Noori Nastaliq in the first case (using U+06C2) is the correct one.

Apologies again for creating a lot of confusion. I should be doing a bit more research before I file bugs.

**Comment by marrish** [comment]
In my opinion there is no problem at all. Such combination is not needed as it is non-existent in the languages like Urdu. All the illustrations are wrong as it is simply قطرۂ آب what needs to be written, that's all.

**Comment by marekjez86** [comment]
closing the bug. please reopen if still some action needed
