### ISSUE TITLE
Kaithi font does not cover ZWJ and ZWNJ

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#569]
Below is the excerpt from the Unicode standard section 15.2.  ZWJ and ZWNJ can be used to explicitly specify which form to use for a consonant cluster, but the current Kaithi font does not cover ZWJ/ZWNJ. 

@roozbehp 
@dougfelt : do we check for ZWJ/ZWNJ in Kaithi ? 

---

Consonant conjuncts in Kaithi are represented with a virama between the two consonants
in the conjunct. For example, the ordinary representation of the conjunct mba would be by
the sequence:

```
U+110A7 kaithi letter ma + U+110B9 kaithi sign virama +
U+110A5 kaithi letter ba
```

Consonant conjuncts may be rendered in distinct ways. Where there is a need to render
conjuncts in the exact form as they appear in a particular source document, U+200C zero
width non-joiner and U+200D zero width joiner can be used to request the appropriate
presentation by the rendering system. For example, to display the explicitly ligated
glyph V for the conjunct mba, U+200D zero width joiner is inserted after the virama:

```
U+110A7 kaithi letter ma + U+110B9 kaithi sign virama +
U+200D zero width joiner + U+110A5 kaithi letter ba
```

To block use of a ligated glyph for the conjunct, and instead to display the conjunct with an
explicit virama, U+200C zero width non-joiner is inserted after the virama:

```
U+110A7 kaithi letter ma + U+110B9 kaithi sign virama +
U+200C zero width non-joiner + U+110A5 kaithi letter ba
```

**Comment by dougfelt** [comment]
On Tue, Nov 17, 2015 at 10:22 AM, jungshik <notifications@github.com> wrote:

> Below is the excerpt from the Unicode standard section 15.2. ZWJ and ZWNJ
> can be used to explicitly specify which form to use for a consonant
> cluster, but the current Kaithi font does not cover ZWJ/ZWNJ.
>
> @roozbehp <https://github.com/roozbehp>
> @dougfelt <https://github.com/dougfelt> : do we check for ZWJ/ZWNJ in
> Kaithi ?
>
​No, we don't.​

**Comment by kmansourMT** [comment]
The formation of conjuncts in Kaithi is deterministic and fully predictable. For instance, if we wanted to form the ligature **_KSa_**, we need only enter the text (**_Ka Virama Sa_**) to obtain such a result as in  
![screen shot 2017-06-09 at 16 06 20](https://user-images.githubusercontent.com/12738181/26997341-c3eaa782-4d2d-11e7-8d59-1bf9f7ab1334.png)
There is no need to add a ZWJ to coerce the formation of the conjunct.

Should we wish to prevent the formation of such a ligature, we can insert a ZWNJ into the text as in (**_Ka Virama ZWNJ Sa_**), , resulting in the non-ligated form as in
![screen shot 2017-06-09 at 16 06 27](https://user-images.githubusercontent.com/12738181/26997375-0a4dbfac-4d2e-11e7-976e-a3adef844930.png)

**Comment by marekjez86** [comment]
recent delivery has ZWJ and ZWNJ
