### ISSUE TITLE
Kaithi has ZWNBSP (U+FEFF) but not ZWSP (U+200B) in the cmap

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#570]
Kaithi's cmap has U+FEFF (ZWNBSP) but does not have ZWSP (U+200B). 

@dougfelt , @roozbehp  : can you think of a reason for the above? 

@kmansourMT : is it intentional?

**Comment by kmansourMT** [comment]
Please state why ZWNBSP and ZWSP might be required.

**Comment by jungshik** [comment]
@dougfelt : Yes, that's my question.

**Comment by kmansourMT** [comment]
The upcoming delivery will include ZWSP (200B). I don't see a compelling reason to include ZWNBSP (FEFF).
