### ISSUE TITLE
Some Javanese combinations join poorly

### ISSUE THREAD

**Issue by dougfelt** [googlei18n/noto-fonts#574]
This is in v1.04 of NotoSansJavanese.

![jv-java_text3_07_v4](https://cloud.githubusercontent.com/assets/9939212/11313945/ec339cbe-8f95-11e5-8373-686fd882b021.png)

This text is
\ua9a5\ua9bf\ua9a7\ua9ae\ua9ba\ua981\u200b\ua9a5\ua994\ua9c0\ua9ae\ua9b1\u200b\ua9a6\ua9bf\ua9a8\ua9b8\ua9c8

At the right of this sample there are two sequences where there's an abrupt transition in what otherwise I'd expect to look like a continuous stroke.  In one case (\ua9a6\ua9bf) this looks like a small bump, in the other (\ua9a\ua9b8) a thin line abuts a thicker line.

**Comment by dougfelt** [comment]
ping

**Comment by NorbertLindenberg** [comment]
Please label this bug as Script-Javanese.

**Comment by kmansourMT** [comment]
In version 1.05 of Noto Javanese, the listed errors have been corrected and render as follows:
![pa_mu-ra-ba_mu-u-ext](https://cloud.githubusercontent.com/assets/12738181/11795014/3488a578-a269-11e5-8a5e-e337b310ded3.png)

**Comment by dougfelt** [comment]
Thanks, this is better.  hb-view (on linux using cairo) doesn't seem to do so well with smaller point sizes, there's still a clear 'seam' between murda and suku at 16 and 24pt. Not sure if anything can be done about that when using separate glyphs.

16pt: 
![jv-java_text3_07_v5_16](https://cloud.githubusercontent.com/assets/9939212/11800090/7fe27aec-a28e-11e5-8e8a-7a7e6490a428.png)
24pt:
![jv-java_text3_07_v5_24](https://cloud.githubusercontent.com/assets/9939212/11800100/8aa6fd72-a28e-11e5-8bee-97b758b53b59.png)
32pt:
![jv-java_text3_07_v5_32](https://cloud.githubusercontent.com/assets/9939212/11800104/93a7854a-a28e-11e5-95d9-9143f7a9ff94.png)
48pt:
![jv-java_text3_07_v5_48](https://cloud.githubusercontent.com/assets/9939212/11800126/c066d2d4-a28e-11e5-9f49-1b015faf2aaa.png)

**Comment by dougfelt** [comment]
@kmansourMT, any idea what's going on with the smaller point sizes above?

**Comment by kmansourMT** [comment]
This is a case where the edges of two overlapping components are aligning differently to the grid. This might be due to the grid-fitting of this particular rasterizer, or due to a minute misalignment of the anchor points. I will look at the details, and will report back.

**Comment by dougfelt** [comment]
@kmansourMT ping?

**Comment by xiangyexiao** [comment]
@kmansourMT ping?

**Comment by kmansourMT** [comment]
We are actively working on this issue and will report back soon.

**Comment by marekjez86** [comment]
thanks

**Comment by kmansourMT** [comment]
The recently released version of Noto Javanese includes all the necessary changes to clear issue 574. The following graphic shows all consonantal characters in combination with the U & UU vowel marks (u+A9B8, A9B9), followed by the phrase cited by Doug Felt on Dec 14. We have tuned all the various factors that can contribute to the previously reported misalignment. Bearing in mind that the final font is unhinted, it remains possible (but unlikely) that at some combination of size, resolution, and rendering platform, a minor misalignment might appear. 

![javanese-issue_574](https://cloud.githubusercontent.com/assets/12738181/12662574/4b7cf096-c5d6-11e5-87ff-7c06763b089a.png)

**Comment by kmansourMT** [comment]
I’d like to request that errors reported on this new font be issued new numbers. It doesn’t make sense to wade through old posting that are referring to an entirely different font.
Thanks,

Kamal

**Comment by marekjez86** [comment]
that's fair :-)
