### ISSUE TITLE
Cyrillic: small letter shha 04BB and small letter shha with descender 0527 are inconsitent

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#580]
In Noto Sans and Noto Serif, Cyrillic small letter shha 04BB һ is a turned che 0447 ч but should instead use Latin small letter h 0068 as a component (as done in Arimo, Cousine, Tinos).

In Arimo, Tinos, Noto Sans and Noto Serif, Cyrillic small letter shha with descender 0527 ԧ is based on Latin small letter h 0068, so should 04BB.

See ҺһԦԧ (04BA 04BB 0526 0527) in Noto Sans and Noto Sans Italic, Noto Serif and Noto Serif Italic:
![screen shot 2015-12-03 at 23 18 08](https://cloud.githubusercontent.com/assets/1923747/11577258/9190d374-9a14-11e5-8e75-e9c0e3c2ee87.png)

**Comment by alexeiva** [comment]
Both approaches are correct — turned-ч or h. As long as there is consistency between uni04BB and uni0527.

So the second possible option would be to change uni0527 to a ч-based design.

<img width="472" alt="screen shot 2016-06-20 at 10 26 00" src="https://cloud.githubusercontent.com/assets/16634089/16197797/69230862-36d1-11e6-8ad0-071bfd4557e1.png">
Image: h, uni04BB, uni0527 in PT Sans

**Comment by nizarsq** [comment]
Verifying in progress

**Comment by nizarsq** [comment]
Checked (04BA 04BB 0526 0527), I can see there is diffreance in rendering 04BB, I am attaching two pdf files thats shows the difreance in the shap using old Noto Serif Italic and the new version of Noto Serif Italic. Please reopen this bug if you belive this fix is not sufficient.

``<html lang="sr"> <p><span style="font-weight:700">&#1210; &#1211; &#1318; &#1319;</span></p> </html>``
[NotoSerif-Italic-580.pdf](https://github.com/googlei18n/noto-fonts/files/623080/NotoSerif-Italic-580.pdf)
[OldNotoSerif-Italic-580.pdf](https://github.com/googlei18n/noto-fonts/files/623081/OldNotoSerif-Italic-580.pdf)
