### ISSUE TITLE
Cyrillic: small letter pe with descender 0525 is inconsitent with small letter pe 043F in Tinos Italic

### ISSUE THREAD

**Issue by moyogo** [googlei18n/noto-fonts#581]
Cyrillic small letter pe with descender 0525 ԥ is inconsistent with Cyrillic small letter pe 043F п in Tinos Italic.

See пԥ (043F 0525)  in Tinos Italic:
![screen shot 2015-12-04 at 06 36 03](https://cloud.githubusercontent.com/assets/1923747/11583411/52e3a5ba-9a51-11e5-8675-6d11e7a6c2c8.png)

**Comment by moyogo** [comment]
I rephrased the issue. 0525 ԥ should be based on 043F п and not just have a different descender in Tinos Italic.

**Comment by marekjez86** [comment]
![581-tinos-italic-fixed](https://cloud.githubusercontent.com/assets/13322623/15234695/232c4fd4-1869-11e6-9d17-629a8b41051d.jpg)

The bottom line is from the most recent delivery of Tinos (The top line is from the Tinos' precursor - the version I tested against has no 0525). The recent delivery fixed the problem as stated.
