### ISSUE TITLE
Balinese gantungan ᬜ overlaps previous below-base glyphs

### ISSUE THREAD

**Issue by NorbertLindenberg** [googlei18n/noto-fonts#583]
Reported by a customer in Bali using a modified Noto Sans Balinese:

> Can you make a smaller under letter gantungan ᬜ to make it balance?
> In this example the gantungan letter ᬜ is too big so it crossing the other letter. 
> ᬧ᭄ᬭᬚ᭄ᬜ

The customer told me that the preferred solution is to move the gantungan ᬜ to the right, without moving its base character.

**Comment by dougfelt** [comment]
cc @jungshik, @kmansourMT

**Comment by NorbertLindenberg** [comment]
@kmansourMT requested the preferred rendering. I had showed the customer four possible renderings, and he told me that number 2 is the preferred choice:

![gantungan](https://cloud.githubusercontent.com/assets/216206/12898917/e87b0ea6-ce63-11e5-9083-6b483ea881fd.png)

**Comment by kmansourMT** [comment]
If no. 2 is followed by a base (b2), things can get visually complicated because b2 will in part be sitting over a sizable part of a subscript form that belongs to its left neighbor. On the other hand, form no.1 prevents all such ambiguity.

**Comment by kmansourMT** [comment]
@NorbertLindenberg 
By choosing no. 2 above, we now have to explore other related combinations.
**a.** Let's suppose the left neighbor did not have a lower component as inside the green oval of the following graphic
![583-no-left-barrier](https://cloud.githubusercontent.com/assets/12738181/13411690/787c5592-def3-11e5-86eb-57613aedbe23.png)
Would we still need to shift the gantungan letter ᬜ rightward, or could we leave it as in the green oval?

**b.** Likewise, let's suppose the right-hand successor of "no. 2" had no lower component, would we want to render the sequence as in the red or green squares that follow?
![rneighbor-no_overlap](https://cloud.githubusercontent.com/assets/12738181/13411881/7fc3b682-def4-11e5-950e-7809de77fb0b.png)
![rneighbor-overlap](https://cloud.githubusercontent.com/assets/12738181/13411885/830f5076-def4-11e5-8550-df26c354e86d.png)

**Comment by xbypass** [comment]
@kmansourMT
Based on senior high school material, I will answer for the b first. 
b. It should be on red one, as it would prevent the (a) problem.
