### ISSUE TITLE
Balinese gantungan guung and guung mecelek too narrow

### ISSUE THREAD

**Issue by NorbertLindenberg** [googlei18n/noto-fonts#584]
Reported by a customer in Bali using a modified Noto Sans Balinese:

> I see the size of gantungan guung ᬭ᭄ᬭ and guung mecelek ᬭᬺ is too narrow. I think it should be wider to full width of the ᬭ.

**Comment by dougfelt** [comment]
cc @jungshik, @kmansourMT
