### ISSUE TITLE
khmer: Rendering of ង្ខ្យ

### ISSUE THREAD

**Issue by lemzwerg** [googlei18n/noto-fonts#587]
Comparing the rendering of the character cluster 'ង្ខ្យ' with the Noto fonts and `KhmerOS.ttf` (and others), I wonder whether Noto is correct – see the attached images.  It irritates me that with Noto the subglyph overlaps with the glyph before...

A bug?

The images were created with

```
hb-view --output-format=png KhmerOS.ttf "ង្ខ្យ ក្បៀ" > KhmerOS.png
hb-view --output-format=png NotoSerifKhmer-Regular.ttf "ង្ខ្យ ក្បៀ" > NotoSerifKhmer-Regular.png
```

![khmeros](https://cloud.githubusercontent.com/assets/1630245/11622793/945e2ae6-9cc8-11e5-8f46-650b14073187.png)
![notoserifkhmer-regular](https://cloud.githubusercontent.com/assets/1630245/11622800/9ef91c68-9cc8-11e5-9472-fbe1aff4b1f2.png)

**Comment by mungkol** [comment]
Hi,

The KhmerOS version is correct for ង្ខ្យ. However, I have never seen a word with ង្ខ្យ and I think that's the reason why the Noto font designer made that decision in order to save space.

Thanks!

**Comment by mungkol** [comment]
I take back my words since I just found two words with ង្ខ្យ: សង្ខ្យានុគ្រោះ  and សង្ខ្យា. So, the KhmerOS version is correct.

**Comment by lemzwerg** [comment]
BTW, I picked up the first character cluster from http://rishida.net/scripts/khmer/

**Comment by lemzwerg** [comment]
Mungkol mentioned two words that contain the above cluster: សង្ខ្យានុគ្រោះ  and សង្ខ្យា – below you can find renderings with the two abovementioned fonts.
![khmerosx](https://cloud.githubusercontent.com/assets/1630245/11651650/b5f9f71e-9d92-11e5-937b-4d91a4acb875.png)
![notoserifkhmer-regularx](https://cloud.githubusercontent.com/assets/1630245/11651658/c0c2781a-9d92-11e5-8901-9f769d117df6.png)

**Comment by marekjez86** [comment]
current fonts with the current harfbuzz produce

serif
![notoserifkhmer-regular](https://cloud.githubusercontent.com/assets/13322623/22519581/a6ff61c6-e865-11e6-8902-908bb0142a2d.png)
sans
![notosanskhmer-regular](https://cloud.githubusercontent.com/assets/13322623/22519582/a7045eec-e865-11e6-8f13-6b632ec04129.png)

**Comment by marekjez86** [comment]
current fonts with the current harfbuzz produce

_hb-view --output-format=png --language=khm NotoSerifKhmer-Regular.ttf "សង្ខ្យានុគ្រោះ សង្ខ្យា" > NotoSerifKhmer-Regular.png_

![notoserifkhmer-regular](https://cloud.githubusercontent.com/assets/13322623/22520195/3bdb42c2-e868-11e6-9b4f-7b912a5a0375.png)


_hb-view --output-format=png --language=khm NotoSansKhmer-Regular.ttf "សង្ខ្យានុគ្រោះ សង្ខ្យា" > NotoSansKhmer-Regular.png_

![notosanskhmer-regular](https://cloud.githubusercontent.com/assets/13322623/22520206/462918b2-e868-11e6-842a-7fcad80aca23.png)

**Comment by marekjez86** [comment]
IMHO, the above is correct, but @mungkol or @lemzwerg please re-open if my assessment is wrong.

**Comment by punchcutter** [comment]
@marekjez86 With harfbuzz you need some extra space at the bottom to show the full shaping: 
![notoserifkhmer-regular](https://cloud.githubusercontent.com/assets/11257204/22520555/99d51faa-e869-11e6-97ac-dcd114cea615.png)
![notosanskhmer-regular](https://cloud.githubusercontent.com/assets/11257204/22520557/9ca678a0-e869-11e6-8d6e-d79767d6393e.png)
