### ISSUE TITLE
Add Cyrillic Extended-A and Cyrillic Extended-B

### ISSUE THREAD

**Issue by typiconman** [googlei18n/noto-fonts#590]
The fonts do not appear to have any glyphs for Cyrillic Extended-A and Cyrillic Extended-B. These are needed for support of Church Slavic (which according to the website is supported), as well as for writing the Abkhaz alphabet.

Let me know if I can be of assistance in implementing this.

**Comment by marekjez86** [comment]
@BrianKraimerMT and @waksmonskiMT : what would it take to add these to Cyrillic?
Cyrillic Extended-A http://unicode.org/charts/PDF/U2DE0.pdf
Cyrillic Extended-B http://unicode.org/charts/PDF/UA640.pdf

**Comment by waksmonskiMT** [comment]
These Cyrillic Unicode ranges are included in the Phase III LGC deliverables.




_________________________
Sue Waksmonski
Font Project Manager
_________________________
600 Unicorn Park Drive
Woburn, MA 01801
United States
_________________________
Telephone +1 (781) 970 6050
_________________________
monotype.com<http://www.monotype.com/>

**Comment by marekjez86** [comment]
@typiconman while we do not have dates, we intend to include Cyrillic Extended-A and Cyrillic Extended-B with our fonts.

**Comment by soshial** [comment]
Any update on the topic?

**Comment by dougfelt** [comment]
Please check NotoSans-Regular.ttf.  These characters should be supported.

**Comment by soshial** [comment]
Thank you, all is there!
