### ISSUE TITLE
Add Noto Sans Monospace to the repo

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-fonts#592]
It is current in the Android tree, at frameworks/base/data/fonts.

**Comment by dougfelt** [comment]
So, Droid 'Sans' Mono has serifs on the lower case i and l, and a two-story lowercase g.  Noto Sans does not. Do we care?

**Comment by roozbehp** [comment]
Don't call it Noto Sans Mono then. Call it Noto Mono!

**Comment by dougfelt** [comment]
So, a few things:
1) Do we own this?  Can we change the license to OTL, like everything else is?
2) Can we change the vendor fields from Ascender to Google?
3) This has some lint errors that would be straightforward to fix, should I fix them?  Those would be name table errors, removing a cmap subtable format lint says we shouldn't have (Unicode BMP), adding mappings for 0 and 0x000D to the cmap, changing the whitespace advances 2000-200B to the expected values.  There are others that could be fixed, e.g. the ascender/descender/linegap don't agree with what lint expects.
4) What about other lint errors, do we just ignore these?  The vast majority (~260) are bounds related.  There's some bidi errors (math symbols missing rtlm).  One glyph isn't hinted, lint expects all to be.

**Comment by dougfelt** [comment]
Also, typically we only have names with platformID=3, enc=1, lang=0x409, so I'd remove the 1,0,0 versions.

**Comment by dougfelt** [comment]
The fsType bit 8 is set in the Droid font: "Editable embedding: When this bit is set, the font may be embedded but must only be installed temporarily on other systems. In contrast to Preview & Print fonts, documents containing Editable fonts may be opened for reading, editing is permitted, and changes may be saved."

Noto fonts are free to install permanently on other systems, and fsType is 0 for Noto fonts.  Is this something we can change?

**Comment by xiangyexiao** [comment]
On Wed, Dec 16, 2015 at 2:34 PM, dougfelt <notifications@github.com> wrote:

> So, a few things:
> 1) Do we own this? Can we change the license to OTL, like everything else
> is?
>

Based on this contract
<https://drive.google.com/a/google.com/file/d/0B5mC8WkZ7IFnSU9MQUU0cG9nb2c/view>,
Google owns all the rights of the ttf files. We are free to change the font.


> 2) Can we change the vendor fields from Ascender to Google?
>

What's the vendor value for Noto fonts? I would suggest to set the same
value for the Mono font.


> 3) This has some lint errors that would be straightforward to fix, should
> I fix them? Those would be name table errors, removing a cmap subtable
> format lint says we shouldn't have (Unicode BMP), adding mappings for 0 and
> 0x000D to the cmap, changing the whitespace advances 2000-200B to the
> expected values. There are others that could be fixed, e.g. the
> ascender/descender/linegap don't agree with what lint expects.
>

It is better to fix them by ourselves. Mono is not in scope of SOW12 (Phase
II). SOW 15 (Phase III) includes Mono fonts, but it doesn't cover bug
fixing of the old ttf fonts.


> 4) What about other lint errors, do we just ignore these? The vast
> majority (~260) are bounds related. There's some bidi errors (math symbols
> missing rtlm). One glyph isn't hinted, lint expects all to be.
>

I would suggest to ignore the errors since new Monospace fonts will be
generated in phase III. We can fix whatever errors reported by lint on the
new Mono fonts.

**Comment by xiangyexiao** [comment]
On Wed, Dec 16, 2015 at 3:10 PM, dougfelt <notifications@github.com> wrote:

> The fsType bit 3 is set in the Droid font: "Editable embedding: When this
> bit is set, the font may be embedded but must only be installed temporarily
> on other systems. In contrast to Preview & Print fonts, documents
> containing Editable fonts may be opened for reading, editing is permitted,
> and changes may be saved."
>
> Noto fonts are free to install permanently on other systems, and fsType is
> 0 for Noto fonts. Is this something we can change?
>

We have the right to change.

**Comment by dougfelt** [comment]
Fixed.

**Comment by jungshik** [comment]
It's also in CrOs. Anyway, thanks for fixing/rebranding.
