### ISSUE TITLE
Don’t zip up the metric replacement fonts with the Noto family fonts

### ISSUE THREAD

**Issue by flying-sheep** [googlei18n/noto-fonts#596]
The normal noto-unhinted should only contain fonts of the “Noto” family imho.

The fonts not listed on the website should probably be offered separately.

**Comment by dougfelt** [comment]
Which fonts are the problem, exactly?

**Comment by flying-sheep** [comment]
Arimo, Cousine, and Timos.

Also I’m curious to know why they are developed here, as other metrically compatible ChromeOS fonts aren’t, and this repo is called noto-fonts, not chromeos-fonts.

**Comment by flying-sheep** [comment]
hello?

**Comment by dougfelt** [comment]
So... I'm still not quite getting what you're referring to.  On GCS the pkg directory zips don't contain these files, not that I've found, anyway.

They're here in this repo for historical reasons.  The originate with Monotype, who made many of the Noto fonts.  @jungshik maintains the Noto fonts on ChromeOS and maintains these too, I believe.  They're licensed the same as Noto.  When we switched to github we didn't create a separate repo for these.  We could have, is it blocking you in some way?

**Comment by flying-sheep** [comment]
my reason is basically [this bug](https://bugs.archlinux.org/task/47425).

i.e. downstream packagers rope in the other fonts under the label of “Noto fonts”, leading to bad font rendering.

maybe your official clarification that it’s historical reasons is i´enough for them to reconsider, maybe not :smile: thanks anyway!

**Comment by dougfelt** [comment]
I'm not sure by what mechanism the downstream code would consider these three to be 'Noto' fonts.  Fontconfig shouldn't have a problem; they're called Arimo, Tinos, and Cousine, not Arial, Times Roman, or Courier. So I don't see why how it could be making this mistake without some extra code getting involved.  If people are pointing at our repo and getting these fonts, they may be getting three fonts they don't expect, but I don't see how that causes them to use those fonts accidentally.

**Comment by flying-sheep** [comment]
OK, I think this is enough clarification to convince them.
