### ISSUE TITLE
Thai tone marks are not rendered well in Mac/iOS

### ISSUE THREAD

**Issue by chorice** [googlei18n/noto-fonts#598]
Thanks for making and distributing great Thai fonts.

I found tone marks in Noto Sans Thai are not well rendered in Mac and iOS application so I report it.

For example: 
U+0E23, U+0E48, U+0E33 have to be rendered like the below image:

![okay](https://cloud.githubusercontent.com/assets/5214449/11952615/3365a8ba-a8dd-11e5-93c5-658256eb652a.png)

but it is rendered like the below image in iOS/Mac applications.
![bad](https://cloud.githubusercontent.com/assets/5214449/11952625/4944f550-a8dd-11e5-9cbd-4a3016155757.png)

The order of the tone mark (U+0E48) and the order of the rhs one (U+0E33) have to be swapped.

However, same character(U+0E23, U+0E48, U+0E33) is well rendered in Windows and browsers.

**Comment by marekjez86** [comment]
This appears to be fixed in the font, but harfbuzz appears to have rendering problems on Mac (not tested at other locations)
