### ISSUE TITLE
Mulitple Noto fonts overriding color emoji from NotoColorEmoji

### ISSUE THREAD

**Issue by tetsuo55** [googlei18n/noto-fonts#600]
With default configuration on Android many emoji fail to show a color version because higher up in the fallback chain the black and white version is selected from the regular noto fonts (and also from roboto)

Can the fonts be modified so that they either no longer contain these emoji or that they no longer override the colored ones?

These are the emoji that break unless i put NotoColorEmoji above all other noto fonts in the XML

https://cloud.githubusercontent.com/assets/15817790/12004261/97f2af66-ab4a-11e5-8689-b48e8aa15ff7.png

Please see this ticket at emojione for more information: https://github.com/Ranks/emojione/issues/177
Roboto ticket for this issue: https://github.com/google/roboto/issues/146

**Comment by roozbehp** [comment]
This is intentional, since these characters are defined by Unicode to have a text appearance by default. Please see the Emoji_Presenation property in http://www.unicode.org/Public/emoji/2.0/emoji-data.txt.
