### ISSUE TITLE
ot-sanitise warnings

### ISSUE THREAD

**Issue by davelab6** [googlei18n/noto-fonts#603]
The Cham and Lao fonts have a minor warning from the ot-sanitise (git master today for both):

    cd unhinted ;
    for i in `ls -1 *ttf`; do echo $font; ot-sanitise $font; done
	...
    NotoSansCham-Bold.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSansCham-Regular.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSansLao-Bold.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSansLao-Regular.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSansLaoUI-Bold.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSansLaoUI-Regular.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSerifLao-Bold.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSerifLao-Regular.ttf
    WARNING: maxp: bad max_zones: 0
    ...
	
    cd hinted;
    for i in `ls -1 *ttf`; do echo $i; ot-sanitise $i; done
	...
    NotoSansCham-Bold.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSansCham-Regular.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSansLao-Bold.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSansLao-Regular.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSansLaoUI-Bold.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSansLaoUI-Regular.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSerifLao-Bold.ttf
    WARNING: maxp: bad max_zones: 0
    NotoSerifLao-Regular.ttf
    WARNING: maxp: bad max_zones: 0
	...

**Comment by marekjez86** [comment]
@davelab6 Thank you very much for reporting these warnings.

**Comment by jungshik** [comment]
Thanks. This is a dupe to #172
