### ISSUE TITLE
Hosting non-draft version of Noto Nastaliq Urdu font on Google?

### ISSUE THREAD

**Issue by ebraminio** [googlei18n/noto-fonts#605]
I wonder if it would be possible to host the non-draft on Google just like the draft one http://fonts.googleapis.com/earlyaccess/notonastaliqurdudraft.css ? I know here probably is not best place to report this thing but probably is shortest and most seeable one. Thank you.

**Comment by ebraminio** [comment]
@behdad as requested

**Comment by xiangyexiao** [comment]
passed your request to the related team. stay tuned.

**Comment by dkuspawono** [comment]
Stay tuned.Ok

**Comment by xiangyexiao** [comment]
The Noto Nastaliq Urdu font is now live here:
https://www.google.com/fonts/earlyaccess#Noto+Nastaliq+Urdu
