### ISSUE TITLE
Supporting limited set of Arabic characters ("ۆۊۇە") from names of other languages which are using Arabic script

### ISSUE THREAD

**Issue by ebraminio** [googlei18n/noto-fonts#606]
azb: "تۆرکجه", lrc: "لۊری شومالی" and ug: "ئۇيغۇرچە" are names of Arabic script written languages which have characters Noto Nastaliq doesn't support ("ۆۊۇە"). Is it possible to add just this limited set of characters so language link(*) section of Urdu Wikipedia articles won't have broken text?

![image](https://cloud.githubusercontent.com/assets/833473/12352336/622182d0-bb9a-11e5-8f6f-236da787513e.png)

Thank you.

(*) Language link is a right side menu (left hand, on English Wikipedia) of Wikipedia pages which shows correspond pages of an article in other Wikipedia languages and it uses the native language name of that Wikipedia languages, e.g. [an article on Urdu Wikipedia](https://ur.wikipedia.org/wiki/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86) which in order to see the issue you should apply Noto Nastaliq Urdu manually there.

**Comment by ebraminio** [comment]
@behdad as requested

**Comment by dougfelt** [comment]
Looks like  \u06c6 \u06ca \u06c7 \u06d5.  We can request these for the next phase of development.

**Comment by nizarsq** [comment]
I was able to reproduce this issue for ۊ and ۇ,  those characters not supported by Noto Nastaliq, and they fall back to another font which it cause the script to lose ligature between joined letters.

![imited set of arabic characters](https://cloud.githubusercontent.com/assets/22158882/18801827/0359130a-819a-11e6-9e8b-50d51e3bed0e.png)

**Comment by roozbehp** [comment]
No idea why this is assigned to me. But basically, Noto Nastaliq Urdu has a limited character set and doesn't cover the full Arabic script range. @dougfelt should have the list of characters in the spec.

**Comment by dougfelt** [comment]
@nizarsq can you provide a list of the unicode values of the characters necessary for Nastaliq to support the language list in wikipedia mentioned in the original bug?  Or extract a list of strings for testing?  Or are these two the only characters needed?

**Comment by dougfelt** [comment]
@nizarsq ping

**Comment by ebraminio** [comment]
Just these four Unicode characters are needed, I don't think they have presentation form even.

**Comment by nizarsq** [comment]
I am sorry I was busy with other projects, I will work on it tomorrow. Thanks

**Comment by nizarsq** [comment]
@ebraminio Could you check if ۋ  (U+06CB) also have an issue?

**Comment by ebraminio** [comment]
Yes
![image](https://cloud.githubusercontent.com/assets/833473/19089220/43baf004-8a86-11e6-913f-60f4eb8baec3.png)
But what I actually meant was just those four are needed as I know adding all of Arabic characters to Nastaliq font is not practical.

**Comment by ebraminio** [comment]
Steps to repro:

Open https://ur.wikipedia.org/wiki/%D8%A7%DB%8C%D8%B1%D8%A7%D9%86

Click on this button:

![image](https://cloud.githubusercontent.com/assets/833473/19089885/f1025188-8a88-11e6-9f1d-4c65f75d6e7f.png)

Names with character missing:
![image](https://cloud.githubusercontent.com/assets/833473/19089945/2a32af0c-8a89-11e6-8c0e-85e71719c45c.png)

![image](https://cloud.githubusercontent.com/assets/833473/19089947/2ed6f00e-8a89-11e6-81c6-f14138ab9000.png)

![image](https://cloud.githubusercontent.com/assets/833473/19089919/0d8b6fa6-8a89-11e6-8a40-a5a022df4329.png)

**Comment by KrasnayaPloshchad** [comment]
That would make conveniences to Urdu Wikipedia users. BTW I think ۇ should have localized glyphs.

**Comment by roozbehp** [comment]
I would actually recommend against the Noto Nastaliq font doing this, since the list is actually open-ended. Wikipedia can add a language tomorrow that needs yet another letter.

Also, these are language names in the language itself that may not be prefer Nastaliq style at all. For example, modern Uighur (where the spelling of the language name would be ئۇيغۇرچە), is almost always written in Naskh style. Wikipedia should use a Naskh-style to show it too, even on an Urdu wiki.

**Comment by KrasnayaPloshchad** [comment]
@roozbehp Oh yeah, I think Urdu Wikipedia should add an CSS exception for that area.

**Comment by ebraminio** [comment]
> I think Urdu Wikipedia should add an CSS exception for that area. Is there anyway to contact their administrator?

Done. Lets move forward, thanks :)
