### ISSUE TITLE
Ha Na Ca Ra Ka

### ISSUE THREAD

**Issue by dkuspawono** [googlei18n/noto-fonts#608]
Ha Na Ca Ra Ka
Da Ta  Sa Wa La
Pa  Da Ja Ya  Nya
Ma Ga Ba Ta  Nga
it is about twenty basic alphabets of javanese 
in javanese language
.. but what's about font ..

**Comment by dkuspawono** [comment]
:diamond_shape_with_a_dot_inside::diamond_shape_with_a_dot_inside::diamond_shape_with_a_dot_inside: :1234: :+1:

**Comment by dougfelt** [comment]
What's your question?  NotoSansJavanese has these characters in it.  You have to use the Unicode Javanese characters, English transliteration won't work without an input method to convert it.

**Comment by marekjez86** [comment]
Javanese font is at https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoSansJavanese-Regular.ttf
