### ISSUE TITLE
Glyph change for Sharada vocalic L and vocalic LL

### ISSUE THREAD

**Issue by roozbehp** [googlei18n/noto-fonts#609]
Unicode just accepted http://www.unicode.org/L2/L2015/15255-sharada-vocalic-vs.pdf which fixes the Sharada glyphs for vocalic L and vocalic LL. The fixes will be in Unicode 9.0.

The Sharada fonts the Noto project would be designing should make sure to use the correct glyph shapes from that document.

**Comment by marekjez86** [comment]
@waksmonskiMT : this is for the future; nothing needs to be done until we start working on the Sharada fonts
