### ISSUE TITLE
Kannada fonts should support Indic fractions

### ISSUE THREAD

**Issue by roozbehp** [googlei18n/noto-fonts#610]
Unicode just accepted http://www.unicode.org/L2/L2015/15243-kannada-frac.pdf for Unicode 9, which clarifies that certain Indic fraction signs are used in Kannada (potentially with a different style).

They should be added to the Noto Kannada fonts.

/cc @waksmonskiMT

**Comment by marekjez86** [comment]
@dougfelt : could you add these to the checklist?

**Comment by sridatta1** [comment]
This issue may be closed, It's fixed in Both Phase III Noto Sans and Serif Kannada fonts

**Comment by marekjez86** [comment]
@sridatta1 : thank you for verifying it
