### ISSUE TITLE
woff version of noto-fonts?

### ISSUE THREAD

**Issue by ozawa-hi** [googlei18n/noto-fonts#611]
Would like to have noto fonts in woff format.

**Comment by dougfelt** [comment]
We do not reserve the font name 'Noto', for this very reason.

**Comment by jungshik** [comment]
@ozawa-hi, there are multiple tools to generate woff and woff2. For instance, you can use fonttools at https://github.com/behdad/fonttools

**Comment by code-tree** [comment]
I think the point is to just save that extra step of everyone doing it themselves, but yes, it isn't too difficult.

**Comment by ozawa-hi** [comment]
Sorry. The original questions was because of the licensing. The license states not to use the original font name when the font is modified. I was concerned if generating woff and woff2 would be a "modification" so that I would have to change the font name to something else - I didn't want to do that.
