### ISSUE TITLE
Zip Download for Noto CJK

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#62]
```
(From Stuart)

The zip download shouldn't have hinted in the name. It doesn't really mean 
anything in the context of CFF and it will probably be confusing.
```

Original issue reported on code.google.com by `roozbeh@google.com` on 16 Jul 2014 at 8:43

**Comment by behdad** [comment]
cc @roozbehp @fontguy @xiangyexiao @jungshik

**Comment by fontguy** [comment]
Moved to https://github.com/googlei18n/noto-cjk/issues/2
