### ISSUE TITLE
Devanagri Keyboard 

### ISSUE THREAD

**Issue by quakig** [googlei18n/noto-fonts#625]
This is my first attempt at publishing a Hindi website, so excuse my ignorance.

This is how the Hindi typewriter is laid out. This is the layout on which most of the professionally trained Hindi Typists learn to type.

![800px-hindi_typewriter](https://cloud.githubusercontent.com/assets/2546691/13035647/041e8a72-d37b-11e5-90b3-48350ba6899f.jpg)

Here's another mapping for a popular Hindi font, the Kruti Dev Font which follows the same pattern as above:
![index](https://cloud.githubusercontent.com/assets/2546691/13035578/a57ac752-d379-11e5-831f-d104cebbf876.jpeg)

However the mappings of Noto Font are entirely different from the above layout.

So if a professional Hindi typist, wants to use Noto Devanagri Sans font, won't he have to re-learn Hindi typing?

Is this mapping a conscious decision ? Does it offer any particular advantage ?
Or am I missing something ?

**Comment by Kanjilearner817** [comment]
Please add label "Script-Devanagari" to this issue.

**Comment by dougfelt** [comment]
What do you mean by "mappings of Noto font"? The font doesn't have an input
method. Noto uses Unicode encoding, and your input method software has to
generate Unicode.

**Comment by quakig** [comment]
@dougfelt -

Here's what I mean by 'mappings of Noto font'.

In India, we mostly use the QUERTY keyboard to type Hindi. There is no such thing as a separate Hindi Keyboard.

So when I type say the key 'Y' in Microsoft word, most  of the Hindi Fonts will show the Hindi alphabet 'ल' . But with Noto Fonts Devanagri selected, it types 'ब' which is different than what a Hindi Typist expects.  There is a similar difference for all other keys, making it almost impossible for a Hindi typist to work his way through it.

I understand that the font does not have an Input method, but as an end user, it simply does not work with Microsoft word, which is what is used all over India for typing.

**Comment by moyogo** [comment]
@quakig 
The [Devanagari InScript](https://en.wikipedia.org/wiki/InScript_keyboard) keyboard layout maps the Y-key to ब.
You’ll have to install and use a Unicode keyboard layout with the Remington or GAIL layout if you want the Y-key to map to ल.

You can get that keyboard layout from http://bhashaindia.com/ilit/Hindi.aspx. The manual: http://bhashaindia.com/SiteCollectionDocuments/Downloads/IME/Indic3/helpfiles/Hindi%20Indic%20Input%203-User%20Guide.pdf.

**Comment by quakig** [comment]
@moyogo - that solved the issue. Thanks a lot !

**Comment by dougfelt** [comment]
I have trouble understanding how Noto Devanagari would have behaved differently from other fonts when using the exact same input method.  How is it that 'most of the Hindi fonts' produce one character when you type 'Y', while Noto shows something different?  How is it that changing the input method makes the fonts behave the same when they formerly behaved differently?

**Comment by miguelsousa** [comment]
@dougfelt the other fonts are probably not Unicode-encoded.

**Comment by jungshik** [comment]
Anyway, this is not a font bug.
