### ISSUE TITLE
NotoSans Syriac (all three of them) fonts have 2 box drawing characters

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#627]
NotoSans Syriac fonts (three of them) have some unexpected characters. 

1. Two box drawing characters : U+250C, U+2510
2. Combining marks in U+03xx block

**Comment by jungshik** [comment]
Spun off from #617

**Comment by roozbehp** [comment]
Combining marks is intentional. See the Syriac section in the Unicode standard. But I the box drawing characters are weird.

**Comment by jungshik** [comment]
Thank you, @roozbehp, for info on U+03xx block! I meant to check TUS (I just did : Table 9-12).  
BTW, what's your take on ZWSP that is also in Syriac (and other script fonts)?

**Comment by roozbehp** [comment]
IIRC the Microsoft specs calls for ZWSP being in some fonts. But I don't really know.

**Comment by jungshik** [comment]
That's my vague recollection, too, but I couldn't find a reference. Oh I just found one (not the same one that I saw in the past, but still relevant): 

https://www.microsoft.com/typography/OpenTypeDev/USE/intro.htm  : see the section titlled 'Recommended glyphs' that starts with "Unicode code points that are recommended for inclusion in any font using the USE are"

@dougfelt

**Comment by dougfelt** [comment]
I don't see a motivation for some of the Recommended Glyphs listed in the
document Jungshik referenced.  Here's the list:

U+200B Zero Width Space
U+200C Zero Width Non-Joiner
U+200D Zero Width Joiner
U+25CC Dotted Circle
U+00A0 No-break space
U+00D7 Multiplication sign
U+2012 Figure dash
U+2013 En dash
U+2014 Em dash
U+2015 Horizontal bar
U+2022 Bullet
U+25FB White medium square
U+25FC Black medium square
U+25FD White medium small square
U+25FE Black medium small square
Spaces, joiners, dotted circle, I can understand. Dashes and bar, well
maybe, but they seem like punctuation and that depends on the script. The
multiplication sign, bullet, and squares, I don't.

Does anyone have any insight on this?

**Comment by roozbehp** [comment]
Starting from the dotted circle down, these are basically what Microsoft thinks should be possible to be used as bases for showing individual combining marks. I definitely know that multiplication sign and dashes are used in some South and Southeast Asian languages as bases for combining vowels etc. I don't know if bullets and square are used too.

**Comment by dougfelt** [comment]
So then, it would seem that for all of the fonts/scripts USE supports, we
want to include this set of characters in the cmap.

What is the set of scripts that USE supports?  Is it a subset of the
scripts Harfbuzz considers complex?  For reference, I have the following
(based on hb-ot-shape-complex-private):

    Arab Aran Bali Batk Beng Brah Bugi Buhd Cakm Cham Deva Dupl Egyp Gran
    Gujr Guru Hang Hano Hebr Hmng Java Kali Khar Khmr Khoj Knda Kthi Lana
    Laoo Lepc Limb Mahj Mand Mani Mlym Modi Mong Mtei Mymr Nkoo Orya Phag
    Phlp Rjng Saur Shrd Sidd Sind Sinh Sund Sylo Syrc Tagb Takr Tale Talu
    Taml Tavt Telu Tfng Tglg Thai Tibt Tirh


On Mon, Feb 22, 2016 at 2:59 PM, Roozbeh Pournader <notifications@github.com

**Comment by jungshik** [comment]
@dougfelt If you dig into harfbuzz source a bit more, you'll also see which scripts are currently routed to USE (that may not be the same set of scripts as Windows routes to USE, though).

**Comment by Kanjilearner817** [comment]
Microsoft list all of those on [their USE page](https://www.microsoft.com/typography/OpenTypeDev/USE/intro.htm) except for the following, as the existing shaping engines for them apparently work just fine for now (Aran is treated as Arab):

    Arab Aran Beng Deva Gujr Guru Hang Hebr Khmr
    Knda Laoo Mlym Mymr Orya Syrc Taml Telu Thai

> What is the set of scripts that USE supports?  Is it a subset of the
scripts Harfbuzz considers complex?  For reference, I have the following
(based on hb-ot-shape-complex-private):

    Arab Aran Bali Batk Beng Brah Bugi Buhd Cakm Cham Deva Dupl Egyp Gran
    Gujr Guru Hang Hano Hebr Hmng Java Kali Khar Khmr Khoj Knda Kthi Lana
    Laoo Lepc Limb Mahj Mand Mani Mlym Modi Mong Mtei Mymr Nkoo Orya Phag
    Phlp Rjng Saur Shrd Sidd Sind Sinh Sund Sylo Syrc Tagb Takr Tale Talu
    Taml Tavt Telu Tfng Tglg Thai Tibt Tirh

**Comment by xiangyexiao** [comment]
@waksmonskiMT we want two box drawing characters : U+250C, U+2510 to be removed from the three Syriac fonts by end of April, the earlier the better.

**Comment by xiangyexiao** [comment]
@waksmonskiMT update on timeline. We want the fix to happen by end of March. Let me know if it is infeasible.

**Comment by jungshik** [comment]
@xiangyexiao Alternatively, we can just drop them from Phase 2 Syriac fonts very easily unless MTI already has done that.

**Comment by xiangyexiao** [comment]
sounds good. Then we can get Monotype to get the updated fonts from GitHub. @waksmonskiMT have you done this?
