### ISSUE TITLE
Wrong vertical alignment of spacing modifier characters

### ISSUE THREAD

**Issue by sommerluk** [googlei18n/noto-fonts#629]
Consider the following characters:

![example](https://cloud.githubusercontent.com/assets/6830724/13380678/4e053b20-de40-11e5-9281-f5b1cfa18305.png)

It’s the characters “shtre” as spacing modifier characters. Currently, Noto displays s, h and r a little lower. And it displays t and e a little higher. I would expect instead all modifier characters (all types: small characters, capital characters, punctuation marks etc …) to be vertically alligned.

**Comment by moyogo** [comment]
This was brought up in #438.

**Comment by marekjez86** [comment]
Closing this as a duplicate of https://github.com/googlei18n/noto-fonts/issues/438

**Comment by marekjez86** [comment]
#438
