### ISSUE TITLE
Some new characters?

### ISSUE THREAD

**Issue by sommerluk** [googlei18n/noto-fonts#630]
Noto has an increasing coverage, also for new languages.

Are there also plans for adding more general and mathematical symbols? Especially, I’m interested in

✓	U+2713 Name: CHECK MARK
✔	U+2714 Name: HEAVY CHECK MARK
‣	U+2023 Name: TRIANGULAR BULLET
✂	U+2702 Name: BLACK SCISSORS
⌀	U+2300 Name: DIAMETER SIGN
≙	U+2259 Name: ESTIMATES
↗	U+2197 Name: NORTH EAST ARROW
∶	U+2236 Name: RATIO

**Comment by dougfelt** [comment]
We're currently working on 'phase 3' of the Noto fonts, which will support all Unicode characters in the BMP (and more).  These fonts are under development.

**Comment by sommerluk** [comment]
> We're currently working on 'phase 3' of the Noto fonts, which will
> support all Unicode characters in the BMP (and more).

Great news! And for sure a lot of work. Thanks for your effort!

**Comment by roozbehp** [comment]
All of the characters you asked for should also already be available, most probably in Noto Sans Symbols.
