### ISSUE TITLE
Add U+20BF to Noto Sans Symbol (phase 2)

### ISSUE THREAD

**Issue by jungshik** [googlei18n/noto-fonts#631]
Spun off from #548. 
#548 is for adding U+20BF to Noto Sans and Noto Serif in Phase 3. 

This is to add U+20BF (Bitcoin symbol) to Noto Sans Symbol in Phase 2 TTF. 

@xiangyexiao

**Comment by xiangyexiao** [comment]
I have verified 20bf has been added to Noto Sans Symbols. @dougfelt please push to the repo
