### ISSUE TITLE
Noto Serif CJK/Source Han Serif?

### ISSUE THREAD

**Issue by Kanjilearner817** [googlei18n/noto-fonts#639]
Are there any plans for a future serif counterpart to Noto Sans CJK/Source Han Sans?

**Comment by ShikiSuen** [comment]
I already consulted @kenlunde in 2014 regarding such request. He said he couldn't comment on such things: https://twitter.com/ken_lunde/status/496449348482244609

Still I don't know whether it is still a classified topic or not.

**Comment by kenlunde** [comment]
Nothing has changed since that 2014 tweet.

**Comment by kenlunde** [comment]
Also, this should have been posted in [noto-cjk](https://github.com/googlei18n/noto-cjk/issues).
