### ISSUE TITLE
Noto Sans Coptic: issue with continuous macrons for Coptic

### ISSUE THREAD

**Issue by signinstranger** [googlei18n/noto-fonts#653]
It seems that the Unicode characters U+FE24 and U+FE25 used for continuous macrons in Coptic are swapped in Noto Sans Coptic. The sequence ϩ︤ⲛ︥ renders correctly in the Coptic font Antinoou, but in Noto Sans the macrons are placed on opposite ends of the letters ϩⲛ. Since Antinoou is the only Coptic Unicode font that features half macrons (IFAO Copte doesn't seem to have them), it might well be that issue lies with Antinoou. Although it seems more logical to me that the entering sequence should be

> first Coptic character + U+FE24 + second Coptic character + U+FE25

and not 

> first Coptic character + U+FE25 + second Coptic character + U+FE24

**Comment by TidharC** [comment]
It seems U+FE24 and U+FE25 are half macrons in Noto Sans Coptic.  Entering the chars in the order:
03E9 2C9B FE24 FE25
places a full macron on top of the letter Ni ⲛ  This looks conistent with sample Coptic printed text.
Antinoou's rendering of the same sequence looks broken.

Please compare the screenshots to your results and advise.

![copticgospel](https://cloud.githubusercontent.com/assets/16353803/18770696/8ac76808-80ed-11e6-8493-58a7b8b5713b.png)
![copticmacrons](https://cloud.githubusercontent.com/assets/16353803/18770703/98117738-80ed-11e6-8690-0f7b5470c573.png)

**Comment by signinstranger** [comment]
Thank you for looking into this. The rendering of both half macrons in Noto is indeed correct. I don't know what caused the swapping of the characters on my machine but it is gone now. You can close the issue.
