### ISSUE TITLE
Glyph correction needed for Sundanese Letter JA (1B8F)

### ISSUE THREAD

**Issue by diantn** [googlei18n/noto-fonts#657]
http://unicode.org/cldr/trac/ticket/9344

[quote]
we've spotted mistake in the Glyph shown for Sundanese Letter JA (1B8F) in this document:
​http://unicode.org/charts/PDF/U1B80.pdf

The mistake is at the top part of the glyph.
Currently it is displayed as Z shaped

In fact, the top part should be similar to the Sundanese Letter DA (1B93).

The font which implements this correction can be found in:
​http://www.kairaga.com/2015/05/05/font-aksara-sunda-unicode-versi-2013-revisi.html
[/quote]

**Comment by diantn** [comment]
The earliest Sundanese code chart in Unicode 5.1 still depicts the correct Sundanese Letter JA.
ftp://unicode.org/Public/5.1.0/charts/CodeCharts.pdf

**Comment by diantn** [comment]
Unicode Errata on 2016-04-20 already recorded this issue:
http://unicode.org/errata/

![sundaneseja](https://cloud.githubusercontent.com/assets/4076139/15103795/edde4e0e-15d9-11e6-962d-5608cf61e5e3.png)

**Comment by TidharC** [comment]
I am able to repro this (see screenshot).

![notosanssundaneseja](https://cloud.githubusercontent.com/assets/16353803/18897469/8a618cd6-84df-11e6-9c16-0de270c2cc65.png)

**Comment by Ilhamkang** [comment]
The shape of JA has been revised on Unicode 10. Please do correction for the glyph. 

Check the latest Sundanese Unicode chart: 
http://unicode.org/charts/PDF/U1B80.pdf

**Comment by ALloydMT** [comment]
This character has now been corrected and will be available in the next release.

**Comment by marekjez86** [comment]
@diantn , @Ilhamkang : please check  the correction in the font below and let us know. Thank you!

[NotoSansSundanese-Regular.otf.zip](https://github.com/googlei18n/noto-fonts/files/1516412/NotoSansSundanese-Regular.otf.zip)

**Comment by Ilhamkang** [comment]
The glyph shape is now correct. 
Thanks for this correction @marekjez86!

**Comment by marekjez86** [comment]
actually thanks to @ALloydMT ! thank you
