### ISSUE TITLE
Proposal: Quick Noto fonts FAQ

### ISSUE THREAD

**Issue by twardoch** [googlei18n/noto-fonts#662]
Guys, here’s my take on a “Quick Noto fonts FAQ”, adapted from some of the most important FAQ&A from the OFL-FAQ. Feel free to publish it anywhere, as long as you agree with the answers, of course.   

## Quick Noto fonts FAQ

**The Noto fonts are free for anyone to use in any projects, including commercial products.** The Noto fonts are published under the [SIL Open Font License version 1.1](http://scripts.sil.org/OFL) (OFL). This means that you can use the Noto fonts to create physical or electronic products, documents and apps, and you can distribute your creations for free or sell them commercially. You can also create and distribute modified versions of the Noto fonts.

The OFL license only has a few important **restrictions**: you cannot sell the original or modified Noto fonts by themselves, and if you create modified versions of the Noto fonts, you need to keep the original copyright info and license terms. Below are some most important **questions and answers** regarding the Noto fonts. For more details, consult the [OFL](http://scripts.sil.org/OFL) and the [OFL-FAQ](http://scripts.sil.org/OFL-FAQ_web). 

Question: **Can I use the Noto fonts in books or other print publications, to create logos or other graphics or even to manufacture objects based on their outlines? Can I sell the publications and objects created using the Noto fonts?**

Answer: **Yes and yes.** You can use the Noto fonts to create books, magazines, newspapers, logos, posters, business cards, stationery, video titling, signage, t-shirts, personalised fabric, 3D-printed/laser-cut shapes, sculptures, rubber stamps, cookie cutters, lead type, and any other physical objects. And you can distribute the objects created using the Noto fonts for free or sell them commercially. No payment and no additional license or permission is required. 

Question: **Can I embed the Noto fonts in documents? Can I sell the documents created using the Noto fonts?**

Answer: **Yes and yes.** You can embed the fonts inside documents in PDF, Word or any other formats, and you can distribute such documents for free or commercially. 

Question: **Can I host the fonts on a server, for enterprise-wide or for public use?**

Answer: **Yes.** You can make available the original or modified Noto fonts across your company or enterprise, and also to the general public, either in full or a subset. If you create modified versions of the fonts, you need to keep the original copyright and license information of the original Noto fonts inside the modified fonts. 

Question: **Can I distribute or sell a software package that includes the Noto fonts?**

Answer: **Yes.** You can bundle the Noto fonts with any mobile apps, word processors, design and publishing applications, training and educational software, games and entertainment software, etc. You can distribute these software apps for free or sell them commercially. No payment and no additional license or permission is required.  

Question: **Can I convert the Noto into other formats such as WOFF or EOT, add or remove glyphs to them or modify them in any way? Can I distribute such modified versions of the fonts?**

Answer: **Yes and yes.** The only restriction is that you cannot sell such modified fonts by themselves, but you can sell them as part of larger packages. If you create modified versions of the fonts, you need to keep the original copyright and license information inside the modified fonts. The Noto fonts don’t use the “Reserved Font Name” mechanism described in the OFL license, so you don’t need to change the names of the Noto fonts when making converted or modified versions. 

For **more questions and answers** regarding fonts licensed under [OFL](http://scripts.sil.org/OFL) (such as Noto), please visit the [OFL-FAQ](http://scripts.sil.org/OFL-FAQ_web) website. Please remember that the Noto fonts don’t use the “Reserved Font Name” mechanism, so the RFN restrictions of OFL don’t apply to Noto.

**Comment by xiangyexiao** [comment]
Thanks, @twardoch. I really appreciate your enthusiasm for helping us and supporting Noto. Also thanks for your time on writing this.

I checked with our lawyer. Unfortunately, we cannot give other people/companies legal advices. They have to decide what can and cannot be done with Noto by themselves. The only accurate thing we can say is that the fonts are under OFL.
