### ISSUE TITLE
U+0460 and U+047E

### ISSUE THREAD

**Issue by DLasher106** [googlei18n/noto-fonts#668]
One more from http://www.unicode.org/versions/Unicode5.1.0/erratafixed.html.

The designs of U+0460 CYRILLIC CAPITAL LETTER OMEGA and U+047E CYRILLIC CAPITAL LETTER OT should resemble the lowercase U+0461 and U+047F.

**Comment by TidharC** [comment]
The issue is reproducible, but not limited to Noto (see, for example, Courier New in the screenshot).
![notosans-0460-047e](https://cloud.githubusercontent.com/assets/16353803/18769177/b53b12e6-80df-11e6-952a-91c29de9a537.png)

**Comment by TidharC** [comment]
@DLasher106,

Here are the current renderings for Noto Sans and Noto Serif.  Please review and advise if they seem correct.

[specimenNotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/626134/specimenNotoSans-Black.pdf)
[specimenNotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/626133/specimenNotoSansDisplay-Black.pdf)
[specimenNotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/626135/specimenNotoSansDisplay-Italic.pdf)
[specimenNotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/626137/specimenNotoSans-Italic.pdf)
[specimenNotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/626136/specimenNotoSansMono-Regular.pdf)
[specimenNotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/626138/specimenNotoSerif-Black.pdf)
[specimenNotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/626141/specimenNotoSerifDisplay-Black.pdf)
[specimenNotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/626140/specimenNotoSerifDisplay-Italic.pdf)
[specimenNotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/626139/specimenNotoSerif-Italic.pdf)

**Comment by DLasher106** [comment]
Yes, those look OK.

**Comment by marekjez86** [comment]
comment from MTI: "Design new uni0460 and uni047E (decompose uniA7B6 to use old shape)"

**Comment by marekjez86** [comment]
All Noto fonts + Roboto look fine

sample
```html
<html lang="en">
<p><span style="font-size:48.0px">"Ѡ ѡ Ѿ ѿ"</span></p>
</html>
```

[en-668-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683680/en-668-NotoSans-Black.pdf)
[en-668-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683682/en-668-NotoSans-Italic.pdf)
[en-668-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683681/en-668-NotoSans-Regular.pdf)
[en-668-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683683/en-668-NotoSansDisplay-Black.pdf)
[en-668-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683684/en-668-NotoSansDisplay-Italic.pdf)
[en-668-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683685/en-668-NotoSansDisplay-Regular.pdf)
[en-668-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683686/en-668-NotoSansMono-Black.pdf)
[en-668-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683687/en-668-NotoSansMono-Regular.pdf)
[en-668-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683690/en-668-NotoSerif-Black.pdf)
[en-668-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683688/en-668-NotoSerif-Italic.pdf)
[en-668-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683689/en-668-NotoSerif-Regular.pdf)
[en-668-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683691/en-668-NotoSerifDisplay-Black.pdf)
[en-668-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683692/en-668-NotoSerifDisplay-Italic.pdf)
[en-668-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683694/en-668-NotoSerifDisplay-Regular.pdf)
[en-668-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683693/en-668-Roboto-Black.pdf)
[en-668-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683695/en-668-Roboto-Italic.pdf)
[en-668-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683696/en-668-Roboto-Regular.pdf)
