### ISSUE TITLE
Support Siddham

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [googlei18n/noto-fonts#672]
The [Siddhaṃ script](https://en.wikipedia.org/wiki/Siddha%E1%B9%83_script) is a script used for writing Sanskrit from ca 600-1200, this script has already introduced in Unicode, but no Noto fonts support it.

**Comment by Kanjilearner817** [comment]
@KrasnayaPloshchad Siddham was introduced in Unicode 7.0, which will be covered in Phase III.
