### ISSUE TITLE
Latin small letter beta/chi for IPA

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#692]
https://groups.google.com/forum/#!topic/noto-font/BgGv5gpv-K8
When resolved, we should also reply to the user on the mailing list.

**Comment by moyogo** [comment]
When Latin ꞵ U+A7B5 and ꭓ U+AB53 are added, there should be a substitution for <IPPH> to display Greek β U+03B2 and χ U+03C7 with those Latinized glyphs (when different), as suggested in #489.

**Comment by TidharC** [comment]
I checked Noto Sans and Noto Serif.  It seems neither U+A7B5 nor U+AB53 is included in the two fonts.  Also, I see no indication of substitutions:

U+A7B5 ==> U+03B2
U+AB53 ==> U+03C7

**Comment by jungshik** [comment]
@TidharC did you check the latest delivery/build in alpha/ ?

**Comment by marekjez86** [comment]
note from MTI: "In Sans: OpenType substitutions are not needed because the Greek letters added (A7B5 and AB53) are not different than the Greek beta and chi. In Serif: Add OpenType locl GSUB substitutions for Greek letters beta and chi to be substituted by uniA7B5 and uniAB53 in languages IPPH and APPH."

**Comment by marekjez86** [comment]
grep A7B5 *.glyphs */*.glyphs | grep -i unicode in the src directory yields

NotoSans-ItalicMM.glyphs:unicode = A7B5;
NotoSans-MM.glyphs:unicode = A7B5;
NotoSansDisplay-ItalicMM.glyphs:unicode = A7B5;
NotoSansDisplay-MM.glyphs:unicode = A7B5;
NotoSansMono-MM.glyphs:unicode = A7B5;
NotoSerif-ItalicMM.glyphs:unicode = A7B5;
NotoSerif-MM.glyphs:unicode = A7B5;
NotoSerifDisplay-ItalicMM.glyphs:unicode = A7B5;
NotoSerifDisplay-MM.glyphs:unicode = A7B5;

grep AB53 *.glyphs */*.glyphs | grep -i unicode
NotoSans-ItalicMM.glyphs:unicode = AB53;
NotoSans-MM.glyphs:unicode = AB53;
NotoSansDisplay-ItalicMM.glyphs:unicode = AB53;
NotoSansDisplay-MM.glyphs:unicode = AB53;
NotoSansMono-MM.glyphs:unicode = AB53;
NotoSerif-ItalicMM.glyphs:unicode = AB53;
NotoSerif-MM.glyphs:unicode = AB53;
NotoSerifDisplay-ItalicMM.glyphs:unicode = AB53;
NotoSerifDisplay-MM.glyphs:unicode = AB53;
