### ISSUE TITLE
Check rendering of Latin l

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#695]
See https://groups.google.com/forum/#!topic/noto-font/SMstNVwT_UI. We should try to reproduce this, and follow up with the reporter if it’s not reproducible. Also, kerning doesn’t look great.

**Comment by dougfelt** [comment]
Original post:
![screen shot 2016-04-15 at 2 12 36 am](https://cloud.githubusercontent.com/assets/9939212/15615371/c8a5ad22-23f2-11e6-8f22-67aebbe303ff.png)

My attempt to replicate:
![rit](https://cloud.githubusercontent.com/assets/9939212/15615277/2adf9800-23f2-11e6-830d-fdd554cf5a4c.png)

This is Noto Sans 38pt Bold, rendered using my linux box.  I don't see the tight spacing, and I can't match the weight if I render at the size of the original as seen here (140pt).  The serifs are angled.  I would have expected them to be straight and match the thickness of the bar of the T, but I'm no expert and perhaps in other contexts (e. g. mixed-case) the I looks better.

We need to ask how the original poster generated the image.

**Comment by hrhatada** [comment]
If you compare the font with others (e.g. Helvetica, Microsoft San Serif, Arial), you can see the spacing between the char "RIT" & "RA" looks tighter than other chars.  Please refer to the attached screenshot.

![2016-09-23 1 43 37 pm](https://cloud.githubusercontent.com/assets/16353449/18801257/8a963afe-8196-11e6-8ca1-e614e01a58ab.png)

![2016-09-23 1 44 31 pm](https://cloud.githubusercontent.com/assets/16353449/18801263/92b02d26-8196-11e6-89d7-31cc31af8abe.png)

![fontcompareonie](https://cloud.githubusercontent.com/assets/16353449/18801270/9bd155d8-8196-11e6-94ff-efd6b2b1177d.png)

![notosans_iiissue_win](https://cloud.githubusercontent.com/assets/16353449/18801276/a5aa583e-8196-11e6-8eef-3e16390d5f8c.png)

**Comment by dougfelt** [comment]
OK, Sue, can someone look at the RIT here?  It does seem a bit tight.

**Comment by marekjez86** [comment]
[20160926150259327.pdf](https://github.com/googlei18n/noto-fonts/files/494249/20160926150259327.pdf)

IMHO Noto Sans is NOT that tight (see the measurements of a printed image which was adjusted to fit into US letter paper). IMHO, it is as designed.  I'm not certain why I has "serifs", but this is past history which I do not know.

**Comment by dougfelt** [comment]
So, @marekjez86 what course of action are you proposing here?  Sascha proposed replicating the behavior. Harumi replicated it.  I proposed that Sue have someone look at it.

Are you proposing that we just close the bug?

**Comment by marekjez86** [comment]
@waksmonskiMT : Sue, could you ask someone of the team that works on Noto Sans consider this feedback when preparing the next drop of LGC? Thank you.

**Comment by marekjez86** [comment]
![_r_caron](https://cloud.githubusercontent.com/assets/13322623/18877339/d2f7a0d8-8481-11e6-9193-bcf28b5ee7c8.png)
![_uni1e_c_a_](https://cloud.githubusercontent.com/assets/13322623/18877346/d5d33a74-8481-11e6-955d-b24612fea742.png)

The above images compare Regular with Bold for similar glyphs. Given that the next release will have {TRBH}x{CR} the design might need to be altered. If that's the case please take the above issue into consideration.

**Comment by marekjez86** [comment]
MTI response: "Spacing looks good as is"

**Comment by marekjez86** [comment]
sample
```html
<html lang="en">
<p><span style="font-size:48.0px">AVORITE</span></p>
<p><span style="font-size:48.0px">DOTSTRA</span></p>
</html>
```
yields the following

[en-695-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683727/en-695-NotoSans-Black.pdf)
[en-695-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683726/en-695-NotoSans-Italic.pdf)
[en-695-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683728/en-695-NotoSans-Regular.pdf)
[en-695-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683724/en-695-NotoSansDisplay-Black.pdf)
[en-695-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683725/en-695-NotoSansDisplay-Italic.pdf)
[en-695-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683729/en-695-NotoSansDisplay-Regular.pdf)
[en-695-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683730/en-695-NotoSansMono-Black.pdf)
[en-695-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683733/en-695-NotoSansMono-Regular.pdf)
[en-695-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683731/en-695-NotoSerif-Black.pdf)
[en-695-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683732/en-695-NotoSerif-Italic.pdf)
[en-695-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683734/en-695-NotoSerif-Regular.pdf)
[en-695-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683735/en-695-NotoSerifDisplay-Black.pdf)
[en-695-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683736/en-695-NotoSerifDisplay-Italic.pdf)
[en-695-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683737/en-695-NotoSerifDisplay-Regular.pdf)
[en-695-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/683738/en-695-Roboto-Black.pdf)
[en-695-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/683740/en-695-Roboto-Italic.pdf)
[en-695-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/683739/en-695-Roboto-Regular.pdf)

agreed not to change it
