### ISSUE TITLE
Noto Sans Coptic broken on Office for Mac?

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#698]
On https://groups.google.com/forum/#!topic/noto-font/nEX6qeMaYjI, we got a report that Noto Sans Coptic does not work in Office for Macintosh. We should check (sorry, I don’t have Office, otherwise I’d just have checked it myself) and reply to the reporter. Looking at the font, I don’t see anything wrong and our the [specimen](http://www.google.com/get/noto/#sans-copt) looks fine. But maybe it’s a weird interaction with Office, who knows. Sample text can be found here: https://en.wikipedia.org/wiki/Coptic_(Unicode_block)

**Comment by jungshik** [comment]
Replied to the email.

**Comment by jungshik** [comment]
This is an offline reply. I have an old version of MS Office for Mac and I'm afraid I can't reproduce this problem with that version. Below is an offline reply I got from the original reporter. 

> Hi, my OS is El Capitan 10.11.5, Office is Word for Mac 15.22.1.

> The function works fine with TextEdit as well as TextWrangler and Nisus. It is in word that several characters automatically switch over to Noto Sans Coptic and shows only tofu.
> 
> Here´s a sample: ⲥⲉⲥⳁⲟ︦ⲩ ⲙ̄ⲙⲟϥ·
> 
> In office when I enter in the first connective supralinear stroke, the font changes into Noto Sans Coptic and all subsequent text is only tofu until I turn it back into antinou (but the supralinear stroke itself remains a tofu). It seems that this is a Word for Mac related problem, but I don´t understand the role of Noto Sans Coptic in it.

**Comment by marekjez86** [comment]
Word on Mac issue
