### ISSUE TITLE
Rename Script-TaiLue to Script-TaiTham?

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#699]
In the GitHub repo “googlei18n/noto-fonts”, we have defined a label for [Script-TaiLue](https://github.com/googlei18n/noto-fonts/issues?q=is%3Aissue+is%3Aopen+tai+label%3AScript-TaiLue). But isn’t [Tai Lü](https://en.wikipedia.org/wiki/Tai_L%C3%BC_language) a language, and its script is called [Tai Tham](https://en.wikipedia.org/wiki/Tai_Tham_alphabet)? (Also in [Unicode](https://en.wikipedia.org/wiki/Tai_Tham_(Unicode_block))). So we probably should rename the label.

**Comment by dougfelt** [comment]
I expect it was shortened from NewTaiLue.  Anyway, I renamed it to TaiTham and created another label for NewTaiLue.  We don't have labels for all the scripts-- we probably should have them ready to go instead of creating them on demand.
