### ISSUE TITLE
Some Lao and Khmer fonts have extra cmap subtables

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#7]
```
The following fonts have extra cmap subtables, with platform IDs of 0 or 1. 
These cmap subtables should be removed:

hinted/NotoSansLao-Bold.ttx
hinted/NotoSerifKhmer-Regular.ttx
hinted/NotoSerifKhmer-Bold.ttx
hinted/NotoSansLao-Regular.ttx
hinted/NotoSansLaoUI-Regular.ttx
```

Original issue reported on code.google.com by `roozbeh@google.com` on 26 Jul 2013 at 2:05

**Comment by behdad** [comment]
cc @roozbehp

**Comment by jungshik** [comment]
Again, Khmer and Lao were not made by MTI. In phase 3, they'll improve upon the existing fonts and we'll put together cmap tables ourselves. 

For phase 2, we can just drop unnecessary cmap tables.

**Comment by jungshik** [comment]
I took a look all the Lao and Khmer fonts. Only Khmer Serif Regular and Bold have this issue and they're fixed now.
