### ISSUE TITLE
Script-Devanagari wrong rendering 

### ISSUE THREAD

**Issue by quakig** [googlei18n/noto-fonts#702]
How do I for example write the word 'Prem' in Hindi ?
Noto Devanagari font writes it as **प्रेम** which is clearly wrong.

It should instead be written as  shown in the following image.
![1](https://cloud.githubusercontent.com/assets/2546691/15601164/c7e76e7a-240b-11e6-8cf5-aaaea1db0f2a.png)

All such words made by combining letters प and र render incorrectly.

**Comment by jungshik** [comment]
@quakig,  can you copy and paste the word 'Prem" written in Devanagari (instead of Latin trasnliteration) here?

Thanks

**Comment by dougfelt** [comment]
Works correctly for me using hb-view on my system.  What operating system/software are you using to view this?

**Comment by quakig** [comment]
The font renders correctly. I don't know how i was getting that problem in the first place. Closing the issue.
