### ISSUE TITLE
Are languages being updated?

### ISSUE THREAD

**Issue by kmuncie** [googlei18n/noto-fonts#706]
I see some active development here being done for languages, but when I look at https://www.google.com/get/noto/ it seems like nothing has been updated for some time. Do the downloads accessed there represent the latest version of these fonts or are they frozen in time until the work being done here is released?

I am just striving to keep my font stacks up to date with all the hard work being done here but its hard to know without version numbers.

**Comment by dougfelt** [comment]
Yes, this is my bad.  I've neglected to update the site for awhile, we were doing a small redesign and then other projects got in the way.  For what it's worth, it should update soon.

The noto-fonts, noto-cjk, and noto-emoji repositories on github are the primary staging areas and the fonts here are current (although fonts in noto-fonts/alpha is not quite ready for use yet).  When we update the get/noto site, these locations are where the fonts are sourced from.
