### ISSUE TITLE
Mac and Linux issues

### ISSUE THREAD

**Issue by liamcoded** [googlei18n/noto-fonts#709]
Hello, none of the fonts have worked in the past 4 or 5 months(if memory serves me right). They just render as regular fonts. I am looking to used  Noto Sans Glagolitic and Noto Sans Gothic. 

Until recently I have used MacBook Pro with Mavericks, and have only recently changed to El Capitan. But that hasn't fixed anything. They stoped working under Mavericks and Ubuntu, as I said about 4 to 5 months. 

Apps where I have tried using them are Sketch 3, Pages, Inkscape. There are others for creation of comic books but these mentioned are the most important. Please, help. Pages app won't even display them as a choice.

**Comment by brawer** [comment]
To reproduce this bug report, I’ve installed Noto Sans Glagolitic on MacOS X El Capitan 10.11.5, opened Pages 5.6.2, and pasted some Glagolitic characters. Here’s a screenshot; would you have expected anything different?

<img width="872" alt="pages with noto sans glagolitic" src="https://cloud.githubusercontent.com/assets/1527880/15813469/a09b5410-2bbf-11e6-89b8-2d2e8b21c14f.png">

Just wondering—maybe the Noto Sans font is perfectly fine, but you’re having trouble to _enter_ Glagolitic characters? Try copy/pasting the characters below:

```
ⰀⰁⰂⰃⰄⰅⰆⰇⰈⰉⰊⰋⰌⰍⰎⰏ
ⰐⰑⰒⰓⰔⰕⰖⰗⰘⰙⰚⰛⰜⰝⰞⰟ
ⰠⰡⰢⰣⰤⰥⰦⰧⰨⰩⰪⰫⰬⰭⰮ
ⰰⰱⰲⰳⰴⰵⰶⰷⰸⰹⰺⰻⰼⰽⰾⰿ
ⱀⱁⱂⱃⱄⱅⱆⱇⱈⱉⱊⱋⱌⱍⱎⱏ
ⱐⱑⱒⱓⱔⱕⱖⱗⱘⱙⱚⱛⱜⱝⱞ
```

**Comment by liamcoded** [comment]
Thank you for the message. Appears that you are right. Something must be wrong on my end. Because I copied and pasted text just fine but it doesn't appear as an option in Pages, and in Sketch I can choose the font it's just not changing anything if picked. In Pages only Noto Serif and Noto Sans work.

![inpages](https://cloud.githubusercontent.com/assets/9016588/15814770/619473ae-2b8e-11e6-8163-34bfb1ee97ab.jpg)

![insketch](https://cloud.githubusercontent.com/assets/9016588/15814815/9930c5c4-2b8e-11e6-8447-6094218f9724.jpg)

**Comment by brawer** [comment]
Ah, I believe I understand what’s going on here. In recent versions of MacOS X, Apple has started to package certain Noto fonts into the operating system. This is great, and very much appreciated by Google. For example, if you select “Helvetica” as the font in Pages, and then enter Glagolitic text, MacOS will behind the scenes fall back to a pre-installed version of Noto Sans Glagolitic that isn’t shown in any font menu. If you then install Noto Sans Glagolitic as a separate font, you can of course select it explicitly from the font menu, but that second font happens to look exactly like the pre-installed hidden fallback font.

This user interface is indeed a bit confusing, but clearly much better than if MacOS showed “tofu” boxes. Also, there’s not much we could do about it from the fonts side. Therefore, I’m closing this bug; but feel free to re-open in case you think the font should change. Also, please don’t hesitate to tell if the font has missing glyphs, has bad kerning, etc.; we’re really appreciating your feedback.

**Comment by liamcoded** [comment]
Since this is not a bug, is there a way I could ask you few questions some other way? I mean there were no Noto fonts on my MacBook once I installed El Capitan. I see no way to convert any sort of writing to glagolitic, or to even write in it. Last part would be really hard, even if I could type in glagolitic, since it's a dead language, old church slavonic. 

I need to write it in a alphabet before converting it and it's not letting me do that. I have no idea why copy and paste from your post worked at all. And I see no way to interact with glagolitic font, and I haven't found anyone that has this same problem. Is there anything you can tell me how to use it or point me to a resource regarding it's use, if I missed any?

Even if Noto Sans and Noto serif came with OS X, it still not letting me use other fonts. The only place I can see some of them is in the Font Book. Some don't show at all, please take a look below. But I really only need glagolitic and gothic to work in OS X software. 


![coptic](https://cloud.githubusercontent.com/assets/9016588/15819188/4abe2080-2ba7-11e6-91ce-2e7e009d9aca.jpg)

**Comment by brawer** [comment]
To enter Glagolitic on a MacOS keyboard, go to “System Preferences”, choose “Keyboard”, then select the “Input Sources” tab. On the bottom left, you’ll see a little button with + and –. Click on “+”, then choose “Unicode Hex Input”. Personally, I’d also recommend checking the “Show Input menu in menu bar” at the bottom of the keyboard preferences panel. Then, you’ll be able to choose “Unicode Hex Input” in the keyboard menu at the top right of the menu bar, between the WiFi status and battery charge level.

Once you’ve done this, you can enter any character in Unicode. Unicode publishes charts with all characters, which can be found at [www.unicode.org/charts/](http://www.unicode.org/charts/). For example, here’s the [Unicode chart for Glagolitic](http://www.unicode.org/charts/PDF/U2C00.pdf#page=2). It says that Ⰼ “GLAGOLITIC CAPITAL LETTER DJERVI” has code 2C0C. To make clear that it’s a Unicode codepoint, this often gets written as `U+2C0C`; the U+ indicates a Unicode codepoint.

To enter this Glagolitic character Ⰼ into a MacOS machine, make sure that “Unicode Hex Input” is selected from the keyboard menu (see above for the set-up). Then, hold down the option key (on some Apple keyboards, the key is literally called “option”; on others, it has a ⌥ symbol). While keeping the option key pressed, type the four keys 2 C 0 C; then release the option key. You will see Ⰼ.

Likewise, to enter Coptic symbol Stauros ⳧, look for it in the [Unicode chart for Coptic](http://www.unicode.org/charts/PDF/U2C80.pdf). You’ll see it is at U+2CE7. After making sure that “Unicode Hex Input” is selected, hold the option or ⌥ key, then type 2 C 8 0, then release the option or ⌥ key again. As with Glagolitic, Apple seems to pre-install a hidden version of Noto Sans Coptic into recent MacOS X versions, so you won’t even need to install the font yourself.

**Comment by liamcoded** [comment]
For some reason I thought this was just like a regular don't I could type. At least I remember I was able to. Why was it changed and is there a chance this will ever be changed back?

**Comment by brawer** [comment]
You want to get Ⰰ by typing `A` on a keyboard? For this, your operating system would have to come with something called “keyboard layout” or “input method.” To my knowledge, Apple has currently no Glagolitic keyboard layout; not sure about X11 (for GNU/Linux). However, there are websites with “virtual keyboards” such as http://virtualkeyboard.biz/glagolitic where you can type Glagolitic text into a web page, copy the entered text into your clipboard, and then paste it into any application you want.

**Comment by brawer** [comment]
@liamcoded, does it work now? By the way, have you seen [“Church Slavonic Typography in the Unicode Standard”](http://www.unicode.org/notes/tn41/tn41-1.pdf) (Unicode Technical Note 41)? Of course this is diverging quite far from the topic of this bug; I just happened to run into that document, and thought that somebody working in Glagolitic might find it interesting to read.
