### ISSUE TITLE
NotoMono-Regular.ttf not included in the download tar

### ISSUE THREAD

**Issue by jriddell** [googlei18n/noto-fonts#711]
NotoMono-Regular.ttf isn't included in the download tar on the Noto website, but has been in the Git repostiory for 6 months.  Does this mean it's not advised to use it yet or has it just been missed out from somewhere in the release process?

**Comment by marekjez86** [comment]
Thank you for the question. NotoMono-Regular.ttf and all the other fonts on github and quite usable (and in many cases "better" than what is available at Noto website - this statement applies to https://github.com/googlei18n/noto-fonts/tree/master/hinted and https://github.com/googlei18n/noto-fonts/tree/master/unhinted ). We are still working on speeding up the processes :-)
