### ISSUE TITLE
Mention Unicode 9.0 on FAQ?

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#717]
Can we say on the [FAQ](https://github.com/googlei18n/noto-fonts/blob/master/FAQ.md#what-are-googles-plans-for-noto) that Noto “phase 3” plans to cover 100% of Unicode 9.0? Or would this be misleading? The current roadmap is a little vague.

**Comment by roozbehp** [comment]
Minus some of CJK of course...

**Comment by brawer** [comment]
Which part of CJK will not be supported, specifically? (This kind of info is probably quite important for people reading the FAQ).

**Comment by roozbehp** [comment]
Thousands and thousands of characters. Most of Extensions B, C, D, and E, IIRC. @kenlunde has the details.

**Comment by c933103** [comment]
How about the 7500 Tangut?

**Comment by dougfelt** [comment]
Tangut is planned for phase 3.  All scripts will be covered as completely as we can except for CJK, which is just too large.

**Comment by kenlunde** [comment]
Noto Sans CJK covers a little under 30K of the 80K CJK Unified Ideographs in Unicode Version 8.0 (unchanged in Version 9.0), so it's tens of thousands, not thousands. Of course, those are the rarely-used ones. An additional 7,500 or so are expected to be in Unicode Version 10.0 (Extension F).

**Comment by xiangyexiao** [comment]
Having this info in FAQ is good.
For CJK, is it accurate to say we will support all Plane 1 CJK in Unicode 9? @kenlunde

**Comment by kenlunde** [comment]
@xiangyexiao: I think you meant BMP, not Plane 1. The BMP is Plane 0.

Anyway, in terms of relevant CJK characters in the BMP and considering Unicode Version 9.0, Source Han Sans / Noto Sans CJK are missing glyphs only for U+9FD1 through U+9FD5. These are Unicode Version 8.0 characters. They are already on the list for the Version 2.000 update.

**Comment by xiangyexiao** [comment]
yep. I meant Plane 0. sounds like we can say that we plan to cover 100% of Unicode 9.0, including CJK.

**Comment by xiangyexiao** [comment]
updated FAQ. Please check:
https://github.com/googlei18n/noto-fonts/blob/master/FAQ.md

**Comment by dscorbett** [comment]
> We plan to extend character/script coverage to cover 100% of Unicode 9.0. For CJK, we plan to cover Plane 0 (BMP) CJK characters in Unicode 9.0

The second sentence makes it sound like you don’t plan to cover non-BMP CJK. If you don’t cover non-BMP CJK, you can’t have 100% coverage of Unicode 9.0.

**Comment by dougfelt** [comment]
Yeah, we're not covering all of Unicode 9 because we're not covering all of
CJK, for details there see Ken. Exclusive of CJK, though, we do plan to
cover all of Unicode 9, though it will take awhile.

**Comment by kenlunde** [comment]
The CJK coverage of the BMP is quite good at this point. Outside the context of CJK, even the BMP includes plenty of esoteric characters.

Anyway, I keep track of the CJK ideographs, unified and compatibility, [here](https://blogs.adobe.com/CCJKType/files/2016/07/ideographs-unicode-9.pdf) (for Unicode Version 9.0). I am tracking tentative Unicode 10.0 additions [here](https://blogs.adobe.com/CCJKType/files/2016/07/ideographs-unicode-10.pdf).
