### ISSUE TITLE
Combining Enclosed Mark ( ⃝ ) is not well supported in noto fonts

### ISSUE THREAD

**Issue by c933103** [googlei18n/noto-fonts#718]
See https://ja.wikipedia.org/wiki/三式潜航輸送艇 , in noto font, the character cannot enclose a hiragana character into it as would have been expected. (The combination: ゆ⃝ )

**Comment by dougfelt** [comment]
This is a CJK issue, and we track those in googlei18n/noto-cjk.  I'll track this there.

**Comment by c933103** [comment]
@dougfelt While I used  a kana as example, this issue actually cover all other non-katakana characters, for instance, ⍢⃝ and y⃝ are also expected to work except they didn't, and the mark itself is from a symbol block not han block, thus I am not sure about why it would be a issue for Noto cjk.

**Comment by dougfelt** [comment]
OK, I can reopen this if you'd like.

Practically speaking, we are not going to be able to render enclosing mark around each of ~62,000 distinct codepoints, even if we group the glyphs there are 1000's of glyph classes we'd need to support across over 100 font families.  It's just not a priority. If there are particular codepoints you want to prioritize, we need a list.

**Comment by c933103** [comment]
1. A while ago I was told that it is not particularily hard to implement...Is the one who tell me this misinformed? see http://www.unicode.org/mail-arch/unicode-ml/y2015-m05/0289.html

**Comment by dougfelt** [comment]
Well, different sized glyphs require different sized circles, and they have to be in the same font for the circle to have the correct size and to position correctly.  Depending on the behavior of the enclosing mark it might enclose a special form, it might participate in reordering-- not sure.  So someone has to examine the glyphs in each font, group them into classes by size, and arrange for there to be appropriately-sized circles for each size, and set up the positioning of the circle for each.

For a single, small font, yes, it is perhaps not so much work.  For hundreds of fonts in multiple styles with the number of characters we have, it is significant.  Not unimaginable, but significant.

**Comment by c933103** [comment]
I see. Then, can developers handle the case for hiragana and katakana, hanzi/kanji, latin and punctuation, greek and cryillic, numbers and simple maths symbols, miscellaneous symbol (like ⌓̈◡̈ᵋ͚̈.☄⚘ྉ⍥⍨⍩⃜∵⍤⍨∵♡⍢⍤⍨ which are common characters that Japanese people used to form emoticon with the original character and can be displayed correctly on iPhone/to a certain extent Windows)?

Also, please also include support for these character for other combing enclosed character for instance ⃣

**Comment by c933103** [comment]
For instance, http://d.hatena.ne.jp/nonokoo/20111106/1320587095 show a number of instance where the symbol would be used together with some symbol, and it also indicated that these would look correctly on ios, persumably with its default font.

https://twitter.com/search?vertical=default&q=%E2%83%9D&src=typd show numerous usage for the symbol together with arabic, numerous random kanji, hiragana, etc. As of writing the character get used on twitter (click Live tab in the search result) for more than a dozen time per every hour to combine with some random symbol/character that cannot be predicted which mean close to 100k tweets carrying the special symbol per year. And I don't know what font twitter used but text displayed correctly on my Win 7 with default setting. Similar usage level is also seen on weibo http://s.weibo.com/weibo/%25E2%2583%259D?topnav=1&wvr=6&b=1

It's also used in album names like http://rateyourmusic.com/artist/%E2%96%B2%E2%83%9D_%E2%96%B2%E2%83%9D_%E2%96%B2%E2%83%9D , and people use it for twitter handle and such https://twitter.com/c_ues

Win8's IE can also partially display that effect despite with some inperfect rendering.

Cambria and Cambria Math font support enclosing of other characters.

https://www.google.com.hk/search?q=%E2%83%A3&rls=com.microsoft:en-US&biw=1280&bih=929&source=lnt&tbs=lr:lang_1zh-CN%7Clang_1zh-TW&lr=lang_zh-CN%7Clang_zh-TW&sa=X&ved=0ahUKEwiWnO_PosrNAhXEr48KHTgsDbs4ChCnBQgU Some example usage about other enclosed characters
