### ISSUE TITLE
Noto Sans Myanmar: Non-Burmese language diacritics + U+102F overlap each other

### ISSUE THREAD

**Issue by sven-oly** [googlei18n/noto-fonts#740]
I've found a character combination that does not render correctly in this font, but looks OK in other Myanmar fonts. The problem sequence is: u+1016 u+1060 u+102f u+1036. The two lower diacritics (1060 and 102f) overlap.

The same problem appears with these non-Burmese language diacritics and u+102f:
1058, 1059, 105e, 105f, 1082, 108d, and potentially others.

This looks right in the following Unicode fonts:
- Panglong
- Pang Long 2011
- Mon3
  ![selection_595](https://cloud.githubusercontent.com/assets/10751250/18484857/1281cbae-799f-11e6-83fc-939ea42e79f4.png)
- MS mmrtext (but the 102f diacritic is short
  ![selection_594](https://cloud.githubusercontent.com/assets/10751250/18484842/fc7f6050-799e-11e6-9e08-342f0037fee3.png)
  ![selection_593](https://cloud.githubusercontent.com/assets/10751250/18484841/fc7b7198-799e-11e6-8e33-972459a07d9c.png)

.)

**Comment by sven-oly** [comment]
Note that u+1060 and U+105X are used for the Mon language. The 1082 and 108d are used in the Shan language.

**Comment by roozbehp** [comment]
@sven-oly, I don't see this problem on the latest version of Android. Is this possible you are using an old version of HarfBuzz or an old version of Noto Sans Myanmar?

**Comment by sven-oly** [comment]
Thanks for checking. 

I see the problem on Chrome OS, version 52.0.2743.116 on ChromeBook Pixel 2.

I see similar results on Chrome Version 54.0.2840.16 , running on Linux Ubuntu 14.04. Noto Sans is from Sept. 28, 2015.

**Comment by roozbehp** [comment]
Assigning to @marekjez86 to see if it reproduces with latest font and latest HarfBuzz.

**Comment by sven-oly** [comment]
I see it rendering correctly on Android, too. I'll check my web font version. I'm looking at this in http://zawgyi-unicode-test.appspot.com/mon/?text=%E1%80%96%E1%81%A0%E1%80%AF%E1%80%B6, which uses a web font.

**Comment by jungshik** [comment]
@roozbehp: @sven-oly is using a web font without local():
```
@font-face {
    font-family: NotoSans;
    src: url(/fonts/NotoSansMyanmar-Regular.ttf);
  }
```

The sequence involved is U+1016, U+1060, U+102F, U+1036

**Comment by jungshik** [comment]
In Chrome  on Android (55.0.2860.0) and Mac (53.0.2785.101), I can reproduce the issue. 

'Noto Sans Myanamar' was last updated in Sep 2015 (phase 2) so that @sven-oly is using the latest release of the font. 

Phase 3 version of Myanmar is not yet ready, I'm afraid.

**Comment by jungshik** [comment]
@roozbehp, @sven-oly : when you said you couldn't reproduce this on Android, did you test it with TextView on Android or use Chrome? If the latter, what version of Chrome did you use?

**Comment by roozbehp** [comment]
> when you said you couldn't reproduce this on Android, did you test it with TextView on Android or use Chrome? If the latter, what version of Chrome did you use?

I used TextView. This is Android version 6.0.1, build number MTC20F.

**Comment by jungshik** [comment]
Thank you, @roozbehp.

@KatMomoi, can you test with harfbuzz stand-alone (hb-*) + the release build of Noto Sans Myanmar (UI) and Noto Serif Myanmar?

**Comment by jungshik** [comment]
@KatMomoi, there is a new delivery. This issue has to be tested against the latest delivery.

**Comment by TidharC** [comment]
Tested Noto Sans Myanmar in and UI and non-UI versions.  Results:

MacOS 10.12:
*  OK in Firefox and Safari.
*  In Chrome, sequences containing U+1060 are rendered as tofu.

Linux:
*  OK in Chrome, Firefox, HarfBuzzViewer.

Windows 8.1:
* OK in Chrome, Firefox, IE except: U+102F is missing its top half in the combination
   U+1016 U+1060 U+102F U+1036

![myanmar740macoschrome](https://cloud.githubusercontent.com/assets/16353803/20498516/52feab7e-afe2-11e6-928f-b4d62727b79a.png)

![myanmar740windowschrome](https://cloud.githubusercontent.com/assets/16353803/20498521/5bcda782-afe2-11e6-833d-cfc8a4887fb7.png)

![myanmar740harfbuzzviewerlinux](https://cloud.githubusercontent.com/assets/16353803/20498528/6332fbbc-afe2-11e6-8c4b-3ca40c2ef16a.png)

**Comment by marekjez86** [comment]
@sven-oly : I believe it is fixed in Phase III delivery  (see font in https://github.com/googlei18n/noto-fonts/blob/f393d4440bdf11d3a46b6e6dab9604d6e17474f8/alpha/from-pipeline/unhinted/otf/sans/NotoSansMyanmar-Regular.otf )
