### ISSUE TITLE
DEVANAGIRI and THAI fonts for itext.

### ISSUE THREAD

**Issue by yrmishra** [googlei18n/noto-fonts#741]
Little bit of history about the issue first.
Currently we are using itext for generating pdf reports in our application. We had to support Japanese market so we included cjk otf font in our application under basefont. Now we need to support the INDIA and THAI market as well but we only require currency symbol for them rest is english only. While testing with using devanagiri otf file, the rupee symbol comes with numbers but english fonts dissapeared in  our pdf. Same with thai otf file. Now based on locale we are switching the otf file in our code but it is causing lot of performance issue while looping in every cell of pdf. 
Is there a way we can merge these 3 otf files and only use single otf file or any solution to these would be helpful.

Thank You.

**Comment by KatMomoi** [comment]
I guess the user wants to compose (on the fly) a single font out of 3 fonts or a solution to his/her problem in some other way. I've CC'ed a few people -- someone should be able to answer your question.

**Comment by KatMomoi** [comment]
yrmishra: can you clarify what you mean by this passage below?

"While testing with using devanagiri otf file, the rupee symbol comes with numbers but english fonts dissapeared in our pdf. Same with thai otf file. "

In particular what does "English fonts disappeared.." mean?

**Comment by dougfelt** [comment]
My guess is this means that when they tried using only the Devanagari font
the English part of their text didn't render, since the font doesn't
contain Latin characters.

Apparently either itext doesn't provide a fallback mechanism, or it's
really inefficient so they can't use it.  Noto relies on fallback so we can
avoid duplicate Latin glyphs in all of the individual fonts.

**Comment by yrmishra** [comment]
yes the above statement is correct, when testing only using devanagiri or thai otf the english part of text didn't render where as while using cjk it renders it.
Since our application is going to launch in india and thailand we need to show the currency symbols in pdf.
Looked everywhere to merge these 3 otf file into one but could not find any solution for it. And definitely we want to get rid of the the switch for picking up otf file based on locale because it is affecting our performance.

**Comment by yrmishra** [comment]
yes the above statement is correct, when testing only using devanagiri or thai otf the english part of text didn't render where as while using cjk it renders it.
Since our application is going to launch in india and thailand we need to show the currency symbols in pdf.
Looked everywhere to merge these 3 otf file into one but could not find any solution for it. And definitely we want to get rid of the the switch for picking up otf file based on locale because it is affecting our performance.

**Comment by xiangyexiao** [comment]
Would you be able to try fonttools to merge the fonts by yourself? fonttools is at:
https://github.com/behdad/fonttools

**Comment by Sagir8453** [comment]
Thanks :)

**Comment by Sagir8453** [comment]
I need to download 7 python files to install this fontool ?
On 16-Sep-2016 2:05 pm, "Sagir Ahmed" <sagir8453@gmail.com> wrote:

Thanks :)

**Comment by Sagir8453** [comment]
Hi can you merge all scripts except cjk and emoji for me and many people?
It will help us a lot ... I'm quite new in Python and font designing
...thanks :)

**Comment by Artoria2e5** [comment]
You don't need to know Python to use apps written in Python.

```sh
# install fonttools, following the README...
easy_install pip
pip install fonttools
# merge fonts, e.g.:
pyftmerge hinted/NotoSans*-Regular.ttf
```

**Comment by jungshik** [comment]
This is not really a Noto font issue. (and this issue has nothing to do with CJK) 

It's iText not supporting font fallback. 

Anyway, for Devanagari and Thai, you can merge Noto Sans LGC (NotoSans-{weight}.ttf) with NotoSans{Devangari, Thai} UI-{weight}.ttf with pyftmerge. 

Make sure to take the glyphs for ASCII digit and ASCII punctuation come from NotoSansDevanagari-UI when merging it with Noto Sans LGC>

**Comment by jungshik** [comment]
Filed #746 for a documentation issue. Closing this one.

**Comment by Sagir8453** [comment]
Ok thanks.
