### ISSUE TITLE
Noto Sans Devanagari letter inversion

### ISSUE THREAD

**Issue by dennisr35** [googlei18n/noto-fonts#742]
I'm trying to write an PDF generator with support for Devanagari script. The main problem is the u093f character which is displayed before the consonant.
For example
u0935
u093f
should be substituted with:
u093f
00935

I would like to know, how the inversion of characters is handled in the Noto Sans Devanagari font. Is it an entry in the GSUB table? if so, which? (I could not find it)

**Comment by dougfelt** [comment]
Layout engines like Harfbuzz will handle this.  What are you using?

**Comment by dennisr35** [comment]
I try to implement this in C# without using external component. I need to know in which table of the font file the information about the letter inversion is stored.

**Comment by dougfelt** [comment]
1) There is no font table in which this information is stored.  Indic reordering behavior is defined in the spec and implemented by layout engines in OSs and some applications.  See https://www.microsoft.com/typography/otfntdev/indicot/
2) People have spent decades developing and refining text layout engines.  Even if you limit yourself to Indic, it is unlikely that you will achieve the speed, completeness, and correctness of these systems.   If your goal is to generate PDFs I'd advise you leverage the work other people have already done.  If instead you are doing this for your own education then expect to learn a lot.
3) The spec is not exactly written from an implementer's point of view.  To understand the spec in practice you need to look at an implementation.  Open source implementations are Harfbuzz (http://www.github/com/behdad/harfbuzz) and ICU (deprecated in favor of Harfbuzz but I believe the source is still available, start at http://userguide.icu-project.org/layoutengine)
