### ISSUE TITLE
Noto Sans Fonts don't include ASCII characters

### ISSUE THREAD

**Issue by dennisr35** [googlei18n/noto-fonts#745]
Would it be possible to include ASCII characters in all Noto Fonts? I tried to create a PDF with Noto Sans Hebrew, but the comma showed as unrecognized character. I recommend to include all ASCII characters in every Noto Sans font.

**Comment by Artoria2e5** [comment]
> include all ASCII characters in every Noto Sans font

Negative impacts on font fallback expected...

**Comment by dougfelt** [comment]
That is how Noto is supposed to be used.  We do not want to duplicate ASCII across 150+ font files.
