### ISSUE TITLE
NotoSansBalinese has high contrast

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#749]
NotoSansBalinese has a high contrast, also compared to other fonts in the NotoSans family. Compare eg. NotoSansMyanmar-Regular (left) to NotoSansBalinese-Regular (right). Perhaps NotoSansBalinese shoud be renamed to NotoSerifBalinese, and/or a lower-contrast NotoSansBalinese could be made in phase 3?

<img width="329" alt="NotoSansMyanmar versus NotoSansBalinese" src="https://cloud.githubusercontent.com/assets/1527880/18882568/fba3b374-84df-11e6-8373-7c5d95f21a8a.png">

**Comment by NorbertLindenberg** [comment]
Which definitions of “serif” and “sans-serif” are you using here?

**Comment by brawer** [comment]
“Serif” = High contrast, “sans” = low contrast. Agree that the naming is suboptimal.

**Comment by hrhatada** [comment]
Sound like product decision required.
