### ISSUE TITLE
Noto Sans Sumero-Akkadian Cuneiform

### ISSUE THREAD

**Issue by trevorpowell** [googlei18n/noto-fonts#752]
Am looking for the Noto Sans font for this Unicode block:
https://en.wikipedia.org/wiki/Early_Dynastic_Cuneiform#Chart

It sounded like there might be a font called "Noto Sans Sumero-Akkadian Cuneiform" that is different than "Noto Sans Cuneiform" that might cover it. Do you know if that's the case?

**Comment by dougfelt** [comment]
I think these were introduced in Unicode 8 and Noto does not yet support them (current support is mostly limited to Unicode 6).  They are on our roadmap to be added to the current Cuneiform font.

**Comment by trevorpowell** [comment]
Thanks!
