### ISSUE TITLE
macOS Font Book 6 serious errors 

### ISSUE THREAD

**Issue by chuckreynolds** [googlei18n/noto-fonts#754]
![screen shot 2016-10-06 at 23 25 14](https://cloud.githubusercontent.com/assets/46185/19180693/bea2755c-8c1c-11e6-85c2-a650b4769e52.png)

Seems like the `'post' table usability` is the issue in all the ones listed.
Only one that had an additional red X was "NotoColorEmoji.tff" > "Noto Color Emoji" `System Validation` had the red X in addition to the `'post'`

MacOSX El Capitan v10.11.6
Font Book v6.0 (279)

pardon me if this was already made an issue; i didn't see one yet so here it is.

**Comment by brawer** [comment]
For Lao, see https://github.com/googlei18n/noto-fonts/issues/715.

**Comment by fractalgee** [comment]
actually none of the fonts validate on macos X 10.11.6

**Comment by amire80** [comment]
Same here with macOS Sierra 10.12.

**Comment by moritzfl** [comment]
exactly the same issue as chuckreynolds with macOS 10.12

**Comment by lwb52** [comment]
10.11.6 Fontbook does not properly display (tofus) every accepted (non-error-marked) Noto font, tho a dubl-klik shows them in a window. However, even dubl-kliking gets some tofu in Cherokee, and ALL-tofu in the 3 Syriacs...

**Comment by AlexPoulsen** [comment]
Same exact issues, considering this is a font designed to remove boxes (or "tofu), the amount of boxes is surprising.
Also couldn't the fonts be put into one font within font book on mac? That way when the "Noto Sans" is selected, you would have support for whatever language, not just the one that the font file supports plus maybe english too.

**Comment by jungshik** [comment]
Noto Color Emoji uses one of 4 standard color font formats (using CBDT, CBLC tables), but that format is not supported by Mac OS.

**Comment by brawer** [comment]
I think we can close this bug. We already have #715 for Lao, and the Emoji font is according to spec. Apple doesn’t implement the full OpenType spec, but that’s not the font’s problem.

**Comment by BrianRisch** [comment]
![image](https://cloud.githubusercontent.com/assets/24611769/21273337/13ab7aca-c391-11e6-883d-dba5f5882c8f.png)
All fonts don't validate on my Mac OS 10.11.6, but I install anyway and they work. Really bothers me though, any solutions known to fix this yet? Thanks.

**Comment by brawer** [comment]
@BrianRisch, sorry to hear that you’ve got problems with some font files. But the fonts in your screenshot are not from Google. So there’s nothing we can do to fix your problem.
