### ISSUE TITLE
zero is indistinguishable from O in monospace version

### ISSUE THREAD

**Issue by XANi** [googlei18n/noto-fonts#755]
![zaznaczenie_2016-10-07_001](https://cloud.githubusercontent.com/assets/147394/19197596/fa07a966-8cba-11e6-8574-5dd3c7f2df78.png)

It is almost impossible to spot the difference, dotted or slashed zero would be much more useful

**Comment by dougfelt** [comment]
Agreed.

**Comment by lvml** [comment]
I'd like to second the request for making 0 better distinguishable from O in the Monospace version.
I thought that much of "Noto Monospace" was taken from Adobe Source Code Pro - but the latter does have distinguishable 0 / O characters.

**Comment by marekjez86** [comment]
MTI comment: "Zero.slash is default zero different than cap O - Fixed"

**Comment by marekjez86** [comment]
sample
```html
<html lang="en">
<p><span style="font-size:48.0px">"O (uppercase oh) and 0 (zero) -- 0O0"</span></p>
</html>
```

produce all differentiable results

[en-755-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/685332/en-755-NotoSans-Black.pdf)
[en-755-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/685336/en-755-NotoSans-Italic.pdf)
[en-755-NotoSans-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/685334/en-755-NotoSans-Regular.pdf)
[en-755-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/685335/en-755-NotoSansDisplay-Black.pdf)
[en-755-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/685333/en-755-NotoSansDisplay-Italic.pdf)
[en-755-NotoSansDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/685337/en-755-NotoSansDisplay-Regular.pdf)
[en-755-NotoSansMono-Black.pdf](https://github.com/googlei18n/noto-fonts/files/685338/en-755-NotoSansMono-Black.pdf)
[en-755-NotoSansMono-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/685343/en-755-NotoSansMono-Regular.pdf)
[en-755-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/685339/en-755-NotoSerif-Black.pdf)
[en-755-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/685340/en-755-NotoSerif-Italic.pdf)
[en-755-NotoSerif-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/685342/en-755-NotoSerif-Regular.pdf)
[en-755-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/685341/en-755-NotoSerifDisplay-Black.pdf)
[en-755-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/685345/en-755-NotoSerifDisplay-Italic.pdf)
[en-755-NotoSerifDisplay-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/685344/en-755-NotoSerifDisplay-Regular.pdf)
[en-755-Roboto-Black.pdf](https://github.com/googlei18n/noto-fonts/files/685346/en-755-Roboto-Black.pdf)
[en-755-Roboto-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/685348/en-755-Roboto-Italic.pdf)
[en-755-Roboto-Regular.pdf](https://github.com/googlei18n/noto-fonts/files/685347/en-755-Roboto-Regular.pdf)
