### ISSUE TITLE
U+02BB glyph missing in NotoMono

### ISSUE THREAD

**Issue by keoladonaghy** [googlei18n/noto-fonts#756]
Hawaiian support in NotoMono is incomplete. Needs to have the glottal character (single open quote) at U+02BB. This is the character that has used for the glottal on Mac OS Hawaiian keyboard since 2002. Other system (iOS and Microsoft) use U+2018; this character is fine in NotoMono.

Other Noto fonts seem to include this character at U+02BB.

**Comment by dougfelt** [comment]
Thanks.  This is scheduled to be in phase 3 for Mono.
