### ISSUE TITLE
OFL is not a free software license

### ISSUE THREAD

**Issue by luke-jr** [googlei18n/noto-fonts#758]
It prohibits sale of the font by itself. (I'm aware of the FSF's "loophole", but disagree it would hold up legally.)

Why not dual license it under OFL | Apache | GPL or something? (Or just use the standard MIT license which most free software fonts use...)

**Comment by dougfelt** [comment]
So, your problem is with our use of the word 'free', or is your problem the fact that you can't sell the font by itself?

**Comment by luke-jr** [comment]
I simply don't use non-free software on principle, so my "problem" is that Noto currently is not in this category, which seems unfortunate and simple to improve.

**Comment by davelab6** [comment]
Luke, thanks for raising this issue. I wrote my MA dissertation on the
topic of what it means for a font to be free, and I have spent many whole
days discussing it, during the past ten years in which I dedicated myself
to advancing the software freedom movement for fonts.

Concerning the status of the ofl as a license that respects your freedom,
I'm sad to say that this ship has sailed; your personal definition of what
constitutes a free cultural work, which I think has merit, doesn't matter.
The software freedom movement is a social movement and the fsf and osi
license lists include the ofl. You and I can say that this doesn't make
rational sense, but there isn't a single free cultural institution that
agrees with us. As a movement, the ofl has been widely accepted as a
license that respects user freedom, and it forms an exclusive commons. It
would be a net loss for the movement to produce work outside this pool of
work.

The exclusivity of the old commons is particularly relevant to your
proposal for Google to distribute a font under several licenses: The ofl
has a peculiar wording that may even be interpreted to prohibit downstream
multilicense redistribution: "and no other license."

If you want to fork Noto under Apache, you can go back to the final release
made under that license, and attempt to maintain the fonts... Sounds
expensive ;)

**Comment by luke-jr** [comment]
There are plenty of fonts under non-OFL licenses. There's no reason Noto couldn't join them.

**Comment by davelab6** [comment]
> There are plenty of fonts under non-OFL licenses. There's no reason Noto couldn't join them.

How many? :)

**Comment by luke-jr** [comment]
```
$ eix media-fonts/* -v|grep License|grep OFL|wc -l
66
$ eix media-fonts/* -v|grep License|grep 'MIT\|GPL'|wc -l
74
```

**Comment by davelab6** [comment]
> media-fonts

What is that? 

    $ ls -1 fonts/ofl/*/OFL.txt | wc -l
    796

**Comment by luke-jr** [comment]
Fonts available on Gentoo.

**Comment by davelab6** [comment]
Font files, or font families? :)

**Comment by luke-jr** [comment]
Packages, which typically means font families.

**Comment by davelab6** [comment]
So around 10% of the GF OFL collection are MIT or GPL, but there are many more OFL families not in the GF collection today, so it may be 5-8%. 

I remain convinced those 5-8% are a strategic error for the movement by standing outside the OFL commons.

**Comment by luke-jr** [comment]
And I remain convinced that OFL fonts are non-free and not part of the free font commons at all. ;)

**Comment by davelab6** [comment]
I'm curious why you think this.

**Comment by davelab6** [comment]
> by itself

Why does this matter?

**Comment by luke-jr** [comment]
Because it's part of what defines free software.

**Comment by davelab6** [comment]
Why does free software matter?

**Comment by luke-jr** [comment]
RMS considers "not by itself" acceptable *only* because he doesn't intend to respect it. He is overlooking that courts enforce the license not by the exact language, but by the intent. This is why his loophole used to overlook the OFL's non-freeness is irrelevant.

There are no "higher order principles" behind free software. Free software is the goal/end in itself.

**Comment by davelab6** [comment]
> because he doesn't intend to respect it

**Comment by luke-jr** [comment]
> That intent by the license authors is explicitly stated in http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ofl-faq_web#98ed3755

> I think calling it a 'loophole' misrepresents the intent of the OFL authors. It isn't a workaround, it is working as intended.

The intent stated in the FAQ doesn't change the problem. It still forbids sale of the font by itself. FSF's comments [here](https://www.gnu.org/licenses/license-list.en.html#SILOFL) state an interpretation of bypassing this rule by bundling a dummy program, which clearly violates the spirit of the license, since the intent of doing so would be to sell the font by itself while merely satisfying the word of the license on a technicality.

**Comment by davelab6** [comment]
On Oct 21, 2016 7:03 PM, "Luke-Jr" <notifications@github.com> wrote:
>>
>> That intent by the license authors is explicitly stated in
http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=ofl-faq_web#98ed3755
>>
>> I think calling it a 'loophole' misrepresents the intent of the OFL
authors. It isn't a workaround, it is working as intended.
>
> The intent stated in the FAQ doesn't change the problem. It still forbids
sale of the font by itself. FSF's comments here state an interpretation of
bypassing this rule by bundling a dummy program, which clearly violates the
spirit of the license, since the intent of doing so would be to sell the
font by itself while merely satisfying the word of the license on a
technicality.

Please explain to me how the OFL FAQ answer I linked to shows aggregating a
simple program violates the spirit of the license but aggregating another
non-OFL font does not.

**Comment by luke-jr** [comment]
If the intent is to sell the OFL font itself, it seems to clearly violate the spirit of the license no matter what you aggregate with it in an attempt to satisfy the exact language of the license.

**Comment by davelab6** [comment]
> If the intent is to sell the OFL font itself, it seems to clearly violate the spirit of the license no matter what you aggregate with it in an attempt to satisfy the exact language of the license.

I think you have misunderstood the spirit of the license.
