### ISSUE TITLE
Noto Serif Kannada - Serious bug

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#759]
In Mac OS sierra and chrome browser, setting default font to Noto Serif Kannada yields distorted text. But the same webpage with Noto Sans Kannada doesn't distort the text. So, I think it is not "Apple's Core Text Engine" that is causing issue.

Please review.

https://kn.wikipedia.org/wiki/ಆಂಗ್ಲ

I used chrome extension "Advanced Font Settings" to change the default font.
![screen shot 2016-10-09 at 12 16 29 pm](https://cloud.githubusercontent.com/assets/14062593/19222333/87648caa-8e1b-11e6-8990-e4e96e0abc29.png)
![screen shot 2016-10-09 at 12 18 14 pm](https://cloud.githubusercontent.com/assets/14062593/19222331/87641ba8-8e1b-11e6-80b1-b324fa31323a.png)
![screen shot 2016-10-09 at 12 24 05 pm](https://cloud.githubusercontent.com/assets/14062593/19222332/876432f0-8e1b-11e6-8065-cd9c5c5138a6.png)

**Comment by brawer** [comment]
Thanks for the report! Would you mind copying a few badly rendered Kannada words into this bug, as plaintext? It would help to find out what’s happening.

For example, here’s the word ಕಾನ್ಸೊನಂಟ್ಸ್ in Noto Sans and Noto Serif rendered by [FontView](https://github.com/googlei18n/fontview). FontView uses the HarfBuzz library for shaping, not CoreText. The red rectangles look different; is this just a stylistic difference between the two fonts, or is one of the renderings broken? (Which one?)

<img width="223" alt="screen shot 2016-10-10 at 12 46 54 pm" src="https://cloud.githubusercontent.com/assets/1527880/19233748/d180d0d8-8ee7-11e6-893f-ab8ede123b24.png">

**Comment by MayuraVerma** [comment]
@brawer It is not styling issue. It is 100% rendering issue.

But the same text in "Pages" displayed correctly with Noto Serif Kannada, expect "ನ್ನಾ" glyphs is discontinous.
![kannada noto serif2](https://cloud.githubusercontent.com/assets/14062593/19224899/b126e2a2-8e54-11e6-8e69-36d52befb682.png)

I have copied few text below. This is not full list. This could help diagnose the root cause. 

ಲ್ಲಿ
ಟ್ಸ್
ಳಿ
ಡಿ
ಮೆ
ರಿ
ಖ್ಯೆ
ಫ್ರಿ
ನೆ
ಗಿ
ಷ್ಟಿ
ಯಿಂ
ಚೀ
ನಿ
ಗ್ಲಿ
ಷಿ
ಗೆ
ದ್ವಿ
ತೀ
ಮಿ
ಲಿ
ಗಿ
ನ್
ಬಿ
ಲಿ
ನ್ನಿಂ
ಲ್ಲಿ
ಧಿ
ಪೌ
ವಿಂ
ಡಿ
ಟಿ
ನಿ
ಧಿ

**Comment by brawer** [comment]
@MayuraVerma, thanks so much! Just to confirm, is it correct that ಟ್ಸ್ should be rendered like in the left picture, and the right picture is wrong? (Left is CoreText on macOS 10.12; right picture is HarfBuzz).

<img width="135" alt="screen shot 2016-10-10 at 8 03 33 pm" src="https://cloud.githubusercontent.com/assets/1527880/19246049/a71ad82e-8f24-11e6-8353-9b68512a4434.png">

**Comment by MayuraVerma** [comment]
@brawer yes. Left is correct, right is incorrect rendering.

**Comment by jungshik** [comment]
Just in case it's not clear, Chrome on Mac also uses HarfBuzz.  
@behdad

**Comment by brawer** [comment]
@MayuraVerma, would you mind checking the image at https://github.com/behdad/harfbuzz/issues/347 and confirm that the “Expected” line is correct? (Please ignore that some glyphs are cut off at the edges, just check the visible part). Thanks for your help — we’re trying to find out if HarfBuzz, CoreText, or the Noto font is broken.

**Comment by MayuraVerma** [comment]
@brawer Yes, the first line is correct. 

This might not be affected by CoreText, since this is happening in Chrome but in Pages (Although, Pages has a different issue).

**Comment by brawer** [comment]
@MayuraVerma, thanks for your confirmation. So either HarfBuzz or CoreText is broken; they should produce the same output when rendering the same string with the same font but currently they don’t.

Does anyone have a way to reproduce this with DirectWrite, ideally on a recent build of Windows 10? I’ll try to get a box but it’ll take me a while.

**Comment by MayuraVerma** [comment]
@brawer I have latest Windows 10 as bootcamp. I will report by the day (CST).

**Comment by MayuraVerma** [comment]
More trouble with "Noto Serif Kannada"
Chrome in Windows 10 and mac also has issue rendering this text "ನ್ಫ್ಲೆ" for Noto Serif Kannada.
MS Word 2010 on Windows 10 also has issue rendering this text.
Pages on Mac OS Sierra doesn't has trouble rendering this text!
![screen shot 2016-10-11 at 7 47 44 pm](https://cloud.githubusercontent.com/assets/14062593/19293680/ed9ec93c-8feb-11e6-9a06-8d7f1390b9b5.png)

Chrome and MS Word 2010 in Windows 10 with Noto Serif Kannada, doesn't the problem rendering the paragraph in discussion. (I am assumed this is what you needed with DirectWrite)
![screen shot 2016-10-11 at 7 49 31 pm](https://cloud.githubusercontent.com/assets/14062593/19293681/ed9f811a-8feb-11e6-974e-46fef13df4a1.png)

**Comment by jungshik** [comment]
@MayuraVerma 
> Chrome and MS Word 2010 in Windows 10 with Noto Serif Kannada, doesn't the problem

Do you mean Chrome and MS Word 2010 on Windows 10 agree with each other and both have the correct shaping ?  hmm...

How about this test page? 
http://jungshik.github.io/noto/kannada/bug759.html

Do Chrome on Windows (or Mac) agree with IE 11 or Edge on WIndows 10? How about Safari on OS X?

**Comment by MayuraVerma** [comment]
@jungshik 
on Windows 7 and chrome: failed marked in RED
![capture3](https://cloud.githubusercontent.com/assets/14062593/19665252/bd0f32ca-9a09-11e6-99a6-f7cc9219d6e5.JPG)

on Windows 7 and IE 11: Passed
![capture4](https://cloud.githubusercontent.com/assets/14062593/19665295/f2752dc0-9a09-11e6-8116-9d790bdbd06a.JPG)

On Windows 10 and Edge: will check in the evening
On Mac OS X and Safari: will check in the evening

**Comment by MayuraVerma** [comment]
All screenshots updated.

**Comment by lianghai** [comment]
Confirmed a HarfBuzz issue. Although we can also make changes in the fonts to avoid this major issue.
Please see my comment in: https://github.com/behdad/harfbuzz/issues/347

**Comment by brawer** [comment]
Added some Kannada test cases to the [Unicode text rendering test suite](https://github.com/unicode-org/text-rendering-tests); see output from [HarfBuzz](https://raw.githack.com/icu-project/text-rendering-tests/master/reports/FreeStack.html#SHKNDA-1) and [CoreText](https://raw.githack.com/icu-project/text-rendering-tests/master/reports/CoreText.html#SHKNDA-1). If expectations are wrong, send a pull request.

**Comment by MayuraVerma** [comment]
This issue is resolved in newer version of harfbuzz.
Thanks @behdad @brawer @lianghai @jungshik @roozbehp
