### ISSUE TITLE
Noto Sans Cham should define pref feature

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#766]
See https://github.com/behdad/harfbuzz/issues/348

**Comment by behdad** [comment]
I believe in the rework Monotype is doing this will be fixed.  In the mean time, the font is rather bogus.

**Comment by TidharC** [comment]
Can someone please create a "Script-Cham" label?  I don't see one in the list.

**Comment by marekjez86** [comment]
[NotoSansCham.zip](https://github.com/googlei18n/noto-fonts/files/1039230/NotoSansCham.zip)

Fixed in this release
