### ISSUE TITLE
Improve Catalan support

### ISSUE THREAD

**Issue by jmontane** [googlei18n/noto-fonts#768]
Hi,
Catalan language has a typographical issue, the geminated el (l·l, L·L). Catalan language uses a common character · U+00B7 MIDDLE DOT (AKA interpunct, texperiodcentered, anno teleia,...) between two L's (booth uppercase or booth lowercase) and usually "L·L" rendering is wrong according Catalan rules. This is the case for Noto fonts (Sans, Serif, and Mono). In short, a customization is needed for Catalan L·L. 

"Typographically, there are two things to consider. Firstly, there is no word space between the two L/l. In other words, it should still look like one word, not two. So, the extra distance caused by the insertion of the middot must not be too much. Secondly, the dot needs to appear in the optical center between the two L/l."

There are different approaches to achieve a good "L·L". I'm not a font designer, so I don't give you any hint, but you can read a typographical post about Catalan L·L here [1], with some approaches dealing with Catalan L·L.

[1] https://www.glyphsapp.com/tutorials/localize-your-font-catalan-punt-volat

**Comment by jungshik** [comment]
@TrueTyper @SteveMatteson

**Comment by TrueTyper** [comment]
The Noto LGC fonts use the "Ldot" method discussed in the GlyphsApp tutorial. @jmontane can you include an illustration of where you see an issue?

**Comment by TidharC** [comment]
Retested with several new fonts (see below).  The punt volat U+00B7 seems OK, except for one case: in Sans Serif Black fonts, the dot seems too close to the lowercase l's.

jmontane@, please check the PDFs below and advise.

[specimenNotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/620428/specimenNotoSans-Black.pdf)

[specimenNotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/620429/specimenNotoSansDisplay-Black.pdf)

[specimenNotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/620430/specimenNotoSansDisplay-Italic.pdf)

[specimenNotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/620431/specimenNotoSans-Italic.pdf)


[specimenNotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/620432/specimenNotoSerif-Black.pdf)

[specimenNotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/620434/specimenNotoSerifDisplay-Black.pdf)

[specimenNotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/620435/specimenNotoSerifDisplay-Italic.pdf)

[specimenNotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/620433/specimenNotoSerif-Italic.pdf)

**Comment by fitojb** [comment]
I’m not Joan, but:

> in Sans Serif Black fonts, the dot seems too close to the lowercase l's

Given that the black weight should be used for bigger sizes in good typography, I don’t think it’s an issue at all¹, but the interpunct in these heavier weights can be made a tad smaller to avoid a clogged look (at least that’s what I’ve seen in some other typefaces).

¹ www.l·l.cat cites Fabra and Alcover’s 1913 *Normes ortogràfiques*, where they describe the sequence “L·L / l·l” as a single modified letter, where “both ells are as close one from the other as they are in the symbol *ll*” (*les dues l tan acostades l’una a l’altra com les del símbol ll*).

**Comment by jungshik** [comment]
@TidharC  could you add 'l·l' to the PDF ? I don't see any 'l·l' in the PDF. 

BTW, how did you generate PDF files?  PNGs generated hb-view might be more convenient to view in github (pngs can be viewed inline).

**Comment by marekjez86** [comment]
From MTI: "<SW> Steve responded to this stating we followed the guidelines in the tutorial the bug reported points to. Nothing may be needed here."
