### ISSUE TITLE
Noto Serif Kannada issue rendering "ನ್ಫ್ಲೆ"

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#770]
Chrome in Windows 10 and mac also has issue rendering the text "ನ್ಫ್ಲೆ" for Noto Serif Kannada.
MS Word 2010 on Windows 10 also has issue rendering this text.
Pages on Mac OS Sierra doesn't has trouble rendering this text!
![screen shot 2016-10-11 at 7 47 44 pm](https://cloud.githubusercontent.com/assets/14062593/19293680/ed9ec93c-8feb-11e6-9a06-8d7f1390b9b5.png)

**Comment by nizarsq** [comment]
@MayuraVerma could you post a screenshot for the correct rendering for this text, and if you can post a link for an article that contain this string will be helpful (Not screen shot). Thanks

**Comment by MayuraVerma** [comment]
@nizarsq https://kn.wikipedia.org/wiki/ಆಂಗ್ಲ

look for the word "ಇನ್ಫ್ಲೆಕ್ಷನಲ್"

**Comment by nizarsq** [comment]
Assigned to @marekjez86 for further investigation.

**Comment by MayuraVerma** [comment]
Correct rendering in Windows 7 on chrome with default font.

![capture](https://cloud.githubusercontent.com/assets/14062593/19451648/763d9db4-9473-11e6-8cd4-39aa81e909d7.JPG)

**Comment by MayuraVerma** [comment]
@brawer Could you please add this text to test with different fonts and shaping engine. I can report back.

**Comment by MayuraVerma** [comment]
@brawer please assist

**Comment by MayuraVerma** [comment]
ಇನ್ಫ್ಲೆಕ್ಷನಲ್
ಇನ್ಫ್ಲೆಕ್ಷನ್

**Comment by MayuraVerma** [comment]
another word broken in Apple core text engine
ಜಿ಼ೕಬೆನ್
