### ISSUE TITLE
Diacritics superimpose the dot of the isolated ghain (Arabic script)

### ISSUE THREAD

**Issue by barkoosh** [googlei18n/noto-fonts#772]
In Noto Naskh Arabic, any diacritic over the letter ghain (063A), in its isolated form only (FECD), superimposes the dot instead of appearing above it. The diacritic appears correctly over the final ghain (FECE).
(Windows 10)

![capture](https://cloud.githubusercontent.com/assets/7565719/19417046/e0f32ea4-93aa-11e6-8808-846c5a2e0e32.JPG)

**Comment by nizarsq** [comment]
Tested reported scenarios on extEdit on Mac OS 10.11.6 and was able to reproduce the issue.
![screen shot 2016-10-17 at 10 16 00 am](https://cloud.githubusercontent.com/assets/22158882/19447544/c9a24b38-9452-11e6-9474-8ecb5b84c75a.png)

**Comment by jungshik** [comment]
I'm not sure if Arabic Presentation form is supposed to work together with 'diacritics'. 

Do you have the same issue when U+063A is used instead of U+FECD?   
@barkoosh @nizarsq 

@roozbehp @behdad @kmansourMT

**Comment by nizarsq** [comment]
Both U+063A and U+FECD have same issue. Thanks
![screen shot 2016-10-17 at 3 51 38 pm](https://cloud.githubusercontent.com/assets/22158882/19458567/bb6fcdb8-9481-11e6-801e-62f90bba6e6e.png)

**Comment by roozbehp** [comment]
There's actually a lot of data on the web using Arabic Presentation forms (and diacritics), so yes, they should work.

But as Nizar discovered, the bug also exists for normal isolated form of ghain, which makes the bug critical for Android. Please provide us with a fix ASAP.

**Comment by marekjez86** [comment]
@nizarsq : could you provide me with the text for this to create tests?

**Comment by nizarsq** [comment]
Here the text     غٌ غُ غّ غً

**Comment by nizarsq** [comment]
As far as i can see NotoNaskhArabicUI is ok, but NotoNaskhArabic has the problem

**Comment by marekjez86** [comment]
@roozbehp : this is only in the NotoNaskhArabic (not in the UI version). Is this critical to fix (I do not have it yet)?

**Comment by marekjez86** [comment]
![overlap-arabic](https://cloud.githubusercontent.com/assets/13322623/24947071/9150df94-1f65-11e7-8426-d68b8a7e4714.jpeg)

**Comment by dougfelt** [comment]
Confirming that the latest drop from Monotype fixed this.
