### ISSUE TITLE
Missing sources for Noto Serif Khmer

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#774]
We already seem to have design sources for [Noto Sans Khmer “phase 3”](https://github.com/googlei18n/noto-source/tree/master/src/NotoSansKhmer), but not for Noto _Serif_ Khmer. Is this intentional? For phase 2, the sources of Noto Serif Khmer would be [here](https://github.com/danhhong/NotoSerifKhmer/tree/master/Source).

**Comment by marekjez86** [comment]
I expect Noto Serif Khmer and Noto Sans UI to appear at end of this year or early next year (i.e., 2017). It is as designed at this point :-)
