### ISSUE TITLE
Noto Sans Myanmar rendering issue

### ISSUE THREAD

**Issue by JackfromMc** [googlei18n/noto-fonts#778]
Hi everyone,

The combination U+1009 U+1037 U+103A   ဉ့်  (canonical) doesn't display properly;

The combination U+1009 U+103A U+1037   ဉ့်  (usual) neither.

This happens in Android M of which I don't know the font version and on Windows 8.1 with font version 1.10 in MS Word, Chrome etc.

Although quite rare, these combinations can be found in common words like ရှဉ့် (squirrel) and ငါးရှဉ့် (eel).

**Comment by brawer** [comment]
Google’s Burmese linguist confirms that the above is proper Unicode, not Zawgyi.

**Comment by JackfromMc** [comment]
Hi @brawer,
No, it is not Zawgyi.
One could have guessed by the use of the word "canonical".
Anyway this is what a correct rendering should look like :
![20161027_004751](https://cloud.githubusercontent.com/assets/23061375/19739179/f4203bf6-9bdf-11e6-882f-6f15c15f66ac.png)
Font used : Myanmar Text

This being a genuine flaw in the font (the font being almost 3 years old), I'm a bit surprised that noboby mentioned it before. And for the same reason, I'm also surprised that this issue hasn't yet been assigned nor labeled considering the haste with which some other less flagrant issues are dealt with.

**Comment by JackfromMc** [comment]
I see what you did there... although it's not an android specific issue

**Comment by TidharC** [comment]
The following is the rendering I see on Chrome/MacOS and on Android.
![myanmarrendering](https://cloud.githubusercontent.com/assets/16353803/19749817/f829b270-9ba0-11e6-957f-ca8f56e85d03.png)

**Comment by JackfromMc** [comment]
Just to be complete : the problem seems to be identical in the bold weight.

And to whomever this may concern : thanks for what you're doing for us all, gone, present and yet to come. Sounds cheesy but as a regular, typical end user, I'm pretty sure you don't get enough praise from us for your endeavours.

**Comment by marekjez86** [comment]
The previous bug was discovered in Noto Sans Mynmar.

I it also present in Noto Sans Myanmar UI
![myanmarsansui](https://cloud.githubusercontent.com/assets/13322623/19785190/67f4c0e8-9c4d-11e6-85ab-204a586e9c08.jpg)



and 

Noto Serif Myanmar
![myanmarserif](https://cloud.githubusercontent.com/assets/13322623/19785204/6f26a1e2-9c4d-11e6-9bcd-605afb26f1a6.jpg)

**Comment by davelab6** [comment]
https://github.com/google/fonts/issues/412 also reports some issues with Noto Myanmar

**Comment by davelab6** [comment]
cc @wichert

**Comment by marekjez86** [comment]
@JackfromMc : 
the fonts at 
https://github.com/googlei18n/noto-fonts/blob/f393d4440bdf11d3a46b6e6dab9604d6e17474f8/alpha/from-pipeline/unhinted/otf/sans/NotoSansMyanmar-Regular.otf (and related ttf or variable fonts) fix the issue

**Comment by JackfromMc** [comment]
Problem's solved. Thanks to everyone. Just a quick question if someone ever reads this: is there a place for general discussions about fonts for a specific script like a "Noto Myanmar fonts forum" ? Because often I would like to make suggestions or discuss the font family without having to open a thread on what are not real issues thus making professionals lose their time. Might be an idea. Anyway, thanks again for making one of the few almost perfect Myanmar Unicode fonts.

**Comment by JackfromMc** [comment]
And great looking Myanmar Serif font btw !!!

**Comment by marekjez86** [comment]
@JackfromMc : my advice, until there's a better place, would be to file a bug/issue here. we use labels for scripts, we differentiate between bugs and enhancement requests, etc.. Please do not hesitate your feedback with us here.

Thank you for help making things better.
