### ISSUE TITLE
Characters in Noto Gurmukhi

### ISSUE THREAD

**Issue by shuchita-g** [googlei18n/noto-fonts#783]
![screen shot 2016-10-28 at 3 21 36 pm](https://cloud.githubusercontent.com/assets/15228071/19802637/45eb2462-9d22-11e6-92a0-05f1d23d7831.png)
Can you please clarify the use of these characters present in the noto gurmukhi glyphset.
Thanks

**Comment by TidharC** [comment]
According to the Unicode standard, these are common Indic number forms:

http://www.unicode.org/charts/PDF/UA830.pdf

Assigning to MT for more information on inclusion in Noto Sans Gurmukhi.

**Comment by roozbehp** [comment]
These are common Indic numbers forms, that according to Unicode are used in various Indic scripts, including Gurmukhi. From http://www.unicode.org/Public/UCD/latest/ucd/ScriptExtensions.txt:
```
A836..A837    ; Deva Gujr Guru Kthi Mahj Modi Sind Takr Tirh # So   [2] NORTH INDIC QUARTER MARK..NORTH INDIC PLACEHOLDER MARK
A838          ; Deva Gujr Guru Kthi Mahj Modi Sind Takr Tirh # Sc       NORTH INDIC RUPEE MARK
A839          ; Deva Gujr Guru Kthi Mahj Modi Sind Takr Tirh # So       NORTH INDIC QUANTITY MARK
```
