### ISSUE TITLE
Some Noto fonts not working on my mac

### ISSUE THREAD

**Issue by webguide1** [googlei18n/noto-fonts#790]
Some of the Noto fonts is just question marks on my Macbook Air Sierra (10.12.1), its various fonts. E.g.
Javanese (all questionmarks)
Hebrew (some questionmarks)
Sans Lao (some questionmarks)
Sans syriac (all questionmarks)
Etc.
.
.
.

Have any one else expreienced this?

**Comment by marekjez86** [comment]
if you are talking about what is displayed in the FontBook after you click on the font, then what you see there is Apple's guess/attempt to display a sample of the text of characters Apple thinks ought to be in the font. If a character required by the sample is not in the font it is displayed as a boxed question mark.

For example, look at Lao MN font. The second line from bottom are Latin characters. The line with left and right parentheses has some of the symbols (e.g. @).

These characters are NOT in Noto Sans Lao (for example). Noto fonts, in general, have only characters required for that script only.

These question marks are a sign of a bad assumption by FontBook about what should be in the sample and not the quality or usability of the font itself.

**Comment by webguide1** [comment]
Ah, thanks for the answer! :)
