### ISSUE TITLE
Noto Sans/Serif latin superscript characters are vertically miss-aligned

### ISSUE THREAD

**Issue by sommerluk** [googlei18n/noto-fonts#796]
Noto Sans/Serif latin superscript characters are vertically miss-aligned.

They do not have all the same baseline. I would expect them to have the same baseline.

Example with “1ᵉʳ”
U+0031 DIGIT ONE
U+1D49 MODIFIER LETTER SMALL E
U+02B3 MODIFIER LETTER SMALL R
![grafik](https://cloud.githubusercontent.com/assets/6830724/20651618/7dab9aaa-b4e0-11e6-952a-9e308de954aa.png)

**Comment by jungshik** [comment]
This might have been fixed in a version recently delivered. Needs to be checked.

**Comment by sommerluk** [comment]
Indeed. In alpha from pipe, this is fixed.

Sorry for inconveniance.

Closing.

**Comment by marekjez86** [comment]
@sommerluk : thank you for checking and filing the bug.

I created a test case for fontdiff:
[en-796.html.zip](https://github.com/googlei18n/noto-fonts/files/617308/en-796.html.zip)

Tested it with all recent Noto LGC fonts and they look good:
[en-796-NotoSans-Black.pdf](https://github.com/googlei18n/noto-fonts/files/617312/en-796-NotoSans-Black.pdf)
[en-796-NotoSans-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/617311/en-796-NotoSans-Italic.pdf)
[en-796-NotoSansDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/617310/en-796-NotoSansDisplay-Black.pdf)
[en-796-NotoSansDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/617313/en-796-NotoSansDisplay-Italic.pdf)
[en-796-NotoSerif-Black.pdf](https://github.com/googlei18n/noto-fonts/files/617315/en-796-NotoSerif-Black.pdf)
[en-796-NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/617314/en-796-NotoSerif-Italic.pdf)
[en-796-NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/617317/en-796-NotoSerifDisplay-Black.pdf)
[en-796-NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/617316/en-796-NotoSerifDisplay-Italic.pdf)

**Comment by lemzwerg** [comment]
[I suppose that this bug tracker should also be used for noto-font-alpha issues.]

What about digits?  Even in noto-fonts-alpha, superscript digits in NotoSerif-Regular are not aligned with the remaining characters.  Is there a reason for it?

![notosans-superscripts](https://user-images.githubusercontent.com/1630245/28743088-7fe8328a-7441-11e7-8b60-42471635de94.png)

**Comment by marekjez86** [comment]
@lemzwerg : could you give me the text for this? I want to prepare a test case and the text (and knowing the Unicode code points) would help me and save time.

**Comment by lemzwerg** [comment]
Here it is.

Test ⁰ ³ ⁵ ⁷ ᵀ ᴴ ᴱ ᴼ Test ⁰ ¹ ² ³ ᴱ ᴸ ᴼ ᵁ Test

**Comment by marekjez86** [comment]
@lemzwerg : thank you

**Comment by iceager** [comment]
There is an issue with the superscript designs at the moment, which is preventing me from using Noto Serif in a project although it would otherwise be the only fit.  Here's what I see when I test the following string with Noto Serif Light version 2.000:
x⁽⁰¹²³⁴⁾x⁵⁺⁶⁻⁷⁼⁸⁹xᵃᵇᶜᵈᵉᶠᵍʰⁱʲᵏˡᵐⁿᵒᵖʳˢᵗᵘᵛʷˣʸᶻxᵝᵞᵟᶿᶥᵠᵡ
![image](https://user-images.githubusercontent.com/435692/47960447-5f360900-e037-11e8-960b-0f52a814e1a5.png)
The superscript minuscules are weirdly extended, with the stretching taking place in the upper half of the x-height. You can see this most clearly in ᵃ, ᵉ, ᵝ, and ᶿ. There are alignment issues as well with the superscript numerals and operators, but for me it is specifically the design of ʰ which is making this unusable. I will probably get around it by using a simulated superscript in the word processor, but the font needs to be fixed.

**Comment by lemzwerg** [comment]
This is a ttfautohint bug that has been found a few weeks ago.  Reason is that FreeType (that I use mainly for testing) displays the font just fine, see below.  However, FreeType itself has a bug (that I have to fix first, and which is non-trivial, alas) while hinting scaled composite glyphs; it applies hinting and scaling in the wrong order, causing the ugly results you are experiencing on Windows.

I hope to fix both FreeType and ttfautohint before January.

![notoserif-light-freetype](https://user-images.githubusercontent.com/1630245/47961743-326efb00-e011-11e8-9271-1c67199d3c86.png)

**Comment by sommerluk** [comment]
@iceager See also #1265

**Comment by lemzwerg** [comment]
BTW, you might also try the OTF version of the font, which is not affected by this problem.

**Comment by anthrotype** [comment]
Or the unhinted TTFs
