### ISSUE TITLE
version numbers are wrong in some phase 3 fonts

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-fonts#800]
Font	Phase_2_version#	Phase_3_version#
NotoSansArmenian-Bold.ttf	2.03	1.902
NotoSansArmenian-Regular.ttf	2.03	1.902
NotoSansHanunoo-Regular.ttf	1.04	1.04
NotoSansOsmanya-Regular.ttf	1.03	1.03
NotoSansShavian-Regular.ttf	1.03	1.03
NotoSansTaiTham-Regular.ttf	1.04	1.04

P3 version number should be larger than P2's.

**Comment by marekjez86** [comment]
fixed
