### ISSUE TITLE
alpha release Phase 3 fonts for NotoSansMyanmar, NotoSansMyanmarUI, and NotoSerifMyanmar

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-fonts#801]
please generate phase 3 fonts for NotoSansMyanmar, NotoSansMyanmarUI, and NotoSerifMyanmar fonts in alpha. They have been approved.

**Comment by marekjez86** [comment]
Monotype is still working on ensuring interpolatability. Until this is done we cannot generate these fonts.

**Comment by marekjez86** [comment]
all generated
