### ISSUE TITLE
NotoSansHebrew generated different numbers of weight instances for each width

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/noto-fonts#802]
Phase 3 source for NotoSansHebrew generated different numbers of weight instances for each width:
9 weights were generated for NonCondensed width, 
9 weights were generated for Condensed width,
9 weights were generated for ExtraCondensed width, 
10 weights were generated for SemiCondensed width, 
1 weight were generated for LightSemiCondensed width.

There is at least some configuration issues (hopefully)

**Comment by marekjez86** [comment]
Not a pipeline nor source issue. The oddly named fonts were remnants from the old build (before the names were changed) that somehow were left over. There were more issues (see the image below). All of the fonts below were deleted.

![old-ttf-stuff](https://cloud.githubusercontent.com/assets/13322623/20900051/b2125e1c-bae1-11e6-9871-626f7eccdc40.jpg)
