### ISSUE TITLE
Hinted fonts missing for some living scripts

### ISSUE THREAD

**Issue by Scarletts** [googlei18n/noto-fonts#803]
> For all living scripts, Noto includes hinted and unhinted fonts

(quote: FAQ.md)

This doesn't seem to be true. I found a few fonts for living scripts that are missing hinted versions. Specifically, these:

* NotoSansCanadianAboriginal-Regular.ttf
* NotoSansCherokee-Regular.ttf
* NotoSansNKo-Regular.ttf
* NotoSansOsmanya-Regular.ttf
* NotoSansTifinagh-Regular.ttf
* NotoSansVai-Regular.ttf
* NotoSansSyriacEastern-Regular.ttf
* NotoSansSyriacEstrangela-Regular.ttf
* NotoSansSyriacWestern-Regular.ttf
* NotoSansMongolian-Regular.ttf
* NotoSansYi-Regular.ttf
* NotoSansBuginese-Regular.ttf
* NotoSansJavanese-Regular.ttf
* NotoSansBuhid-Regular.ttf
* NotoSansTagbanwa-Regular.ttf
* NotoSansBatak-Regular.ttf
* NotoSansSundanese-Regular.ttf
* NotoSansHanunoo-Regular.ttf
* NotoSansMandaic-Regular.ttf

NotoSansSymbols-Regular.ttf is also quite significant and it would be a shame if users missed it by only installing fonts from the hinted folder.

There might be more.

Some references:

* https://en.wikipedia.org/wiki/List_of_writing_systems#List_of_writing_scripts_by_adoption
* https://upload.wikimedia.org/wikipedia/commons/2/25/WritingSystemsOfTheWorld.png
* Specifically regarding the African scripts, they're supported by Microsoft in [Ebrima](https://en.wikipedia.org/wiki/Ebrima)

**Comment by dougfelt** [comment]
Thanks for pointing this out, "all living scripts" is clearly wrong.  "Most major living scripts" is probably better.  We should also move this question closer to the one describing how to autohint if you need a hinted version of one we don't provide.  But perhaps we should revisit whether to just autohint the fonts that we didn't get the designers to hint for us, and push those.  Currently I think all the fonts in the hinted directory were hinted by the designers, not autohinted.

**Comment by dougfelt** [comment]
@xiangyexiao or @marekjez86 can you comment?

**Comment by xiangyexiao** [comment]
I think we should auto hint the Phase 3 fonts.

**Comment by brawer** [comment]
Note that [ttfautohint](https://www.freetype.org/ttfautohint) currently won’t work for any of the scripts in @Scarletts’s list. (Apart from Cherokee, which got added a few days ago). At Google, we currently have no plans to add autohinting for any additional scripts. But it’s all free software, so anyone can extend ttfautohint themselves if they want. Here’s how: https://www.freetype.org/ttfautohint/doc/ttfautohint.html#extending-ttfautohint-with-new-scripts

**Comment by xiangyexiao** [comment]
'ttfautohint won't work' means the quality is relatively low compared to the supported languages, or it totally doesn't work?

**Comment by brawer** [comment]
To assess the quality, try using the existing Noto fonts on low-end devices. (But Apple’s platforms mostly ignore hints these days; also, high-resolution screens have made hinting less important than it was in the past). Some background on https://en.wikipedia.org/wiki/Font_hinting.

**Comment by lemzwerg** [comment]
If someone is going to extend the set of covered scripts in ttfautohint, please send patches to the FreeType maling list!  I will then incorporate the changes into FreeType also.

**Comment by dougfelt** [comment]
So, I'll just edit the FAQ so we don't make a false claim about hinting all living scripts, since we don't and can't.

**Comment by dougfelt** [comment]
I'm going to close this for now since we can't generate hinted versions by autohinting at the moment.  I removed the claim that all living languages had hinted versions.

**Comment by Scarletts** [comment]
@dougfelt The other points in that FAQ section probably still need to be changed:

"For all major living scripts, Noto provides two weights" - Actually not true.

I think the current use of "Major" in the points is misleading since some scripts that are currently only available unhinted in regular weight have many more users than some scripts with hinted UI and bold versions, though perhaps not in the digital world.

"For historical scripts, Noto has unhinted fonts with one weight" as it is, also might lead to surprise. Perhaps "For all scripts covered, living and historical, Noto has unhinted fonts with one weight" would be more accurate.
