### ISSUE TITLE
Combine Simplified Chinese and Traditional Chinese

### ISSUE THREAD

**Issue by fifiteen82726** [googlei18n/noto-fonts#809]
In some reasons, I need to support `Simplified Chinese` and `Traditional Chinese`.

Does google provide the way that we can use them?

**Comment by brawer** [comment]
[NotoSansCJK.ttc](https://github.com/googlei18n/noto-cjk/blob/master/NotoSansCJK.ttc.zip?raw=true) supports all variants. But you need to use an application where you can set the language of your text.

* In HTML documents, you can set the language by putting `lang="zh-Hans"` (or `lang="zh-Hant-HK"`, etc.) into the page. With most modern browsers, this makes a difference for text rendering.

* In XML documents, you can set the language with the `xml:lang` attribute. See [Language tags in HTML and XML](https://www.w3.org/International/articles/language-tags/) for a nice introduction.

* Many apps allow you to set the language in their Graphical User Interface. For example, our macOS demo app [FontView](https://github.com/googlei18n/fontview) has a popup menu where you can choose the language of the text. Other applications have similar menus, but of course this really depends on the app.

For “legacy” applications where users cannot set a language, we currently ship some fonts that try to work around the problem; but it makes the user interface more complicated. See [here](https://github.com/googlei18n/noto-cjk/blob/master/README.formats) for details.
