### ISSUE TITLE
Font on my Java-swing application look pixelized on remote desktop

### ISSUE THREAD

**Issue by Naamani** [googlei18n/noto-fonts#817]
I'm changing the look and feel of a Java application using Synth. The font in the app used to be "Ariel" and I changed it to "Noto". It works fine until I try to view the application from a remote desktop connection. Then it the letters get pixelized as:  
![1111](https://cloud.githubusercontent.com/assets/12220732/21548290/34788352-cdf4-11e6-976f-ba2bf654571b.png)
)
![2222](https://cloud.githubusercontent.com/assets/12220732/21548330/5f80645c-cdf4-11e6-8e11-55959106faa6.png)

Instead of:  
![3333](https://cloud.githubusercontent.com/assets/12220732/21548337/66f20484-cdf4-11e6-9c55-3769fc92596e.png)
![4444](https://cloud.githubusercontent.com/assets/12220732/21548340/6ac2f618-cdf4-11e6-982b-21b8eb255595.png)

Some notes:

It sometimes works when I enable the "ClearType" But with each remote desktop new connection I need to repeat it.
When I return to the original desktop (The one I've connected to through "remote desktop"), the view is still corrupted. If I refresh the view of the app (using SwingUtilities.updateComponentTreeUI(....) the fonts return to look fine.

Regards.

**Comment by Naamani** [comment]
Thanks for the quick reply.
I'm using Noto-sans. The OS on which the java application is running is Windows 7. We tried remote desktop from windows 7 and windows 10. Occurs on both.

**Comment by moyogo** [comment]
Remote Desktop sessions will disable font smoothing (anti-aliasing) as default to save bandwidth, see https://technet.microsoft.com/en-us/library/cc742823.aspx.

**Comment by moyogo** [comment]
@Naamani Sorry, I should have mentioned Arial has TrueType instructions that optimize the screen rasterization of the font with or without anti-aliasing.

**Comment by moyogo** [comment]
@Naamani Depending on what version of the Noto fonts you have they may have TrueType instructions, but only optimized for anti-aliasing. So when Remote Desktop disables font-smoothing,  things don’t look right.

**Comment by twardoch** [comment]
Indeed. Arial is an old font, developed in the period when font rasterization was purely black and white (Windows 3.1). Creating such font via manual hinting is very laborious, and would not be possible for a huge font family such as Noto.

**Comment by Naamani** [comment]
Got it. Thank you all.
