### ISSUE TITLE
jho ಝೊ is incorrect in Noto Sans Kannada

### ISSUE THREAD

**Issue by sridatta1** [googlei18n/noto-fonts#819]
ಝೊ ಝೋ are currently rendered in Noto Sans Kannada as ![jho sans](https://cloud.githubusercontent.com/assets/23263723/21580700/f338e7b6-d031-11e6-9c66-e0cf1059d187.PNG) 
with an extra ು element,but it is written similar to ಮೊ ಯೊ ( see pg 3 of [L2/14-005](http://www.unicode.org/L2/L2014/14005-telugu-kannada-vs-o-oo--UTN.pdf))
But it is designed correctly in Noto Serif Kannada
![jho comp](https://cloud.githubusercontent.com/assets/23263723/21580837/69f7ca82-d039-11e6-9e8f-0f1d5cf55dd7.PNG)

**Comment by JelleBosmaMT** [comment]
In all fairness: Noto Sans is not exactly the only font design using the
regular form of ಝ. The design has been reviewed and has been used for
several years before this issue has been reported. I recommend to get
feedback from a significant amount of other reviewers, before we come to
the conclusion about the (in)correctness of the current form of rendering.

**Comment by MayuraVerma** [comment]
Hello @JelleBosmaMT,

I second @sridatta1 review on this issue. I am native Kannada personal.
This is a issue that needs to be rectified. Since many type designers are benchmarking Noto Kannada, in their Kannada fonts initiated by Google. This font needs to be as accurate as possible with the script.

**Comment by sridatta1** [comment]
>In all fairness: Noto Sans is not exactly the only font design using the
regular form of ಝ. The design has been reviewed and has been used for
several years before this issue has been reported.
>
While observing that some fonts use this form of ಝೊ ಝೋ with an extra ು element. It is most probably due to the fact these syllables rarely occur in Kannada( may be only in ಝೋಂಪಿಸು,ಝೊಂಪಿಸು, ಝೊಂಪು etc ) thus they may not have realized these have special forms and  have used the regular forms of ೊ ೋ.
JHA ಝ, MA ಮ and YA ಯ have an ು element. Thus these consonants use the ಾ instead of ū  ೂ for its second part of vowel signs O and OO. That is, the two-part form is a composition of ĕ  ೆ and ā ಾ.

If the current glyph with extra ು element is the standard form, then it is unclear why the exceptions occur only for MA and YA, but not for JHA which is having similar graphical criteria.
also attaching use of ಝೋ  from a  published dictionary
![jho](https://cloud.githubusercontent.com/assets/23263723/23500700/ee0b55e0-ff56-11e6-9b8a-f7f0d37cb470.PNG)
Thus this issue needs to be rectified.

**Comment by JelleBosmaMT** [comment]
I agree, and added the character to my source files in January. Unfortunately I cannot make any predictions to when this will be available as that is out of my control.

**Comment by sridatta1** [comment]
> I agree, and added the character to my source files in January. Unfortunately I cannot make any predictions to when this will be available as that is out of my control.

Thank you

**Comment by MayuraVerma** [comment]
@JelleBosmaMT Hello Jelle,
Off-topic question!
Do you have predictions on when we get Kannada font with multiple weights?

**Comment by JelleBosmaMT** [comment]
I don't know about progress for the Noto Serif Kannada. For the Noto Sans Indics the Kannada is in a group with priority 3. At the moment I work on Bengali, the last of priority 2. Bengali is a major hurdle to take in the first half of the year. I don't know if there is a preference for Kannada, Telugu, Malayalam or Gujarati next.

**Comment by MayuraVerma** [comment]
@JelleBosmaMT Thank you.

Hopefully, Kannada is one top of list in that group.

**Comment by sridatta1** [comment]
This issue ( and many other issues) was fixed in the phase 3 fonts, thus closing this issue.
https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only
