### ISSUE TITLE
Noto Serif ᵑ̊ badly placed

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#823]
In Noto Serif, the combining character on top of superscript eng isn’t well placed.

For example, here’s the text ᵑ̊ʘˀ in Noto Serif: 
![image](https://cloud.githubusercontent.com/assets/1527880/21932783/a05615f8-d9a2-11e6-8f3a-f33695bd8ee0.png)

Compare eg. to Lucida Grande, pre-installed on macOS:
![image](https://cloud.githubusercontent.com/assets/1527880/21932813/c1cf1374-d9a2-11e6-8517-534256f73229.png)

Or Doulos SIL:
![image](https://cloud.githubusercontent.com/assets/1527880/21932827/d2fa2cd8-d9a2-11e6-8f27-a2970194874d.png)

The test string from [IPA tests](https://raw.githack.com/googlei18n/noto-source/master/test/und-fonipa.html) ([source](https://github.com/googlei18n/noto-source/blob/master/test/und-fonipa.html)) also appears on [Wikipedia](https://en.wikipedia.org/wiki/Bilabial_nasal_click#Glottalized_bilabial_nasal_click).

**Comment by marekjez86** [comment]
created https://github.com/google/roboto/issues/230
IMHO this should be closed (but I'll let @brawer to decide)

**Comment by brawer** [comment]
Thanks, you Marek.
