### ISSUE TITLE
Directory truncation for unhinted alpha fonts

### ISSUE THREAD

**Issue by Kanjilearner817** [googlei18n/noto-fonts#825]
The alpha font folder "from-pipeline/unhinted" currently truncates, at least for me, as there are more than a thousand files on record in the same directory. Might I suggest putting the font files in different folders for different scripts or so?

**Comment by marekjez86** [comment]
Thank you for the reminder. I'll split serif vs sans, but if you have any other suggestions, please let me know.

**Comment by marekjez86** [comment]
restructured the directories. we bought some time (sans has 723 font files; serif 333)
see https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-pipeline/unhinted
