### ISSUE TITLE
Both ARABIC-INDIC digits should have the same width

### ISSUE THREAD

**Issue by SafaAlfulaij** [googlei18n/noto-fonts#832]
The digits :
- ARABIC-INDIC DIGIT ZERO→NINE
-  EXTENDED ARABIC-INDIC DIGIT ZERO→NINE

does not have the same width, which causes aliging problems in chats.
Look at the left bracket and how it goes right and left inconsistency:
![screenshot](http://i.imgur.com/ofvoFTs.png)

Sample text:
```
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٢٤:٢٩‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٢٥:٤٨‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٢٥:٥٨‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٣١:٢٧‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٣٣:٠٣‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٣٤:١٤‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٣٤:٥٩‎]
[‏٣‏/٢‏/٢٠١٧ ١٨:٣٦:٢٣‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٣٦:٢٦‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٣٦:٤٧‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٣٧:١٢‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٤٢:٣٨‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٤٦:٠٠‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٤٦:٥٠‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٤٨:٠٥‎]
‏[‏٣‏/٢‏/٢٠١٧ ١٨:٤٨:١٩‎]
```

I got to know that `lnum` feature should do that, if the font supports it. But I don't know how can this be done.
I am using "Noto Naskh Arabic UI" font, under ArchLinux.

**Comment by TidharC** [comment]
Width difference is also reproducible with TextEdit on MacOS (see screenshot).

![notoarabicnumerals](https://cloud.githubusercontent.com/assets/16353803/22668423/8fabb6f0-ec75-11e6-81a5-a79732b77732.png)

**Comment by roozbehp** [comment]
This is working as intended. Software that needs Arabic-Indic digits to be aligned need to change to either use the lnum feature, or us a font that has fixed-width digits.
