### ISSUE TITLE
NotoNaskhArabicUI bottom baseline is high

### ISSUE THREAD

**Issue by nizarsq** [googlei18n/noto-fonts#835]
Comparing NotoNaskhArabicUI with NotoSansArabicUI and noticed the bottom baseline is higher for NotoNaskhArabicUI, this could cause some clipping problems and unaligned string when multiple script used in one sentence. Please check screenshot
![notonaskharabicui and notosansarabicui](https://cloud.githubusercontent.com/assets/22158882/22832961/e85bb83a-ef64-11e6-8e75-fbb2b368cd8f.png)

**Comment by jungshik** [comment]
@roozbehp

**Comment by jungshik** [comment]
Related to this is #842. 

As for the baseline alignment, I've just tried Arabic UI on Android.  Unlike Khmer (to my non-native/untrained eyes), this misalignment does not look bad with Roboto + Noto Naskh Arabic UI on Android.

**Comment by jungshik** [comment]
Anyway, Noto Naskh Arabic UI is a phase 2 font and we're supposed to be done with it. Despite that, #842 does need to be addressed, but this one I think can be left alone.

**Comment by marekjez86** [comment]
I talked to @roozbehp on Monday about truncation and he, IIRC, implicitly indicated that that this shift is acceptable by stating if Khmer is shifted no more than Noto Naskh Arabic UI, then it doesn't need to change.
