### ISSUE TITLE
Myanmar: suboptimal rendering of <1014, 1039, 1010, 103D> (ntwa)

### ISSUE THREAD

**Issue by mjansche** [googlei18n/noto-fonts#841]
The grapheme cluster န္တွ <1014, 1039, 1010, 103D> is rendered suoptimally using the latest HarfBuzz (at GitHub head, d4bb52b9) and noto-fonts/hinted/NotoSansMyanmar-Regular.ttf  version 1.10 (at GitHub head, 5e752397).

See the following image produced by hb-view:

![abbhuggantvaa](https://cloud.githubusercontent.com/assets/11460451/22986461/85d00534-f3a3-11e6-9947-6984d351cb31.png)

In particular:
1) the descender of န (1014) did not get shortened; and
2) the subscripted တ is positioned too far to the left, butting into the preceding subscript.

**Comment by roozbehp** [comment]
The cluster is actually quite common. Setting the priority to Critical.

**Comment by jungshik** [comment]
@marekjez86  what's the status of Myanmar in phase 3?  We have to make sure that Phase 3 delivery does not have this issue. 

@waksmonskiMT

**Comment by roozbehp** [comment]
We need a quick fix on Phase 2 fonts.

**Comment by marekjez86** [comment]
@mjansche : could you provide the rest of the text for the image that you used (I have no knowledge of Myanmar)?

**Comment by marekjez86** [comment]
@waksmonskiMT : 1. please ask the designer of SOW 15 fonts to test the above string and 2. when could we get a fix for the previous SOW 12 fonts?

**Comment by mjansche** [comment]
@marekjez86 : The text is အဗ္ဘုဂ္ဂန္တွာ

**Comment by marekjez86** [comment]
@mjansche : phase III font is fixed (see https://github.com/googlei18n/noto-fonts/blob/f393d4440bdf11d3a46b6e6dab9604d6e17474f8/alpha/from-pipeline/unhinted/otf/sans/NotoSansMyanmar-Regular.otf )

**Comment by mjansche** [comment]
Thanks, that looks much better now:
![image](https://cloud.githubusercontent.com/assets/11460451/23619210/dab87af4-028a-11e7-9b12-ce59d0daecf1.png)
