### ISSUE TITLE
Khmer diacritic rendering is inconsistent between static and variable fonts

### ISSUE THREAD

**Issue by TidharC** [googlei18n/noto-fonts#847]
SUMMARY

Khmer diacritic rendering is inconsistent between static and variable versions of Noto Sans Khmer.

REPRODUCTION STEPS

0.  Install the appropriate fonts and modified fonts.xml file, then reboot.  Also, have another device with the original (static) fonts and fonts.xml file; this is needed for comparison.
1.  Navigate through system settings and content, e.g. websites.

OBSERVED RESULTS

Inconsistent diacritic rendering (see screenshot).

EXPECTED RESULTS

Consistent diacritic rendering.

ADDITIONAL INFORMATION

Font name(s): NotoSansKhmer-GX.ttf 1.901, NotoSansKhmerUI-GX.ttf 1.900

Platform: Android

I am not sure what is the correct rendering for the different diacritic combinations (is the static font completely correct?).  It is advisable to have a native Khmer reader review this issue.

![khmerdiacritics](https://cloud.githubusercontent.com/assets/16353803/23088135/92ea1fc0-f52e-11e6-9297-4f0ec1f8e91a.png)

**Comment by punchcutter** [comment]
The right side is correct and represents the latest version. The version on the left is the old version. If you compare the updated static font with the GX font they will match.

**Comment by marekjez86** [comment]
@TidharC : Where did the left hand version come from? Was it installed on the device (if yes, from where) or "came" with it?

**Comment by jungshik** [comment]
I talked to @TidharC, the left is an old version as currently installed on Android device. 

A newer version has to be checked to see if this is fixed. 
@TidharC, you can grab a newer version from 'from-pipeline' directory.

**Comment by hrhatada** [comment]
I verified with the phase III font, and it looked like the right hand side.

![image](https://cloud.githubusercontent.com/assets/16353449/23975519/8ad2faf8-099e-11e7-8918-9550e7500b21.png)
