### ISSUE TITLE
NotoNaskhArabicUI could clip top diacritics when more than one used or if it placed on the top of hamza

### ISSUE THREAD

**Issue by nizarsq** [googlei18n/noto-fonts#853]
Tested NotoNaskhArabicU on Android and noticed if I place more than one diacritic on the top of character or if diacritic placed on the top of hamza it will be clipped and not displayed correctly. This test case just an example and could be found in many other cases. I used NotoNaskhArabicUI Version 1.06 uh pulled from Android most recent build. String tested"أُوْلَئِكَ" on Keep App and on our personal tool.
![screen shot 2017-02-27 at 10 42 58 am](https://cloud.githubusercontent.com/assets/22158882/23376275/6e00d65e-fce0-11e6-81c0-72144144a1c2.png)

**Comment by marekjez86** [comment]
@waksmonskiMT : could somebody look at this issue?

**Comment by marekjez86** [comment]
test case with the numbers:
font_file_name=" NotoSansArabicUI-Regular.ttf "
language=" Arabic "

ymin -293, ymax 1069 --> that's what is expected
but 

- u'\u0627\u064b\u0627' gives 1086 as ymax (17 more than maximum should be)
- u'\u0623\u064b\u0623' gives 1219 as ymax (150 more than maximum should be)

**Comment by marekjez86** [comment]
using https://github.com/googlei18n/noto-source/blob/master/test/Arabic/specimen-Arabic-NOT-clipping.html
as an input to
https://github.com/googlei18n/nototools/blob/master/nototools/test_vertical_extents.py 
program 
with the fonts that were provided on June 24, 2015
https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoNaskhArabicUI-Regular.ttf

I get the following results (all exceeding the maximum):

======= specimen-Arabic-NOT-clipping.html =======

language=" Arabic "
ymin -555, ymax **2163**
[((170, **2231**), u' \u0623\u064e'), ((170, **2314**), u' \u0623\u064b'), ((170, **2344**), u' \u0623\u064f'), ((170, **2344**), u' \u0623\u064c'), ((-20, **2285**), u'0652 \u0623\u0652')]
" أ" (170, 2231)
" أ" (170, 2314)
" أ" (170, 2344)
" أ" (170, 2344)
"0652 أ" (-20, 2285)

**Comment by nizarsq** [comment]
Thanks Marek for these results, do you think it is good idea to push the font build that doesn't have clipping and test it on actual device?

**Comment by marekjez86** [comment]
the fonts in https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-thirdparty fix the problem describe here. please verify it is fixed. thank you.

**Comment by nizarsq** [comment]
This fix verified on NotoNaskhArabicUI-Bold/hinted and NotoNaskhArabicUI-Regular/hinted 1.07 and NotoNaskhArabicUI-Bold/unhinted and NotoNaskhArabicUI-Regular/unhinted build 1.07uh. Thanks
![hinted](https://cloud.githubusercontent.com/assets/22158882/24157781/9afe7862-0e17-11e7-9429-290c2eb1b22d.png)
![unhinted](https://cloud.githubusercontent.com/assets/22158882/24157785/9c945e08-0e17-11e7-9ef6-1510108eff79.png)

**Comment by nizarsq** [comment]
Reopening this bug because the fix is not the ideal fix, apparently to solve this issue letter alif got squeezed when ever a diacritics come over the hamza, this behavior make the hight of this letter not consistent with the other letters, please look at attached screenshot.
![853](https://cloud.githubusercontent.com/assets/22158882/24206184/b513ad44-0eda-11e7-9310-e9ea2e2e8d67.png)

**Comment by marekjez86** [comment]
However, this is what we agreed to do with the designers :-)
