### ISSUE TITLE
Naskh Arabic UI hyphens too low

### ISSUE THREAD

**Issue by roozbehp** [googlei18n/noto-fonts#858]
The hyphen characters in Noto Naskh Arabic UI fonts are too low. They are supposed to be vertically aligned with the horizontal stems of the Arabic letters (which is shifted up in Arabic UI fonts), but instead they are on the font baseline. They should be shifted up the same amount as the Arabic letters, so they would have the appearance of being on the baseline.

(Note that this only happens in the UI fonts. The non-UI fonts have both the baseline for the Arabic letters and the hyphens at the actual font baseline.)

**Comment by nizarsq** [comment]
Was able to see this behavior 
![screen shot 2017-03-03 at 8 47 44 am](https://cloud.githubusercontent.com/assets/22158882/23560137/3fdac1ac-ffee-11e6-80cc-84f00d55cf31.png)

**Comment by marekjez86** [comment]
the fonts in https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-thirdparty fix the problem describe here. please verify it is fixed. thank you.

**Comment by nizarsq** [comment]
Retested this issue on NotoNaskhArabicUI-Bold/hinted and NotoNaskhArabicUI-Regular/hinted 1.07 and NotoNaskhArabicUI-Bold/unhinted and NotoNaskhArabicUI-Regular/unhinted 1.07uh and 
![858](https://cloud.githubusercontent.com/assets/22158882/24158807/97d18352-0e1a-11e7-8825-41199ce378a8.png)
![858](https://cloud.githubusercontent.com/assets/22158882/24158851/b26ac66a-0e1a-11e7-8498-64bbf153fc37.png)

issue still producible.

**Comment by marekjez86** [comment]
@nizarsq : what's the text that I could use to test it?

**Comment by nizarsq** [comment]
lets use same in the original bug "نــــزار"

**Comment by roozbehp** [comment]
@nizarsq's screenshots is unrelated to the problem. His screenshots are about underscores. The bug is the height of hyphen characters U+2010 and U+2011.

**Comment by nizarsq** [comment]
@roozbehp sorry I misunderstood the issue.

**Comment by marekjez86** [comment]
@roozbehp : in the fonts that's in my hands and are in  https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-thirdparty
both hyphen characters U+2010 and U+2011 went up from Y=0 to Y=276 (font has 2048 units per Em). this is what Monotype already fixed

**Comment by marekjez86** [comment]
difference in Regular weight 
(red: old version; green: font from https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-thirdparty )
U+2010 
![uni2010](https://cloud.githubusercontent.com/assets/13322623/24471803/29623146-1478-11e7-8e63-92ba2ea671fb.png)

U+2011
![uni2011](https://cloud.githubusercontent.com/assets/13322623/24471820/39486594-1478-11e7-990b-222975febd62.png)

**Comment by marekjez86** [comment]
@jungshik : to pickup the font from  https://github.com/googlei18n/noto-fonts/tree/master/alpha/from-thirdparty (if not done already)
