### ISSUE TITLE
Myanmar Serif : Expected ligature not performed

### ISSUE THREAD

**Issue by JackfromMc** [googlei18n/noto-fonts#860]
Greetings to all!

The string of characters "u1012\u1039\u1013\u1039\u1014" should result in a ligature which glyph is called "da dha na". Unfortunately the ligature is not performed. Probable cause is a small error in a lookup. I believe this happens in all fonts. Pity this ligature is not possible in the Myanmar Sans family.

OBSERVED BEHAVIOUR:
![capture d ecran 8](https://cloud.githubusercontent.com/assets/23061375/23576716/72cee80c-00db-11e7-9b8f-83df93e5e53d.png)
Font: NotoSerifMyanmar-Regular.ttf

EXPECTED BEHAVIOUR:
![capture d ecran 10](https://cloud.githubusercontent.com/assets/23061375/23576722/9895f27e-00db-11e7-8f5b-03eb163c438d.png)
Font: NotoSerifMyanmar-Regular.ttf as modified by myself

POSSIBLE SOLUTION:

In Lookup 17 : Replace string of glyphs to be ligatured from "da dha.sub **na.sub2** with "da dha.sub **na.sub**".

Thanks

**Comment by marekjez86** [comment]
test case https://github.com/googlei18n/noto-source/blob/master/test/Myanmar/my-860.html
observed with the most recently built fonts

SERIF top
SANS bottom

![my-860](https://cloud.githubusercontent.com/assets/13322623/23665947/c46fff0e-030e-11e7-9178-e4790bae710d.jpeg)

**Comment by JackfromMc** [comment]
The glyph doesn't exist in the Myanmar Sans family. It's not that big of a deal, almost no one knows this ligature in Myanmar and it is not used in the Myanmar language. It is only used for Sanskrit. But I thought because the glyph was so beautifully designed it might as well be nice to be able to use it.

**Comment by mgbellarosa** [comment]
@JackfromMc 
In the next release of Myanmar Serif, the ligature has been enabled.
![screen shot 2017-08-10 at 3 20 45 pm](https://user-images.githubusercontent.com/29443471/29194851-6b4ecd2c-7de0-11e7-9db0-de23c09f9d4b.png)

Best,
Glenda

**Comment by marekjez86** [comment]
mgbellarosa: tested Myanmar Serif from https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/serif . the ligature has been enabled. thank you.
