### ISSUE TITLE
Copyright attribution

### ISSUE THREAD

**Issue by pulkomandy** [googlei18n/noto-fonts#861]
Hi,
I am bundling Noto (Sans and CJK JP for now, possibly others later) fonts inside other software. According to the licence I think I should comply to this:

```
2) Original or Modified Versions of the Font Software may be bundled,
redistributed and/or sold with any software, provided that each copy
contains the above copyright notice and this license. These can be
included either as stand-alone text files, human-readable headers or
in the appropriate machine-readable metadata fields within text or
binary files as long as those fields can be easily viewed by the user.
```

However, the licence file does not include any "above copyright notice". What is the proper copyright attribution for the fonts?

**Comment by twardoch** [comment]
For Noto Sans CJK, the copyright attribution is: 

```
Copyright © 2014, 2015 Adobe Systems Incorporated (http://www.adobe.com/).
```

For other Noto fonts, the copyright attribution is: 

```
Copyright 2015, 2016, 2017 Google Inc. All Rights Reserved.
```

**Comment by dougfelt** [comment]
Also, the copyright lines are included in the copyright portion of the name table built into the font.  I believe this meets the condition you cite.  So, basically, if you change or redistribute the font you just need to leave the copyright notice in the font.
