### ISSUE TITLE
Noto Urdu issues

### ISSUE THREAD

**Issue by mhmangum** [googlei18n/noto-fonts#870]
So I downloaded the font and installed it on my Nexus 5X via rooted iFont app. There is Tofu in the interface. Moreover, the spacing is so off for the parts where latin characters come that they are being cut off in the UI.

I know this is a very UI specific issue but shouldn't the font be designed in a way that the font and UI work in harmony.

Also, is there any way to combine the roboto and Noto Urdu in way that these issues can be resolved.

Link to screenshots:
https://goo.gl/photos/Zy8EkMzK9E2fs6nBA
https://goo.gl/photos/MB3NHWMji436Mdxt5
https://goo.gl/photos/T8zXpQ81xqiXuPVJ7
https://goo.gl/photos/qETY5zpCtVhUnnAU6

Also, 
This font (Noto Sans Urdu) is readable, and can be understood, but only few number are in Arabic style Such as date 2016  digit 6 is in Arabic form and can be hard for normal readers to understand. It is  easily read able.

**Comment by marekjez86** [comment]
@mhmangum : did you install any Latin fonts also? What I see is not a Roboto nor Noto Sans.

**Comment by mhmangum** [comment]
Yes Roboto is installed and Noto Sans Urdu was just installed.

**Comment by jungshik** [comment]
Noto Sans Urdu font is **not** for UI.  I don't know what iFont app does, but if you made Noto Sans Urdu as the primary UI font on Nexus 5x, what you see is kinda expected. 

@roozbehp

**Comment by roozbehp** [comment]
Confirming that to get the font working properly on Android, the app needs to be aware of different metrics etc. Nothing fixable here really.
