### ISSUE TITLE
Myanmar Serif : Anchors badly placed on U+1012

### ISSUE THREAD

**Issue by JackfromMc** [googlei18n/noto-fonts#871]
Greetings everyone!

Superscribed and subscribed diacritics and letters are badly placed on this specific character in all fonts of the Myanmar Serif family. They're not perfectly aligned on the vertical axis.

![capture d ecran 12](https://cloud.githubusercontent.com/assets/23061375/23896032/4663986e-08d6-11e7-9bc9-8be889fc0c6d.png)

fonts: NotoSerifMyanmar-light, regular and bold .ttf ; text: "ဒီ"="this" (demonstrative) ; "ဗုဒ္ဓ"="Buddha"

All other characters are fine

**Comment by mgbellarosa** [comment]
@JackfromMc 
In the next release of Myanmar Serif, the placement of diacratics under u1012 and of the subscript form of u1012 has been optimized.
![screen shot 2017-08-10 at 3 25 04 pm](https://user-images.githubusercontent.com/29443471/29194961-f878d486-7de0-11e7-9891-885379891a5f.png)

Best,
Glenda

**Comment by marekjez86** [comment]
please check https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/serif fonts
