### ISSUE TITLE
Missing Scripts

### ISSUE THREAD

**Issue by TsavyPrince** [googlei18n/noto-fonts#873]
You probably already know about this but many scripts are missing and maybe a few symbols.

**Comment by kenlunde** [comment]
Vagueness → 💩👎💩
Details, to include specific scripts and code points → ✨👍✨

**Comment by marekjez86** [comment]
Thank you for the feedback -- we are in progress of enlarging the script library. Also currently supported scripts will be updated up to Unicode 9. Anything beyond Unicode 9 will be updated in the future.
