### ISSUE TITLE
More Unicode Characters

### ISSUE THREAD

**Issue by TsavyPrince** [googlei18n/noto-fonts#875]
Since I'm planning to use special Unicode characters not used for scripts in documents, could you please add symbols like misc symbols, optical character recognition characters, and other things like that.
You may have already planned to do these things.

**Comment by dougfelt** [comment]
Yes we are. In short we aim to support all of Unicode 9 with the exception of CJK, which will continue to leave plane 2 mostly uncovered. For details of planned character support see the nototools repo, in nototools/data/noto_cmap_phase3.xml.
