### ISSUE TITLE
NotoSansThaiUI-VF.ttf font has the diacritics shift problem

### ISSUE THREAD

**Issue by hrhatada** [googlei18n/noto-fonts#879]
1. On the device A, replace 
   - NotoSansThai-Reguler.ttf
   - NotoSansThai-Bold.ttf
   - NotoSansThaiUI-Reguler.ttf
   - NotoSansThaiUI-Bold.ttf
to 
   - NotoSansThai-VF.ttf
   - NotoSansThaiUI-VF.ttf
and modify the fonts.xml file
         
2. On the device B, replace the NotoSansThai fonts to the phase III fonts
3. Reset the both devices to start the setup wizard, and compare the fonts.

RESULT : Some of the variable font's diacritics position shift is slightly shifted to the left. Please refer to the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/16353449/24124804/aa33244e-0d82-11e7-9c1e-7d7b6dd82137.png)

**Comment by xiangyexiao** [comment]
@hrhatada you mentioned that the diacritics shifting issue is gone offline. could you confirm and close the bug?

**Comment by hrhatada** [comment]
Yes, diacritics problem had gone on the different OS.
