### ISSUE TITLE
ConScript Unicode Registry Support

### ISSUE THREAD

**Issue by TsavyPrince** [googlei18n/noto-fonts#883]
Will there be ConScript Unicode Registry support or not? I am also looking for Under-Conscript Unicode Registry Support.

**Comment by sommerluk** [comment]
Well, I’m not a contributer of this project (only a user), but the FAQ at https://github.com/googlei18n/noto-fonts/blob/master/FAQ.md#what-are-googles-plans-for-noto-so-called-phase-3 says:

> We plan to extend character/script coverage to cover 100% of Unicode 9.0 except for CJK. For CJK, we plan to cover Plane 0 (BMP) CJK characters in Unicode 9.0

ConScript Unicode Registry is not part of Unicode, so it is not covered.

If Noto developers would ever decide to extend Noto to PUA (defined outside Unicode), IMHO there might be more obvious and useful choises like Mufi/Lincua (http://folk.uib.no/hnooh/mufi/, http://andron-typeforum.xobor.de/t10f13-Towards-a-linguistic-corporate-use-area-LINCUA.html).

**Comment by brawer** [comment]
Noto exists to support Unicode. To add a character that isn’t in Unicode yet, simply make a [proposal to extend Unicode](http://unicode.org/pending/proposals.html); anyone can do this. For example, MUFI has filed such requests in [N3027](http://folk.uib.no/hnooh/mufi/proposals/n3027-medieval.pdf) and [N4707](http://folk.uib.no/hnooh/mufi/proposals/n4704-medieval-punct.pdf). Your request will then get reviewed by the Unicode committee. For example, see [here](http://www.unicode.org/L2/L2016/16004.htm#146-C2) for the discussion of N4707. Once the characters are in Unicode, the entire computing industry will eventually follow. Admittedly it’s a long process to go through Unicode, and it will take years from initial proposal to widespread font support. But it will have a **much** longer-lasting impact than building a few hacked-up fonts here and there. — Said this, anyone is free to fork Noto and draw their own glyphs; the sources are [here](https://github.com/googlei18n/noto-source).

**Comment by Binary-Hazard** [comment]
I made [this](https://github.com/Binary-Hazard/Font-List).
