### ISSUE TITLE
NotoSansMyanmarUI fonts have the string overlap problem on Android platform.  Happens on all phase II & III, and the variable font, too.  

### ISSUE THREAD

**Issue by hrhatada** [googlei18n/noto-fonts#885]
STEPS TO REPRODUCE
0. You need Android MNC or NYC device which support Myanmar.
1. Change the system language to Myanmar(မြန်မာ)
2. Launch the Settings
3. Check the system setting UIs

RESULT : The string overlap occurs the UI which contains the multiple line strings.

NOTE : This happens on the phase III & variable fonts, too.

![image](https://cloud.githubusercontent.com/assets/16353449/24427335/6b260e36-13bf-11e7-8948-c13f9c8c27a6.png)

**Comment by roozbehp** [comment]
Not really a Noto bug since the fonts follow the guidelines given to them by Android as far as I can tell.
