### ISSUE TITLE
Add support of Latin Extended-D

### ISSUE THREAD

**Issue by Kendos-Kenlen** [googlei18n/noto-fonts#893]
Some languages needs support of characters in [Latin Extended-D](https://unicode-table.com/en/blocks/latin-extended-d/) script.

**Comment by brawer** [comment]
The currently released version of Noto targets Unicode 6.1, which pre-dates Latin Extended D. The upcoming version will cover Unicode 9, including Extended D. Here is an alpha version of the new fonts: https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-pipeline/unhinted/ttf/sans/

**Comment by verdy-p** [comment]
Great, at least we'll be able to write also some African languages in addition to Northern and Eastern European languages as they were standard still in the 1910's (notably for books that fall now in the public domain and are still perfectly readable in their original orthography).
Even today (including in English!) there's a use for some ligatures (such as ao and AO) only found in Latin Extended-D. This is not just for medievalists (even if most additions in Extended-D was addressing their demand) as many texts exist that were in the modern period (long after the middle-age and renaissance, up to the 20th century at least).
These letters have still not disappeared and are being reused for other minority languages, and are reintroduced also in Western European languages (after the short dark age of ASCII, which is the very old Middle Age for computers !)
