### ISSUE TITLE
Typo in issue reporting template

### ISSUE THREAD

**Issue by behdad** [googlei18n/noto-fonts#903]
The issue reporting template misspells "HarfBuzz" as "Harbuzz".  Please fix.  Also, mention hb-view and hb-shape tools.

## Where you downloaded the font file and when, e.g.

Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArmenian-hinted.zip
Date: 2017-04-10 (preferred format)
Note: Write the OS version and build ID if the font is pre-installed on an OS (usually available in the Settings apps)

## Version info (or OS version and build if the font is pre-installed in a build)

Mac - right mouse click on a font and try Preview to see version info
Win -- right mouse click on a font (Local Disc > Windows > Fonts) and see version info on Properties
Linux -- use (Gnome) Font Viewer: open a font and click on Info tab

## Issue summary (if you are filing a defect report)

(Summarize the issue briefly -- one paragraph preferred.)

  # include reproduction steps: Step 1. …, Step 2. …, etc.
  # Observed results
  # Expected results
  # Other relevant information (Unicode chart, technical specs, shaping info, comparison with non-Noto fonts, comparison with earlier version of the same font (regression cases)

## Include real characters data to illustrate your issue -- Unicode codepoints are helpful
Developers who might not know the language/script can copy/paste the text to reproduce the issue.

## Include a screenshot or an image illustrating the issue -- added annotations are very helpful

  # You can use use tools like Harbuzz (shaping characters) to help isolate if an issue is in an app/OS, shaping engine or in the font.  
  # You can use Fontview to attach an screenshot how a sample text displays. If you want to show how 2 versions of the same fonts differ in display of the same text, you can use Fontdiff.

Note: These tools are all available at: https://github.com/googlei18n/

**Comment by KatMomoi** [comment]
Thanks,  corrected the typo and added a mention of hb-view and hb-shape. Please take a look -- you were assigned as a reviewer for the patch.
