### ISSUE TITLE
Repo size has grown too big again

### ISSUE THREAD

**Issue by behdad** [googlei18n/noto-fonts#906]
Total size of actual fonts in hinted/ and unhinted/ are under 100MB.  Yet, the repo has grown into over a GB because of the alpha/ directory.  This makes cloning the repo or just updating very painful.

I suggest we surgically remove alpha/, and move it to a new noto-alpha repo.

@dougfelt @marekjez86  wdyt?

**Comment by marekjez86** [comment]
I'm fine with noto-alpha

**Comment by dougfelt** [comment]
That would buy us a little bit of time.  Certainly for noto-fonts as a
repository of the released fonts, which was its original purpose.

noto-alpha would continue to grow though, this won't give it much room.

**Comment by fitojb** [comment]
Note that you can do a “[shallow clone](https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt)” with no history, which has no impact on development if you use a recent version of Git. That will save you time and space when cloning big repositories.

**Comment by twardoch** [comment]
I agree that the noto-fonts repo would be a great place to only hold the font files that are "released" or "close to release". For example, alpha or beta fonts but only in 1-2 flavors. And wet could settle on a somewhat stable folder structure. 

"Experiments" like versions built using different toolchains (glyphsapp vs pipeline etc.) where ultimately the folder structure will change massively and some files are only there for the time being but aren't intended to stay could go to a different repo, such as "noto-alpha" or "noto-devel". 

I think having one repo for sources, one for build workflows and experiments, and one for "deliverables" (of different staging quality) would be a logical system.

**Comment by behdad** [comment]
I like that separation as well.  noto-build maybe even.  One day it will carry automatically built fonts whenever noto-source or fontmake change.  I'll go ahead and do the split some time.

**Comment by twardoch** [comment]
In other words, I'd propose the following: 
* [**noto-source**](https://github.com/googlei18n/noto-source) as the repo for questions about **design**, with the issue tracker dedicated possibly to design questions or just to the organization of the repo itself 
* **noto-build** as the repo for the **build** process, stuff regarding `glyphsLib` and `fontmake` in relation to the Noto fonts, the different planned delivery scenarios (variable, non-variable, OTF, TTF etc.), with the issue tracker targeting mostly "font developers" and "font software developers", or possibly some 3rd parties who have a developer's mindset and are heavy into experimenting
* [**noto-fonts**](https://github.com/googlei18n/noto-fonts) as the repo for the **delivery** process, i.e. hosting more or less final font files in the formats that we actually intend to deliver, and that are either ready for wide consumption or are ready for "public testing" of sorts, with the issue tracker mostly open to outside users who'd posting general questions about usage of Noto, or be reporting problems with the fonts in outside scenarios.

**Comment by twardoch** [comment]
Hehe, I just wrote "noto-build" as well :)

**Comment by behdad** [comment]
I see @dougfelt created https://github.com/googlei18n/noto-fonts-alpha already.  Doug: when everything is moved there, let me know and I'll do git surgery to remove alpha/ from this repo's history.

**Comment by dougfelt** [comment]
I think @marekjez86 was going to move them.  I can if he doesn't.

We don't need to maintain the history of these files, do we?  Generally they get replaced en masse whenever Marek does a new pipeline build anyway.

I'm still concerned about storing all these binaries in github, we'll hit their limits again as we build more fonts out.  But this will give us some room and is a better organization anyway.

**Comment by marekjez86** [comment]
I finished moving them (but I dropped the history :-)). The fonts are in https://github.com/googlei18n/noto-fonts-alpha

**Comment by sommerluk** [comment]
The alpha folder still exists at https://github.com/googlei18n/noto-fonts/tree/master/alpha and contains Noto Sans Historic. Is this intentional?

**Comment by dougfelt** [comment]
Yes, it predates the use of alpha to hold the phase 3 in-development fonts.   Previously this held a few phase 2 fonts that weren't quite ready that we were experimenting with and wanted to make available more broadly.  NotoSansHistoric is the only one of those left.

(NotoSansHistoric was an early experiment with combining multiple scripts into a single font.  Sometime after that we decided to split fonts apart by script as much as possible, but this remained.  Different people prefer different packaging and we've never quite resolved how to deal with this.)

**Comment by behdad** [comment]
Opening and reassigning to myself to remove alpha/ from history.

**Comment by behdad** [comment]
> Yes, it predates the use of alpha to hold the phase 3 in-development fonts. Previously this held a few phase 2 fonts that weren't quite ready that we were experimenting with and wanted to make available more broadly. NotoSansHistoric is the only one of those left.
> 
> (NotoSansHistoric was an early experiment with combining multiple scripts into a single font. Sometime after that we decided to split fonts apart by script as much as possible, but this remained. Different people prefer different packaging and we've never quite resolved how to deal with this.)

I think we should go ahead and remove it... It was part of our merging effort, which we are not currently pursuing anymore.

**Comment by behdad** [comment]
Done.
