### ISSUE TITLE
Missing smallcaps African letters

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#912]
Currently, Noto Sans looks very uneven for African languages in small caps. The reason is that the font doesn’t seem to have smallcaps variants for African letters, so the Chrome browser (and other text rendering systems) falls back to lowercase. Can we add the missing glyphs?

![image](https://cloud.githubusercontent.com/assets/1527880/25791067/a168cc2c-3372-11e7-8443-9a4c9c0c8bdc.png)

For a longer example, see the [Universal Declaration of Human Rights in Guinea Kpelle](https://github.com/googlei18n/noto-fonts/files/982418/udhr_kpe.pdf) (scroll down a few pages for the small caps rendering). For later reference, I’m also attaching the [HTML file](https://github.com/googlei18n/noto-fonts/files/982421/udhr_kpe.html.zip) used to generate this PDF.

**Comment by moyogo** [comment]
@brawer duplicate of #913?

**Comment by brawer** [comment]
Strange; indeed.
