### ISSUE TITLE
Braille Character (Points 4, 5, 6) Alignment

### ISSUE THREAD

**Issue by profaurore** [googlei18n/noto-fonts#932]
Font: NotoSansSymbols-Regular.ttf
Site: https://noto-website.storage.googleapis.com/pkgs/NotoSansSymbols-unhinted.zip
Date: 2017-06-02
Version: 1.09 uh
OS: Microsoft Windows 8.1
Software: Google Chrome 58.0.3029.110 (64-bit)

Issue: I linked to the Noto Sans Symbols file from an HTML page and set the font face of the page to Noto Sans Symbols. I wrote the following three Braille symbols: ⠿⠨⠿ (u283F, u2828, u283F). The expected result is to see two full cells (points 1-2-3-4-5-6) around two right-aligned points (points 4-6). The sequence, however, renders two left-aligned points (points 1-3), which is equivalent to ⠿⠅⠿ (u283F, u2805, u283F).

The top text is Arial and the bottom is the same text from Noto Sans Symbols.
![braille_sequence](https://cloud.githubusercontent.com/assets/10480819/26755135/5d3fad98-4855-11e7-8e06-decce3aacb70.PNG)

**Comment by TidharC** [comment]
This is also reproducible with TextEdit on Mac.

![notosanssymbolsbraille](https://user-images.githubusercontent.com/16353803/26858795-516a5e10-4ae8-11e7-83eb-66b5002d8e12.png)

**Comment by marekjez86** [comment]
u2828 and u2805 are currently identical in Symbols2 ; u2828 should be "mirror symmetric" to u2805

**Comment by roozbehp** [comment]
This apparently also happens with U+2808, U+2818, U+2838, etc basically making Noto unusable for Braille. Please fix.

**Comment by dougfelt** [comment]
So, the thing to do is look at
https://github.com/googlei18n/noto-fonts-alpha/blob/master/from-pipeline/unhinted/ttf/sans/NotoSansSymbols2-Regular.ttf
and see if this is still a problem there.

**Comment by marekjez86** [comment]
@waksmonskiMT : 2828 and 2805 are the same. 2828 should be symmetric to 2805 across the vertical axe.

Also bad: 
2808, 2818, 2838, 2830, 28B8, 2898, 28A8, 2888, 2810, 28B0, 2890, 2820, 28A0, 2880

In summary:
the most recent version of Symbols2 has the following Braille characters wrong:
2808, 2810, 2818, 2820, 2828, 2830, 2838, 2880, 2888, 2890, 2898, 28A0, 28A8, 28B0, 28B8

In general anything using only a subset of dots 4,5,6,8 is positioned incorrectly (it is located where dots 1,2,3,7 are).

Note there might be other Braille issues.

**Comment by marekjez86** [comment]
I also checked the source (to make sure that the incorrect characters are not result of the pipeline/fontmake problems). These issues are present in the source:


![symbols2-glyphs](https://user-images.githubusercontent.com/13322623/28718323-3cd1edf2-735a-11e7-8d6e-4d352d18bc40.jpeg)

**Comment by marekjez86** [comment]
for the fixed fonts please see https://github.com/googlei18n/noto-fonts-alpha/blob/master/from-pipeline/unhinted/ttf/sans/NotoSansSymbols2-Regular.ttf
