### ISSUE TITLE
Noto Sans Kaithi has Devanagari glyphs for ascii Digits(0-9)

### ISSUE THREAD

**Issue by sridatta1** [googlei18n/noto-fonts#933]
### Title 
  > Noto Sans Kaithi has Devanagari glyphs for u+0300-u+0309 (0-9) instead of 0-9

### Where the font came from, and when
  >
  >   https://www.google.com/get/noto/#sans-kthi
  >   Date: 2017-05-06 (preferred format)

**Comment by marekjez86** [comment]
Here are the digits in the font currently: 
![kt-digits](https://user-images.githubusercontent.com/13322623/26945918-4e707590-4c42-11e7-88c9-4d435789c0a6.jpeg)

There are Kaithi digits U+0966->U+96F and Devanagari digits in the U+0030->U+0039 Latin range.

@sridatta1 : are you saying that Kaithi uses Latin digits and not Devanagari versions? Have they ever used Devanagari digits?

**Comment by roozbehp** [comment]
The glyphs in the range U+0030..U+0039  should either be removed from the font, or show the common European form 0, 1, 2, 3, ..., 9.

**Comment by marekjez86** [comment]
@waksmonskiMT : Sue another set of Latin glyphs to be removed from the fonts.

**Comment by kmansourMT** [comment]
In the upcoming delivery (SOW15), there are no ASCII digits in the font. In addition, the Devanagari digits are encoded at the correct range of u+0966-096F.

**Comment by marekjez86** [comment]
@sridatta1 : please check the attached fonts. these should be fixed

 
[NotoSansKaithi-Regular.ttf.zip](https://github.com/googlei18n/noto-fonts/files/1519879/NotoSansKaithi-Regular.ttf.zip)

**Comment by sridatta1** [comment]
Version 1.05
![image](https://user-images.githubusercontent.com/23263723/33515920-5b885846-d78f-11e7-95ee-e5f4ae2fdd83.png)
They still remain.
Also existing glyphs of Devanagari digits should remain (northern style)
