### ISSUE TITLE
Noto cannot display some Mon characters

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#934]
Noto Myanmar fails to correctly render the [Universal Declaration of Human Rights in the Mon language](http://www.unicode.org/udhr/d/udhr_mnw.html).

![image](https://user-images.githubusercontent.com/1527880/26864698-c3f690cc-4b59-11e7-9413-b57b810e6462.png)

![image](https://user-images.githubusercontent.com/1527880/26864867-9136f66c-4b5a-11e7-9d31-c4bb8d9f946d.png)

Interestingly, SIL Padauk has the same problem:

![image](https://user-images.githubusercontent.com/1527880/26864894-a72a2bb0-4b5a-11e7-9ec2-045e4d95515f.png)

Whereas the [Pyidaungsu font](http://www.mcf.org.mm/download-center/pyidaungsu-font.html) renders the same text correctly:

![image](https://user-images.githubusercontent.com/1527880/26864910-b73aadfe-4b5a-11e7-8f2f-cd1748cf120e.png)

**Comment by marekjez86** [comment]
first I'd like to fix a fontmake bug https://github.com/googlei18n/fontmake/issues/265 and rerun these tests

**Comment by andjc** [comment]
@brawer i had a quick look at the Mon translation of the UDHR. There are a range of spelling errors in the document. Ie invalid character sequences so the rendering will be broken in places. Not a font issue. An input and editing issue.

Eg

တှေ်  versus တှ်ေ

**Comment by brawer** [comment]
@andjc, thanks for telling! Would you know anyone who could fix the spelling errors in http://www.unicode.org/udhr/d/udhr_mnw.xml ? (This XML file is the actual source, used to generate the HTML and other versions).

**Comment by andjc** [comment]
@brawer will ask around. If I have time I could do some of the obvious ones. In the examples you give, it's a single systemic typing or conversion error. Repeated.

**Comment by miguelsousa** [comment]
Eric Muller used to be the maintainer of UDHR.

**Comment by mjansche** [comment]
I ran a [UTN11 canonicalization tool](https://github.com/googlei18n/language-resources/blob/master/my/check_myanmar_text.py) over the text, which fixed most of the representation issues except for a few stray/duplicate occurrences of 103A (ASAT). After that I don't see any obvious rendering problems anymore. Barring further discoveries, I would agree with andjc that this is an input/representation issue, not a font issue.

**Comment by marekjez86** [comment]
@mjansche @brawer : where could I get the corrected version of Mon UDHR?

**Comment by marekjez86** [comment]
This is not a font issue but a UDHR issue. Closing this.
