### ISSUE TITLE
Full width punctuations U+2018, U+2019, U+201C and U+201D in Chinese

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#94]
```
What steps will reproduce the problem?
1. Set font to Noto Sans CJK Traditional Chinese in browser and word processor 
2. Browse a web page or edit a document containing these characters

What is the expected output? What do you see instead?
These punctuation marks should be rendered proportionally. Instead they are 
full-width.

What version of the product are you using? On what operating system?
Noto Sans CJK Traditional Chinese, initial release.

Please provide any additional information below.
The texts in the attached screenshots are:
1. How Hooters Came to Symbolize Bond Market’s Desperation
2. 「這很好」英文可以說 “It’s good”

```

Original issue reported on code.google.com by `ping...@google.com` on 24 Jul 2014 at 8:33

Attachments:
* [apostrophe on plurk.png](https://storage.googleapis.com/google-code-attachments/noto/issue-94/comment-0/apostrophe on plurk.png)
* [Screen Shot 2014-07-24 at 11.30.48 AM.png](https://storage.googleapis.com/google-code-attachments/noto/issue-94/comment-0/Screen Shot 2014-07-24 at 11.30.48 AM.png)

**Comment by fontguy** [comment]
Moved to https://github.com/googlei18n/noto-cjk/issues/5
