### ISSUE TITLE
Underlined version of ordinal indicators

### ISSUE THREAD

**Issue by sommerluk** [googlei18n/noto-fonts#940]
Current rendering (current Noto alpha):
![screenshot 3](https://user-images.githubusercontent.com/6830724/27517446-856a000c-59bc-11e7-9bd2-341b2596612a.png)

It would be nice to have an underlined version of the ordinal indicators

U+00AA FEMININE ORDINAL INDICATOR
U+00BA MASCULINE ORDINAL INDICATOR

maybe as a stylistic set.

**Comment by TidharC** [comment]
Note that the indicators are also not underlined in non-Noto fonts, e.g. Arial, Lucida Grande, Times New Roman etc.

**Comment by fitojb** [comment]
Typographically speaking, the underline of ª and º was an alternative form of the mandatory dot that goes with abbreviations; nowadays, it’s only found in handwriting. In some old books you can also find fonts where these _letras voladas_ didn’t have an underline, but a dot below, positioned more or less like an interpunct ·. In modern Spanish and Portuguese, you just use a period like this: _M.ª, n.º, 13.<sup>er</sup>, Sr.<sup>as</sup>_, etc. That makes the underline unnecesary. If underlines are to be added, then you have to remove the dot from the abbreviation (many people do that), but that goes against the grammar rules specified by ASALE.

If the motivation behind this request is to distinguish º from the degree symbol °, which happens too often, even among Spanish speakers (differing keyboard layouts to blame?), I suggest making the ordinal characters a little bigger, which is good practice anyway.

**Comment by sommerluk** [comment]
Thanks for the explication. I didn’t know about the point-vs-underline typografic connection in Spanish and indeed I did it wrong (without dot) until know when writing Spanish.

By the way: What is the recommended way to deal with cases like 13.<sup>er</sup> (or 2<sup>de</sup> in french, or D<sup>r</sup>)? The “subs” OpenType feature does not seem to work in Noto for these letters. Modifier letters like U+1D48 MODIFIER LETTER SMALL D? Like Madame (Mᵐᵉ) et Mademoiselle (Mˡˡᵉ)? The ordinal indicators do not share the same baseline with the modifier letters…

**Comment by moyogo** [comment]
@sommerluk The recommended way is with the 'ordn' OpenType feature which Noto fonts (or most fonts actually) are lacking for the relevant characters. The modifier letters were encoded for phonetic transcriptions or mathematical notations and, in theory, should not be used for ordinals.

See #820 for the OpenType superscript and subscripts, and for the alignement #438.

**Comment by sommerluk** [comment]
Thanks for excplication.

So I’ll close this issue…
