### ISSUE TITLE
Noto Sans Myanmar

### ISSUE THREAD

**Issue by YinMayOo** [googlei18n/noto-fonts#941]
### Title 
  > Rendering error for one colloquial combination

### Font 
  > NotoSansMyanmar font
 

### OS name and version
  > In all platforms including Android

### Issue

The below_dot u1037 is added behind some names or pronouns to indicate possession, similar to ('s) in english. 
When there is u103A in the sequence, u1037 is before u103A in unicode canonical sequence. 

When it is written in the combination 
ခင် -> ခင့် 
u1001 + u1004 + u103A -> u1001 + u1004 + u1037 + u103A

There is another combined vowels using u103A.

This is the existing combination - ခေါ် , ဂေါ် , ငေါ် , ဒေါ် , ပေါ်, ဝေါ် 
[Consonant] + u1031 + u102B + u103A

This is the inflection with added u1037  - ခေါ့် , ဂေါ့် , ငေါ့် , ဒေါ့် , ပေါ့် , ဝေါ့် 
[Consonant] + u1031 + u102B + u1037 + u103A
Rendering in Noto does not look right for this combination.

### Screenshots
[Rendered for non canonical sequence](https://drive.google.com/a/google.com/file/d/0B0DCvdiX_PIReldvRkgyeklYN29HUkV1OVZUTmFOdDZDU2lR/view?usp=sharing)

[Correct sequence, Wrong rendering](https://drive.google.com/a/google.com/file/d/0B0DCvdiX_PIROS1TY0huc25PdFFVMVRxV0FvUUlaeGdZRENz/view?usp=sharing)

[Correct sequence, Correct rendering. Rendered in Tharlon font](https://drive.google.com/a/google.com/file/d/0B0DCvdiX_PIRVkFQTVBfTDdSX3ZQUmxYZDdIckhVUzRDU2Zz/view?usp=sharing)

Thank you!

**Comment by JackfromMc** [comment]
Greetings to all!!!

The bug is also present in the Noto Serif Myanmar family.
It's quite a serious issue

**Comment by marekjez86** [comment]
@YinMayOo @JackfromMc : thank you for the bug reports on Noto Sans Mynamar and Noto San Serif.

**Comment by marekjez86** [comment]
@waksmonskiMT : same issue is present in Noto Sans Serif (see https://github.com/googlei18n/noto-fonts/issues/945 ). Note that this could be a fontmake issue or our rendering issue, but please check on your OTF/TTF files first.

**Comment by marekjez86** [comment]
the screenshot images
=================
Rendered for non canonical sequence
![tall_a_asat_dot](https://user-images.githubusercontent.com/13322623/28066946-eec15328-65f3-11e7-9148-5698d679d6c0.png)

Correct sequence, Wrong rendering
![- noto-incorrect](https://user-images.githubusercontent.com/13322623/28066955-f551a544-65f3-11e7-92a5-7b8a7f98f815.png)

Correct sequence, Correct rendering. Rendered in Tharlon font
![- tharlon-correct](https://user-images.githubusercontent.com/13322623/28066964-fcb77aa2-65f3-11e7-944f-8793b5c34a9e.png)

**Comment by marekjez86** [comment]
Noto tests for various weights

[my-941-Myanmar-SerifSans-PBlackAndPBlack.pdf](https://github.com/googlei18n/noto-fonts/files/1139079/my-941-Myanmar-SerifSans-PBlackAndPBlack.pdf)
[my-941-Myanmar-SerifSans-PBoldAndPBold.pdf](https://github.com/googlei18n/noto-fonts/files/1139082/my-941-Myanmar-SerifSans-PBoldAndPBold.pdf)
[my-941-Myanmar-SerifSans-PMediumAndPMedium.pdf](https://github.com/googlei18n/noto-fonts/files/1139081/my-941-Myanmar-SerifSans-PMediumAndPMedium.pdf)
[my-941-Myanmar-SerifSans-PRegularAndPRegular.pdf](https://github.com/googlei18n/noto-fonts/files/1139080/my-941-Myanmar-SerifSans-PRegularAndPRegular.pdf)
[my-941-Myanmar-SerifSans-PThinAndPThin.pdf](https://github.com/googlei18n/noto-fonts/files/1139083/my-941-Myanmar-SerifSans-PThinAndPThin.pdf)

**Comment by mgbellarosa** [comment]
@YinMayOo @JackfromMc @marekjez86 
Hello,
This bug has been fixed and will be in the next release of Myanmar.
![screen shot 2017-08-10 at 3 49 45 pm](https://user-images.githubusercontent.com/29443471/29195510-b926a04e-7de3-11e7-8fd9-a58a5e08925f.png)

Best,
Glenda

**Comment by marekjez86** [comment]
Fixed in https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/serif fonts.

@mgbellarosa : thank you
