### ISSUE TITLE
Noto Sans Myanmar : Critical bug sequence U+1014/U+1037

### ISSUE THREAD

**Issue by JackfromMc** [googlei18n/noto-fonts#945]
Greetings to all!!!

All fonts in the Noto Sans Myanmar family including UI from https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/otf/sans and https://github.com/googlei18n/noto-fonts/tree/master/hinted
Date: 2017/7/8

The sequence U+1014/U+1037 is faulty and is never performed this way in this script.

Observed behaviour:
![smartselectimage_2017-07-09-15-11-19](https://user-images.githubusercontent.com/23061375/27994199-f07b0128-64b8-11e7-8daa-79dad7787cb6.png)
Font: NotoSansMyanmarUI-regular.ttf newer version

Expected behavior:
![smartselectimage_2017-07-09-15-10-29](https://user-images.githubusercontent.com/23061375/27994213-338b1430-64b9-11e7-8543-1ed56795fa83.png)
Font: NotoSansMyanmar-regular.ttf older version (Android Nougat)

Please be aware that this is a serious issue, don't publish the new fonts before correcting this bug.

**Comment by marekjez86** [comment]
@waksmonskiMT : same issue is present in Noto Sans Serif (see https://github.com/googlei18n/noto-fonts/issues/945 ). Note that this could be a fontmake issue or our rendering issue, but please check on your OTF/TTF files first.

**Comment by marekjez86** [comment]
@YinMayOo @JackfromMc : thank you for the bug reports on Noto Sans Mynamar and Noto San Serif.

**Comment by marekjez86** [comment]
Noto tests for various weights

[my-945-Myanmar-SerifSans-PBlackAndPBlack.pdf](https://github.com/googlei18n/noto-fonts/files/1139092/my-945-Myanmar-SerifSans-PBlackAndPBlack.pdf)
[my-945-Myanmar-SerifSans-PBoldAndPBold.pdf](https://github.com/googlei18n/noto-fonts/files/1139091/my-945-Myanmar-SerifSans-PBoldAndPBold.pdf)
[my-945-Myanmar-SerifSans-PMediumAndPMedium.pdf](https://github.com/googlei18n/noto-fonts/files/1139094/my-945-Myanmar-SerifSans-PMediumAndPMedium.pdf)
[my-945-Myanmar-SerifSans-PRegularAndPRegular.pdf](https://github.com/googlei18n/noto-fonts/files/1139093/my-945-Myanmar-SerifSans-PRegularAndPRegular.pdf)
[my-945-Myanmar-SerifSans-PThinAndPThin.pdf](https://github.com/googlei18n/noto-fonts/files/1139095/my-945-Myanmar-SerifSans-PThinAndPThin.pdf)

**Comment by r12a** [comment]
@marekjez86 i'm not sure how to read the tests. The pink background seems to be saying that the expected result (ie. with the dot to the right of the line) is wrong, and the result on green (with the dot below the NA and short vertical line is correct).  Is that right? because it seems to be the opposite of what is needed.  How does one read those test results?

**Comment by marekjez86** [comment]
Here I compared the new Serif (Pink) with new Sans (Green). I think placement of dot below is wrong in both cases. In addition, Sans U+1014 has the wrong shape

**Comment by JackfromMc** [comment]
@marekjez86 @r12a The pink one (Noto Serif) is the correct (expected) rendering, there's nothing wrong with it.
And I don't see any problems with the different shapes of the glyph (U+1014), only maybe the one without the tail from Noto Sans looks odd to me and is not to my taste but is not _wrong_.

**Comment by mgbellarosa** [comment]
@JackfromMc @marekjez86 
Hello, this has been fixed and will be in the next release of Myanmar Sans.
![screen shot 2017-08-10 at 3 39 29 pm](https://user-images.githubusercontent.com/29443471/29195247-4d0e81ca-7de2-11e7-989e-3e3202d7c019.png)

Best,
Glenda

**Comment by marekjez86** [comment]
@mgbellarosa : thank you

**Comment by marekjez86** [comment]
fixed in https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/sans
