### ISSUE TITLE
Latin Noto fonts are missing non-breaking hyphen (U+2011)

### ISSUE THREAD

**Issue by paperboyo** [googlei18n/noto-fonts#946]
Hello,

All NotoSans[weight] and NotoSerif[weight] fonts, latest versions (as of today) on all platforms are missing non-breaking hyphen glyphs.

As Noto is often used as a fallback font, missing U+2011 creates potential problems, like e.g. https://github.com/guardian/frontend/issues/17506.

I thought as hard as I can, but couldn’t come up with potential reasons why not to include them, even more so – because they are included in e.g. NotoNaskhArabic-Regular.ttf. No tofu!

I may be wrong, obviously...

Regards
m.

**Comment by dougfelt** [comment]
Yes, sorry, this should have been in LGC as well.  The beta version of LGC has non-breaking hyphen.  This will be fixed once the new LGC becomes final.

**Comment by paperboyo** [comment]
Great! Thank you, @dougfelt! Closing as there is no point in keeping it open. Although browsers should be cleverer here...

**Comment by paperboyo** [comment]
Sorry, me again, @dougfelt... I couldn't find this mentioned beta version [anywhere](https://fonts.google.com/earlyaccess), but I just hope it also contains a, currently missing too, U+2010 hyphen for reasons similar to above (please also see https://github.com/behdad/harfbuzz/issues/517#issuecomment-319725784).

**Comment by dougfelt** [comment]
Sorry, I should have mentioned that. Alpha fonts are in noto-fonts-alpha on
GitHub. They are all in various stages of usability, the main LGC font is
relatively good. Look under from-pipeline in the ttf folder.

**Comment by marekjez86** [comment]
@paperboyo : please look for the fonts at subdirectories in https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted

**Comment by paperboyo** [comment]
Thank you, @marekjez86! Indeed the alpha version of at least Noto Serif contains U+2010 too, so all is well (as soon as released fonts trickle down all the Android update cycles 😉).

I still think apps should be a bit wiser about all the hyphens, as [HurfBuzz won't take care](https://github.com/behdad/harfbuzz/issues/517#issuecomment-319942583) of missing U+2010>U+002D fallback within one font.

Now I have to learn how to dump all hyphen glyphs in popular fonts and compare designs of U+002D vs. U+2010 (where U+2010 is actually present) to see if it makes sense to bother browser makers to include that fallback. Because that still seems easier than making all the fonts in the world contain both U+2010 and U+2011 😉.
