### ISSUE TITLE
Any documentation of which codepoint ranges are covered by which fonts?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#95]
```
Is there any way to find out, for a specific unicode codepoint, which Noto 
fonts can render that codepoint?
```

Original issue reported on code.google.com by `joelars...@gmail.com` on 25 Jul 2014 at 4:42

**Comment by fontguy** [comment]
cc @dougfelt 

Doug, could we add a feature to the tools to generate this table?

**Comment by marekjez86** [comment]
quoting fontguy "Doug, could we add a feature to the tools to generate this table?"

**Comment by shyndman** [comment]
Looks like this might do it:
https://github.com/googlei18n/nototools/blob/master/nototools/coverage.py

**Comment by dougfelt** [comment]
Do we want to generate a table, though?  It would be rather big.  Maybe just generate some data and a tool that you could provide one or more codepoints to and it would list the font families that support it?

**Comment by shyndman** [comment]
If you're willing to hook it up, there's a function in there that can generate ranges. It seems to be a dependency of other tools in the package.

**Comment by dougfelt** [comment]
Like I said, a table of all unicode characters mapping to all fonts would be large.  Are you ok with a tool or do you really want a table?

**Comment by moooas838** [comment]
Moooas838@hotmail.com

**Comment by dougfelt** [comment]
The tool takes a list of codepoints and/or codepoint ranges (in hex) and reports the font families that support these in their cmaps (all fonts in a noto family cover the same codepoints).

**Comment by dougfelt** [comment]
committed the change to googlei18n/nototools: cb2b7876364f3dc13942e42de7de23215fde6fda

Please open an issue in nototools if you want to change/add/remove features from this tool.
