### ISSUE TITLE
Buhid glyphs abnormally large

### ISSUE THREAD

**Issue by lemzwerg** [googlei18n/noto-fonts#951]
[noto-fonts-alpha a5ad06038e200c8f41d8e0a686f54cb1c69cb395]

The font `from-pipeline/unhinted/ttf/sans/NotoSansBuhid-Regular.ttf` contains abnormally large glyphs in comparison to other scripts covered by Noto.

Is there a reason for it?

![buhid](https://user-images.githubusercontent.com/1630245/28755275-58e9978e-7557-11e7-953c-d33b1b3cdf50.png)

**Comment by lemzwerg** [comment]
Please ignore.  This is a problem of xelatex.

**Comment by lemzwerg** [comment]
I have to take that back.  It *is* a problem with too large glyphs.

The font has an em-size of 1000, but the global ascent and descent values in the `hhea` table are 2189 and -600, respectively.

Looks like an em-size conversion error...

**Comment by marekjez86** [comment]
It was a wrong conversion. Deleting the fonts until we get a proper one.

**Comment by marekjez86** [comment]
please check the font again; fixed the "large font issue" and recompiled the font

**Comment by lemzwerg** [comment]
Size is OK now, thanks.
