### ISSUE TITLE
Coptic glyphs abnormally large

### ISSUE THREAD

**Issue by lemzwerg** [googlei18n/noto-fonts#953]
[noto-fonts-alpha a5ad06038e200c8f41d8e0a686f54cb1c69cb395]

The font `from-pipeline/unhinted/ttf/sans/NotoSansCoptic-Regular.ttf` contains abnormally large glyphs in comparison to other scripts covered by Noto.

The font has an em-size of 1000, but the global ascent and descent values in the `hhea` table are 2189 and -600, respectively.

Looks like an em-size conversion error...

![coptic](https://user-images.githubusercontent.com/1630245/28786200-d79e3582-7618-11e7-9c50-83310e8fa14d.png)

**Comment by marekjez86** [comment]
It was a wrong conversion. Deleting the fonts until we get a proper one.

**Comment by marekjez86** [comment]
please check the font again; fixed the "large font issue" and recompiled the font

**Comment by lemzwerg** [comment]
OK now, thanks.
