### ISSUE TITLE
Saurashtra font in alpha has abnormally large glyphs

### ISSUE THREAD

**Issue by lemzwerg** [googlei18n/noto-fonts#955]
[noto-fonts-alpha fd79fd7e79377a8f805759f1802e64fd44f2147c]

`from-pipeline/unhinted/ttf/sans/NotoSansSaurashtra-Regular.ttf` seems to be another failed conversion...

![saurashtra](https://user-images.githubusercontent.com/1630245/28816978-10bdb0fc-76a7-11e7-8d4e-39693b989844.png)

**Comment by marekjez86** [comment]
deleted the fonts produced by this incorrect do-it-yourself creation of the sources from the old TTF files.

**Comment by marekjez86** [comment]
please check the font again; fixed the "large font issue" and recompiled the font

**Comment by lemzwerg** [comment]
OK now, thanks.
