### ISSUE TITLE
Sundanese font in alpha has abnormally large glyphs

### ISSUE THREAD

**Issue by lemzwerg** [googlei18n/noto-fonts#956]
[noto-fonts-alpha 295aa8b2eeed5bf4acf99e3426d934403d316ecd]

`from-pipeline/unhinted/ttf/sans/NotoSansSundanese-Regular.ttf` seems to be another failed conversion...

![sundanese](https://user-images.githubusercontent.com/1630245/28872519-db9346f6-7789-11e7-8d16-6b71139560e6.png)

**Comment by marekjez86** [comment]
I decided to try to correct it, as opposed to deleting it. Please check newly released from-pipeline/unhinted/ttf/sans/NotoSansSundanese-Regular.ttf ... If this works I may go back and redo the others that I deleted. Note that sooner or later we might get the officially re-done fonts from MTI. These were just my attempts.

**Comment by lemzwerg** [comment]
Looks OK now, thanks!  And yes, please redo the others :-)
