### ISSUE TITLE
Tai Viet font in alpha has abnormally large glyphs

### ISSUE THREAD

**Issue by lemzwerg** [googlei18n/noto-fonts#957]
[noto-fonts-alpha 295aa8b2eeed5bf4acf99e3426d934403d316ecd]

`from-pipeline/unhinted/ttf/sans/NotoSansTaiViet-Regular.ttf` seems to be another failed conversion...

![taiviet](https://user-images.githubusercontent.com/1630245/28878536-dc8b4fde-779f-11e7-9c93-4124cfe5f047.png)

**Comment by marekjez86** [comment]
should be fixed; please check

**Comment by lemzwerg** [comment]
No change – it seems you have forgotten to actually commit the new version.

**Comment by marekjez86** [comment]
please try again; my bad

**Comment by lemzwerg** [comment]
OK now, thanks.
