### ISSUE TITLE
Noto Serif and Sans Myanmar : Critical bug for kinzi (U+1004/U+103A/U+1039)

### ISSUE THREAD

**Issue by JackfromMc** [googlei18n/noto-fonts#968]
Greetings to all!

In all the newest fonts of the serif and the sans family the kinzi is not performed anymore.

Observed behaviour:
![20170920_082102](https://user-images.githubusercontent.com/23061375/30623303-ca0d50f6-9ddc-11e7-8782-9b3a1fabdc33.png)
![20170920_081731](https://user-images.githubusercontent.com/23061375/30623341-f6aa073a-9ddc-11e7-92ee-4bd2c3a4845b.png)
Fonts: Noto Serif Myanmar Regular.ttf and Sans Regular.ttf newest versions (added September 19th 2017) Text: မင်္ဂလာပါ = "blessings" (common form of greeting)

Expected behaviour:
![20170920_082030](https://user-images.githubusercontent.com/23061375/30623424-8c8a34d2-9ddd-11e7-86b8-c60b0ce7fa4b.png)
![20170920_082005](https://user-images.githubusercontent.com/23061375/30623432-9ac39de0-9ddd-11e7-86a8-e95f98471fcf.png)
Fonts: Noto Serif Myanmar Light and Sans Regular older versions

The same goes for the "ra kinzi" U+101B/U+103A/U+1039:
![20170920_081844](https://user-images.githubusercontent.com/23061375/30623527-0f67df3a-9dde-11e7-959a-5eb8bc57b6cd.png)
![20170920_081933](https://user-images.githubusercontent.com/23061375/30623533-15b3246c-9dde-11e7-96f9-8d8d7e4786d6.png)
![20170920_081822](https://user-images.githubusercontent.com/23061375/30623537-1c6c446e-9dde-11e7-9126-4dc8eaf0e6fb.png)
![20170920_081918](https://user-images.githubusercontent.com/23061375/30623540-237384de-9dde-11e7-870c-1591bb125caa.png)
Fonts: as above   ;   Text: နိရ်္ဝါန "Nirvāna" in Sanskrit

This is a VERY serious issue. @mgbellarosa

**Comment by marekjez86** [comment]
@mgbellarosa: could you check in your build of fonts before you try to fix it? It might be a fontmake/pipeline problem.

**Comment by kyawthusoe3142** [comment]
Which noto myanmar fonts have this problem?
I tested it on "noto myanmar" and "noto myanmar UI" and it is fine.

**Comment by JackfromMc** [comment]
@kyawthusoe3142  The newest versions of the fonts that can be found there : https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/sans
https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/serif
These fonts are not published yet.

**Comment by kyawthusoe3142** [comment]
I confirm these issues with my noto-fonts(20170920-2).
Before that, the first issue is ok.
I can't say anything for the second issue because I don't know how to type it. :)

**Comment by mgbellarosa** [comment]
Hello,
The Kinzi and Ra Kinzi have been fixed and will be released in the next version.
Thank you.

-glenda

@JackfromMc @marekjez86 @kyawthusoe3142

**Comment by JackfromMc** [comment]
Thanks a lot @mgbellarosa 
@kyawthusoe3142  you can type the Ra kinzi the same way you type the kinzi but with ရ instead of င : ရ + ် + ္

**Comment by kyawthusoe3142** [comment]
Thank you. Release soon.

**Comment by kyawthusoe3142** [comment]
@JackfromMc Is this solved on your observation?

**Comment by kyawthusoe3142** [comment]
My distribution receives noto by the url https://www.google.com/get/noto/ .
It seem that the vendor have only updated the unhinted ttf's, not the hinted ones that they package.
When I complained, they told me to notify the upstream.
Update the hinted ones, please.

**Comment by kyawthusoe3142** [comment]
https://bugs.archlinux.org/task/56053
Did this kinzi issue fix? If so, which release fixed it? Please point me to that release.

**Comment by kyawthusoe45** [comment]
Please, release the hinted ttf.
Refer to: https://bugs.archlinux.org/task/56053
Why does it take you too long?

**Comment by jungshik** [comment]
@marekjez86 @davelab6 :  update tar balls at google.com/get/noto . See also #1515 .

**Comment by jungshik** [comment]
@kyawthusoe45  : FreeType auto hinting should work reasonably well. Hinted versions will be auto-hinted by Freetype autohinter anyway. So, there's no real benefit of pre-hinted versions unless you're on Windows, which is not the case.
