### ISSUE TITLE
Noto Kannada Sans issue with Ra (+nukta), ZWJ, consonant conjugate and halant

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#973]
### Font 
  > 'NotoSansKannada-Regular.ttf'.
  > 

### Font Version
  > 1.03uh

### OS name and version
  > Mac OS High Sierra GM

### Application name and version
  > Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Issue
ರ‍್ನ್ (\u0cb0\u200d\u0ccd\u0ca8\u0ccd )
ರ‍್ನ್ಕ್  (\u0cb0\u200d\u0ccd\u0ca8\u0ccd\u0c95\u0ccd )
ರ಼‍್ನ್ (\u0cb0\u0cbc\u200d\u0ccd\u0ca8\u0ccd)
ರ಼‍್ನ್ಕ್ (\u0cb0\u0cbc\u200d\u0ccd\u0ca8\u0ccd\u0c95\u0ccd)

Output in Chrome
![screen shot 2017-10-04 at 11 10 55 pm](https://user-images.githubusercontent.com/14062593/31210657-55f999da-a959-11e7-9aee-c6023e85a4bf.png)

Halant at the end is not joined with the base "ರ".

  1. Test "ರ‍್ನ್	ರ‍್ನ್ಕ್	ರ಼‍್ನ್	ರ಼‍್ನ್ಕ್" with Noto Sans Kannada in Chrome
  2. Halant(u0ccd) at the disjoined with the base ರ (u0cb0)
  3. Halant joined with the base ರ
  4. This could be due to the presence of the zero-width-joiner after the base ರ (u0cb0), which is required with ರ (u0cb0) to obtain the consonant conjugate

**Comment by MayuraVerma** [comment]
@JelleBosmaMT Please review this.

**Comment by JelleBosmaMT** [comment]
Thank you for pointing this out. I added a fix to my source file, so that U+200D (ZWJ) doesn't leave a displaced virama in the new version of the fonts. 
At the time Noto Sans Kannada was designed Mac OS wasn't supporting Kannada OpenType, so the rendering was tested with Windows. 
Windows re-orders the vowel signs that combine with the base consonants right after the base, before the ZWJ. Therefore there was no problem with life conjuncts with ZWJ, and evidently I didn't test the dead conjunct case.
I now discovered that Mac OS re-orders the vowel signs after the ZWJ, and the vowels were displaced too. So two fixes in one go ;-)

**Comment by MayuraVerma** [comment]
@JelleBosmaMT 
Great. I thought this was issue with Apple Coretext for vowel displacement, because it was working fine in chrome.

Please check this blog http://kannadafont.blogspot.com/2017/10/case-4-b-ra-with-consonant-conjugate.html with the new version.

Is it possible I can get a copy of the new version?

**Comment by MayuraVerma** [comment]
Hello @JelleBosmaMT

Could try the new version, please.

**Comment by marekjez86** [comment]
@MayuraVerma  ( cc @JelleBosmaMT ) : we, Google, are officially releasing the fonts once we get the source files. Hence, I would prefer not to do a one-of by Jelle. However, if he sends me sources I have no problem building a single weight TTF or OTF file and send you for testing.

**Comment by MayuraVerma** [comment]
Thank you.

**Comment by marekjez86** [comment]
@MayuraVerma : I have attached here a file courtesy of JelleBosmaMT which you can use for testing. Please post any feedback here. Thank you.

[NotoSansKannada-Regular_OTL-not-for-further-distribution.otf.zip](https://github.com/googlei18n/noto-fonts/files/1384244/NotoSansKannada-Regular_OTL-not-for-further-distribution.otf.zip)

**Comment by MayuraVerma** [comment]
This version is displaying correctly in Chrome.
Although libreoffice uses harfbuzz, we issue with nukta.
Please check.
![screen shot 2017-10-14 at 12 02 12 am](https://user-images.githubusercontent.com/14062593/31572783-50d59a50-b073-11e7-9e8a-9f4e94eff886.png)

**Comment by JelleBosmaMT** [comment]
If there is a dotted cycle, it is the software that decides that there is an invalid combination of Unicode characters. This is not a font issue.

**Comment by kalapi** [comment]
I fixed this in Noto Serif Kannada as well:

![screen shot 2017-11-09 at 10 58 55 pm](https://user-images.githubusercontent.com/15804460/32619869-eff60190-c5a1-11e7-9424-f01aeefa68b7.png)

**Comment by MayuraVerma** [comment]
FYI:
I was using LibreOffice 5.2.2 which was using Apple CoreText.
After upgrading to LibreOffice 5.4.2 which uses harfbuzz, text is rendering correctly.

Screenshot from LibreOffice
![screen shot 2017-11-19 at 10 02 00 pm](https://user-images.githubusercontent.com/14062593/33001729-536ebb4c-cd75-11e7-9a51-602619f090ff.png)

**Comment by MayuraVerma** [comment]
@kalapi 
ರ‍್ (\u0cb0\u200d\u0ccd)
![image](https://user-images.githubusercontent.com/14062593/45529757-83e6d080-b7ac-11e8-9699-af48576a11cf.png)
ರ‍್ಯ್ (\u0cb0\u200d\u0ccd\u0caf\u0ccd)
![image](https://user-images.githubusercontent.com/14062593/45529801-b5f83280-b7ac-11e8-8ae6-36f5bf059742.png)

I check these combinations with the latest build 2.001. It is still collapsed.
Please review.

**Comment by kalapi** [comment]
Hi @MayuraVerma 

Can you tell me what environment you're testing on? It works for me on all the latest browsers on OSX 10.11.6 (El Capitan).

Just as a precaution, if you've installed a previous version, there might be a caching issue locally. 

Can you test the combinations on [this testing page](http://www.cyreal.org/Font-Testing-Page/)? Simple drag and drop the TTF file to the grey area at the top that says 'Drag fonts here!' and edit the text in the lines below. It should just work. 

Let me know what you find.

**Comment by MayuraVerma** [comment]
Hello Kalapi,

I have tested in pages in Mac OS mojave, High Sierra.
also, Window 10 - Word 2010 combination
Windows 7 and Word 2016 combination

All same result.

![image](https://user-images.githubusercontent.com/14062593/45554343-ca175080-b7fb-11e8-9117-fc0f9ec18a76.png)

**Comment by MayuraVerma** [comment]
Also, https://github.com/googlei18n/noto-fonts/issues/1076 is still unresolved. Please take a look at it.

**Comment by chandrab699** [comment]
two more issues

nukta ->https://github.com/googlei18n/noto-fonts/issues/1293

below form consonants and vowels-> https://github.com/googlei18n/noto-fonts/issues/1294

**Comment by chandrab699** [comment]
Subs/Subs Sp.
![image](https://user-images.githubusercontent.com/30884806/45569455-36f31080-b825-11e8-8d45-d51c60f5d19a.png)
Tall Subs Sp.
![image](https://user-images.githubusercontent.com/30884806/45569488-47a38680-b825-11e8-9f2f-5d647190cc6e.png)
comma-> this is not desirable. Comma must outside the sub. or composite letter
![image](https://user-images.githubusercontent.com/30884806/45569553-73bf0780-b825-11e8-809f-f14d2d778ff3.png)
same thing here
![image](https://user-images.githubusercontent.com/30884806/45569618-a406a600-b825-11e8-9170-01a2bf2da10b.png)

ru overlapping
![image](https://user-images.githubusercontent.com/30884806/45569719-fba51180-b825-11e8-8cf7-51bc1f00d5ef.png)

comma overlapping
![image](https://user-images.githubusercontent.com/30884806/45569771-2b541980-b826-11e8-87b3-c0ded81d00db.png)

visually ಟ looks like not of the same family as the rest of the character. Perhaps stroke width can be reduced and/or stroke length be reduced to match the rest of the consonants
![image](https://user-images.githubusercontent.com/30884806/45569836-68b8a700-b826-11e8-8332-df145e2594f0.png)

**Comment by chandrab699** [comment]
ರ‍್ ರ‍್ಯ್ ರ‍್ಯ್ನ್
Chrome vs Internet explorer in Windows 7.
Chrome is fine, expect double subscript overlaps
font fails in IE.
same result is found in Safari in Mac. 

If you are testing in Mac OS, must use Safari to test against Core-Text. Chrome in mac OS will use harfbuzz shaping engine.
![image](https://user-images.githubusercontent.com/30884806/45570179-5ee37380-b827-11e8-844c-dcb71be84506.png)

**Comment by MayuraVerma** [comment]
@kalapi @marekjez86 please review this
