### ISSUE TITLE
Noto Sans Arabic and Noto Naskh need Kashmiri GSUB lookups

### ISSUE THREAD

**Issue by roozbehp** [googlei18n/noto-fonts#975]
Noto Sans Arabic (alpha?) and Noto Naskh need Kashmiri GSUB lookups for digits. The digit forms used in Kashmiri are identical to the Urdu forms, so the GSUB information can simply be copied from Urdu.

This is very important for users in India, since Kashmiri is one of the scheduled/official languages of India.

**Comment by marekjez86** [comment]
Note that Noto Naskh are the older SOW12 fonts that need to be modified.

**Comment by marekjez86** [comment]
@waksmonskiMT : you own SOW15 part
@marekjez86: owns SOW12 part

**Comment by marekjez86** [comment]
The Noto Naskh fonts with GSUB changes are at
https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoNaskhArabic-Bold.ttf
https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoNaskhArabic-Regular.ttf
https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoNaskhArabicUI-Bold.ttf
https://github.com/googlei18n/noto-fonts/blob/master/unhinted/NotoNaskhArabicUI-Regular.ttf

**Comment by jungshik** [comment]
http://jungshik.github.io/noto/arabic/digits.html (I grabbed the latest versions of NotoNaskhArabic(UI) and use them as web fonts in the page) does not seem to work as expected in Chrome canary (65.x with Harbuzz 1.6.3) and Firefox 57.

**Comment by jungshik** [comment]
BTW, hinted fonts also need to be updated. Chrome/Chromium OS still use hinted fonts.

**Comment by jungshik** [comment]
I also used the Harbuzz ToT and hb-view. The result is the same. Urdu is correct, but Kashimir is not. 

Kashimir  (with --language=ks passed to hb-view)
![ext_arab_digits ks](https://user-images.githubusercontent.com/8578343/34130714-bd0faa04-e3fd-11e7-9d6f-89ad378c79ce.png)

Urdu: (with --language=ur passed to hb-view)

![ext_arab_digits ur](https://user-images.githubusercontent.com/8578343/34130747-d75a8186-e3fd-11e7-8c5c-2ce297244fb8.png)

The text used is 
```
۴ ۶ ۷
```

**Comment by jungshik** [comment]
I dumped GSUB tables of NotoNaskhArabic-Regular.ttf with and without Marek's change and I don't see any issue with his change. As far as I can tell, his change should work. 

And, Harfbuzz does map 'ks' (ISO 639 / BCP 47 lang tag)  to 'KSH ' (ot language tag).

**Comment by jungshik** [comment]
The only potential issue is that langsys records are not sorted alphabetically. 

"FAR ", "SND ", "URD " and "KSH ". 

Perhaps, they should be.  

"FAR ", "KSH ", "SND ", "URD ".

**Comment by jungshik** [comment]
Yes, that's it. LangSys records have to be sorted.

**Comment by marekjez86** [comment]
Thank you Jungshik!
