### ISSUE TITLE
glyph of ಱಾ ಱ್ ೞಾ ೞ್ in Noto sans Kannada

### ISSUE THREAD

**Issue by sridatta1** [googlei18n/noto-fonts#977]
### Font 
Noto Sans Kannada

### Where the font came from, and when
 
https://www.google.com/get/noto/#sans-knda
### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

ಱಾ ಱ್ ೞಾ ೞ್

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

![nga](https://user-images.githubusercontent.com/23263723/31546548-651739a6-b041-11e7-9dff-980ed3808c8a.JPG)
For consonants which don't have headstroke and round head in top-right corner (ಙಞಱೞ and optionally ಣ) take special forms for signs ಾ ೆ ೇ ೈ ೊ ೋ ್ since these vowel signs replace the headstroke.
shape of ಾ   ್ should be as in ಙ್ ಙಾ

![llaa](https://user-images.githubusercontent.com/23263723/31546787-7d20045a-b042-11e7-8d34-c3346514bb2b.JPG)

![llla](https://user-images.githubusercontent.com/23263723/31546788-7d5fa2a4-b042-11e7-8ab5-4f19098dfbdf.JPG)
these appear correctly in Noto Serif Kannada
![serif](https://user-images.githubusercontent.com/23263723/31546821-97d62d9c-b042-11e7-8a6b-cd413b4cae0d.JPG)

![kannada](https://user-images.githubusercontent.com/23263723/31546936-0cfe438e-b043-11e7-9231-f42d44d459b6.JPG)

**Comment by sridatta1** [comment]
@JelleBosmaMT notify if you haven't seen. Thank you.

**Comment by JelleBosmaMT** [comment]
@sridatta1  Have seen it now and know what to do. Thanks.

**Comment by sridatta1** [comment]
Here is attestation for ಱ್ and ೞ್
![image](https://user-images.githubusercontent.com/23263723/35054488-a87fbe48-fbd2-11e7-833c-730ed02752e8.png)

**Comment by sridatta1** [comment]
This issue ( and many other issues) was fixed in the phase 3 fonts, thus closing this issue.
https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only
