### ISSUE TITLE
Kannada Anuswara with reph (arkavattu)

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#980]
## Defect Report
Kannada anuswara (U+0C82) when present after ra+halant (U+0CB0, U+0CCD) and any Kannada consonant. The arkavattu (reph form) formed by U+0CB0, U+0CCD should precede the Kannada anuswara (U+0C82). With "Google Noto Sans Kannada font" open type font, anuswara is position before arkavattu (reph form) in Safari.

### Title 
  > Kannada Anuswara with reph (arkavattu)

### Font 
  > 'NotoSansKannada-Regular.ttf'
  > 'NotoSerifKannada-Regular.ttf'

### Where the font came from, and when
  > https://www.google.com/get/noto/#sans-knda 

### Font Version
  >Noto Sans Kannada 1.03uh
  >Noto Serif Kannada 1.01uh
 
### OS name and version
  > Mac OS high Sierra

### Application name and version
  > Safari on Mac OS High Sierra

### Screenshot
 Safari Screenshot
<img width="895" alt="screen shot 2017-10-16 at 1 39 57 am" src="https://user-images.githubusercontent.com/14062593/31598464-716ad3b0-b213-11e7-8c61-3d6149c8b06d.png">
Chrome Screenshot
<img width="922" alt="screen shot 2017-10-16 at 1 40 22 am" src="https://user-images.githubusercontent.com/14062593/31598465-717d2330-b213-11e7-9b56-05d48a16c0e2.png">
 Numbers Screenshot
<img width="574" alt="screen shot 2017-10-16 at 1 47 07 am" src="https://user-images.githubusercontent.com/14062593/31598584-10a16084-b214-11e7-9d5d-a561a2b74a67.png">

**Comment by marekjez86** [comment]
@MayuraVerma : could you also provide here the text (in addition to the screenshots) so I can create the test files?

**Comment by MayuraVerma** [comment]
I have also created a blog. You can open this in Chrome and Safari on Mac to visualize the difference.
http://kannadafont.blogspot.com/2017/10/case-11-kannada-anuswara-with-arkavattu.html

Raw text:
ಅರ್ಧಾಂಗಿ
ಜ್ಯೋತಿರ್ಲಿಂಗ
ಮಾರ್ನಿಂಗ್ 

Thanks.

**Comment by MayuraVerma** [comment]
@JelleBosmaMT @kalapi Please review this.

**Comment by JelleBosmaMT** [comment]
In principle it is the software that re-orders the reph forms. Windows does put the anusvara after the reph-form and so does HarfBuzz (Chrome).  I installed Mac OS version High Sierra last week, and it seem to get it right... at least as long as there is no vowel in the syllable. Following image with and without vowel:

![knda order](https://user-images.githubusercontent.com/12729011/31906706-11415250-b832-11e7-8985-f15270eb81ef.png)

This is really an Apple software bug, not a font bug. At the time Noto Sans Kannada was designed Apple did not support Indic OpenType at all. So there was no way I could have known there being a need to add a work around.

**Comment by MayuraVerma** [comment]
Thanks but how is it doing fine with Kannada Sangam MN and Kannada MN fonts. Recently they are also updated. My understanding is they are also using Opentype feature. Just curious.

**Comment by JelleBosmaMT** [comment]
In the MN fonts the OpenType have features that re-order the reph-form.  But the fonts also have the old AAT render tables. I don't know what is used.

**Comment by MayuraVerma** [comment]
Regarding MN fonts, it stores both AAT and OT features. 
Mac OS picks up AAT for all the Apple apps. 
3rd party apps, picks up OT features.

This is a Apple CoreText Issue. 
It's reporting to Apple, hopefully fix will come soon.
This is not a font issue, so I am closing this issue.
