### ISSUE TITLE
Add Polish letterforms

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#981]
Could Noto support the Polish Kreska shape? Noto already has localized letterforms for Navajo and Marshallese, but not yet for Polish. Should be very little work:
https://glyphsapp.com/tutorials/localize-your-font-polish-kreska
http://www.twardoch.com/download/polishhowto/kreska.html

**Comment by twardoch** [comment]
Luckily, the acute forms in Noto (both Sans and Serif) are designed in a way that is sufficiently "universal" so they don't require localization. More upright forms would be needed if the acute were flatter, but the way it is, it's good.

**Comment by brawer** [comment]
Great, thanks. Roboto is OK, too?

**Comment by twardoch** [comment]
Yes. Most major fonts made in recent years are much better in terms of diacritics design. It seems that type designers are much more aware of the various cultural preferences and are doing a very good job balancing them.
