### ISSUE TITLE
Armenian fonts set ignoreMarks lookup flag without having a GDEF table

### ISSUE THREAD

**Issue by khaledhosny** [googlei18n/noto-fonts#984]
It seems that the `kern` lookup in the Armenian fonts sets the `ignoreMarks` flag, but the fonts lack `GDEF` table and do not even seem to have any combining marks. The flag seems superfluous, but it causes OTS to reject the fonts:
```
$ ots-sanitize unhinted/NotoSansArmenian-Regular.ttf 
ERROR: Layout: Lookup flags require GDEF table, but none was found: 8
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
```

This is practically harmless since Chrome and release Firefox don't pass layout tables through OTS, but it would be nice to just remove the flag. (This is a bit annoying for me as it breaks my local OTS test suite).

**Comment by anthrotype** [comment]
It is probably because in ufo2ft (used to compile Noto fonts) in the kern feature writer we always set that flag, regardless of the font having a GDEF or not. Could you open an issue over there as well? Thanks

**Comment by khaledhosny** [comment]
Fixing OTS instead, see the discussion in https://github.com/googlei18n/ufo2ft/issues/184.
