### ISSUE TITLE
Tamil Font 'Noto Sans Tamil' is not displaying properlly on Mac laptop MacBook

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlei18n/noto-fonts#99]
```
Hi,

Tamil Font 'Noto Sans Tamil' is not displaying properlly on Mac laptop MacBook.

Here we are attaching the screen shot. The correct sentence are:

First Link:   விஜய்யோட பள்ளிச் 
சான்றில் மதப் பெயரே கிடையாது! 
- அடித்துச் சொல்லும் எஸ்ஏசி

Second Link:  24 ஆண்டுகளுக்குப் பிறகு 
ஒரே மேடையில் லாலு, நிதிஷ்!

Thanks
Mukesh Kumar
```

Original issue reported on code.google.com by `mukes...@oneindia.co.in` on 28 Jul 2014 at 12:12

Attachments:
* [tamil-screen-shot.png](https://storage.googleapis.com/google-code-attachments/noto/issue-99/comment-0/tamil-screen-shot.png)

**Comment by JelleBosmaMT** [comment]
Is it the fault of the font if it is rendered by software that does not apply the OpenType features Please close this issue.

**Comment by jungshik** [comment]
I don't know what version of Chrome is used on what version of Mac OS X. 

As @JelleBosmaMT wrote, this is NOT a font issue. Moreover, Chrome 45.x does not have any issue at all with reordering on Mac OS X (10.9.x). 

![screen shot 2015-10-06 at 11 14 35 pm](https://cloud.githubusercontent.com/assets/8578343/10330301/3d5036f4-6c80-11e5-8299-14d972d7a390.png)
