### ISSUE TITLE
?? or harfbuzz issue or font issue with Telugu 0C37+0C4D+0C1F+0C4D+0C30  ష్ట్ర 

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/noto-fonts#990]
The font
[NotoSansTelugu-Regular.ttf.zip](https://github.com/googlei18n/noto-fonts/files/1419452/NotoSansTelugu-Regular.ttf.zip)

This is the font that is shipping on Android phones.

In this font 0C37+0C4D+0C1F+0C4D+0C30  ష్ట్ర is rendered as (see the green line)
![telugu-c37 c4d c1f c4d c30](https://user-images.githubusercontent.com/13322623/32068025-ed954c26-ba39-11e7-9a9d-aca4d00f5c6a.jpeg)

the correct character should be rendered as
![telugu-c37 c4d c1f c4d c30](https://user-images.githubusercontent.com/13322623/32067955-b80344b4-ba39-11e7-8219-76233c818444.png)

**Comment by marekjez86** [comment]
Note that this might be fixed by the harfbuzz patch that @roozbehp mentioned in other context. I don't think I have it on my Mac.

**Comment by behdad** [comment]
This looks like something the designer chose to me.

**Comment by behdad** [comment]
Not sure which harfbuzz patch you are referring to.

**Comment by marekjez86** [comment]
Correct: designer chose it. I have a better way of checking it than filing bugs. Closing it.
