### ISSUE TITLE
Add Choktaw Upsilon

### ISSUE THREAD

**Issue by brawer** [googlei18n/noto-fonts#993]
To support the Choktaw language, please add the following three lines to the `locl` feature for Noto Sans and Noto Serif:

```
language CHO;
sub uni028A by upsilon;
sub uni01B1 by uni01B1.loclCHO;
```

And add a glyph shape `uni01B1.loclCHO` that looks like the Greek upsilon but with uppercase size. For comparison, here’s the string `Ʊʊ` in a the [LaserChoktaw font](https://www.linguistsoftware.com/lchoctaw.htm) which was designed for the Choktaw language:

![image](https://user-images.githubusercontent.com/1527880/32254132-33102692-be5c-11e7-933c-559eb9a4b550.png)

/cc @sven-oly

**Comment by moyogo** [comment]
Aren’t those 01B2 Ʋ  and 028B ʋ instead of 01B1 Ʊ and 028A ʊ?

**Comment by moyogo** [comment]
Looking at https://books.google.co.uk/books?id=odIPAAAAYAAJ and https://books.google.co.uk/books?id=-sRUAAAAcAAJ, these are better encoded with 01B2 Ʋ and 028B ʋ. 028B ʋ was called *Latin small letter script v* in Unicode 1.0.

**Comment by brawer** [comment]
Indeed, thank you so much!
