### ISSUE TITLE
Kannada broken text with akhand feature in mac

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#994]
## Defect Report
This text "ಕ್ಜ್ಞೌಕ" is broken in mac Safari browser, but renders correctly in Chrome.

### Title 
  > Kannada broken text with akhand feature in mac

### Font 
  > NotoSansKannada.ttf

### Where the font came from, and when
  > fonts.google.com

### Font Version
  > 1.03uh

### OS name and version
  > mac os 10.13.1

### Application name and version
  > Safari

### Issue
  > I am not sure if this is a font issue or Apple CoreText issue. 

### Screenshot
![screen shot 2017-11-02 at 1 04 15 am](https://user-images.githubusercontent.com/14062593/32312083-cb6bb218-bf69-11e7-8c88-233bcc3f1ad0.png)

**Comment by MayuraVerma** [comment]
is it necessary to use "akhn" feature in the font? 


(ಕ್ಷ, ಜ್ಞ) ksha and jyna were shown as samples in initial microsoft opentype document for akhand feature. But I feel, we can make the Kannada font without that feature.

Avoiding "akhn" feature could simplify the shaping engines.

**Comment by JelleBosmaMT** [comment]
Apple's re-ordering may be a bug, given the fact that Microsoft and Google do not have the problem. But, while keeping the akhn feature, I found a way that works for all three.

**Comment by MayuraVerma** [comment]
Thank you. It is definitely Apple CoreText engine issue. I have reported it to them.
There is no reason to use AKHN for these conjugates. We can treat these below-form just like any other below-form. 
But would need a special treatment in GPOS, to get the below-form sit just below the base letter.

When can we see the alpha versions of Google-Sans-Kannada?
How many weights are we getting?

Thanks.

**Comment by JelleBosmaMT** [comment]
"When can we see the alpha versions of Google-Sans-Kannada?
How many weights are we getting?"

I am submitting them for Monotype QA and subsequent delivery to Google today. Not sure how long it will take for the fonts to show up for download. There will be 36 document fonts and 36 UI versions: From Black to Thin, from normal width to extra condensed.

**Comment by MayuraVerma** [comment]
Apple CoreText engine is already sending indic v3 (KND3)to Universal Shaping Engine. 
Harfbuzz could follow the same soon.
Can Noto Sans Kannada get KND3 features?

**Comment by MayuraVerma** [comment]
This is resolved in Mac OS Mojave Core-Text. It's no more an issue.
