### ISSUE TITLE
Kannada U+0CE2 and U+0CE2 vowel diacritics reordering

### ISSUE THREAD

**Issue by MayuraVerma** [googlei18n/noto-fonts#999]
### Title 
  > Kannada U+0CE2 and U+0CE2 vowel diacritics reordering issue

### Font 
  > NotoSansKannada-Regular_OTL-not-for-further-distribution.otf
  > NotoSerifKannada

### Where the font came from, and when
  > https://github.com/googlei18n/noto-fonts/files/1384244/NotoSansKannada-Regular_OTL-not-for-further-distribution.otf.zip

### Font Version
  > Version 1.800 Design proposal (sans)
  > Version 1.01 uh (serif)

### OS name and version
  > Mac OS High Sierra 10.13.2

### Application name and version
  > Safari and Chrome

### Issue
Check these letters
Vowel |diacritic form | Cons+diacr | Cons conj+diacr | double Cons conj+diacr
-- | -- |-- | -- | --
ಌ | ೢ |ಕೢ | ಕ್ನೢ | ಕ್ನ್ದೢ
-- | -- |-- | -- | --
ೡ | ೣ | ಕೣ | ಕ್ನೣ | ಕ್ನ್ದೣ
-- | -- | -- | -- | --
ಌ಼ | ೢ | ಕ಼ೢ | ಕ಼್ನೢ | ಕ಼್ನ್ದೢ
-- | -- | -- | -- | --
ೡ಼ | ೣ | ಕ಼ೣ | ಕ಼್ನೣ | ಕ಼್ನ್ದೣ

U+0CE2 (ೢ) and U+0CE2 (ೣ) have to sit outside any below form consonants similar to vowel form U+0CC3 (ೃ) and U+0CC4 (ೄ)

But U+0CE2 (ೢ) and U+0CE2 (ೣ) overlaps the below form conjugates. 

Surprisingly, this vowel form is failing in MS office 2016 (Uniscribe), Libreoffice (Harfbuzz), Numbers (Apple CoreText).

I am not sure, if this is shaping engine issue or font issue.

### Character data
  > U+0CE2 (ೢ) and U+0CE2 (ೣ) 

### Screenshot

Libreoffice
![screen shot 2017-11-18 at 8 34 21 am](https://user-images.githubusercontent.com/14062593/32981425-5b6c9de0-cc3b-11e7-8140-5eae3c17d7d5.png)
Excel
![screen shot 2017-11-18 at 8 34 29 am](https://user-images.githubusercontent.com/14062593/32981430-645da098-cc3b-11e7-974f-43cdc3201114.png)
Numbers
![screen shot 2017-11-18 at 8 29 52 am](https://user-images.githubusercontent.com/14062593/32981436-6f16bfba-cc3b-11e7-974a-d52a82f274e4.png)

**Comment by JelleBosmaMT** [comment]
I assume that like the subscript vowels r-vocalic and rr-vocalic, the  subscript vowels l-vocalic and ll-vocalic are supposed to be displayed after the subscript consonants. But it seems they are re-ordered by the shaper in front of the subscript consonants, like the other vowel signs: AA, I, E, U, UU.
If I am right, it is a shaper issue. If I am wrong it is a font issue and I should improve positioning. (The Excel sample seems a shaper issue regardless)

**Comment by JelleBosmaMT** [comment]
I still think this is a shaper issue. But I added a work around that moves subscript consonants out of the way, if they follow l-vocalic or ll-vocalic

**Comment by MayuraVerma** [comment]
Thanks
